### ISSUE TITLE
Css are embeded in the production build

### ISSUE THREAD

**Issue by DarKDinDoN** [vuejs-templates/webpack#10]
Since the last few commits, the css are embeded in the JS files.
This happens only with the vue-router lazy-load method :

 ```javascript
// This works fine, css are extracted.
router.map({
  '/guest': {
    name: 'login',
    component: require('containers/Guest/Guest')
  }
})

// This doesn't work, css are extracted but also remains in the JS chunk
router.map({
'/guest': {
    name: 'login',
    component: function (resolve) {
      require(['containers/Guest/Guest'], resolve)
    }
})
```

**Comment by yyx990803** [comment]
This is expected - only CSS in the initial entry chunk is extracted. Any async-loaded chunks CSS is dynamically inserted. This is actually recommended because you don't want to load all the CSS in your async chunks on initial load.

See http://webpack.github.io/docs/stylesheets.html#separate-css-bundle

**Comment by DarKDinDoN** [comment]
Consider the same example as vuejs/vue-loader#139 with vue-router and lazy-load to switch between ComponentA and ComponentB.

Each component has its own chunk (0.js = ComponentA & 1.js = ComponentB) and each chunk contains the same CSS.

Each chunk has its own piece of css, but each chunk is bigger. It would be best if the CSS was extracted in a file that is required along with the chunk. This way, if the CSS is already in cache, the new chunk use it.

**Comment by yyx990803** [comment]
You can do that if you want to, just remove the `vue-style-loader` argument on these lines: https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.prod.conf.js#L27-L30

**Comment by DarKDinDoN** [comment]
Still the same with `vue-loader-style` removed.

Each chunk contains the required CSS. Even if the CSS code is exactly the same.

**Comment by yyx990803** [comment]
Oh I guess I misunderstood your last comment. See this section: http://webpack.github.io/docs/stylesheets.html#styles-in-commons-chunk

**Comment by DarKDinDoN** [comment]
:+1: You thank you sir !
