### ISSUE TITLE
webpack.DefinePlugin

### ISSUE THREAD

**Issue by itdpong** [vuejs-templates/webpack#1002]
Hi all,
I would like to define the database ip address by webpack.DefinePlugin base on the environment variable. Where should I place this code?? 

config/dev.env.js & prod.env.js
or 
build/webpack.dev.env.js & build/webpack.prod.env.js

**Comment by LinusBorg** [comment]
config/dev.env.js & prod.env.js

**Comment by itdpong** [comment]
but whats wrong with my code? I really don't know whats wrong about it.

//prod.env.js
'use strict'
const webpack = require('webpack')

module.exports = {
  NODE_ENV: '"production"',
  plugins: [
    new webpack.DefinePlugin({
      'API_URL':  JSON.stringify('http://192.168.1.10:8081')
    }),
  ]
}

//main.js
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  created:function(){
    console.log('1=',`${API_URL}`);
    console.log('2=',process.env.API_URL);
    console.log('3=',API_URL);
  },
  components: { App }
})

//console
[Vue warn]: Error in created hook: "ReferenceError: API_URL is not defined"
ReferenceError: API_URL is not defined

**Comment by LinusBorg** [comment]
You should not create  DefinePlugin instance yourself, the template does that for you. All you have to do is define the name and content of the variable, just like the template shows you for the already existing `NODE_ENV` variable:
```javascript
'use strict'
module.exports = {
  NODE_ENV: '"production"',
  API_URL: JSON.stringify('http://192.168.1.10:8081')
}
```

**Comment by itdpong** [comment]
actually I try it before , but it still prompt the same error.

![image](https://user-images.githubusercontent.com/1797326/31933885-05ff72a4-b8dd-11e7-8a98-07931fe04bfa.png)

**Comment by LinusBorg** [comment]
you have toaccess it as `process.env.API_URL`

See also: http://vuejs-templates.github.io/webpack/env.html

**Comment by itdpong** [comment]
thank you so much, finally I make it work!!!

**Comment by naotokono** [comment]
For the people arrived here like me, please note that you should run `npm run dev` again to have the update in `dev.env.js` to take place.
This drove me crazy for hours...
