### ISSUE TITLE
How to handle RTL stylesheets?

### ISSUE THREAD

**Issue by iMomen** [vuejs-templates/webpack#1011]
I'm trying to handle a vue application using this template, it's a multilingual application and I have used this code to navigate between stylesheets

`<link rel="stylesheet" href="./assets/stylesheets/screen-ar.css" v-if="this.$i18n.locale == 'ar'">
    <link rel="stylesheet" href="./assets/stylesheets/screen-en-US.css" v-if="this.$i18n.locale == 'en'">`

it always shows ' File not found: /assets/stylesheets/screen-en-US.css'

Also, when I used **import** it's import the two files not the current required one only 

any advice?

**Comment by myst729** [comment]
Maybe you should put them in "/static" folder. Files under "/src/assets" will be handled with webpack.

**Comment by iMomen** [comment]
@myst729 Thanks, that what I have ended up with.
