### ISSUE TITLE
"The connection was interrupted while the page was loading" on Firefox Quantum

### ISSUE THREAD

**Issue by davidchalifoux** [vuejs-templates/webpack#1016]
Just decided to try out [Firefox Quantum](https://www.mozilla.org/en-US/firefox/quantum/) and for some reason when I reload `http://localhost:8080`, the console outputs an error saying `The connection to http://localhost:8080/__webpack_hmr was interrupted while the page was loading.`

The app still seems to function just fine, but I have no idea why this is happening. Any ideas?

(Also, this doesn't happen on Chrome)

**Comment by LinusBorg** [comment]
Thanks, but since this browser is sill in beta, I don't think we will investigate this, especially since it seems to be related to webpack's core HMR functionality, not Vue-specific implementations.

If you want to have this tracked, maybe open an issue in the webpack HMR repository
