### ISSUE TITLE
chrome is supporrt, but i debug in wechat and mobileself and not show page

### ISSUE THREAD

**Issue by 33033624** [vuejs-templates/webpack#1018]
![_15094285235700](https://user-images.githubusercontent.com/19551550/32209093-65a5fc64-be41-11e7-9072-3c00662f13ff.png)

**Comment by LinusBorg** [comment]
I'm sorry but I have no idea how to help you with just one sentence saying "not show page" and a screenshot.

I don't understand what the problem is and cannot test your code to verify anything.

**Comment by robertmain** [comment]
Have you tried `mounted` instead of `created`?

**Comment by 33033624** [comment]
OK，the question is resolved. i try use babel-pollyfill and the question is resolved. thanks all

**Comment by 33033624** [comment]
yeah，i think the export is no play. and i use the babel-pollyfill and the questionis resolved. but i thank you.
