### ISSUE TITLE
the mobile view is not responsive to the same size in desktop mode

### ISSUE THREAD

**Issue by cosimochellini** [vuejs-templates/webpack#1020]
I'm developing a compatible spa for desktop and mobile viewing, but going to desktop mode the dimensions are responsive, while using a phone (or even the **toggle device toolbar** in Chrome) the spa loses its layout and looks very bad

- Desktop view  ![desktop](https://user-images.githubusercontent.com/24718181/32272335-ee3e4ab0-befd-11e7-91fc-29edbe07ab17.PNG)

- Mobile view ![mobile](https://user-images.githubusercontent.com/24718181/32272346-f9de38ee-befd-11e7-8fd0-d2160df8a92d.PNG)

**Comment by LinusBorg** [comment]
That seems to be a design (CSS) problem, what does this template have to do with it?

**Comment by cosimochellini** [comment]
i use **bootstrap-vue**  , 0 css written on my own
the template is derived from **vue init webpack**

**Comment by LinusBorg** [comment]
So the CSS is from bootstrap-vue, not this template. Maybe ask there.

**Comment by cosimochellini** [comment]
Mm also without bootstrap the spa is not responsive , that's a really weird things

**Comment by LinusBorg** [comment]
We only recently added this meta tag to index.html:
```html
<meta name="viewport" content="width=device-width,initial-scale=1.0">
```

Which you probably need.

**Comment by cosimochellini** [comment]
Yes, now work, sorry for the inconveniences
