### ISSUE TITLE
broken static folder css and js references

### ISSUE THREAD

**Issue by akshayvinchurkar1** [vuejs-templates/webpack#1030]
after " npm run build " dist folder is created but all the references for static files was broken problem is "/" before static folder link so i remove that / and it works like charm.
 but the question is why we need that / before static folder link?

so i find a solution remove the assetsPublicPath key from build object in config folder index.js.

now i want to know the side effects if i do this way

**Comment by LinusBorg** [comment]
> after " npm run build " dist folder is created but all the references for static files was broken

Please be more specific. How were they broken? What should they have bee? how did you test this?

**Comment by akshayvinchurkar1** [comment]
ok specific issue is when dist folder generate i open index.html file but nothing is working because the static css and javascript links are like

this is not working link
```<link href=/static/css/app.ea298c8beb30b3d115fad4c0e0e636b0.css rel=stylesheet>```

this is working link for me without "/" before static folder in windows 7
```<link href=static/css/app.ea298c8beb30b3d115fad4c0e0e636b0.css rel=stylesheet>```

same thing for javascript files

**Comment by rajeevbbqq** [comment]
On your webpack.config.js

```
var path = require('path')
var webpack = require('webpack')

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: './dist/',
    filename: 'build.js'
  },
```

**Comment by akshayvinchurkar1** [comment]
@rajeevbbqq in template there is no webpack.config.js. where to find that file?

**Comment by LinusBorg** [comment]
>  i open index.html file

@akshayvinchurkar1 Have you looked at your terminal when you build for production? It should tell you this:

> Tip: built files are meant to be served over an HTTP server.
> Opening index.html over file:// won\'t work.

The reasons for that is indeed that we use absolute paths by default. And we do that because vue-router's history mode doesn't work with realtive paths. Using that is a common usecase, while using the files directly in a browser is not. 

You can switch to relative paths by changing `assetsRootPath` in `config/index.js` under the `build` key.

**Comment by akshayvinchurkar1** [comment]
ok so using a http server is necessary still my project is working thanks @LinusBorg
