### ISSUE TITLE
Unit tests fails when project contains 3td party components

### ISSUE THREAD

**Issue by graux** [vuejs-templates/webpack#1040]
I am using the latest version of the Webpack Template and Vue.

When I run the unit tests in a simple project, all works fine, but when the project uses components it fails. It seems that for some reason is trying to run the raw node_modules code instead or pre-processing it.
For instance, I am using vue2-portal and vue-bulma-tooltip, when I test **ANY** of my components, even if they do not use any 3rd party components I always get:
`10 11 2017 11:38:38.478:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
10 11 2017 11:38:38.479:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
10 11 2017 11:38:38.482:INFO [launcher]: Starting browser PhantomJS
10 11 2017 11:38:38.759:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket OMI5QJVirToRkqwrAAAA with id 62983926
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Unexpected token '('
  at webpack:///node_modules/vue2-portal/src/portal.js:6:0 <- index.js:90417`

I am sure there is a quick fix for this, but I haven't been able to find it and I thought this should be supported by default by the templates.
I've tried to add to my .babelrc test environment the preset es2015 or es2016, but it did not work.

Thank you for your help!

**Comment by LinusBorg** [comment]
That's nothing specific to unit tests. The webpack config for babel-loader skips `/node_modules` in general - because transpiling *every* package would be a gigantic performance issue. 

Solution: add specific packages' paths to the `include` option of the babel-loader config.
