### ISSUE TITLE
Moutned vue component in unit test has empty HTML

### ISSUE THREAD

**Issue by robertmain** [vuejs-templates/webpack#1043]
So I think there may be an issue with the way the testing setup is configured here.

Given this component:
```html
<template>
    <div class="clock">
        <span class="time">{{dateTimeObj.format(timeFormat)}}</span><br />
        <span class="date">{{dateTimeObj.format(dateFormat)}}</span>
    </div>
</template>

<script>
import * as moment from 'moment';

export default {
    name: 'Clock',
    props: {
        timeFormat: {
            type: String,
            default: 'hh:mm:ss a'
        },
        dateFormat: {
            type: String,
            deafult: 'dddd[,] MMMM Do[,] YYYY'
        }
    },
    data () {
        return {
            dateTimeObj : null
        }
    },
    mounted () {
        this.interval = setInterval(() => {
            this.dateTimeObj = moment()
        }, 500);
    },
    destroyed () {
        clearInterval(this.interval);
    }
};
</script>
```

And this test:

```js
import Vue from 'vue';
import Clock from '@/components/Clock';
import * as chai from 'chai';

const expect = chai.expect;

describe('clock', () => {
    it('displays the time in the requested format', (done) => {
        const Constructor = Vue.extend(Clock);

        const comp = new Constructor({
            timeFormat: 'hh:mm a'
        }).$mount();

        Vue.nextTick(() => {
            expect(comp.$el.textContent.length)
                .to.be.greaterThan(0);
            // Since we're doing this asynchronously, we need to call done() to tell Mocha that we've finished the test.
            done();
        });
    });
});
```

It seems that `comp.$el.textContent` is equal to `<!-- -->`. I can't tell if this is a bug with vue, or a bug with the testing setup here - but I think something is definitely amiss.

**Comment by LinusBorg** [comment]
You have to mount to an actual element. Create one with `document.createElement`

**Comment by robertmain** [comment]
@LinusBorg what do you mean? I'm mounting the component - also `document` wont't exist in that context (my unit test) surely?

**Comment by LinusBorg** [comment]
> what do you mean? I'm mounting the component with $mount()

You are mounting, but not to an element:

```javascript
const comp = new Constructor({
  timeFormat: 'hh:mm a'
}).$mount(document.createElement('DIV'));
```
> also document wont't exist in that context (my unit test) surely?

Of course it exists, the unit tests run in a browser with the karma runner.

**Comment by robertmain** [comment]
OK - so it's still coming up as `<!-- -->`

Are there some docs somewhere? I feel like I'm maybe missing something obvious.

**Comment by LinusBorg** [comment]
Oh, well you are calling `.textContent` on the root element of your template which is a `<div>` and doesn't contain any text - it only contains two `<span>` elements.

**Comment by robertmain** [comment]
Right, but in this case `comp.$el` is still just showing up as `<!-- -->`...like I said - are there docs?

**Comment by LinusBorg** [comment]
There's a very basic guide on the main website, and we have a guide specific to our test utility: 

http://vue-test-utils.vuejd.org

However this is still confusing as this should simply work as it is.

**Comment by robertmain** [comment]
Btw - `vuejd.org` is a non-existant domain - did you mean `vuejs.org`? :)

**Comment by LinusBorg** [comment]
Obviously :-P

**Comment by robertmain** [comment]
I mention it because I haven't finished my second coffee yet and it took me a good 15 minutes to figure out why it didn't work :P

**Comment by robertmain** [comment]
Either way - I'm not using vue-test-utils...just whatever comes bundled with this template...not sure if that's relevant...

**Comment by LinusBorg** [comment]
Nope. I could take a look if you could share a repository, but as far as looking at code snippets goes, I got nothing more to contribute.

**Comment by robertmain** [comment]
Sure - repo is here: https://glow.dev.maio.me/impulse/dashboard/

**Comment by LinusBorg** [comment]
That component looks a bit different and there's no spec in the unit folder - are you sure this is the latest commit?

**Comment by robertmain** [comment]
Whoops - try now. I committed and pushed

**Comment by robertmain** [comment]
OK...so it looks like the test is the problem. My component works just fine in the browser.

This works:
```js
const Constructor = Vue.extend(Clock);

const vm = new Constructor({
    propsData: {
        timeFormat: 'hh:mm a'
    }
}).$mount(document.createElement('div'));
//eslint-disable-next-line
console.error(vm.timeFormat);
```

...however - this:
const Constructor = Vue.extend(Clock);

```js
const vm = new Constructor({
        timeFormat: 'hh:mm a'
}).$mount(document.createElement('div'));
//eslint-disable-next-line
console.error(vm.$el.children);
```

Just prints out `undefined`

Also worth noting that if, in the first example - I do this:

```js
const Constructor = Vue.extend(Clock);

const vm = new Constructor({
    propsData: {
        timeFormat: 'hh:mm a'
    }
}).$mount(document.createElement('div'));
//eslint-disable-next-line
console.error(vm.$el);
```

It prints out `<!-- -->` ....meanwhile `console.log(vm.$el.children)` simply produces `undefined`

**Comment by LinusBorg** [comment]
You still need $nextTick if I remember correctly.

**Comment by robertmain** [comment]
Tried that

```js
onst Constructor = Vue.extend(Clock);

const vm = new Constructor({
    propsData: {
        timeFormat: 'hh:mm a'
    }
}).$mount(document.createElement('div'));
Vue.nextTick(() => {
    //eslint-disable-next-line
    console.error(vm.$children);
    expect(0).to.equal(0);
    done();
});
```

I get `[]` in my terminal

**Comment by LinusBorg** [comment]
$children contains child components. Your component doesn't have any child components.

**Comment by robertmain** [comment]
...oh - I would've thought it would contain child elements...

Either way - `vm.$el` is still showing as `<!-- -->`

Surely I should have something showing up?

**Comment by LinusBorg** [comment]
Can'T say more, couldn't test your app so far.

**Comment by robertmain** [comment]
Ah, ok. I did commit the component and it's tests up earlier I think.

Either way - I appreciate you doing this. I originally thought this was an issue with the testing config in the template...but perhaps it's just my understanding of how to test Vue components :)

**Comment by robertmain** [comment]
Solved it in the end - ended up upgrading to the latest version of the template and using jest instead of mocha and chai.

**Comment by iberflow** [comment]
This is still an issue for the rest of us :(

**Comment by LinusBorg** [comment]
You're the first to come across it as far as I'm concerned, so i don't know that "rest of us".

OPs reproduction is no longer avaliable, and I never had such issues.

If you can provide a clean repository with a minimal reproduction, open a new issue and I am happy to take a look.

**Comment by mjvezzani** [comment]
Apologies that it isn't a clean repository with a minimal reproduction, but I'm getting the same issue. If you care to look:

https://github.com/mjvezzani/redx_application/blob/master/vue_app/test/unit/specs/ProfileForm.spec.js

The `console.log(vm.$el)` in that test outputs `<!---->`. Unsure why that is, seeing as I used Header.vue and Header.spec.js as templates for my ProfileForm.vue and ProfileForm.spec.js files. When I `console.log(vm.$el)` in the Header.spec.js test, I get a set of DOM elements, but that just isn't the case in for ProfileForm.spec.js.
