### ISSUE TITLE
after building project is too big

### ISSUE THREAD

**Issue by facesea** [vuejs-templates/webpack#105]
my dependencies:
```
"dependencies": {
    "babel-runtime": "^5.8.0",
    "cookies-js": "^1.2.2",
    "vue": "^1.0.18",
    "vue-resource": "^0.7.0",
    "vue-router": "^0.7.13",
    "vuex": "^0.6.2",
    "vuex-router-sync": "^1.0.0"
  }
```

fanilly, `app.js   2.82 MB`, i computed `cookies-js + vue + vue-resource +  vue-router + vuex + vuex-router-sync` size is 681KB. so  is `babel-runtime` too big? should i do?

**Comment by chrisvfritz** [comment]
Hi @facesea. 😃  Beyond dependencies that you explicitly import/require, some other things that will contribute to the size of your project:

- Your own code (obviously) 😛 
- Webpack's code to tie everything together
- Images that are small enough to be base64 encoded and inlined

If you still think something strange is going on, would you be able to host a demo project on GitHub that demonstrates the discrepancy you're observing?

**Comment by azamat-sharapov** [comment]
You should clarify - is this dev build or production? For dev builds, it's normal, I think, because [sourcemaps](https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.dev.conf.js#L13) add a lot of text.
But for production build, [sourcemaps are enabled by default](https://github.com/vuejs-templates/webpack/blob/master/template/config.js#L10) too.

**Comment by yyx990803** [comment]
Production source maps are separate from the js files. There is obviously something wrong, possibly related to the recent `babel-runtime` upgrade (we are using 6.x now).

**Comment by chrisvfritz** [comment]
@facesea Can you confirm whether upgrading to `babel-runtime` 6.x fixes your issue?

**Comment by facesea** [comment]
@chrisvfritz can not fixes my issue when i upgraded `babel-runtime`, own code just have 400kb(include all static assets),maybe the problem is method that i used `Vue` is wrong.

**Comment by chrisvfritz** [comment]
@facesea Possibly. Can you publish a project demonstrating what you're seeing on a fresh project?

**Comment by chrisvfritz** [comment]
This has been open for a while without repro, so I'm closing. Happy to reopen if someone provides a minimal example of a new project demonstrating the issue. 😃

**Comment by peterchaula** [comment]
@facesea & @chrisvfritz the issue should be coming from the webpack config. I removed #inline-source-map and my build was down to  197kb
