### ISSUE TITLE
Remove unnecessary `minimize` option for css-loader

### ISSUE THREAD

**Issue by LinusBorg** [vuejs-templates/webpack#1056]
https://github.com/vuejs-templates/webpack/blob/86d4970b5a9ccdaaaf9f65eae3cb5570f629af74/template/build/utils.js#L20

We shouldn't need this, since we use OptimizeCSSPlugin in the productionbuild anyway, right?

https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.prod.conf.js#L54

**Comment by maxiong1** [comment]
Why delete css-loader minimize: process.env.NODE_ENV === 'production'.
I know OptimizeCSSPlugin can compress；
but webpack.prod.conf.js new ExtractTextPlugin({ filename: utils.assetsPath('css/[name].[contenthash].css?v=111111')}),
Css packaged without compression did not go heavy

**Comment by LinusBorg** [comment]
Please open a new issue and provide more information
