### ISSUE TITLE
HMR doesn't work in a monorepo

### ISSUE THREAD

**Issue by sammkj** [vuejs-templates/webpack#1057]
Hello there, I `vue init` a fresh webpack project and couldn't get HMR to work. Here are the steps to reproduce:

```
git clone https://github.com/sammkj/vue-webpack-hmr-repro
yarn install
cd client/apps/web-test
yarn run dev
```

Then try to edit any files under `src`. HMR is not triggered.

**Comment by mprandot** [comment]
To me, nothing about HMR is working :\ 
I have to run "npm run dev" every time

**Comment by githoniel** [comment]
disable your auto-save feature of your ide

use `ctrl + s`  to trigger HMR

**Comment by LinusBorg** [comment]
The normal installation works well for me, just tested a could of hours ago for #1054

I will test this specific case when I get home - until then: can you provide me with details aboiut your environment? Virtual Machines? synced folders  ()google drive etc.)?

**Comment by sammkj** [comment]
Dell Ubuntu 16.04 LTS is my development environment. after a few trial and errors (`rm -rf node_modules`, edit webpack config, etc.), I finally got it working.
