### ISSUE TITLE
Suggestion: add image compressor to template

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs-templates/webpack#106]
Would it be possible to have this template ship with an image compression plugin?
I think most people would use that in their builds.

I tried my hand at implementing https://github.com/tcoopman/image-webpack-loader but I have no real webpack knowledge and following the instructions in that repo produced no results for me.

**Comment by chrisvfritz** [comment]
This is something I'd be open to if someone finds a good solution that compresses images losslessly (at least by default).

**Comment by mdsb100** [comment]
hybird 
use gulp?

**Comment by chrisvfritz** [comment]
@TheDutchCoder I really like the idea of out-of-the-box, lossless image compression, but having just done a little more research into this problem, it looks like it won't be that simple. 😕  

- The quality (and sometimes availability) of binaries for various image compressors seems to vary wildly.
- Depending on how images are used in a project, I worry that the optimal size/quality tradeoff will be quite different from project to project.
- The types and quality of compressions possible are very different for each image format, likely making the results of image compression difficult to predict for users of the template.

@mdsb100 Beyond the above concerns, I'd also really like to avoid increasing the complexity of the build process by introducing more build tools.

Closing for now, but open to revisiting this in the future, pending better and more predictable tooling that can default to lossless compression.
