### ISSUE TITLE
Remove double console messages

### ISSUE THREAD

**Issue by areknow** [vuejs-templates/webpack#1064]
All console messages are repeated twice.

Steps to reproduce:
```
$ vue init webpack test-app
? Project name test-app
? Project description A Vue.js project
? Author xxx <xxx@xxx.com>
? Vue build standalone
? Install vue-router? No
? Use ESLint to lint your code? No
? Setup unit tests No
? Setup e2e tests with Nightwatch? No
$ cd test-app
```
Make a small syntax error in a component file and save. 
```
$ npm start
```

The error will be reported to the console twice. I am not sure if this is an issue with webpack or with this template.

<img width="857" alt="screen shot 2017-11-14 at 4 03 38 pm" src="https://user-images.githubusercontent.com/6361609/32804611-75ddd56a-c955-11e7-8565-9a9a359f4c11.png">

Thank you!

**Comment by LinusBorg** [comment]
Hm, you're right. Honestly - no idea where this is coming from :(

**Comment by areknow** [comment]
@LinusBorg glad its not just me 😅

**Comment by LinusBorg** [comment]
Ah, got it. the FriendlyErrorsPlugin is added twice. :D

**Comment by areknow** [comment]
Thanks for the quick fix!
