### ISSUE TITLE
webpack dev server does not serve over LAN by default

### ISSUE THREAD

**Issue by duckness** [vuejs-templates/webpack#1065]
According to [this](https://github.com/webpack/webpack-dev-server/issues/345#issuecomment-184405150), we just need to append `--host 0.0.0.0` to `"dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`

I don't know webpack well enough to say this is the best solution though.

**Comment by LinusBorg** [comment]
you can easily change the host in `/config/index.js`.
