### ISSUE TITLE
New option for postcss introducing import bug

### ISSUE THREAD

**Issue by Tirke** [vuejs-templates/webpack#1066]
Hello,

`'postcss-import': {},` was added to `.postcssrc.js` in last release.
Currently this option is failing build using `~`import in sass files for me.
I have one stylesheet with an import like : `@import "~flatpickr/dist/flatpickr.css"`.
With `'postcss-import': {},` set, an error is thrown :
`Module build failed: Error: Failed to find '~flatpickr/dist/flatpickr.css'`
Without it, everything is fine.

**Comment by LinusBorg** [comment]
Hm, that's very weird. Inside .vue file or inside a .scss file?

I don't really understand why because SCSS is supposed to take care of those imports ...

**Comment by Tirke** [comment]
Sure quite easy : [here you go](https://github.com/Tirke/postcss-import-bug-repro)

**Comment by LinusBorg** [comment]
Thanks. Will take a look in a few hours, will be on the road until then.

**Comment by LinusBorg** [comment]
So, I could verify the behaviour, and could also verify that removing the tilde makes it work:
``sass
@import 'flatpickr/dist/flatpickr.css'
```

But that is not a real solution because people used to sass-loader expect the code to work *with* the tilde.

Unfortunately, I'm a bit baffled why postcss-loader even processes this import. sass-loader is supposed to do that, itsn't it?

**Comment by LinusBorg** [comment]
Note: postcss-import doesn't respect the `~` like other loaders, like css-loader or sass-loader do. That explains reason for the error, at least.

as to *why* postcss-loader is called in the first place: I think sass-loaer hands off loading the `.css`-file to the loader-config for that file type - which uses postcss-loader. I still don't find it logical that postcss-import is executed in *that* step (rather than on `@import`s *inside of* a `.css` file only), but that sems to be what happens.

So the easy way out would be to simply say: 'don't use tildes when importing `.css`, but use it for `.sass` and other preprocessor files', but that won't really be an acceptable solution, we'll have to figure out something else.

**Comment by Tirke** [comment]
Thanks for the quick "hacky" fix. I do agree that remembering a special case is not ideal though.
We may have to reach out to the postcss-import maintainers no ?

**Comment by LinusBorg** [comment]
No, I don't think that would be promising. I Dr a a couple of issues around this question, and it seems this is the "postcss" way of handling imports. 

I will probably attempt use use css-loader's `importLoaders` option to let css-loader handle the imports, but then still need a solution for vue-loader which applies postcss without postcss-loader, so this option is not on the table. 

Maybe we even need a fix in vur-loader itself.

**Comment by jarrodldavis** [comment]
I ran into this same problem yesterday and the issue is because

1. `vue-loader` uses PostCSS directly instead of relying on `postcss-loader`
2. `sass-loader` skips any imports for paths that end with `.css`

I was able to workaround the issue by omitting the file extension in the import statement

**Comment by LinusBorg** [comment]
@jarrodldavis thanks for this. 

While I don't think the first point is entirely valid/important (I also reproduced it with an in port I `main.js`, the second point was the missing piece for me. 

The behaviour makes much more sense now, thanks. 

I will still try and improve this behaviour, but now I understand what'd going on and that it's "expected".

**Comment by jcastrov** [comment]
I have the same issue with [Bootstrap SASS files](https://github.com/twbs/bootstrap/tree/v4-dev/scss). They use their imports without extension (See [Sass Basics](https://sass-lang.com/guide)) and I get the same error as @Tirke:

**[_functions.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_functions.scss)**
```sass
// Normal code
```

**[bootstrap.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap.scss)**
```sass
@import "functions";
// More imports
```

**Error message**
```
Module build failed: Error: Failed to find 'functions'
  in [
    project-path\node_modules\bootstrap\scss
  ]
    at resolveModule.catch.catch (project-path\node_modules\postcss-import\lib\resolve-id.js:35:13)
    at <anonymous>

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-04c2046b","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-296 13:3-17:5 14:22-304
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

**Comment by jcastrov** [comment]
A temporal solution for me was importing main SCSS files in main.js, instead of SASS @import, like this

```javascript
import Vue from 'vue'
import App from './App'

require('bootstrap/scss/bootstrap.scss');
require('../src/style/mycustomstyles.scss');
```

And it works like a charm 😉

**Comment by dangthang7100** [comment]
I have the same issue when use vue-nprogress plugin (Failed to find '~nprogress/nprogress.css'), is there any solution for this issue yet? I dont want to custom this plugin by remove the tilde.

**Comment by robbiemu** [comment]
I'm having a more complicated and sticky problem with this.
vue-multiselect has styles that we would have to clobber with !important rules, unless we import them in scope. But our project uses submodules, and the main project is where package.json is .. so effectively I *have* to use webpack aliases like:

```
@import "~@fe/node_modules/vue-multiselect/dist/vue-multiselect.min.css";

```

that works when loaded from main.js in an scss file:
## main.js
```
require('sass/app.scss')
//...
```
## app.scss
```
@import "~@fe/node_modules/vue-multiselect/dist/vue-multiselect.min.css";
...
```
but does *not* work from the component in the submodule:
```
<style lang="scss" type="text/scss" scoped>
@import "~@fe/node_modules/vue-multiselect/dist/vue-multiselect.min.css";
```

no other formulation works from the submodule either:
`@import "@fe/node_modules/vue-multiselect/dist/vue-multiselect.min.css";`
`@import "~/vue-multiselect/dist/vue-multiselect.min.css";`

**Comment by meteorlxy** [comment]
@robbiemu 
It may use `css-loader` to load `.css` file.

**Comment by robbiemu** [comment]
The error message says post-css

**Comment by meteorlxy** [comment]
@robbiemu 
For me, this does work:
```html
<style type="text/css" lang="scss">
@import 'github-markdown-css/github-markdown.css'
</style>
```
But this fails:
```html
<style type="text/css" lang="scss">
@import '~github-markdown-css/github-markdown.css'
</style>
```
