### ISSUE TITLE
Production build broken by caniuse-db after tring to upgrad old project to current template

### ISSUE THREAD

**Issue by robertmain** [vuejs-templates/webpack#1068]
When I attempt to run any e2e tests, or run the `build` npm script, I get an error saying that there is a syntax error in `data.json` for `caniuse-db`. See below:

```
$ npm run e2e

> dashboard@1.0.0 e2e C:\Users\robert\Code\Node\dashboard
> node test/e2e/runner.js

module.js:595
    throw err;
    ^

SyntaxError: C:\Users\robert\Code\Node\dashboard\node_modules\caniuse-db\data.json: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:592:27)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\robert\Code\Node\dashboard\node_modules\cssnano\node_modules\browserslist\index.js:5:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\robert\Code\Node\dashboard\node_modules\cssnano\node_modules\autoprefixer\lib\autoprefixer.js:5:18)
```

Sure enough, if I go and look at `caniuse-db/data.json` - I see this:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://caniuse.com/data.json">here</a>.</p>
</body></html>
```

Things I've tried:

- Upgrading to the latest vue/webpack template
- Re-installing all of my `node_modules`
- `npm rebuild`

I've searched this issue tracker and I don't see anyone else running into this, so I'm starting to wonder if it's something I'm doing...

Curiously, if I generate an entirely new project and run the production build there - that works fine. However - I tried copying the `config`, `build` and other such dot files over to my project with no success...

**Comment by LinusBorg** [comment]
It seems you have an old version of that package installed, which tried to get that an from an url that doesn't exist anymore. 

Try `npm ls caniuse-db` to find out which package's depebdency it is, and upgrade those to their latest versions.

**Comment by robertmain** [comment]
That's what I don't get though.... I've blown my `node_modules` folder away multiple times and I'm using the same version as the the newest template uses... Yet it still doesn't work.... Is something cached somewhere or something?

**Comment by LinusBorg** [comment]
Two things come to mind:

* lockfiles: if you still have a `package-lock.json` or `yarn.lock` (or whatever it's called) in your project root, that might force the install of an older, out-of-date package with the old url ...
* are you using yarn? Yarn caches packages locally for a while, while npm doesn't, by defaul.

Other than that, no idea at the moment.

**Comment by robertmain** [comment]
- The lockfile is a possibility - I'll try binning it and re-installing
- No, I'm not using yarn. My friend is - but I'm not...interestingly, it works fine on the CI server with the exact same lockfile....

**Comment by robertmain** [comment]
Yep - binning `node_modules` **AND** `package-lock.json` fixed this. Thanks!

Closing :)
