### ISSUE TITLE
template v1.2.3 can't serve in remote server.

### ISSUE THREAD

**Issue by SidKwok** [vuejs-templates/webpack#1069]
I have a remote server named `aa.bb.com`, and the ip is `11.22.333.444`. When I use the template with express version, I can access my website in `aa.bb.com:8080` or `11.22.333.444:8080` after I ran `npm run dev`. But with `v1.2.3`, I can't do that, and the browser tells me that it can't visit the website.

I have to rewrite `host` in `config/index.js` with `aa.bb.com` or `11.22.333.444`, it's ok when you only have on remote server. But consider we often work with others, and everyone has their own remote server, so we have to rewrite `host` multiple times and ignore it in git. But if we do that, we can't share our proxy or other config in `config/index.js`.

**Comment by LinusBorg** [comment]
Simply set your host to `0.0.0.0`

**Comment by duckness** [comment]
Yeah I had this problem as well in #1065, just set `host` to `0.0.0.0` in `config/index.js`

**Comment by SidKwok** [comment]
how about using `0.0.0.0` by default in the template? it can still use `localhost`.

**Comment by LinusBorg** [comment]
Well that would make your machine Ccessible from outside by default, which I don't feel as a secure default.

**Comment by SidKwok** [comment]
You've got a point here
