### ISSUE TITLE
Build for dev?

### ISSUE THREAD

**Issue by mariaczi** [vuejs-templates/webpack#107]
Hi,
I am missing one function - build dev.
Why? I am using it with Laravel, a lot of ajax etc and I need to run it from Laravel not from dev: localhost:8080.
It is also giving me issues with devtools...

**Comment by chrisvfritz** [comment]
@phanan What's your typical strategy for Laravel integration? I can explain what I do for Rails and I'm guessing the general strategy should transfer, but Laravel-specific instructions would probably be more helpful. 🙂

**Comment by mariaczi** [comment]
@chrisvfritz Interactions with server/templates, also I am using bootstrap components which are using bootstrap CSS etc.
What's your suggestions?

**Comment by chrisvfritz** [comment]
@mariaczi I actually [just published this](https://github.com/chrisvfritz/rails-javascript-integrations/), which demos 3 different Vue integrations with Rails, including one that [uses this template _and_ includes Bootstrap](https://github.com/chrisvfritz/rails-javascript-integrations/tree/vue-webpack). What may be of particular interest to you is [the `proxyTable` config](https://github.com/chrisvfritz/rails-javascript-integrations/blob/vue-webpack/frontend/config.js#L14-L16) and how [Bootstrap is included via `bootstrap-sass`](https://github.com/chrisvfritz/rails-javascript-integrations/blob/vue-webpack/frontend/src/app.vue#L26-L38).

**Comment by phanan** [comment]
Hey, sorry I missed this. I've never tried Vue Webpack + Laravel combo before actually, but will try to find some time this weekend to look at it.

**Comment by chrisvfritz** [comment]
@mariaczi I'm moving this issue to the forum, as it looks like [someone has found a good solution](http://forum.vuejs.org/topic/3904/laravel-webpack-elixir-vue-cli-template) and is able to answer questions about it.
