### ISSUE TITLE
The console error log does not print correctly when there is an unknown variable in the index.html template

### ISSUE THREAD

**Issue by wolfstark** [vuejs-templates/webpack#1070]
Because I accidentally annotated a code, the error log can not be printed correctly, I can not find the source of the BUG.

```js
    new webpack.DefinePlugin({
      'process.env': require('../config/dev.env')
      // doman: JSON.stringify('http://cm.cn'),
    }), 
```
![image](https://user-images.githubusercontent.com/15010463/32876209-bc852c70-cad6-11e7-9fcd-801edfb02518.png)
The print result I expect is below, so that I can find the problem.

 error：Template execution failed: ReferenceError: doman is not defined

**Comment by LinusBorg** [comment]
I don't understand. What does index.hyml have to do with it, or the comment in that code?

**Comment by LinusBorg** [comment]
Okay, saw the PR and understand the issue now. Thanks!

**Comment by LinusBorg** [comment]
merged
