### ISSUE TITLE
Confusing with babel-runtime package

### ISSUE THREAD

**Issue by jacobsun** [vuejs-templates/webpack#1080]
I found the template uses `babel-plugin-transform-runtime` to centralize bable runtimes, but  the project does not include the actual runtimes, `babel-runtime`.
 [babel doc] (https://babeljs.io/docs/plugins/transform-runtime/),
Is it a problem or ...

I hope someone can clarify whether we need `babel-runtime` or not,  thanks.

**Comment by LinusBorg** [comment]
The wording on that page is confusing - we don' need `babel-runtime` because we transpile our code during build, we don't run babel in production (that would be crazy).
