### ISSUE TITLE
npm run dev on Homestead doenst seem to do anything

### ISSUE THREAD

**Issue by T0miii** [vuejs-templates/webpack#1084]
Hi,
first of all thank you for the great work and effort.
I  run into a problem. I am working on a new project where i would love to use Laravel and backand and Vue as standalon frontend SPA.

I installed Laravels Homestead VM as development enviroment. I created the Laravel project works fine.

Then i installed vue cli
![image](https://user-images.githubusercontent.com/10532141/32978632-64c9a5e4-cc46-11e7-81ca-49785aff8244.png)

instead of npm i have to use yarn cause npm encounters a problem while installing a pavkage, he cant remove a dir name fsevents. So i just use yarn works fine he installs all the packages.

yarn install --no-bin-links

I open my  code in phpstorm, the index.html but there is no script tag? What do i have to include there?
"npm/yarn run dev" doesnt seem to create anything. 

If i do npm/yarn run build and direct my app into the dist directory i can see the VUE start page. But i cant develope like that.

This is the directory stucture after yarn run dev:

![image](https://user-images.githubusercontent.com/10532141/32978664-37eb0cec-cc47-11e7-97c6-52c4cf55ecea.png)

**Comment by LinusBorg** [comment]
`npm run dev` starts a development server on `localhost:8080`, and this server directly builds and serves your files in memory. That means no files are created.

The script tags for index.html are also automatically inserted etc., so there's nothing you have to do at all. Just run the `dev` script and visit the URL your command line tells you.

**Comment by T0miii** [comment]
If i do all this under my locale machine windows it works just fine. But in my VM (Homestead) if i `npm run dev` there is nothing under localhost.

I think its time to create a dualboot ubuntu system.

**Comment by LinusBorg** [comment]
You might want to change the hostr from `localhost` to `0.0.0.0` in `/config/index` so it's reachable from outside.

I don't work with Homestead of Vagrant and don't knopw how they expose their network interface, but I would assume you have ot find out that box's IP and access the server through that.
