### ISSUE TITLE
HRM not working

### ISSUE THREAD

**Issue by 328480460** [vuejs-templates/webpack#1097]
i use vue-cli to create my project, then  cnpm install to load package, then  npm run dev to start my project,
it didnt open my browser as usual and i got a log  '95% emitting DONE  Compiled successfully in 5897ms14:36:49       I  Your application is running here: http://localhost:8080 '  like this;
![t ee7gx id24 04c bkor](https://user-images.githubusercontent.com/19699468/33113594-10fcc288-cf94-11e7-89e5-f7ef0c0edd1a.png)
so i open http://localhost:8080  and  got a vue page, but when i revise code, HRM not working , i need refresh browser by myself, broser log a error 

![u r bnknsa9q8lk17 7f 1](https://user-images.githubusercontent.com/19699468/33113906-5c9673f0-cf95-11e7-9c40-465c5646f3f6.png)
at sametime  i got same log in shell  like first picture, i dont know what happend, i need help !!

**Comment by afontcu** [comment]
It might have something to do with windows and hosts... could try changing your host from localhost to `0.0.0.0` in `config/index.js`? Solved a couple of issues for me.

Hope it helps.

**Comment by 328480460** [comment]
@afontcu  thanks for help ,  i rewrite  host and port ,  HRM comes back; i dont know the reason, bu it dose useful, thanks again!!! 
![ymg626 inkqq20xdp b3_o](https://user-images.githubusercontent.com/19699468/33166157-3b9a4f84-d074-11e7-8401-a98cd1c03410.png)

**Comment by luandro** [comment]
I'm also having this problem using this template to develop for the [SAFE Browser](https://github.com/maidsafe/safe_browser). A few versions back it used to work, but after a few updated I get error:

```
XMLHttpRequest cannot load http://localhost:3000/sockjs-node/info?t=1511445071485. The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'localhost://p:3000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

client?843a:164 [WDS] Disconnected!
```
I get the same error using other boilerplates that user HMR. Anyone knows what has been recently updated in Webpacks's HMR config that could cause this?

I've tried adding `headers: { 'Access-Control-Allow-Origin': '*' }` to config, but that doesn't help...

**Comment by LinusBorg** [comment]
Have any of you tried the `poll` option in `/config/index.js`?
