### ISSUE TITLE
dev 生成的 png 文件带有 hash，build 生成的 png 文件不带 hash

### ISSUE THREAD

**Issue by hanai** [vuejs-templates/webpack#11]
目测是 `webpack.prod.conf.js` 中的这段没有考虑到 `url-loader` 的 `query`

``` js
// generate loader string to be used with extract text plugin
function generateExtractLoaders (loaders) {
  return loaders.map(function (loader) {
    return loader + '-loader' + (SOURCE_MAP ? '?sourceMap' : '')
  }).join('!')
}
```

**Comment by yyx990803** [comment]
请说具体一点。我这里 build 的图片是带 hash 的。

**Comment by hanai** [comment]
``` bash
vue init webpack tmp
```

拿一个大一点的不会被转换成base64的图片替换掉 `src/assets/logo.png`，

``` bash
npm run build
```

结果如图

<img width="465" alt="2016-01-25 4 08 58" src="https://cloud.githubusercontent.com/assets/1222115/12545514/fefe40d0-c37d-11e5-9a32-9c26eecc78da.png">

logo.png 没被添加 hash

但是在 `npm run dev` 的时候是有 hash 的

![2016-01-25 4 10 28](https://cloud.githubusercontent.com/assets/1222115/12545542/3cf4eab0-c37e-11e5-9ff1-72bb7e074018.png)

**Comment by yyx990803** [comment]
图片文件名本身不带 hash，但是你模板里的 url 是带 hash 的... 因为这里的 hash 是 url 请求的 query 而不是文件名的一部分。
