### ISSUE TITLE
how can I know vue-cli has over

### ISSUE THREAD

**Issue by wklc2014** [vuejs-templates/webpack#110]
when I use vue-cli command
~~~~
vue init webpack my-vue-project-demo
~~~~~

the tips is next:
~~~~
   vue-cli Generated "my-vue-project-demo".

   To get started:
     cd my-vue-project-demo
     npm install
     npm run dev

   Documentation can be found at https://vuejs-templates.github.io/webpack
~~~~~

but how can I know it is over or not?

**Comment by yyx990803** [comment]
What do you mean?...

**Comment by chrisvfritz** [comment]
I might be misunderstanding, but isn't the implication of "generated" that it is done generating?

**Comment by wklc2014** [comment]
I mean I have to manually press CTRL + c to stop the command line, and command 
~~~~
cd project-folder-name && npm install 
~~~~
to next steps or open new cmd window to perform the above command.

**Comment by chrisvfritz** [comment]
@wklc2014 Are you on Windows by any chance? I've noticed that using Git Bash and sometimes other Windows terminals that many commands fail to quit properly (not just with `vue-cli`).

**Comment by wklc2014** [comment]
@chrisvfritz  Thank you very much, so I stop it press CTRL + c and go on.

**Comment by chrisvfritz** [comment]
Yes, that's what I recommend.
