### ISSUE TITLE
If HOST is provided through environment, friendly notification won't display the actual one

### ISSUE THREAD

**Issue by joltmode** [vuejs-templates/webpack#1101]
There is this: https://github.com/vuejs-templates/webpack/blob/7cf7d4134607348f296287b661dfa8764880c605/template/build/webpack.dev.conf.js#L68

If host is provided through environment, this won't get updated and will still display the value found in config, not taking in mind that it could be changed here: https://github.com/vuejs-templates/webpack/blob/7cf7d4134607348f296287b661dfa8764880c605/template/build/webpack.dev.conf.js#L24

It's a simple fix, though: 
```
messages: [`Your application is running here: http://${devWebpackConfig.devServer.host}:${port}`]
```

I won't bother with expected/actual behaviour, because the code lines should be simple to follow.

---

Posted in response to https://github.com/vuejs-templates/webpack/issues/1099#issuecomment-346556740, because if the switch was made to use internal portfinder of `webpack-dev-server` this message will most definitely need a check-up.

**Comment by LinusBorg** [comment]
Hi @joltmode , thanks for this report, this should indeed be easy to fix.
