### ISSUE TITLE
When BABEL_ENV is not set correctly => "Unit testing not working: unexpected token import"

### ISSUE THREAD

**Issue by dalaidunc** [vuejs-templates/webpack#1104]
Used the vue-cli to create a new template and installed jest for unit testing (as one of the options).

By default the test just has the HelloWorld test.

Then I run `npm test` and it fails (I have not changed any code from the template - this is completely cleanly generated template):

```js
test/unit/setup.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Vue from 'vue';
                                                                                             ^^^^^^
{

    SyntaxError: Unexpected token import
```

I've tried:
- --no-cache option for jest, 
- editing .babelrc
- changing NODE_ENV

Can't work out how to fix this. Any workaround greatly received.

**Comment by dalaidunc** [comment]
ok it seems I have to set BABEL_ENV=test before running the tests. This was not very clear though.

**Comment by LinusBorg** [comment]
That should not be necessary unless you set NODE_ENV to something else besides `test` - otherwise, Jest will set it to `test`, and babel will fall back to that value in absence of BABEL_ENV.

What was your setup before?

**Comment by LinusBorg** [comment]
Maybe we can / should explicitly set BABEL_ENV in `test/unit/setup.js`

**Comment by LinusBorg** [comment]
It seems this was a unique problem of OP,
