### ISSUE TITLE
vuejs-templates v1.2.3，v1.2.4 qq浏览器，支付宝自带浏览器打开空白

### ISSUE THREAD

**Issue by xihadandan** [vuejs-templates/webpack#1105]
vuejs-templates v1.2.3，v1.2.4 qq浏览器，支付宝自带浏览器打开空白
微信自带浏览器可以打开！这是为什么

**Comment by xihadandan** [comment]
还没有找到为什么！官方的人好像不重视这个问题！我只知道v.1.1.2和v1.1.3没有问题

**Comment by iocool** [comment]
安卓上貌似除了UC浏览器,QQ浏览器和使用qq浏览器内核的浏览器都不行,页面空白,我看好像是app.js加载完没有执行后续的请求代码,导致路由被阻塞而页面上router-view没有加载出来

**Comment by xihadandan** [comment]
对！是那么回事！你可有找到解决办法？

**Comment by iocool** [comment]
我也没有解决办法,按照你的说法,我下载了v1.1.3现在测试没有问题了,然后我对比了一下最新版和1.1.3的package文件,里面有很多组件都换了,应该是新的组件对于旧版浏览器内核支持的问题吧,目前看来,还是用旧版稳定一点,新版过段时间在看吧

**Comment by youdianfan** [comment]
请问这个问题怎么解决啊?

**Comment by PanJiaChen** [comment]
may be same as https://github.com/vuejs-templates/webpack/issues/1140

solution
in `./build/webpack.base.config.js`
```bash
{
  test: /\.js$/,
  loader: 'babel-loader',
  include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client')]
}
```

**Comment by minowu** [comment]
应该是没有引入 babel-polyfill 导致的。你试试加入 babel-polyfill 去解决兼容问题。http://babeljs.io/docs/usage/polyfill/
