### ISSUE TITLE
Anyone who wishes to include bundle-buddy [not an issue]

### ISSUE THREAD

**Issue by CharlesKumar** [vuejs-templates/webpack#1107]
Bundle buddy gets rid of code duplication

It works along with common-chunks-plugin

https://github.com/samccone/bundle-buddy

Take a look at it and vote for this if you found useful

**Comment by LinusBorg** [comment]
Is this supposed to be a feature request or how should I label this? :)

**Comment by CharlesKumar** [comment]
An opinionated feature request (sort of)

may be better than webpackBundleAnalyser/ webpack visualizer

if you look into the [code](https://github.com/samccone/bundle-buddy/blob/master/viz/src/App.js), a simple react app to analyse the bundles. [code](https://github.com/samccone/bundle-buddy/blob/master/viz/src/index.js)

Let's see how many votes bundle buddy gets when webpackBundleAnalyser is already included in [this](https://github.com/vuejs-templates/webpack) template

**Comment by CharlesKumar** [comment]
Hello developers !!

what about this brotl compression over gzip 

using this [webpack-plugin](https://www.npmjs.com/package/brotli-webpack-plugin)

Read this [article](https://hacks.mozilla.org/2015/11/better-than-gzip-compression-with-brotli/) and share your views on compression techniques

**Comment by LinusBorg** [comment]
This also has nothing to do with the proposed feature of this issue. Please stop posting comments to issues that have nothing to do with the original topic.

**Comment by LinusBorg** [comment]
I'll close this for inactivity. I don't think we will add this to the standard
