### ISSUE TITLE
No browsers config for current version of babel

### ISSUE THREAD

**Issue by jakub300** [vuejs-templates/webpack#1108]
Browsers were removed from `.babelrc` in #1004, but current version of `babel-preset-env` (v1.6.1) support configuration only in `.babelrc`, not others sources supported by `browserslist`. They will be supported in upcoming babel v7.

Readme for v1.6.1: https://github.com/babel/babel-preset-env/tree/v1.6.1
Readme for master: https://github.com/babel/babel/tree/master/packages/babel-preset-env#browserslist-support

**Comment by LinusBorg** [comment]
that will be fixed with #1083
