### ISSUE TITLE
package.json: may contain empty lines

### ISSUE THREAD

**Issue by jakub300** [vuejs-templates/webpack#1109]
Running
```
yarn add vuex
```
on generated projects is causing devDependencies to be sorted and one empty line removed:
![image](https://user-images.githubusercontent.com/610941/33216960-5ae0c05e-d136-11e7-88d9-8b5532a46838.png)

For reference, my answers during generation, but obviously similar problems will happen for every combination of answers:
```
? Generate project in current directory? Yes
? Project name vue-app
? Project description A Vue.js project
? Author Jakub Bogucki <jakub.bogucki@xfive.co>
? Vue build runtime
? Install vue-router? Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Airbnb
? Setup unit tests Yes
? Pick a test runner jest
? Setup e2e tests with Nightwatch? No
```

**Comment by LinusBorg** [comment]
We can't order dependencies because we have to conditionally add dependencies with a templating language, depending on the answers the developer gave when creating his project.

We should fix the empty lines, though.

**Comment by LinusBorg** [comment]
empty line fixed with https://github.com/vuejs-templates/webpack/commit/01a4b646dd4fd92605368070acc23e16e30c5714

**Comment by jakub300** [comment]
Hey @LinusBorg, I looked into it and I disagree that you can't solve problem with dependencies order.
You could do it either by creating more conditions in right places, for example _lint_ condition is twice in dependencies so at least at some point somebody intended to keep right order.
You could also [provide complete function](https://github.com/vuejs/vue-cli#writing-custom-templates-from-scratch) that would ordered it properly, probably simpler solution considering number of conditions.

**Comment by LinusBorg** [comment]
You are right that its *possible* technically, of course. 

More conditionals are out of the questions for reasons of maintainability / readability. 

But a sorting function would be possible. I would welcome a PR that introduces such a function. Just bs aware that we can't use third-paety packages (without hackery) during project generation since vue-cli doesn't run a npm install (and I don't think we want it to).
