### ISSUE TITLE
WebView shows blank when running dev mode

### ISSUE THREAD

**Issue by kuoruan** [vuejs-templates/webpack#1111]
```
Uncaught SyntaxError: Use of const in strict mode. 
```
![2017-11-25 3 44 29](https://user-images.githubusercontent.com/8685618/33228485-d9a3ca3c-d1f7-11e7-8949-52773329cfe2.png)

related to #968

**Comment by LinusBorg** [comment]
That'sa safari being a dick, and it won't happen anymore since we switched to webpack-dev-server with [v1.2.0](https://github.com/vuejs-templates/webpack/releases/tag/1.2.0)

**Comment by kuoruan** [comment]
Fixed with: #1140 549078351ef381e9b4cdd73d7aa7a4d57534e4a2
