### ISSUE TITLE
This relative module was not found

### ISSUE THREAD

**Issue by wangrongkang** [vuejs-templates/webpack#1113]
when add 
`background: url(../assets/attribute.png) no-repeat;`

then said 
`* ../assets/attribute.png in ./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-5f7be88e","scoped":true,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0&bustCache!./src/pages/vote/Vote.vue`

why?

**Comment by kuil09** [comment]
hello, I have a situation like yours. Could you show me how to solve it?

**Comment by wangrongkang** [comment]
yahhhh,
`background: url(../assets/attribute.png) no-repeat;`
exactitly, it should be this:
`background: url(../../assets/attribute.png) no-repeat;`
the file catalog is wrong!
not the module lost;
