### ISSUE TITLE
Pre-commit

### ISSUE THREAD

**Issue by Fl0pZz** [vuejs-templates/webpack#1117]
Proposal to use [pre-commit](https://github.com/observing/pre-commit). It can be optional

**Comment by Fl0pZz** [comment]
Or https://github.com/typicode/husky

**Comment by LinusBorg** [comment]
...for what? linting?

**Comment by Fl0pZz** [comment]
And https://github.com/okonet/lint-staged
@LinusBorg  for both of them (linting and tests)

**Comment by LinusBorg** [comment]
I don't have a nice idea of how to integrate this in a way that offers actual advantage without forcing it on users. Another question in the questionnaire at the beginning is not a good idea, the feature is too "small" to justify another question.

So I will close this. If someone comes up with a nice concept, open an new issue or send a PR.
