### ISSUE TITLE
Can webpack template uglify the js

### ISSUE THREAD

**Issue by cshjarry** [vuejs-templates/webpack#1125]
I run `npm run build` and then deploy my app to server.But when I browser app  with chome (62.0.3202.94), I find this in my devtools tabs.  In **Sources** panel, there is an director named `webpack://`，and it lists all the source file with the suffix **.vue** just like my source code before build it to production.

<img width="500" alt="2017-11-29 9 08 21" src="https://user-images.githubusercontent.com/19209634/33376678-a0474368-d549-11e7-91df-8a81ab59d1aa.png">
I wonder if I don't configure the webpack correctly(I change  a little about proxy), or chrome analysis the code and parse it to this director?

**Comment by LinusBorg** [comment]
the source is uglified, but we also build sourcemaps by default, and you sem to serve those as well. Those sourcemaps are respüonsible what you are seeing.

Simply don't serve the *.map files  or deactivate sourcemapping for the production build in  `/config/index.js`

**Comment by cshjarry** [comment]
thank you very much😁😁😁😁
