### ISSUE TITLE
In the mobile browser, when the page is opened with 'vue init webpack myproject', there is nothing can be seen

### ISSUE THREAD

**Issue by fantasy525** [vuejs-templates/webpack#1129]
`1: "node": " 4.0.0",
"npm": " 3.0.0"`
`2: "vue":"2.9.1"
"vue-cli":"2.9.2"`
`3. webpack template version is  1.2.4`
today,I build a new project width ` vue init webpack`,then I ` npm install ,npm run dev`
then I open page in the mobile browser( eg: UC,QQ browser),
I can't see anything,there is nothing to show,but in the PC browser (eg:chrome) is OK,WHY?

**Comment by LinusBorg** [comment]
I have no idea, and don'T know this browser or how to debug this.

Since no one seems to answer here, try asking on forum.vuejs.org // chat.vuejs.org
