### ISSUE TITLE
Build forked pull requests on CircleCI

### ISSUE THREAD

**Issue by gucong3000** [vuejs-templates/webpack#1138]
CircleCI was not build for PRs. we need to update config: 
https://circleci.com/gh/vuejs-templates/webpack/edit#advanced-settings

![image](https://user-images.githubusercontent.com/1171691/33535741-72ab6dcc-d8ea-11e7-98a3-ab5cf17a61d3.png)

**Comment by LinusBorg** [comment]
I activated that option - can you push a commit to trigger it?

**Comment by gucong3000** [comment]
[done.](https://circleci.com/gh/vuejs-templates/webpack/292?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by gucong3000** [comment]
> push a commit to trigger it

Other PRs can be trigger by close and reopen.
