### ISSUE TITLE
how can i point index.hml to index.blade.php (laravel) 

### ISSUE THREAD

**Issue by midascodebreaker** [vuejs-templates/webpack#114]
http://vuejs-templates.github.io/webpack/backend.html

I read this guide, i got the path set up 

but of course i still see the same index.html in localhost:8080

it should have been the mix up with my index.blade.php

how can i do this?

**Comment by chrisvfritz** [comment]
Since this is neither a bug nor a feature request, I recommend posting your question on either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue).
