### ISSUE TITLE
vue-cli init with some unknown error : Uncaught SyntaxError: Use of const in strict mode. 

### ISSUE THREAD

**Issue by Hillkinsh** [vuejs-templates/webpack#1140]
when I initial a new project, I used commands as follows:
vue init webpack my-pro
cd my-pro/
npm install
npm run dev

then, it shows : 
" DONE Compiled successfully in 5653ms

Your application is running here: http://localhost:8080" in command line",

but when I open chrome and address in localhost:8080, 
there is an error: 
"Uncaught SyntaxError: Use of const in strict mode. "

so, how could I solve it?

ps: node version v8.8.0

**Comment by afontcu** [comment]
Hm, that's weird. Could you just double check that you are using node 8.8.0? As long as you are on node greater than v4, you should be good to go.

Could you just describe your environment a little more? node, npm versions, OS, etc.
Are you running your app from the OS cli or using some IDE?

**Comment by Hillkinsh** [comment]
OK, my OS is ubuntu 14.04.  node v8.8.0 npm 5.4.2, vue 2.9.2.
No one had such a problem before. So confused!!!!!

**Comment by LinusBorg** [comment]
I can't reproduce this (I'm on OS X though).

Does the error tell you where that syntax error is happening?

**Comment by Hillkinsh** [comment]
Well, I use command "vue init browserify my-bro", and everything's ok.

I'll show you everything  that happend on me.

Ops, why can't I paste any picture here?

**Comment by simll** [comment]
I think I got the same error, there are something helpful for me:

https://github.com/webpack/webpack-dev-server/issues/1105
https://github.com/mrdulin/blog/issues/35

there are two way to resolved it:
1. use `webpack-dev-server` version `2.7.1`;
2. set `babel-loader` include `webpack-dev-server/client/index.js`;

I resolve it like that:
set `./build/webpack.base.config.js`
```js
{
  test: /\.js$/,
  loader: 'babel-loader',
  include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client')]
},
```

**Comment by LinusBorg** [comment]
Hm, that's a weird choice by the maintainers. 

I think we should add this workaround to the template. 

Thanks for getting to the bottom of this.

**Comment by LinusBorg** [comment]
I just pushed that fix to the develop branch, anyone interested can test it out with 
```
vue init webpack#develop
```

**Comment by Hillkinsh** [comment]
I update my OS to Ubuntu 14.04. and then everything is OK.

**Comment by FirstAurora183** [comment]
Thank you very much!

**Comment by Olivia2008** [comment]
I met the same problem
and i did it like that
1、use webpack-dev-server version 2.7.1;
2、set babel-loader include webpack-dev-server/client/index.js;

but it did not work, i dont know how to resolve it
who could do me a favor?

**Comment by yjwSurCode** [comment]
> I think I got the same error, there are something helpful for me:
> 
> [webpack/webpack-dev-server#1105](https://github.com/webpack/webpack-dev-server/issues/1105)
> [mrdulin/blog#35](https://github.com/mrdulin/blog/issues/35)
> 
> there are two way to resolved it:
> 
> 1. use `webpack-dev-server` version `2.7.1`;
> 2. set `babel-loader` include `webpack-dev-server/client/index.js`;
> 
> I resolve it like that:
> set `./build/webpack.base.config.js`
> 
> ```js
> {
>   test: /\.js$/,
>   loader: 'babel-loader',
>   include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client')]
> },
> ```
我这边设置 没有用啊

**Comment by hoelshen** [comment]
> > I think I got the same error, there are something helpful for me:
> > [webpack/webpack-dev-server#1105](https://github.com/webpack/webpack-dev-server/issues/1105)
> > [mrdulin/blog#35](https://github.com/mrdulin/blog/issues/35)
> > there are two way to resolved it:
> > 
> > 1. use `webpack-dev-server` version `2.7.1`;
> > 2. set `babel-loader` include `webpack-dev-server/client/index.js`;
> > 
> > I resolve it like that:
> > set `./build/webpack.base.config.js`
> > ```js
> > {
> >   test: /\.js$/,
> >   loader: 'babel-loader',
> >   include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client')]
> > },
> > ```
> 
> 我这边设置 没有用啊

我也是不生效
![image](https://user-images.githubusercontent.com/23608829/110228656-b6b54e00-7f3d-11eb-867c-e4863eda24c8.png)
