### ISSUE TITLE
Question: Will the Webpack template use the new Vue ESLint plugin?

### ISSUE THREAD

**Issue by rdytogokev** [vuejs-templates/webpack#1143]
I was excited to hear that the new official Vue ESLint plugin is available.
https://github.com/vuejs/eslint-plugin-vue

I am hoping that the Webpack (and the other templates) will be set up to either offer this as an option or default.

Thanks for your hard work.

**Comment by LinusBorg** [comment]
Sure, once it's released as a stable version we will add it asap.
