### ISSUE TITLE
How to get rid of error of indentation and others...

### ISSUE THREAD

**Issue by midascodebreaker** [vuejs-templates/webpack#115]
I i cannot compiled my old files because it is squawking like so...

```
ERROR in ./src/main.js

  error  no-multiple-empty-lines  More than 1 blank line not allowed
  C:\UsersCodes\vue-ui\resources\assets\js\vue\src\main.js:15:2

    ^

```

What do i need to configure?

**Comment by chrisvfritz** [comment]
To fix the linting issues or turn off the linter?

**Comment by chrisvfritz** [comment]
Since this is neither a bug nor a feature request, I recommend posting your question on either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue).
