### ISSUE TITLE
Out of the box after `vue init webpack`, index.html does not hot-reload.

### ISSUE THREAD

**Issue by richardkmichael** [vuejs-templates/webpack#1150]
With an "out of the box" setup (`vue init webpack .`) and no modifications by me, `index.html` does not hot-reload.

I started the dev server as `npm run dev`, loaded the page and then made a change to the root-level `index.html`.  I expected the browser reload with my changes.  In the browser devtools (both Chrome and Firefox), I see an XHR request for `<unique-id>.hot-update.json` file with a 200 response and payload, but the page does not change.  If I manually reload the page, the content does change as expected.

If I change the the `src/App.vue` component, the page auto-reloads as expected.

I'm not sure what `webpack.dev.config` is doing with the generated `index.html` file via the `HTMLWebpackPlugin` .. is that related?

**Comment by LinusBorg** [comment]
See #1022

**Comment by richardkmichael** [comment]
@LinusBorg Thank you, sorry about the dupe.  (I only searched for `index.html` in the issue tracker.)
