### ISSUE TITLE
Missing npm install tips in "To get started" message

### ISSUE THREAD

**Issue by Toilal** [vuejs-templates/webpack#1157]
When choosing to run npm commands manually, the message doesn't tell user to run npm install

```
# Project initialization finished!
# ========================

To get started:

  cd vue-test
  npm run lint -- --fix
  npm run dev
```

```npm install``` is missing in the get started steps.

BTW, last commits are great :+1:

**Comment by LinusBorg** [comment]
Oh, thought I had tested that thoroughly enough. Will take a look, thanks.

> BTW, last commits are great

Thanks :)

**Comment by LinusBorg** [comment]
@Toilal Try this branch:

```
vue init webpack#fix_complete_msg_1157 
```

**Comment by Toilal** [comment]
It's OK. for yarn, you can omit `run` keyword. (`yarn lint --fix`)

**Comment by LinusBorg** [comment]
Will change that.
