### ISSUE TITLE
Different CSS for different users

### ISSUE THREAD

**Issue by morganzysman** [vuejs-templates/webpack#1159]
Hi everyone,

I have a large sass solution that i'm migrating to vuejs2/webpack.
I have used vue-cli to install this template.

In my current project, I have a gulp task that allows me to generate different css files, that mostly have the same code except color ( I have a different color / user ).

I want to be able to do the same using webpack:
![capture d ecran 2017-12-12 a 17 24 47](https://user-images.githubusercontent.com/5576762/33895793-998b2f7c-df61-11e7-8f92-5f0c32e25127.png)

This is the current structure I have, so basically I want webpack, to loop through all users, get the variables and then generate the .css file per client.

Any help would be appreciated, I understood I need to at least use extract-text-webpack-plugin

Regards

**Comment by LinusBorg** [comment]
That would probably require some drastic changes, I think you will be better off asking on the forum or the chat (forum.vuejsorg / chat.vuejs.org) or simply build your SCSS with gulp like you are used to.
