### ISSUE TITLE
Multiple builds

### ISSUE THREAD

**Issue by solidevolution** [vuejs-templates/webpack#1163]
As common, we've got more systems than "prod" with different env config to build/deploy.

Is there a elegant solution to extend the build process within the template for another config/stage.env?

Goal should be this:

```
npm run build:demo => create demo bundle
npm run build:prod => create prod bundle
```

Currently I see nothing extendable in configuration and I don't want to rewrite the build stack, again.

**Comment by LinusBorg** [comment]
I started working on this today, as a matter of fact. Will push a WIP PR as soon as I have tested it once, hopefully tonight.

Doing this cleanly requires some rewiring of the webpack configs and adjusting documentation, so I don't think it will be ready in the coming few days, but won't take weeks either.

**Comment by solidevolution** [comment]
What we forgot: Separating config from code (build) would be a dream.

**Comment by LinusBorg** [comment]
That's what vue-cli v3 will bring, but that's still in the concept phase.

**Comment by solidevolution** [comment]
@LinusBorg Thanks for fast answers.

Would be nice if v3 includes this factor:d https://12factor.net/config

**Comment by LinusBorg** [comment]
Oh, that will be part of the PR I'm working on for this twmplate. 

I think we wording is confusing: we have a `/config/index` file which mostly general, environment-independent app settings (and a few things over editable by env variables). 

What is called "config" in your link Normandy  trying to improve, and part of that improvement will be `.env` files and env files for webpack for any number of deploy environments.

**Comment by LinusBorg** [comment]
Please see #1163

**Comment by alxppp** [comment]
@LinusBorg Do you have a test version we could try out?

**Comment by BoyardIsBack** [comment]
@solidevolution I think @LinusBorg meant #1178

**Comment by solidevolution** [comment]
I followed the development #1178 and it solves multiple builds.

In this first step, it doesn't improve the complete idea of an atomic build (no differences between the bundle on all stages, remove config from code)

For me an atomic SPA build has minimum the following files:

index.html
files/app.css
files/app.js
static/*

plus some environment dependent files like:

robots.txt
config.js

But yes, it differs from the idea of multiple builds. The title should be "Ship builds to multiple stages"
