### ISSUE TITLE
Output css rather than inline

### ISSUE THREAD

**Issue by alessandrotesoro** [vuejs-templates/webpack#1164]
I'm having trouble figuring out how to output all the scss into a css file during development. Just like an app.js file is automatically injected into the app html I'd need a css file to be injected too. I'm guessing the ExtractTextPlugin is involved, I've tried playing around with it but nothing seemed to work.

Anyone had the same issue that could point me into the right way?

Thank you.

**Comment by LinusBorg** [comment]
Have a look at `/build/vue.conf.js`, there's a call to a utils function which has an `extract` parameter. 

Set this to `true`.

Just be warned that this will **seriously** slow down rebuilds during development, I can't recommend this.

**Comment by alessandrotesoro** [comment]
Sweet thanks, I'll give it a try later. I need the css to be extracted too just because the app I'm building is being tested in a different environment so I need to reference the js and css files into the files of the app in the other env because js and css injection isn't working for some reason.

**Comment by LinusBorg** [comment]
Will close this for now.
