### ISSUE TITLE
Upgrade path from old template to new

### ISSUE THREAD

**Issue by ahulab** [vuejs-templates/webpack#1166]
I'm working on a project that has been using this template for quite a while, it's still using mocha instead of jest and is using the express server instead of webpack-dev-server. I'd like to update the project to be inline with this template, is there a recommended method of doing that, or is it just up to me to reconcile the differences and apply them?

**Comment by LinusBorg** [comment]
There's no easy upgrade path yet -  we aim to solve this with vur-cli 3.

For now, the best way to go depends on the level of customization that you applied to the template. 

Of you hardly changed anything, it's actually quite simple to roll out a fresh install of the template, copy all your source files and tests and replace everything in your original project directory with that. 

Just make sure to adjust anything  you changed in  `/config` and `/build` afterwards.

**Comment by ahulab** [comment]
alright thanks, I'm interested to see what changes vue-cli 3 will make. I ended up just going thru the main build files in each project and resolving differences. However it's rather tricky to manually remove the unneeded package.json devDeps
