### ISSUE TITLE
Auto-Install fails on some OS/node combinations

### ISSUE THREAD

**Issue by LinusBorg** [vuejs-templates/webpack#1168]
### The problem:

For the original bug report, see https://github.com/vuejs/vue-cli/issues/681

### Immediate solutions/workarounds.

One thing we can immediately improve is the error handling. This error is not "fatal" - all people have to do is run `npm install` themselves. So I will add a nice error message explaining that to users.

### so what's the Problem, really?

As to the original source of the problem, I'm a bit dumbfounded for the moment.

> When you then elect to have scaffolding restore your packages (whether through npm or yarn), you are not in the project directory, but above it, so the package install/restore command fails

That would be weird - being in the wrong directory should lead to an error on OSX as well, but doesn't (for me). 

I also think I set the cwd for the npm call to the right directory here: 

https://github.com/vuejs-templates/webpack/blob/develop/meta.js#L155-L158

**Comment by LinusBorg** [comment]
So it seems The solution was actually pretty simple - something got lost in a merge/rebase.

#1170 by @sudo-suhas should fix this.

* @xiejiamiao
* @KyleLehtinenDev
* @IcedKnight
* @songhongjiang
* @lambdakris

could any of you run this and test it out?

```
vue init webpack#develop
```

**Comment by lambdakris** [comment]
@LinusBorg fix works for me, thanks!

**Comment by songhongjiang** [comment]
@LinusBorg Solved the problem by using cmd "vue init webpack#develop",  Thank you!

**Comment by LinusBorg** [comment]
The fix is now available though the normal command as well.

**Comment by xiejiamiao** [comment]
![default](https://user-images.githubusercontent.com/6270998/34047496-5dbbf666-e1eb-11e7-8418-88ebfd47b941.PNG)

it work fine on windows 10 by using 
```vue init webpack```
THX

**Comment by LinusBorg** [comment]
Thanks for testing and reporting back!
