### ISSUE TITLE
webpack-dev-server in UCBrowser fail and airbnb eslint error

### ISSUE THREAD

**Issue by shoyuf** [vuejs-templates/webpack#1174]
1. UCBrowser 
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
when i change to `webpack-dev-server to @2.7.1` , it's works
has any solution?

2. ESLint
like main.js has some `Missing semicolon` `Missing trailing comme` error on ESLint(Airbnb)

**Comment by LinusBorg** [comment]
1. See #1140. Will apply that fix in this template later, asap.
2. Not for me. Did you try the latest template version?

**Comment by LinusBorg** [comment]
About 1.: I just pushed that fix to the develop branch, you can test it out with 
```
vue init webpack#develop
```
