### ISSUE TITLE
Attempts at providing data to the template results in a compilation error

### ISSUE THREAD

**Issue by mjvcallibrity** [vuejs-templates/webpack#1179]
After a basic `vue-cli init webpack projectName`, I changed the HelloWorld template to Header, and attempted to provide data to my template. Please see attached picture:

![screen shot 2017-12-16 at 2 03 33 pm](https://user-images.githubusercontent.com/19933141/34073590-99201fd2-e26a-11e7-94e8-bb5a6b4d138b.png)

I don't really understand the error "Component template should contain exactly one root element." It only shows up after I add the following line of code:

`<p v-for="product in products" track-by="id">{{ product.name }}</p>`

It is as though my data isn't available to my template. Where am I going wrong here? Any help is appreciated. 

Also, here is a picture of my `App.vue` file:

![screen shot 2017-12-16 at 2 09 40 pm](https://user-images.githubusercontent.com/19933141/34073599-d0b42970-e26a-11e7-8719-d5ffcffd3e9b.png)

**Comment by LinusBorg** [comment]
Well, the error is pretty clear: each component can only gave or root element. Your has multiple: 

* the `h1` element
* one or more `p` elements. 

Solution: wrap everything in a `div` or any other suitable element. 

Please read the docs or ask on forum.vuejs.org for further help - this question is not related to this template.
