### ISSUE TITLE
Question: is circle ci need extra config (forked project build fail) ?

### ISSUE THREAD

**Issue by gengjiawen** [vuejs-templates/webpack#1182]
I forked this project and try to build this with circle ci, but it failed. 
https://circleci.com/gh/gengjiawen/webpack/1

**Comment by LinusBorg** [comment]
Not really, no.

But it seems the current setup has reached its limit. If you read the error, it says "out of memory". I have that error as well with a larger PR: #1178 

I'm currently checking out how to move the tests to circleci v2, which is much more fficient and faster as far as I have experienced. Until then, you are pretty much on your own, sorry.

**Comment by gengjiawen** [comment]
I first run into this problem with https://github.com/gengjiawen/ts-scaffold. It use the same config as this project. I think the main problem is not lies in memory, but with this in `test.sh`
```bash
yes "" | ./node_modules/.bin/vue init . test
```
I ssh into the circle ci machine (ubuntu 14.04), execute the command will stuck.  
If you execute `./node_modules/.bin/vue init . test` in bash, and press enter manually, everything works fine. 
I do some search,  change to 
```bash
echo -ne '\n' | ./node_modules/.bin/vue init . test
```
But it won't generate the `test` folder.

**Comment by LinusBorg** [comment]
I'm closing this since the normal banches do build fine for us, and there's no specific setting you have to use. Nothing we an help you with.
