### ISSUE TITLE
Question: build and upload sourcemaps to Bugsnag

### ISSUE THREAD

**Issue by nicooprat** [vuejs-templates/webpack#1184]
I'm trying to log errors with Bugsnag. Errors are correctly sent, but the stack trace is unreadable. Bugsnag has some tools to upload sourcemaps in their service, but I don't know where to start to integrate them with the webpack build process: https://docs.bugsnag.com/platforms/browsers/vue/source-maps/

I'm using Netlify to host my app, which is configured to run the `build` command itself when deploying, so it might be a good idea to do it here, but it would need my Bugsnag API key and I'd rather not commit it.

Has anyone any experience with this? Thanks.

**Comment by LinusBorg** [comment]
We,, I would simply insert the bugsnag code here:

https://github.com/vuejs-templates/webpack/blob/develop/template/build/build.js#L34

..and Netlify allows you to set Environment variables, that should allow you to pass in the api key without comitting it to git.

**Comment by nicooprat** [comment]
Gave it a few try but could get it working... I would have to loop for each generated file and upload it along with its sourcemap, but I'm not webpack-expert enough.

Then I found this: https://github.com/jmshal/webpack-bugsnag-plugin

Just works 👍
