### ISSUE TITLE
Please provide an option to turn off desktop notification. 

### ISSUE THREAD

**Issue by intijk** [vuejs-templates/webpack#1190]
When you development, 99% time there is a notification on desktop shows 'syntax error', this is pretty annoying , could we make it turn off as default option?

**Comment by PanJiaChen** [comment]
https://github.com/vuejs-templates/webpack/blob/cd4d7d957c9af3d37092c79bf490b56b8d88b108/template/config/index.js#L20

**Comment by shanegibney** [comment]
In config/index.js

    notifyOnErrors: false,
