### ISSUE TITLE
Why put logo.png  in template/build/

### ISSUE THREAD

**Issue by dlintw** [vuejs-templates/webpack#1193]
Is it necessary? or can use symbolic link to assets/logo.png?

**Comment by 66beta** [comment]
build/utils.js
```js
notifier.notify({
      title: packageConfig.name,
      message: severity + ': ' + error.name,
      subtitle: filename || '',
      icon: path.join(__dirname, 'logo.png')
    })
```

_assets_ is for your project

**Comment by dlintw** [comment]
Does this will pack into final production package? If I don't want it, could I remove this icon line safely?

**Comment by PanJiaChen** [comment]
If you set 
https://github.com/vuejs-templates/webpack/blob/cd4d7d957c9af3d37092c79bf490b56b8d88b108/template/config/index.js#L20

```js
notifyOnErrors: false
```
you will never use it. And it used only in dev env.

**Comment by LinusBorg** [comment]
Can confirm. This logo is only used for the notifications you can get on build errors.
