### ISSUE TITLE
Suggestion: Use clean-webpack-plugin to wipe assetsRoot during build

### ISSUE THREAD

**Issue by ianwalter** [vuejs-templates/webpack#1196]
https://github.com/johnagan/clean-webpack-plugin

This plugin has worked well for me and would reduce the custom code footprint in this template. I'll submit a PR if any maintainers agree.

**Comment by LinusBorg** [comment]
Hi and than a for the suggestion, but I don't think we need another plugin to replace two lines of code. 

If this plugin offered additional advantages I would reconsider, but I don't see them.
