### ISSUE TITLE
using an .env file 

### ISSUE THREAD

**Issue by SSmale** [vuejs-templates/webpack#1198]
Hi,

I have added a .env file to pull in my firebase API key (FIREBASE_KEY) to the root of my project but I cannot get the variable out using process.env.FIREBASE_KEY. how do I go about doing this?

**Comment by chiayutsaipersonal** [comment]
const dotenv = require('dotenv')

dotenv.config() // before process.env.FIREBASE_KEY is accessed

**Comment by LinusBorg** [comment]
I'm actually working on a bigger PR to support this properly across all features / modes of this template in #1178 

hiayutsaipersonal has already gotten th important part - using `dotenv`, I just want to make clear that this only gets you the API key into the node process that's running (ie.e webpack), not into your app.

So to get it into your app, you would have to add it to `/config/dev,ev.js`:
```javascript
require('dotenv').config()

module.exports = {
  NODE_ENV: '"development"',
  FIREBASE_KEY: JSON.stringify(process.env.FIRBASE_KEY)
}
```

**Comment by SSmale** [comment]
Awesome thanks. Yes that last part is the bit I was missing to pass the param through. 

Kind regards,

Simon Smale
