### ISSUE TITLE
Error during build - TypeError: requestShortener.shorten is not a function

### ISSUE THREAD

**Issue by jingle2008** [vuejs-templates/webpack#1200]
Reproduction link (this is created using the webpack template with very little change)
https://github.com/jingle2008/doc-browser

Steps to reproduce
In CLI, npm run build
What is expected?
Expected a Vue build without errors.

What is actually happening?
λ npm run build

> portal@1.0.0 build F:\Development\Web\Vue\portal
> node build/build.js

- building for production...F:\Development\Web\Vue\portal\node_modules\uglifyjs-webpack-plugin\dist\index.js:272
          return new Error(`${file} from UglifyJs\n${err.message} [${requestShortener.shorten(original.source)}:${original.line},${original.column}][${file}:${err.line},${err.col}]`);
                                                                                      ^

TypeError: requestShortener.shorten is not a function
    at Function.buildError (F:\Development\Web\Vue\portal\node_modules\uglifyjs-webpack-plugin\dist\index.js:272:87)
    at F:\Development\Web\Vue\portal\node_modules\uglifyjs-webpack-plugin\dist\index.js:206:56
    at Array.forEach (<anonymous>)
    at F:\Development\Web\Vue\portal\node_modules\uglifyjs-webpack-plugin\dist\index.js:189:21
    at step (F:\Development\Web\Vue\portal\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:90:11)
    at done (F:\Development\Web\Vue\portal\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:99:22)
    at F:\Development\Web\Vue\portal\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:105:15
    at F:\Development\Web\Vue\portal\node_modules\worker-farm\lib\farm.js:191:19
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portal@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the portal@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Dev server will run as expected, tried updating packages (including global ones).
When looking at the source code in Webpack, I do see "shorten" as a function defined.
Vue is version 2.5.13, and CLI is latest.

**Comment by PanJiaChen** [comment]
Maybe you can focus on  https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/197

**Comment by jingle2008** [comment]
I googled first and didn't find that one, thanks

**Comment by LinusBorg** [comment]
It seems the plugin was updated and 1.16 should have this fixed:

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v1.1.6
