### ISSUE TITLE
What is the advantage of using Jest if snapshotting doesn't work?

### ISSUE THREAD

**Issue by ffxsam** [vuejs-templates/webpack#1203]
I noticed the new Jest option in the webpack template (nice!). But without the snapshot feature (one of Jest's most compelling features), I'm not sure what the advantage is over using Mocha & Karma.

**Comment by LinusBorg** [comment]
You are assuming that we know the problem you are talking about?

**Comment by LinusBorg** [comment]
So I just tested this out of curiosity, and sure enough it works well:

Added this test:
```javascript
  it('should match snapshot', () => {
    const Constructor = Vue.extend({ ...HelloWorld})
    const vm = new Constructor().$mount()
    expect(vm.$el.outerHTML).toMatchSnapshot()
  })
```

Result:

![bildschirmfoto 2018-01-02 um 15 53 15](https://user-images.githubusercontent.com/1444526/34487557-15544f5c-efd5-11e7-8cca-5c3e2eaf686b.png)

Changing the component's output fails the snapshot test, running with `-u` updates the snapshot - just as expected.

**Comment by ffxsam** [comment]
@LinusBorg That's great! It wasn't documented at all so I wasn't sure how to go about doing it.

**Comment by LinusBorg** [comment]
Hm, I didn't really document it because didn't know what to document. the only thing to "know" is how to get the HTML via `vm$el.outerHTML`
