### ISSUE TITLE
Postcss cannot build

### ISSUE THREAD

**Issue by Vocal** [vuejs-templates/webpack#1204]
Hi all,

i'm an vuejs newbie, I have problem with build component with postcss, it's can't transform to css.

i create new project with
```
$ npm install -g vue-cli
$ vue init webpack my-project
$ cd my-project
$ npm install
$ npm run dev
```

In my component 
```
<style lang="postcss">
:root { 
  --red: #d33;
}
a { 
  &:hover {
    color: color(var(--red) a(54%));
  }
}
</style>
```

after run `npm run build `
```:root {
  --red: #d33;
}
a.temp {
  color: #7fffd4;
  &:hover {
    color: color(var(--red) a(54%)) !important;
  }
}
```

How can i build postcss ?
Thanks!

**Comment by LinusBorg** [comment]
postcss doesn't transform css vriables by default, you have to inlcude a postcss-plugin that does, i.e. [cssnext](http://cssnext.io/).

Just install it and add it to the postcss config file in your project's root.
