### ISSUE TITLE
Full Page Reload instead of HMR

### ISSUE THREAD

**Issue by codeofsumit** [vuejs-templates/webpack#1209]
Since a couple of months every old and new project reloads the whole page instead of specific components.

I use single file components and no matter what I change - it's a full page refresh every time.
Is this intended?

**Comment by LinusBorg** [comment]
Of course not, why should we disable HNR on purpose? 

What's confusing me is that you say that happens for old projects as well. Otherwise I would have thought we have a problem with the new webpack-dev-server setup (which works well for me).

**Comment by codeofsumit** [comment]
hmm no. Brand new project, regular file system on a mac...
Is there a project I can clone where you can verify Hot Module Reloading works? Then I can nail down if it's my project setup or something with my mac.

**Comment by codeofsumit** [comment]
oh, and have a save and fun new years 🍾 🚀 😊

**Comment by codeofsumit** [comment]
@LinusBorg based on [this comment](https://github.com/webpack/webpack-dev-server/issues/949#issuecomment-315283799) I tried commenting out line 41 in `build/dev-server.js` and HMR is working again 🎉 

```js
hotMiddleware.publish({ action: 'reload' })
```

Not sure what that means exactly I just tried what I found during research. Can you make any sense of that?

**Comment by LinusBorg** [comment]
Ah, yes. 

That part of the devservrr was responsible for reloading the page when index.html changes. 

However. the html-webpack-plugin we use to process index.html doesn't play nice with webpack >=3 in that regard, so we had to remove that code when we moved to webpack 3 a while back. 

I assume you moved to webpack 3 on your own...

**Comment by codeofsumit** [comment]
ah ok. Weird 🤔.
So I can remove that line without damage to the setup?

**Comment by LinusBorg** [comment]
Yes. As I said we removed it as well.
