### ISSUE TITLE
Keep ejs tags in index file

### ISSUE THREAD

**Issue by Herover** [vuejs-templates/webpack#1210]
I'm trying to export the the project with a bit of the text on the page inserted into a `<noscript>` tag for people with javascript off and search engines. 
However, the code inside ejs tags seems to be run when building the project so that `<noscript><%- 1+2 %></noscript>` turns into `<noscript>3</noscript>`.
I have tried adding `ignoreCustomFragments: [ /<%[\-\=].*?%>/ ],` to the HTMLMinifier without any luck.

**Comment by LinusBorg** [comment]
the [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) does that. You would have to check the README or ask in their github how to fix it.

Alterntively, ask on forum.vuejs.org or chat.vuejs.org if people now a trick.

**Comment by Herover** [comment]
Thank you, I got it working by installing html-loader and adding 
```
      {
        test: /\.ejs$/,
        use: [{
          loader: 'html-loader'
        }]
      }
```
to `module.rules` in the webpackConfig.
