### ISSUE TITLE
migrate to new template

### ISSUE THREAD

**Issue by miladmeidanshahi** [vuejs-templates/webpack#1212]
Hi how can i migrate my old webpack template to new one ?

**Comment by MaxMilton** [comment]
I believe there's no automated way to do this right now. You'll need to manually run a diff against the changes.

Use `vue init webpack vue-webpack-fresh` to get an up-to-date base template and then use a diff tool such as [meld](http://meldmerge.org) to see what the changes are.

**Comment by jpikora** [comment]
You can also "re-init" the template directly in existing project and then resolve the changes. I've done it multiple times, it's not that bad :).
