### ISSUE TITLE
Support absolute reference of assets from templates

### ISSUE THREAD

**Issue by italomaia** [vuejs-templates/webpack#1213]
Given I have a assets folder in my src folder, with some images inside, like this:

```
src/assets/
.. img01.png
.. img02.png
```

It would be very nice to reference these resources with a absolute path, rather than a relative path. It is very bad for coupling to reference a image in such path as: <img src="../../assets/img01.png" alt="" /> when the absolute path is known.

**Comment by LinusBorg** [comment]
That's what webpack aliases can be used for. The template already comes with one, `@/` is an alias for the srcn`/src` directory. 

So you can simply do this: `'@/assets/img01.png'`

**Comment by LinusBorg** [comment]
Notw that you would have to prepend that with a tilde (`~`) when used in a template or css
