### ISSUE TITLE
What is meant by 'first-in-class'?

### ISSUE THREAD

**Issue by 311289189** [vuejs-templates/webpack#1222]
@yyx990803 on line 36 in `README.md` what is meant by 'first in class'?

```
- `npm run dev`: first-in-class development experience.
```
I am just curious
Thanks

**Comment by LinusBorg** [comment]
It just means that it gives you a very good deception emu experience because it's configured with many good things that make your development experience better. 

You can check the rest of the docs to learn what that entails.

**Comment by 311289189** [comment]
@LinusBorg Sorry, what is a deception emu experience?

**Comment by LinusBorg** [comment]
That was my phone trying to auto correct 😂 

I meant "development experience"

**Comment by 311289189** [comment]
ahh thanks @LinusBorg!
