### ISSUE TITLE
Last update broke routing on dev server

### ISSUE THREAD

**Issue by AlexAlabyev** [vuejs-templates/webpack#1224]
After the `webpack.dev.conf.js` file has been updated in the last update, routing doesn't work on localhost in `mode: 'history'` anymore:

### Steps to reproduce
Run default installation to create a new project:
`vue init webpack projectName`

1. Run: `npm run dev`
2. Create any component (e.g. `Contact.vue`)  
3. Import it as usual and add the route (e.g. `/contact`)
4. Add `mode: 'history'`

---

- You won't be able to open the route by typing it in the address bar, you'll see: `Cannot GET /contact`
- If you navigate to it by pressing a button with route link, you will see the component, but refresh the page and you'll get the same result: `Cannot GET /contact`

### What is expected?
To work in mode: 'history' on localhost (`npm run dev`)

### What is actually happening?
Router doesn't work in mode: 'history' on localhost (`npm run dev`)

---
Additional info:

https://stackoverflow.com/questions/48123503/why-does-vue-router-webpack-dev-server-shows-cannot-get-path-on-page-refresh

**Comment by LinusBorg** [comment]
Are you on windows? I just fixed a bug concerning this for windows users, but haven't pushed it to master yet. You can test the develop branch

**Comment by AlexAlabyev** [comment]
@LinusBorg Yes, I'm on windows, thank you for fixing it. 

Just to make sure, is the `vue init webpack projectName` command going to get the fixed version of the template as soon as you push it into the master, right? 

Do you think it will take approximately in a few days? Or more like a week?

**Comment by LinusBorg** [comment]
Tomorrow late evening at the latest.  may be n the next two hours. I'm on a trip right now, but have my laptop in the hotel.

**Comment by LinusBorg** [comment]
Give it another try, should work now.

**Comment by AlexAlabyev** [comment]
@LinusBorg yes it does. Thank you for such a quick fix! I think the issue can be closed now (if you think so)
