### ISSUE TITLE
Last update broke assets on dev server

### ISSUE THREAD

**Issue by AlexAlabyev** [vuejs-templates/webpack#1225]
After the last update Webpack doesn't see images in assets folder created by Vue CLI and you have to transfer all the images into "static" folder (which took me personally an hour to figure out. I would imagine it will confuse a lot of people)

### Steps to reproduce
1. Run default installation to create a new project:
`vue init webpack projectName`

2. Run dev server:
`npm run dev`
  
3. Put an image in assets folder and try to display it in the code, it will return `404`

**Comment by LinusBorg** [comment]
> try to display it in the code, 

* What exactly did you do? 
* does the Vue logo show up for you? 

While I'm on mobile atm and can't verify, I can say that I installed the latest template multiple times in the last days and the logo always showes up, which means that images from `./assets` do work as expected.

**Comment by AlexAlabyev** [comment]
I just create a new project the same way as described above, and changed 

**This default code:**

`<img src="./assets/logo.png">
`

**To this:** 

```
<img :src="image">

[...]

export default {
  name: 'app',
  data () {
    return {
      image: './assets/logo.png'
    }
  }
}
```

**Which gives me this console error:**

`GET http://localhost:8080/assets/logo.png 404 (Not Found)`

Now if I copy the logo into static folder and change the path it will work:

```
export default {
  name: 'app',
  data () {
    return {
      image: '../static/logo.png'
    }
  }
}
```

**Comment by LinusBorg** [comment]
Yeah that never worked that way. 

If you want to define the path in your js,  it have to use `require('. /....')`

**Comment by AlexAlabyev** [comment]
@LinusBorg sorry, I'm a newbie, but It did work before the template update. I've just copied pasted everything in the new project that I created after the template update.   
I don't understand why did it all my images worked before? What kind of black magic is this?

**Comment by LinusBorg** [comment]
It may have worked by accident, since the dev server served static content from the project root before extent update. 

But it would have broken in production. 

Read The template docs about handling static assets.

**Comment by wowlin** [comment]
$ vue init webpack vue-project

  Unknown command init.


   vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)
