### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by robertmain** [vuejs-templates/webpack#1232]
Wondered if someone could point me in the right direction of getting font awesome to load with this template? It seems not to be pulling through the stock webpack setup. 

I installed `fontawesome` with npm, and I can `require()` it just fine in my `App.vue` - however, it looks like no CSS is pulling through..

**Comment by grantcarthew** [comment]
Are you using SASS?

Put this in your app.scss file:

```css
// Load font-awesome
$fa-font-path: '~font-awesome/fonts';
@import '~font-awesome/scss/font-awesome';
```

**Comment by saintplay** [comment]
This seems like a forum question.
I suggest you to use https://github.com/Justineo/vue-awesome

**Comment by robertmain** [comment]
@grantcarthew Yeah, that failed. I got this message:
```
Module build failed:
undefined
^
      File to import not found or unreadable: ~font-awesome/scss/font-awesome
```

@saintplay Do you have the URL of the forum?

**Comment by saintplay** [comment]
https://vuejs.org/v2/guide/join.html

**Comment by robertmain** [comment]
Thanks, @saintplay - VueAwesome seems to be working for me :)
