### ISSUE TITLE
"ERROR" vue init webpack my-project

### ISSUE THREAD

**Issue by Shiyinq** [vuejs-templates/webpack#1237]
When i done install vue-cli  like this (npm install --global vue-cli) 
and then i create project like this  (vue init webpack my-project)
but i get some error like this..

D:\Dokumen\Vue>vue init webpack my-project
C:\Users\Shiyinq\AppData\Roaming\npm\node_modules\vue-cli\node_modules\is\index.js:1
(function (exports, require, module, __filename, __dirname) { ��Y�6�P��h�����Ѐ���W�:��V�p��������؀
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Shiyinq\AppData\Roaming\npm\node_modules\vue-cli\node_modules\metalsmith\lib\index.js:6:10)

why this is happen ?

**Comment by LinusBorg** [comment]
What's your node version?

**Comment by Shiyinq** [comment]
This is i use..

node -v = v8.9.1

npm -v = 4.6.1

vue -V = 2.9.2

**Comment by LinusBorg** [comment]
Versionsook fine, no idea what may cause that on your end. All. Is working fine for me.

**Comment by Shiyinq** [comment]
I do not know .. I have not found the solution yet, and I still get the same error.
is this a bug ? or is there something i missed by me ? Please let me know.

**Comment by IlhamWahabiGX** [comment]
try to update your npm

**Comment by Shiyinq** [comment]
hahha thankyou bro@IlhamWahabiGX this problem solved..  :D

**Comment by Shiyinq** [comment]
just update npm to version 5.6.0 and then uninstall vue-cli and then install again vue-cli, the last.. vue init webpack my-project and SOLVED.
.
thank you verry much  @IlhamWahabiGX
.
i can close issue now..
