### ISSUE TITLE
init webpack fails when vue isn't installed globally

### ISSUE THREAD

**Issue by adimit** [vuejs-templates/webpack#1264]
Given the following `package.json`

```
{
  "name": "details",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "author": "",
  "license": "ISC",

  "dependencies": {
    "vue": "^2.5.13"
  },
  "devDependencies": {
    "vue-cli": "^1.0.0"
  }
}
```

I've run the following commands in a docker container so they're reproducable:

```
docker run --rm -ti -v $(pwd):/src --user 1000 node:8 bash
$ cd /src
```

When initialising an empty webpack repo, vue-cli just fails with a JS error:

```
$ npm install
$ node_modules/.bin/vue init webpack test
description: test.js
if_or: (y/N) y
if_eq: (y/N) y
e2e: (y/N) 
name: (test) 
unit: (y/N) y
author: me <me@me.com>
lint: (y/N) y
router: (y/N) n
template_version: 
unless: (y/N) y
```
This configuration results in:

```
   vue-cli · ((helpers.if_or || (depth0 && depth0.if_or)) || helperMissing).call is not a function
```

I've tried several different combination of flags (the flags have no documentation at all that I could find. Not very newbie-friendly!) and the error remains the same, except when I don't include `if_or`:

```
   vue-cli · Missing helper: 'if_or'
```

**Comment by LinusBorg** [comment]
I'm not sure whats going on here since this template does not ask you if you want to include if_or or something. 

I also have no what flags you are talking about, can you clarify?

**Comment by adimit** [comment]
Thanks for your answer, @LinusBorg 
I do have the feeling something is rather wrong in the way I'm trying to set up the template.

So I've tried it with `vue-cli` being installed *globally* (with `npm install -g vue-cli`) and it worked as expected. I can reproduce the above behaviour only with a package-local install of `vue-cli` to `node_modules/.bin/vue`.

As such, the problem is probably not, after all, related to this template in particular, but to `vue-cli`. I don't know enough about vue to decide that — but feel free to close this issue if you think it sin't relevant to the template.

I called the above `y/N` questions "flags" in my report.

**Comment by LinusBorg** [comment]
Okay, I understand.

But we use a locally installed vue-cli package in all of our automated tests in CircleCI, which also run on docker, and those work fine:

https://github.com/vuejs-templates/webpack/blob/develop/.circleci/config.yml

So maybe it's related to the docker image you use, or the npm version installed or something else you do.

**Comment by adimit** [comment]
Interesting. Maybe I can try to find a way to replicate the problem with your setup. Though for me the problem occurred with a local installation both on my Fedora 27 host machine, and on the official docker `node:8` image, so I didn't really have that esoteric a setup.

**Comment by MarkProffitt** [comment]
I have the same problem on:
Ubuntu 16.04 
vue-cli@2.9.2 
node v8.9.4
npm 5.6.0

**Comment by LinusBorg** [comment]
@adimit I only now noticed that you installed vue-cli with `^1.0.0` version. Why? That would install a very old version which very probably doesn't worm wit this template. 

@MarkProffitt that doesn't apply to yiu, obviously. I would assume your situation is different, what're exactly is happening?

**Comment by MarkProffitt** [comment]
vue init webpack wptut

  A newer version of vue-cli is available.

  latest:    2.9.2
  installed: 2.0.2

[ { name: '1.0',
    commit: 
     { sha: '49b3ac5de552ab82ac6b44f3bb197bfc54063688',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/49b3ac5de552ab82ac6b44f3bb197bfc54063688' } },
  { name: 'develop',
    commit: 
     { sha: 'd8fb86400e67be892208cb1d606a9681de949648',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/d8fb86400e67be892208cb1d606a9681de949648' } },
  { name: 'fix_installerror_1168',
    commit: 
     { sha: 'a5a47eda8566e900ea24e4b9216216f45c16e133',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/a5a47eda8566e900ea24e4b9216216f45c16e133' } },
  { name: 'gh-pages',
    commit: 
     { sha: '73e8b76a64193f291c99dd46daf6fbec46030b7f',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/73e8b76a64193f291c99dd46daf6fbec46030b7f' } },
  { name: 'improve_env_var_usage',
    commit: 
     { sha: '4f0f8eb160090879d206a61f023d26b5b52f728f',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/4f0f8eb160090879d206a61f023d26b5b52f728f' } },
  { name: 'improve_template_tests',
    commit: 
     { sha: '730f331630051b6fc1ca4913aec4d29cd5a33be6',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/730f331630051b6fc1ca4913aec4d29cd5a33be6' } },
  { name: 'master',
    commit: 
     { sha: 'c29ab6a4679f74d970e025bb60c4602542eaff08',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/c29ab6a4679f74d970e025bb60c4602542eaff08' } },
  { name: 'optimize_CI_recognition',
    commit: 
     { sha: '1fdcdd976394c671fd98d45e34b29c176203e4fd',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/1fdcdd976394c671fd98d45e34b29c176203e4fd' } } ]
? name wptut
? author me
   **vue-cli · Missing helper: "if_or"**

I've tried uninstalling, installing local and global. I don't know why it's getting that message about the latest version. It randomly comes & goes.  It doesn't matter what version is shows it always get the error 
**vue-cli · Missing helper: "if_or"**

webpack-simple: works
pwa: fails 
webpack: fails

**Comment by LinusBorg** [comment]
> latest: 2.9.2
> installed: 2.0.2

Your version is outdated

**Comment by MarkProffitt** [comment]
I get the same error with both versions

vue init webpack wptut

[ { name: '1.0',
    commit: 
     { sha: '49b3ac5de552ab82ac6b44f3bb197bfc54063688',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/49b3ac5de552ab82ac6b44f3bb197bfc54063688' } },
  { name: 'develop',
    commit: 
     { sha: 'd8fb86400e67be892208cb1d606a9681de949648',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/d8fb86400e67be892208cb1d606a9681de949648' } },
  { name: 'fix_installerror_1168',
    commit: 
     { sha: 'a5a47eda8566e900ea24e4b9216216f45c16e133',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/a5a47eda8566e900ea24e4b9216216f45c16e133' } },
  { name: 'gh-pages',
    commit: 
     { sha: '73e8b76a64193f291c99dd46daf6fbec46030b7f',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/73e8b76a64193f291c99dd46daf6fbec46030b7f' } },
  { name: 'improve_env_var_usage',
    commit: 
     { sha: '4f0f8eb160090879d206a61f023d26b5b52f728f',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/4f0f8eb160090879d206a61f023d26b5b52f728f' } },
  { name: 'improve_template_tests',
    commit: 
     { sha: '730f331630051b6fc1ca4913aec4d29cd5a33be6',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/730f331630051b6fc1ca4913aec4d29cd5a33be6' } },
  { name: 'master',
    commit: 
     { sha: 'c29ab6a4679f74d970e025bb60c4602542eaff08',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/c29ab6a4679f74d970e025bb60c4602542eaff08' } },
  { name: 'optimize_CI_recognition',
    commit: 
     { sha: '1fdcdd976394c671fd98d45e34b29c176203e4fd',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/1fdcdd976394c671fd98d45e34b29c176203e4fd' } } ]
? name wptut
? author me
   **vue-cli · Missing helper: "if_or"**

**Comment by LinusBorg** [comment]
If that helper is missing, you do *not* use the most recent version.

**Comment by MarkProffitt** [comment]
OK, how do I get it I?  I've uninstalled. Installed locally, Installed globally. I've tried sudo. Nothing solves this problem. I just tried installing it again but as I've said it doesn't matter if the version warning happens or not, the **vue-cli · Missing helper: "if_or"**  always happens with webpack

mark@Sputnik:/var/www/html$ npm i -g vue-cli
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/home/mark/.npm-global/bin/vue-init -> /home/mark/.npm-global/lib/node_modules/vue-cli/bin/vue-init
/home/mark/.npm-global/bin/vue -> /home/mark/.npm-global/lib/node_modules/vue-cli/bin/vue
/home/mark/.npm-global/bin/vue-list -> /home/mark/.npm-global/lib/node_modules/vue-cli/bin/vue-list
+ vue-cli@2.9.2
updated 1 package in 17.214s
mark@Sputnik:/var/www/html$ vue init webpack wptut

  A newer version of vue-cli is available.

  latest:    2.9.2
  installed: 2.0.2

[ { name: '1.0',
    commit: 
     { sha: '49b3ac5de552ab82ac6b44f3bb197bfc54063688',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/49b3ac5de552ab82ac6b44f3bb197bfc54063688' } },
  { name: 'develop',
    commit: 
     { sha: 'd8fb86400e67be892208cb1d606a9681de949648',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/d8fb86400e67be892208cb1d606a9681de949648' } },
  { name: 'fix_installerror_1168',
    commit: 
     { sha: 'a5a47eda8566e900ea24e4b9216216f45c16e133',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/a5a47eda8566e900ea24e4b9216216f45c16e133' } },
  { name: 'gh-pages',
    commit: 
     { sha: '73e8b76a64193f291c99dd46daf6fbec46030b7f',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/73e8b76a64193f291c99dd46daf6fbec46030b7f' } },
  { name: 'improve_env_var_usage',
    commit: 
     { sha: '4f0f8eb160090879d206a61f023d26b5b52f728f',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/4f0f8eb160090879d206a61f023d26b5b52f728f' } },
  { name: 'improve_template_tests',
    commit: 
     { sha: '730f331630051b6fc1ca4913aec4d29cd5a33be6',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/730f331630051b6fc1ca4913aec4d29cd5a33be6' } },
  { name: 'master',
    commit: 
     { sha: 'c29ab6a4679f74d970e025bb60c4602542eaff08',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/c29ab6a4679f74d970e025bb60c4602542eaff08' } },
  { name: 'optimize_CI_recognition',
    commit: 
     { sha: '1fdcdd976394c671fd98d45e34b29c176203e4fd',
       url: 'https://api.github.com/repos/vuejs-templates/webpack/commits/1fdcdd976394c671fd98d45e34b29c176203e4fd' } } ]
? name wptut
? author me
   vue-cli · Missing helper: "if_or"

mark@Sputnik:/var/www/html$

**Comment by LinusBorg** [comment]
So `vue -v` says `2.9.2`, yet installing the template fails? 

In that case: absolutely no idea where to start. 

If that command doesn't return `2.9.2` even though you did `npm install vue-cli@latest -g`, then your node npm installation is probably messed up.
