### ISSUE TITLE
Default config babel not support Destructuring parameters.

### ISSUE THREAD

**Issue by chuanxd** [vuejs-templates/webpack#1272]
The older Chrome browsers are failed, when js code have Destructuring parameters.
```
Uncaught SyntaxError: Unexpected token {
```

```javascrip
function fn ({ foo, bar }) { ... }
```

**Comment by LinusBorg** [comment]
Babel should transpile that, and I never came across this.

Are you sure the .bablerc config is intact?

**Comment by chuanxd** [comment]
ok, I don't understand why my project have this issue.
