### ISSUE TITLE
webpack.DefinePlugin has weird constraints and does not work, use webpack.EnvironmentPlugin instead

### ISSUE THREAD

**Issue by diit** [vuejs-templates/webpack#1275]
// Partial Bug report / Feature Request

## Expected:
- Added variable to `config/dev.env`, have that variable be accessible to the codebase.

## Actual:
- Seemingly no effect, env variables not accessible.

## Fix and Recommended Workaround:
```
new webpack.EnvironmentPlugin(require('../config/dev.env')),
```

This also solves the issue of having to "double-wrap" strings.

**Comment by LinusBorg** [comment]
I don't see such problems, can you provide a real reproduction for us to evaluate? 

Since EnvironmentPlugin is just a wrapper around the DefinePlugin afaik, I would rather suspect a mistake on your part without such a reproduction

**Comment by LinusBorg** [comment]
Hi there!

I close this issue because of inactivity. If you want to follow up on this issue, please open a new one, and provide the necessary information (a working reproduction etc.) in that issue.
