### ISSUE TITLE
`Vue.config.productionTip = false` doesn't seem to be working

### ISSUE THREAD

**Issue by ghost** [vuejs-templates/webpack#1279]
Hello, I read that I'd need to add the above config option to disable the (annoying) production mode warning ("You are running Vue in development mode.") in my console, but noticed that my generated `main.js` already includes this via:

https://github.com/vuejs-templates/webpack/blob/d8fb86400e67be892208cb1d606a9681de949648/template/src/main.js#L11

But the message still appears. Has anyone else solved this problem?

To reproduce, this was a new project created with the current versions from a fresh install of all tools involved.

**Comment by LinusBorg** [comment]
If that really is the case, you should rather open an issue in the main Vue repo. This is not a feature of this template.
