### ISSUE TITLE
Sass number precision

### ISSUE THREAD

**Issue by ehel** [vuejs-templates/webpack#1281]
I'm using bootstrap 3 with webpack template and it looks like I'm having an issue with the default number precision of 5.
Problem is with alignment of an input group:
![input_group_problem](https://user-images.githubusercontent.com/11447762/35589284-00325a5e-060c-11e8-903e-068d99d4393a.png)

I think default number precision should be 8.
![screenshot 2018-01-30 22 25 31](https://user-images.githubusercontent.com/11447762/35589438-841e1790-060c-11e8-8926-39187489d117.png)

Should i create a pull request with this change?

**Comment by LinusBorg** [comment]
I would be open to that if it's  common problem. I personally don't have much experience with that, so I can't tell.

**Comment by whjvenyl** [comment]
Why bootstrap has settled for a precision of 8 instead of 5 (as defined in node-sass) I do not know. But I would avoid from having framework specific tweaks getting into this template.

**Comment by LinusBorg** [comment]
Good point.

**Comment by LinusBorg** [comment]
So I thought about this some more and agree with @whjvenyl - we should not add this.
