### ISSUE TITLE
Extracting imported css/scss with webpack

### ISSUE THREAD

**Issue by Quadriphobs1** [vuejs-templates/webpack#1282]
I have just installed a clean installation of we pack, and I have configured the webpack to extract CSS into a single file, but I still can't figure out how to extract CSS imported in `.js` file, I know it is in the documentation that it has to be configured, but can anyone put me on how that can be done.

I have in my `main.js` this
```
import '@/assets/sass/app.scss'
```

how can I export it in a single file alongside extracted CSS in  `.vue` file.

**Comment by LinusBorg** [comment]
There should be nothing for you to do, this template is pre configured to extract all css, from `.vue` and `.js` files as well.

**Comment by Quadriphobs1** [comment]
Yes its extracting the css and add them to the head tag, but i need to extract them and save it in a file, that is working for styles in .vue but not in .js

**Comment by LinusBorg** [comment]
Are you talking about dev or build? 

In build, *all* css is extracted into one file. 

If that doesn't work for you, please provide a repository with a reproduction

**Comment by Quadriphobs1** [comment]
Well i guess am using dev for now i havent yet tested it on build

**Comment by LinusBorg** [comment]
In dev we inject all styles into head for hot reloading.

**Comment by Quadriphobs1** [comment]
Ohhh okay.
