### ISSUE TITLE
How to use Vuex with this template...?

### ISSUE THREAD

**Issue by glomotion** [vuejs-templates/webpack#1286]
Hey there. 

I'm trying to get Vuex working with this starter template - with quite limited success. Is there a specific config change needed to the prod build - for vuex to function normally online?

Basically, when run locally, vue-devtools detects the vuex store just fine. But when I build and deploy (say, using simple: `$ surge dist/`) - the online version displays: "No Vuex store detected". Even though all store based logic, and other vue component inspection still works just fine.  

**working locally:**
![screen shot 2018-02-02 at 5 53 29 pm](https://user-images.githubusercontent.com/1452237/35720501-10947372-0842-11e8-9412-a0a2f4133fde.png)

**not working online:**
![screen shot 2018-02-02 at 5 44 20 pm](https://user-images.githubusercontent.com/1452237/35720188-b8b93e4a-0840-11e8-8a52-c0672c9f2e6e.png)

So to reproduce this bug:

1. create project: (basic project with vue-router && airbnb eslinting)
`
$ vue init webpack test-vue-vuex
`
2. install vuex as a depdency:
`
$ yarn add vuex
`
3. make /src/main.js the following:
```
import Vue from 'vue';
import Vuex from 'vuex';

import App from './App';
import router from './router';

Vue.use(Vuex);
const store = new Vuex.Store({
  state: {
    moo: true,
  },

  mutations: {
  },

  getters: {
  },

  actions: {
  },
  strict: process.env.NODE_ENV !== 'production',
});

Vue.config.productionTip = false;
Vue.config.devtools = true;

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  components: { App },
  template: '<App/>',
});
```
4. build, then deploy to surge: 
`
$ yarn build; surge dist/
`

**Comment by LinusBorg** [comment]
This is not a big and not related to the template. 

Devtools don't work by default in production mode. Try setting Vue.config.devtools to true. 

https://vuejs.org/v2/api/#devtools

**Comment by glomotion** [comment]
Ummm. Did you see that line in my main.js?

Vue.config.devtools = true;

Is there something else I have to set?

**Comment by glomotion** [comment]
Also, as shown in the screenshots, devtools work just fine online. Only the store inspection doesn’t.

**Comment by LinusBorg** [comment]
I missed that line, sorry. 

Please open an issue in the devtoola repository with a reproduction that the guys can run for themselves. 

The problem is most likely not related to this template.
