### ISSUE TITLE
Keys defined in dev.env.js are not accessible

### ISSUE THREAD

**Issue by pmesgari** [vuejs-templates/webpack#1287]
Hi,

Based on [Environment Variables](http://vuejs-templates.github.io/webpack/env.html) the keys defined in `dev.env.js` file must be accessible when running `npm run dev` in the app.

This is the content of my `dev.env.js`:
```
'use strict'
const merge = require('webpack-merge')
const prodEnv = require('./prod.env')

module.exports = merge(prodEnv, {
  NODE_ENV: '"development"',
  SAMPLE: '"XX"',
  AUTH_URL: '"http://localhost:3030"'
})
```

And when I try to access `AUTH_URL` in `App.vue` like this `process.env.AUTH_URL`, I receive `undefined`

**Comment by thezachcannon** [comment]
Same is happening to me @pmesgari 

EDIT: I had the wrong syntax for my environment variable...Did you restart your server after adding these variables?

**Comment by LinusBorg** [comment]
@pmesgari Any further input? I can't really reproduce this ... Can you provide a repository with a minimal production?

**Comment by pmesgari** [comment]
@LinusBorg I have been trying to reproduce this, it might have been an issue with chrome debugger or webpack itself, I did a complete restart of my computer, and now it works. If it happens again, I will let you know.

**Comment by NoahCardoza** [comment]
I am having a similar problem, `process.env` is empty... even though I haven't touched the config files...

**Comment by vesper8** [comment]
I believe I may be dealing with the same issue. I get process is not defined. I opened an issue here

https://github.com/vuejs/vue-cli/issues/934

Which includes a repro repo
