### ISSUE TITLE
vue with nginx

### ISSUE THREAD

**Issue by umardraz** [vuejs-templates/webpack#1288]
Hi I am running node+express+vue 

Here is my nginx configuration 

```
server {

  listen 443;
  server_name mydomain.com;
  ssl                  on;
  ssl_certificate      /root/mydomain.com.cert;
  ssl_certificate_key  /root/mydomain.com.key;
  ssl_session_timeout  5m;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

  location / {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
    }
}

```
With the above configuration I can access my site using https://mydomain.com but in Chrome's console there are some error appears.

```
GET https://localhost:8080/sockjs-node/info?t=1517580112789 net::ERR_CONNECTION_REFUSED
client?d420:175 [WDS] Disconnected!
sockjs.js?3600:1601 GET https://localhost:8080/sockjs-node/info?t=1517580112789 net::ERR_CONNECTION_REFUSED
```

Would you please help me why localhost:8080 is still appears? and how to fix this

**Comment by LinusBorg** [comment]
This question is only indirectly related to the template and likely not bug. 

I would kindly ask you to use forum.vuejs.org for way rations like these, to keep the issue tracker focused on bugs etc.
