### ISSUE TITLE
Feature Request: Add Gzip to Production Build

### ISSUE THREAD

**Issue by DragonI** [vuejs-templates/webpack#130]
Currently, the production build only minifies JS and CSS files. To improve performance, they should be gzipped.

I used [Webpack's Compression Plugin](https://github.com/webpack/compression-webpack-plugin) and documented in the [Vue forum](http://forum.vuejs.org/topic/4059/adding-gzip-to-webpack-using-compression-plugin)

Thx

**Comment by yyx990803** [comment]
Serving gzipped content will be server-dependent, so it's better to be behind a config flag.
