### ISSUE TITLE
deploy & run production build on nginx/apache server

### ISSUE THREAD

**Issue by swamy526** [vuejs-templates/webpack#1301]
is it possible to  deploy & run production build on nginx/apache server. or node server is mandatory. I am newbie to web-pack build and etc. Please let me know if there are online docs or steps available.

**Comment by heinzdmx** [comment]
Take a look at for example https://stackoverflow.com/questions/42936588/how-to-deploy-vue-app

Your question is not specific to this template, this is very general to how webpack works, so I would suggest you read up on webpack dev/production builds. 

Basically when developing you use `npm run dev`
When you want to create a production build you run `npm run build` and that creates standard html, css and javascript that can be run through any HTTP file server. So to answer your question, yes any nginx and apache server can be used. However your development and build machine needs node to create a production build. 

**Note** if you use Vue router with HTML5 history mode enabled it requires a little more, see [Vue router documentation](https://router.vuejs.org/en/essentials/history-mode.html)

This would probably be better suited as a forum post on [https://forum.vuejs.org/](https://forum.vuejs.org/) or on stackoverflow as this issue tracker is meant to be focused on bugs or new features for the webpack template, and not support questions.
