### ISSUE TITLE
Autoprefix only work on dev not build

### ISSUE THREAD

**Issue by DragonCat1** [vuejs-templates/webpack#1305]
#### I did not change any config
![-1](https://user-images.githubusercontent.com/17510330/36386155-c726fc28-15cf-11e8-800b-64a4902c4d25.png)

**Comment by afontcu** [comment]
Hi!

I think autoprefixer is working fine, it's just using browserslist to decide whether or not prefixes should be added. Try adding `user-select: none` and it will properly [add prefixes](https://caniuse.com/#feat=user-select-none) in your dist files. Transform attribute [does not require](https://caniuse.com/#search=transform) prefixes in last browser versions.


If you change your browserslist config to something like

```json
"browserslist": [
  "> 0.5%",
  "last 15 versions"
]
```

you'll see more vendor prefixes being added.

__

So the question could be "why is dev build adding prefixes?". Is it possible that dev build process ignores browserlist? But... another question: does it even matter? 

hope it helps!

**Comment by DragonCat1** [comment]
@afontcu thanku you are right
