### ISSUE TITLE
backslash instead of forward slash is used in index.html when building on Windows, js and css not found on Firefox

### ISSUE THREAD

**Issue by SNiels** [vuejs-templates/webpack#131]
`<script src=/static\app.e86d343b39ebf3203005.js></script>`instead of `<script src=/static/app.e86d343b39ebf3203005.js></script>` is being injected in the index.html when building project.

All browsers will replace backslashes with forward slashed automatically with the exception of Firefox.
This results in Firefox not finding the javascript and css and getting 404 from my webserver instead.

I temporarily fixed it by adjusting the paths like this in 'webpack.prod.conf.js':
`path.join(config.build.assetsSubDirectory, '[name].[contenthash].css').replace('\\', '/')`.

**Comment by DragonI** [comment]
I'm using Win7 with the latest version of the webpack template. I haven't experienced this problem. I just retested my production build against FF 47.0b6 and 48.0a2 and the script and link tags are properly pathed:

```
<link href="/static/css/app.36d8b7a1d322a4b6cd3dcb054c72ff4c.css" rel="stylesheet">
<script type="text/javascript" src="/static/js/app.a548be7550600628533c.js"></script>
```

BTW, I'm using nginx

**Comment by SNiels** [comment]
I'm using Windows 10 and FF 44.0.2 and Firebase hosting.

**Comment by chrisvfritz** [comment]
@SNiels Are you sure you're not using an older version of the template? The latest `webpack.prod.conf` includes this:

``` js
utils.assetsPath('css/[name].[contenthash].css')
```

rather than:

``` js
path.join(config.build.assetsSubDirectory, '[name].[contenthash].css')
```

**Comment by SNiels** [comment]
I'm using the template that came with Vue 1.0.19. Not entirely sure what version of the vue-cli I had globally installed back then. In that case, this probably isn't an issue in the current version.
Thank you anyways!
