### ISSUE TITLE
Index.html trying to fetch webpack-built resources that don't exist

### ISSUE THREAD

**Issue by qualisign** [vuejs-templates/webpack#1310]
I'm using Vue v. 2.5.2 and Webpack 3.6.0.

I've developed an app that relies on a module that uses a worker (`pdfjs-dist`).   When I try to build my files using `npm run build`, the output seems fine, but when I do something on the site that requires the worker, I get an error in the console saying that the worker file couldn't be found:

`NetworkError: Failed to load worker script at "http://.../docuapp/documentation/_design/uploads/static/js/app.4eb1aecbadc78360a76e.worker.js" (unbekannt) Error: Loading chunk 0 failed. Stack-Trace: u@http://.../docuapp/documentation/_design/uploads/static/js/manifest.a6f78538bddeebdefd4a.js:1:957 manifest.a6f78538bddeebdefd4a.js:1:1378 Error: Loading chunk 0 failed. manifest.a6f78538bddeebdefd4a.js:1:957`

So I check out the url that's failing to load, and the document is missing. But when I remove the worker part of the url, i.e.

http://.../docuapp/documentation/_design/uploads/static/js/app.4eb1aecbadc78360a76e.js

This page loads, and I'm guessing that's the resource that's needed.

Does anyone have any guesses as to what's going wrong here?

**Comment by LinusBorg** [comment]
No. I don't know the package you refer to and you didn't share any code about how you used that package or created the worker.

Also, we have great forum at forum.vuejs.org for questions like these, (about how to use a 3rd party package with the template).
