### ISSUE TITLE
Why is the installed vue version 2.5.2 and not a newer one?

### ISSUE THREAD

**Issue by focussing** [vuejs-templates/webpack#1311]

**Comment by LinusBorg** [comment]
Well, it doesn't. package.json requires "^2.5.2", which is a semver version range and boils down to: "the latest patch release in the 2.5 version range, but at least 2.5.2"

**Comment by focussing** [comment]
So it should update to 2.5.13 after npm install?
Sorry, it doesn't do that.

Not when creating the project:
![schermafbeelding 2018-03-01 om 14 11 49](https://user-images.githubusercontent.com/26736152/36846632-ae0e04a0-1d5b-11e8-8802-12b546ef18e7.png)

Nor when I run `npm install` on the command line again (to be sure).

Could there be a string comparison error, instead of an integer comparison of the third field?
String comparison will say that 2.5.2 is newer than 2.5.13 (versus 2.5.02 is not newer than 2.5.13).

**Comment by LinusBorg** [comment]
> Sorry, it doesn't do that.

How did you verify that?

**Comment by focussing** [comment]
I checked the package.json in the ./node_modules/vue folder. At the bottom of that file the version is stated.
Deleted the node_modules folder and ran npm install again.
Now the version number is correct.

So somewhere I made a mistake. Very sorry for bothering you!
