### ISSUE TITLE
Problems importing font-awesome

### ISSUE THREAD

**Issue by burzum** [vuejs-templates/webpack#1313]
I've tried to use `yarn add font-awesome` and added the import to my `App.vue`:

```html
<template>
  <div id="app">
    <main-nav></main-nav>
    <div class="container">
      <!--<img src="./assets/logo.png">-->
      <router-view/>
    </div>
  </div>
</template>

<script>
  import MainNav from "./components/MainNav.vue";

  export default {
    components: {MainNav},
    name: 'App'
  }
</script>

<style lang="css">
  @import '../node_modules/vue-multiselect/dist/vue-multiselect.min.css';
</style>

<style lang="scss">
  @import '../node_modules/bootstrap/scss/bootstrap.scss';
  @import '../node_modules/font-awesome/scss/font-awesome';
</style>

<style>
  #app {
    font-family: 'Avenir', Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    color: #2c3e50;
    margin-top: 0px;
  }
</style>

```

This error came then up:

```sh
./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-04c2046b","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=1!./src/App.vue
Module not found: Error: Can't resolve '../fonts/fontawesome-webfont.eot' in 'C:\xampp\htdocs\jagd\src'
 @ ./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-04c2046b","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=1!./src/App.vue 7:193414-193457
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-04c2046b","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=1!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

I have no idea why, I've checked the config files and there are loaders for eot, wot and so on defined. Is this an issue with the template configuration? Requires it additional configuration?

It might be just me, but honestly the build setup for JS apps is a huge PITA. :(

**Comment by LinusBorg** [comment]
This is a known problem with font-awesome and similar laibraries that come with fonts etc.

To learn more about it, see this:

https://www.npmjs.com/package/sass-loader#problems-with-url

As to the solution:

font-awesome (You are still using v4, I think) allows you to set a vairable that tells SCSS where lo look for the fonts:

https://github.com/FortAwesome/Font-Awesome/blob/fa-4/scss/_variables.scss#L4

It should be set Like this:
```html
<style lang="scss">
  // I can remember what was correct:
  $fa-font-path: "font-awesome/fonts";
  $fa-font-path: "~font-awesome/fonts";
  $fa-font-path: "./node_modules/font-awesome/fonts";

  @import '../node_modules/bootstrap/scss/bootstrap.scss';
  @import '../node_modules/font-awesome/scss/font-awesome';
</style>
```

**Comment by burzum** [comment]
Thanks a lot @LinusBorg! 

Would be nice if the template contains a note about this in the docs or even asks you if you want to use if and auto adds it for you when creating the template app?

And yes, I'm, using 4 because 5 doesn't seem to be available via npm yet.

**Comment by LinusBorg** [comment]
We won't add font-awesome as an option to the template, I don't think so. That's too specific. 

But I have a feeling we could make this work by adding url-resolve-loader into the loader chain for *css resources . 

I'll look into that.

**Comment by kshitijmehta** [comment]
Hi @LinusBorg  ,
Did adding the 'resolve-url-loader' made the fonts load up ?
 Mine did not. And it is frustrating :@

**Comment by ghost** [comment]
Hi @burzum, @LinusBorg and @kshitijmehta.

You can install fontawesome 5 like this.

```shel
npm install @fortawesome/fontawesome-free-webfonts
```

try this.
enter the path in the $ fa-font-path variable and import all required scss.
```vue
<template>
    <div>
        <h3>
            Hello FontAwesome
            <i class="fa fa-exclamation"/>
            <i class="fas fa-star"/>
            <i class="far fa-star"/>
            <i class="fab fa-linux"/>
        </h3>
    </div>
</template>

<script>
export default {
    name: "FontAwesome"
};
</script>

<style lang="scss">
    $fa-font-path : "~@fortawesome/fontawesome-free-webfonts/webfonts";
    @import "~@fortawesome/fontawesome-free-webfonts/scss/fontawesome.scss";
    @import "~@fortawesome/fontawesome-free-webfonts/scss/fa-solid.scss";
    @import "~@fortawesome/fontawesome-free-webfonts/scss/fa-regular.scss";
    @import "~@fortawesome/fontawesome-free-webfonts/scss/fa-brands.scss";
</style>
```
![image](https://user-images.githubusercontent.com/2777921/40434831-9bcf049a-5e85-11e8-9243-4d8fcbd119ef.png)

I recommend including the <style> part within your main component, usually app.vue or main.vue.

**Comment by wilfredonoyola** [comment]
@psc001 This package has been deprecated, Maybe We will need another solution.

**Comment by danielrsantana** [comment]
There are another way of solving it without additional packages. I've explained [here](https://github.com/webpack-contrib/less-loader/issues/53#issuecomment-460712100). To prevent the possibility of broken link, I will post it again:

Here is how I've solved, considering the solutions posted by (@alexsasharegan and @cchamberlain):

**My architecture:** 
```
    React 16.7.0
    Typescript 3.3.1
    Bulma 0.7.2 (similar to bootstrap)
    FontAwesome 5.7.1
```

1) **Package.json** (packages I've used. You can switch to far or fal)

```
    (...)
    "dependencies": {
        "@fortawesome/fontawesome-free": "^5.7.1",
        "@fortawesome/free-solid-svg-icons": "^5.7.1",
    };
   (...)
```


2) **In your webpack.config (very essential):**

```
    (...)
    {
        test: /.(png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$/,
        use: "url-loader?limit=100000"
    }
    (...)
```


3) **In your main scss file** :
```
    $fa-font-path : "~@fortawesome/fontawesome-free/webfonts";
    @import "./node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss";
    @import "./node_modules/@fortawesome/fontawesome-free/scss/solid.scss";
```

4) **That will allow you to use Font Awesome like this:** 
```    
    <i className="fas fa-check" />
```


**Just in time**: if you want to use FontAwesome as a component, look at their documentation that well explains how to import the JS files to put it to work.

https://fontawesome.com/how-to-use/on-the-web/using-with/vuejs

Hope it helps and I've posted here because since last message some packages changed.

**Comment by OzzyTheGiant** [comment]
If you're using Vue CLI 3, @danielrsantana's method works, with no configuration needed, just add the sass code to your main.scss file.

**Comment by jrichardsz** [comment]
this worked for me:

https://stackoverflow.com/questions/57243755/webpack-module-not-found-error-cant-resolve-webfonts-fa-solid-900-eot/63804707#63804707
