### ISSUE TITLE
Uncaught SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by coderdiaz** [vuejs-templates/webpack#1315]
Arrow functions fails!

![image](https://user-images.githubusercontent.com/1901273/36708785-5e1f7bd6-1b3a-11e8-9bcc-683fd0c244c0.png)

Uncaught SyntaxError: missing ) after argument list :(

**Comment by afontcu** [comment]
Hi!

Could you provide some kind of environment info or even better, a repository link? It's hard to know what's going on without context.

Arrow functions should be working out of the box, so it must be something else.

**Comment by coderdiaz** [comment]
Sorry. 
Error in my config env vars. 🤦‍♂️

**Comment by binarykitchen** [comment]
i'm having this too - which config env var did you have wrong @coderdiaz ?

**Comment by coderdiaz** [comment]
@binarykitchen missing double quote on var, example: 

**Error**
`API_URL: 'http://myservice.com/api'`

**Correct**
`API_URL: '"http://myservice.com/api"'`

**Comment by binarykitchen** [comment]
and where did you define that var @coderdiaz ?

**Comment by coderdiaz** [comment]
The file for dev environment is `config/dev.env.js`

**Comment by binarykitchen** [comment]
ah ok, thx
