### ISSUE TITLE
ESLint not working in .vue files

### ISSUE THREAD

**Issue by zigomir** [vuejs-templates/webpack#132]
I can use double quoted strings in `.vue` files inside `script` tag but `npm run lint` nor webpack dev server won't warn me like it does when you screw up `.js` file. All my packages are latest at this point in time.

I'm using `standard` eslint config. I have [these](https://github.com/vuejs-templates/webpack/blob/dist/template/build/webpack.base.conf.js#L29-L42) `preLoaders` inside `webpack.base.conf.js` file.

I'm reporting issue without PR because I'm not a `webpack` expert. :(

**Comment by chrisvfritz** [comment]
Hmm, I can't reproduce this personally (on OS X 10.11.4, node 5.11.1). What's your OS and node version?

**Comment by zigomir** [comment]
Huh, I see where the problem is now. I'm using `<script type="text/ecmascript-6">` these scripts to get proper ES6 for WebStorm and this breaks ESLint. Will dig deeper.

**Comment by chrisvfritz** [comment]
Ah, would updating to `type="text/babel"` fix it? I _think_ that also works with Webstorm.

**Comment by zigomir** [comment]
That was it. With `type="text/babel"` eslint will work inside `.vue` files and WebStorm will work with ES6 syntax. Thank you @chrisvfritz ! :)

**Comment by sergeymorkovkin** [comment]
With PhpStorm it doesn't seem to work...

**Comment by zigomir** [comment]
It works through webpack and you can se errors in browser + terminal. But inside editor yep. But I think two places are enough :)

**Comment by sergeymorkovkin** [comment]
Php/WebStorm use stdin to pass source code. And (what in more interesting) some tricky algorithms to detect which files should lint, and which should not.

**Comment by devboxr** [comment]
Sorry to dig this up - but I also have this issue. Using Atom, normal JS files show inline errors and warnings [like this](http://prntscr.com/c1xc0n). However, in `.vue` files this is not the case. I do see the errors in the console and browser, but not inline.

Any tips? Or is this intended due to limitations?

**Comment by chrisvfritz** [comment]
@devboxr In the settings for Atom's ESLint package, you have to check a box to enable Linting within HTML files.

**Comment by devboxr** [comment]
@chrisvfritz Thanks! That did indeed do something, but is being followed by this:

```
TypeError: Cannot read property 'map' of undefined
    at /Users/robin/Development/skappbar.dev/node_modules/eslint-plugin-html/src/index.js:86:39
    at Array.forEach (native)
    at Object.postprocess (/Users/robin/Development/skappbar.dev/node_modules/eslint-plugin-html/src/index.js:85:19)
    at processText (/Users/robin/Development/skappbar.dev/node_modules/eslint/lib/cli-engine.js:252:30)
    at CLIEngine.executeOnText (/Users/robin/Development/skappbar.dev/node_modules/eslint/lib/cli-engine.js:761:26)
    at Object.cli.execute (/Users/robin/Development/skappbar.dev/node_modules/eslint/lib/cli.js:181:36)
    at lintJob (/Users/robin/.atom/packages/linter-eslint/lib/worker.js:35:10)
    at /Users/robin/.atom/packages/linter-eslint/lib/worker.js:69:20
    at Emitter.emit (/Users/robin/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /Users/robin/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
```

I'm using a fresh `npm` installation, all files being the default.

```
$ node -v
v6.3.1

$ npm -v
npm@3.10.3 /usr/local/lib/node_modules/npm
```

Any idea?

**Comment by yisibl** [comment]
https://github.com/lkiarest/eslint-plugin-vuefix

**Comment by jbreuer95** [comment]
+1
