### ISSUE TITLE
No PostCSS config found

### ISSUE THREAD

**Issue by Sparkenstein** [vuejs-templates/webpack#1328]
I am working on an application in webpack template, the same project works on linux but on windows when I run `npm run dev` it gives me error : No PostCSS config found in : /my/dir/name on all custom CSS and SCSS files. 
If i change the configuration in webpack.base.conf.js, and add test for css and scss with `vue-loader`, the project compiles successfully but no style renders on webpage when I visit the link. only text. 
Here is the partial section from my package.json
```JSON
"scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "build": "node build/build.js"
  },
"dependencies": {
    "buefy": "^0.6.3",
    "node-sass": "^4.7.2",
    "postcss-load-config": "^1.2.0",
    "sass-loader": "^6.0.6",
    "vue": "^2.5.2",
    "vue-awesome": "^2.3.4",
    "vue-material-design-icons": "^1.1.0",
    "vue-router": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
```
Also, if I change this line:
`rules: utils.styleLoaders({ sourceMap: config.dev.cssSourceMap, usePostCSS: true })`
to 
`rules: utils.styleLoaders({ sourceMap: config.dev.cssSourceMap, usePostCSS: false})`
everything works perfect, but I don't know if this is the acceptable solution. because the first approach works on my arch machine. 
How can different behaviors on different platforms be possible?

**Comment by LinusBorg** [comment]
Hi, sorry this isn't working for you.

> How can different behaviors on different platforms be possible?

In most cases, this is related either to paths (`\` vs. `/`)  or to case-sensitivity (some OS / file-systems are case-sensitive, others aren't).

So is the postcss config file written in all lowercase? Where is it stored, did you alter it?

I'm not quite sure what to look for, to be honest, a runnable reproduction would be helpful, as the error explanation is a bit sparse, a stack trace would be helpful.

>  I don't know if this is the acceptable solution.

Not really. That option make sure that normal *css files are run through postcss for autoprefixing etc.

**Comment by LinusBorg** [comment]
Question: why did you add this as a dependency? 
```
"postcss-load-config": "^1.2.0
```

**Comment by rubaiet** [comment]
Same issue here.

**Comment by LinusBorg** [comment]
No feedback from OP, closing.

**Comment by Vitormdias** [comment]
Same issue here
