### ISSUE TITLE
 Failed to download repo vuejs-templates/webpack

### ISSUE THREAD

**Issue by zzzgit** [vuejs-templates/webpack#1334]
![image](https://user-images.githubusercontent.com/1060733/37695757-856f3094-2d0c-11e8-8c4b-e3258de567a0.png)

**Comment by yoyo837** [comment]
You can only try again, there is no other way.

**Comment by dwfrost** [comment]
I also meet this problem, can vue-cli work?
![image](https://user-images.githubusercontent.com/26833988/40414295-6fdb2812-5eaa-11e8-8a0f-bdeb89658588.png)

**Comment by bobpappas** [comment]
Doesn't work for me.

bpappas-281:Code bpappas$ vue init webpack fire-app

  Unknown command init.


   vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)

**Comment by LinusBorg** [comment]
you're using vue-cli 3 which is a rewrite. The init plugin now lives as a separate plugin.

You can find the docs here: https://github.com/vuejs/vue-cli/blob/dev/docs/cli.md#pulling-vue-cli2x-templates-legacy

I would suggest to use the new cli though.
