### ISSUE TITLE
apparent change in style precedence between dev and prod

### ISSUE THREAD

**Issue by robbiemu** [vuejs-templates/webpack#1337]
https://stackoverflow.com/questions/49437942/vue-cli-webpack-precedence-of-styles

Basically, npm i bootstrap-sass  -- styles there will not override component scoped styles in npm run dev, but will in npm run build.

I'm not sure why this is: it is not apparently OptimizeCssPlugin, ExtractTextPlugin, nor ModuleConcatenationPlugin, as I've brought these across to dev and it still preserves order.

in vue-loader.conf.js, this resolves the problem (but obviously is not ideal):
```
module.exports = {
  loaders: utils.cssLoaders({
    sourceMap: sourceMapEnabled,
    extract: false
  }),
```

**Comment by LinusBorg** [comment]
That will be fixed in vue-loader 15
