### ISSUE TITLE
Change the background-xxx's value

### ISSUE THREAD

**Issue by ChangeZhang** [vuejs-templates/webpack#1339]
i write this 
![image](https://user-images.githubusercontent.com/6948367/37883547-ab5acbe0-30dd-11e8-8e80-81f2698cd16f.png)
after npm run build..
![image](https://user-images.githubusercontent.com/6948367/37883576-cd66d008-30dd-11e8-9e78-e5a0e270af77.png)
How should I solve it not to change this value！！

**Comment by LinusBorg** [comment]
Please use the forum 

forum.vuejs.org
