### ISSUE TITLE
[Feature Request]Any plans to upgrade the following code to MiniCssExtractPlugin

### ISSUE THREAD

**Issue by ruchernchong** [vuejs-templates/webpack#1342]
As per title, are there plans to upgrade the following code to use `MiniCssExtractPlugin` since the Webpack team is ending support for `ExtractTextWebpackPlugin`.

https://github.com/vuejs-templates/webpack/blob/4ffcccb2e3b5c8f18ac5c28023ed983bb183ef96/template/build/utils.js#L48-L51

The reason for this issue is because I am unable to use the `MiniCssExtractPlugin.loader` for extracting the css.

**Comment by LinusBorg** [comment]
We might switch this template to webpack 4 in some time. When we do that, we will use rust plugin as well
