### ISSUE TITLE
No eslintrc is created

### ISSUE THREAD

**Issue by avivace** [vuejs-templates/webpack#1348]
If you decide to enable eslint, the cli doesn't automatically run `./node_modules/.bin/eslint --init` for you, leading to a situation you have npm run dev not working with generic error about eslint.
Why not install the [`vue/essential`](https://www.npmjs.com/package/eslint-plugin-vue) for eslint and add a basic eslintrc using it?

**Comment by LinusBorg** [comment]
I don't understand what you mean.
