### ISSUE TITLE
Mozilla PDF.js in production, worker not found(404) (dist/ae30f3e662c6be53b059.worker.js )

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [vuejs-templates/webpack#1349]
Hi, I'm using [PDF.js,](https://mozilla.github.io/pdf.js/) everything works in DEV mode, but when I run `yarn build` the worker for pdf.js is out of `dist/static/js` folder as the others files are. the PDF file does not show in page because this file is missing on path.

This Guy had the same issue but I can't fix with Vue-cli

[https://github.com/FranckFreiburger/vue-pdf/issues/23]()

See how the file is generated

![pdf1](https://user-images.githubusercontent.com/3034127/38180781-68d9e008-3605-11e8-9ac5-6fa27bd46aec.PNG)

The 404 error

![pdf2](https://user-images.githubusercontent.com/3034127/38180791-77f6c61e-3605-11e8-979a-c1c6a1f3f52d.PNG)

The `build/webpack.prod.conf.js` I tried to change
![pdf3](https://user-images.githubusercontent.com/3034127/38180874-ec596e4e-3605-11e8-8238-f485cff7f2ae.PNG)

What do I need to change in Webpack config to make it work in production?

**Comment by dak** [comment]
Are you importing the webpack script provided?

```js
// import PDFJS from 'pdfjs-dist'; // not for webpack
// import PDFJS from 'pdfjs-dist/webpack'; // webpack script that properly includes worker
```

**Comment by rodrigorodriguescosta** [comment]
I think this issue is because the app is in subfolder on web server, I changed the `config/index.js` from `assetsPublicPath: '/',` to `assetsPublicPath: '/mypath',` but now showing this error

I guess this is not related to that config

![pdf3](https://user-images.githubusercontent.com/3034127/38200650-91cd9e26-366b-11e8-8cfe-7a82e87aec6a.PNG)

**Comment by LinusBorg** [comment]
Guys, please use the forum for questions about stuff like this. 

Forum.vuejs.org

**Comment by MicahDetamore** [comment]
Glad we got a solution to this! Google didn't lead me to the forums, my friend. It led me here! Think of all the people you helped out since this was asked, Linus!
