### ISSUE TITLE
try to quasar build and apk file 

### ISSUE THREAD

**Issue by lavanvickyneshwaran** [vuejs-templates/webpack#1351]
$ quasar build

 app:build Built files are meant to be served over an HTTP server +0ms
 app:build Opening index.html over file:// won't work +0ms

**Comment by LinusBorg** [comment]
What does that have to do with this template?

**Comment by lavanvickyneshwaran** [comment]
@LinusBorg  how to build apk in quasar ? 
i try to 
$npm run build 

npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Thiluxsan\AppData\Roaming\npm-cache\_logs\2018-04-24T07_32_57_586Z-debug.log

but i have some error massage
 i can't build whats problam? 
help me
