### ISSUE TITLE
the font-family in app css

### ISSUE THREAD

**Issue by iulo** [vuejs-templates/webpack#1352]
Hi, a boring question:
Why you guys use `font-family: 'Avenir', Helvetica, Arial, sans-serif;` in `https://github.com/vuejs-templates/webpack/blob/develop/template/src/App.vue#L27`

I never see `Avenir` in any project, most of them use `-apple-system` .
Is it just a personal taste?

Sorry for the boring question.

**Comment by LinusBorg** [comment]
I have no idea to be honest. Evan wrote that css probably 2 years ago
