### ISSUE TITLE
How to use mixins from .scss files in .vue files? 

### ISSUE THREAD

**Issue by kont-wayfinder** [vuejs-templates/webpack#1354]
Hi,

I got an error - "no mixin named sm" when trying to use my scss mixins in Single Vue Components - sm is my mixin variable name.

My _mixins.scss is in my assets/styles folder. How can i use my mixins in .vue files?

**Comment by afontcu** [comment]
Hi,

I think you'll need to import the mixins file in your components. You can read [some alternatives here](https://github.com/vuejs/vue-loader/issues/328).

long story short: `import` the file in your component or add it [to your webpack configuration](https://github.com/vuejs/vue-loader/issues/883#issuecomment-317557131).

Hope it helps!
