### ISSUE TITLE
:img 

### ISSUE THREAD

**Issue by bluelemonade** [vuejs-templates/webpack#1356]
hi,

I tried to change a few image tags to things from the vue store.

`src="../assets/bildname.jpg" `

changed to 

`:src="imageSrc"`

and the computed  method therefore is

```
imageSrc: function(){ 
           return "../assets/" + this.card.jpg  + ".jpg"
       },
```
in the console I got this error:  http://localhost:8080/assets/bildname.jpg (not Found)
ok, how can I include the images from the assets folder?

regards.

**Comment by LinusBorg** [comment]
When the path comes from Js, you have to use require():
```javascript
return require("../assets/" + this.card.jpg  + ".jpg")
```
