### ISSUE TITLE
Vuejs deploying to multiple environments 

### ISSUE THREAD

**Issue by Meenakshise** [vuejs-templates/webpack#1360]
Hi, 

We have multiple test environments. So once the Vuejs build is done. It can be deployed to any of the test environments like testenv1.com, testenv2.com and so on. 

```
module.exports = merge(devEnv, {
  NODE_ENV: '"testing"',
  BASE_URL : '"https://someurl.com/VueAPI/"'
})
```
In the prod.env.js file, the base url for the API call is set. This has to be changed based upon my deployment environment. 

So basically i will just do only one build in team city and with that package (emitted js files (app.js, manifest.js , vendor.js  and css files) i should be able to deploy the same package to multiple environments. 

So in my app.js the below URL has to be changed based upon the enviroment that i am deploying to in octopus. How can we achieve this. 
NODE_ENV:"testing",BASE_URL:"https://someurl/VueAPI/",URL:hello}

Please help me here. I am damn stuck.

**Comment by loama** [comment]
Sure there is a better solution (cleaner) but you could have a function that changes the Base url depending on the host.

Where you are declaring base_url have it inside some ifs or a switch.

**Comment by Meenakshise** [comment]
thanks for the reply. I got a solution in octopus itself and was able to fix it.
