### ISSUE TITLE
Fail on console errors during e2e testing

### ISSUE THREAD

**Issue by ianwalter** [vuejs-templates/webpack#137]
I want to fail my tests if there are any console errors on the page so I added a custom assertion:
```
.assert.noConsoleErrors()
```
I would personally want this assertion in all my projects so my first question is, would adding this assertion to the template be desired?

Secondly, [Vue warn] errors aren't outputted when `process.env.NODE_ENV = 'production'`. If I wanted them to be outputted during testing, should I just create a separate `webpack.test.conf.js` that extends `webpack.prod.conf.js` with `NODE_ENV` changed to `testing`? Would adding that config to the template be desired?

**Comment by chrisvfritz** [comment]
@ianwalter The method you describe of creating a testing config for Webpack sounds logical to me. I'd love to hear others' thoughts on whether this kind of change would be a good fit in the template.

**Comment by chrisvfritz** [comment]
There hasn't been any community desire for this it seems, so I'm closing for now.
