### ISSUE TITLE
Dev server fails abruptly after some changes.

### ISSUE THREAD

**Issue by limistah** [vuejs-templates/webpack#1370]
We have a pretty long list of components, and what we have done is to split all the SFC sections into separate files. Such that we don't interfere and break (unintentionally) what others have done. So the JS, HTML, and CSS all live in separate files.

And now we are running into this problem of the server failing after some time (mostly after the second reload, due to file changes). 

We have checked nearly all our codebase to make sure that nothing is missing and that nothing is taking an unnecessary memory space.

Below is the error from the console output, I will love to provide other details that could be required, and hope it is fixed as soon (if it is from this end). 
`
95% emitting                                                                 . <--- Last few GCs --->
[27913:0x103000000]   259635 ms: Mark-sweep 1370.2 (1406.6) -> 1370.2 (1406.6) MB, 546.5 / 0.2 ms  allocation failure GC in old space requested
[27913:0x103000000]   260262 ms: Mark-sweep 1370.2 (1406.6) -> 1370.2 (1399.6) MB, 627.4 / 0.2 ms  last resort GC in old space requested
[27913:0x103000000]   260827 ms: Mark-sweep 1370.2 (1399.6) -> 1370.2 (1399.6) MB, 564.8 / 0.1 ms  last resort GC in old space requested
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x3a61dd125739 <JSObject>
    1: fromString(aka fromString) [buffer.js:342] [bytecode=0x3a616ba46949 offset=161](this=0x3a61575822d1 <undefined>,string=0x3a61d6f32949 <Very long string[6238990]>,encoding=0x3a61dd135d39 <String[4]: utf8>)
    2: from [buffer.js:193] [bytecode=0x3a616ba46429 offset=14](this=0x3a615ccbb919 <JSFunction Buffer (sfi = 0x3a61dd17e329)>,value=0x3a61d6f32949 <Very long string[6238990]>,encodingOr...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 7: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 8: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
 9: node::Buffer::(anonymous namespace)::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
10: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
11: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
12: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x2be266a042fd
14: 0x2be266abd1e0`

**Comment by afontcu** [comment]
[Here](https://github.com/webpack/webpack/issues/2157) they suggest changing your sourcemap devtool.

Hope it helps!

**Comment by limistah** [comment]
@afontcu I am currently experimenting the suggestion.

**Comment by limistah** [comment]
I have updated `config/index.js` and now have the `devtool` set to:

`
...
module.exports = {
  dev: {
    ...,
    devtool: 'cheap-eval-source-map',
    ...
}
`

So far, I am having a positive result.

As the last resort, I will be using [increase-memory-limit](https://www.npmjs.com/package/increase-memory-limit) package.
