### ISSUE TITLE
Just a feedback

### ISSUE THREAD

**Issue by rowild** [vuejs-templates/webpack#1371]
From what I understood from ES2015 - event hough I didn't find any resource talking about that - trailing semicolons and commas are best not used where possible.
Not: this package, that comes with eslint, throws nothing but errors because of missing commas and semicolons.
Why is that? Why is the package's eslint not configured the way the package needs it to be?
Any reasons?

**Comment by emanuelmutschlechner** [comment]
@rowild What lint configuration do you use? 
* standard
* airbnb
* none

**Comment by rowild** [comment]
AirBnb. I already adjusted the rc file and it is working now. 
But for something that should work out-of-the box, there should be some info coming along, when the user selects the options...

**Comment by emanuelmutschlechner** [comment]
Semicolons are enforced by the airbnb style https://github.com/airbnb/javascript/blob/master/README.md#semicolons

There is a simple and quick fix to most eslint problems:
```bash
npm run lint --fix
```
or
```bash
yarn run lint --fix
```

**Comment by rowild** [comment]
Thanks! That is a very good tip! (It should be mentioned in the setup process, but I assume you are not one of the developers, are you?)

**Comment by emanuelmutschlechner** [comment]
No, I've never contributed to this project yet.

**Comment by emanuelmutschlechner** [comment]
Looking at the source code, there is a message with that lint fix tip. https://github.com/vuejs-templates/webpack/blob/4f564a2715dd9ca39307c5603a3b91f0523f1f67/utils/index.js#L95
