### ISSUE TITLE
Webpack 4 ?

### ISSUE THREAD

**Issue by gplusdotgr** [vuejs-templates/webpack#1373]
Are there plans to move to webpack 4.x? There are plenty of changes. (I just did this myself and there are issues like source maps not working etc)

**Comment by ChadTaljaardt** [comment]
dupe of https://github.com/vuejs-templates/webpack/issues/1280

Also here is a working pr : https://github.com/vuejs-templates/webpack/pull/1369

You can use it by running 

```js 
vue init noamkfir/webpack#webpack-4 project
```

**Comment by ChadTaljaardt** [comment]
Can we close this issue as its a duplicate of the above?
