### ISSUE TITLE
Hot reload no longer works (webpack dev server is not detecting changes)

### ISSUE THREAD

**Issue by kim366** [vuejs-templates/webpack#1380]
Hello, since today hot reload no longer works while using this repo built with vue-cli. I believe the browser is looking for updates by the dev server correctly, but the dev server does not rebuild the files when I make changes. In fact it does not give any indication that it detected the change. I rolled back my git repo and even on the initial commit that it worked on yesterday, it did not work today. Even on a fresh project I could not get hot reloadig to work.

This means that I currently have to Ctrl-C the server and start it again, making it rebuild all files, which takes a couple of seconds and hinders my workflow.

I believe that since yesterday I updated npm and some packages, but nothing that would break the dev server. I also installed Vue devtools, I will see if the issue remains when I uninstall those.

I am using Antergos Linux 4.15.14-1-ARCH x86_64 with NPM version 6.0.1, Node version 9.10.1 and webpack-dev-server 3.1.4 with webpack 4.5.0.

**Comment by taylorren** [comment]
Same issue here. Very strange.

**Comment by kim366** [comment]
Yeah, had to switch back to Windows for the time being, unfortunately.

**Comment by kim366** [comment]
It's magically working again, smh. Was there some update?

**Comment by lefuturiste** [comment]
Same issue
