### ISSUE TITLE
This relative module was not found

### ISSUE THREAD

**Issue by akoboy** [vuejs-templates/webpack#1383]
What's wrong with url's in sass???????

`This relative module was not found:

* ../../images/line-gray.png in ./node_modules/css-loader??ref--10-1!./node_modules/postcss-loader/lib??ref--10-2!./node_modules/sass-loader/lib/loader.js??ref--10-3!./src/assets/sass/main.
scss`

Structure
-src
--assets
---images
---sass
----blocks
----settings
---main.scss
--components
--pages
--router
-App.vue
-main.js

In `settings\_base.scss` a have `.dark-line {background-image: url('../../images/line-gray.png');}`

`resolve-url-loader` also didn't help

**Comment by akoboy** [comment]
changed url to `~@/assets/` and worked

**Comment by abdellahrk** [comment]
@akoboy you saved a life. 
Thank you!

**Comment by Tentative** [comment]
@akoboy Thank you, still saving lives

**Comment by nthieu** [comment]
@akoboy it still works. Thank you!

**Comment by obiwanpelosi** [comment]
@akoboy . It still works, thank you! Wonder what's really causing this problem tho
