### ISSUE TITLE
What is the purpose of logo.png in template/build/ directory?

### ISSUE THREAD

**Issue by jamesjieye** [vuejs-templates/webpack#1396]
There is a `logo.png` file in side the `template/build/` directory. Not sure what's the purpose of adding this file here. And this file was initially added in this commit https://github.com/vuejs-templates/webpack/commit/aba0f9c7b7903a5371469ecbd80b6f7df93fe536. But no mention of why it was added.

My guess is that this file accidentally sneaked into this folder. Maybe should be removed.

**Comment by cngu** [comment]
It's being used for node-notifier (in the same commit you referenced).

**Comment by jamesjieye** [comment]
@cngu Thanks!
