### ISSUE TITLE
Can't get this working with vue-router

### ISSUE THREAD

**Issue by ebuchmann** [vuejs-templates/webpack#14]
Whenever I try to set up the vue router with this template I end up getting a `Cannot GET /` message in my browser. I have a project from a couple weeks ago, using this same template, and it works fine there. The major different that I've noticed is the build/webpack.dev.conf.js file has changed a lot. If I copy the other one over from my working project it starts working again.

To reproduce just set up a new project using this template from the cli and try to set up vue-router. Maybe I'm just doing it wrong too.

**Comment by jondcallahan** [comment]
+1 reproduced this just a few minutes ago

**Comment by yyx990803** [comment]
It's working properly for me... any compilation errors? Can't help without a reproduction.

**Comment by ebuchmann** [comment]
https://github.com/ebuchmann/VueRouterIssue

Here you go. It's the basic install with vue cli using webpack. In the `build/webpack.dev.con.js` file I've commented out an older version of the file that I had, which seems to work fine. Right now it just says `Cannot GET /` and doesn't show anything else in my browser that may help. No errors in the terminal other than linting issues with spaces.

**Comment by yyx990803** [comment]
Did you notice the lint warnings in the console after you do `npm run dev`? You need to fix the lint errors for the bundle to compile.

**Comment by ebuchmann** [comment]
Interesting. Didn't think it would be so picky about leaving a warning about having four spaces instead of two. Thanks!

**Comment by yyx990803** [comment]
The template comes with pre-configured ESlint linting. You can either tweak it to your own preference or disable it by removing `eslint` in [here](https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js#L29) and [here](https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js#L48).
