### ISSUE TITLE
components 里的模块更改不会触发 hot reload

### ISSUE THREAD

**Issue by haozime** [vuejs-templates/webpack#140]
App.vue 会触发 hot reload
Hello.vue 不会

**Comment by chrisvfritz** [comment]
@haozime Can you link to a simple example project with the problem?

**Comment by mdsb100** [comment]
@chrisvfritz 
+1
App.vue hot reload
Hello.vue do not hot reload

Default Template can show this issue.

**Comment by mdsb100** [comment]
Could you use browser-sync replace express?

**Comment by chrisvfritz** [comment]
This is working as intended. What you did is update the initial value of that data property, but after the component is loaded, hot reloading maintains the current state, so that change in initial state makes no difference.
