### ISSUE TITLE
npm install -g vue-cli npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen) npm ERR! Unexpected end of JSON input while parsing near '....1.14":{"name":"async'  npm ERR! A complete log of this run can be found in: npm ERR!     C:\Users\welcome\AppData\Roaming\npm-cache\_logs\2018-07-20T13_33_27_830Z-debug.log

### ISSUE THREAD

**Issue by kamaleshsivaraj** [vuejs-templates/webpack#1423]
when am try to install vue-cli globally this err message is generated ..
![image](https://user-images.githubusercontent.com/38140254/43005231-da37bbb2-8c4f-11e8-9957-239de1db2af6.png)

**Comment by kamaleshsivaraj** [comment]
thank god i solved the issues..by npm cach
![image](https://user-images.githubusercontent.com/38140254/43006091-7147eafc-8c52-11e8-852f-87fdc2b6f5a2.png)
e clean --force command ..this what i fixed..

**Comment by Ahmed-Gamal-Helal** [comment]
run the command as administrator and it will be solved.

**Comment by bhavik204** [comment]
Node version - 10.14.1
npm version - 6.4.1
Cleared cache in cmd as administrator and  also in Powershell as administrator and installed @vue/cli , but showing same error of json input.
