### ISSUE TITLE
Upgrading Babel version to 7

### ISSUE THREAD

**Issue by tqhoughton** [vuejs-templates/webpack#1429]
There are some new Babel plugins I want to use, but unfortunately Babel has stopped creating plugins for versions before 7, and 7 was a pretty big change. And unfortunately, I am a Webpack noob and every time I try to upgrade my babel version myself I end up breaking everything.

Could someone, with perhaps more Webpack knowledge than me, create a version of this template with Babel 7+ installed? I'm sure I'm not the only one who would want this, and it would help this template stay up to date. If there is demand for older Babel versions, it may be helpful to include this as a CLI option that would ask you which Babel version you want.

**Comment by pixelass** [comment]
I'm not sure if all features still work with these changes. I use this and it works great for my needs. 

I updated my .babelrc to this: 

```json
{
    "presets": [
        "@babel/env"
    ],
    "plugins": [
        [
            "@babel/plugin-proposal-decorators",
            {
                "legacy": true
            }
        ],
        [
            "@babel/proposal-class-properties",
            {
                "loose": true
            }
        ],
        "@babel/proposal-object-rest-spread",
        "babel-plugin-transform-vue-jsx",
        "@babel/plugin-transform-runtime"
    ]
}
```

and my package.json: 

```json
{
  "devDependencies": {
    "@babel/core": "7.2.2",
    "@babel/plugin-proposal-class-properties": "7.2.3",
    "@babel/plugin-proposal-decorators": "7.2.3",
    "@babel/plugin-proposal-object-rest-spread": "7.2.0",
    "@babel/plugin-transform-runtime": "7.2.0",
    "@babel/polyfill": "7.2.5",
    "@babel/preset-env": "7.2.3",
    "babel-helper-vue-jsx-merge-props": "2.0.3",
    "babel-jest": "23.6.0",
    "babel-loader": "8.0.5",
    "babel-plugin-dynamic-import-node": "2.2.0",
    "babel-plugin-syntax-jsx": "6.18.0",
    "babel-plugin-transform-vue-jsx": "3.7.0",
    "@babel/register": "7.0.0",
  }
}
```
