### ISSUE TITLE
webpack version 3.x, vue-loader version 13.x, a little bit old

### ISSUE THREAD

**Issue by lovetingyuan** [vuejs-templates/webpack#1433]

**Comment by jonashackt** [comment]
With the new Vue CLI 3, the templates of Vue.js are now legacy (this should be somehow noted in the README of this project here!).

A shift to the new Plugin architecture of Vue CLI 3 (see https://cli.vuejs.org) will automatically do the upgrade to webpack 4.x etc.

**Comment by lovetingyuan** [comment]
well, thanks

**Comment by jonashackt** [comment]
If you want to have a full blown example, you can have a look at https://github.com/jonashackt/spring-boot-vuejs - where I only recently updated to Vue CLI 3 and webpack 4, mainly in this commit: https://github.com/jonashackt/spring-boot-vuejs/commit/61778f66ca33ae9fba814ab12884611d72642724
