### ISSUE TITLE
vue cli 3 didn't prompt error/warning when max_user_watches is exceed

### ISSUE THREAD

**Issue by luaz** [vuejs-templates/webpack#1441]
I am runing `npm run serve` for development and hot reloading, and realize some changes to nested file (e.g. `assets/css/test.css`) are not reloaded but reloading works on certain files (e.g. `assets/test.css`).

I took me half a day before I realize the culprit is inotify watchers `max_user_watches`.

It would be useful if vue cli could warn of the usual `Failed to watch directory ... no space left on device` error.

**Comment by LinusBorg** [comment]
This is the wrong repository. You are looking for vuejs/vue-cli
