### ISSUE TITLE
Error when fresh new run 'npm run build'

### ISSUE THREAD

**Issue by jaschweder** [vuejs-templates/webpack#146]
I'm facing this error when running 'npm run dev' and 'npm run build', see image bellow:

http://pix.toile-libre.org/upload/original/1464870344.jpg

I was abble to fixing this changing the files bellow:

File: ./src/main.js
```javascript
// from
import App from './App';
// to
import App from './App.vue';
```

File: ./src/App.vue
```javascript
// from
import Hello from './components/Hello';
// to
import Hello from './components/Hello.vue';
```

Is there a better fix to this ?

**Comment by yyx990803** [comment]
Hmm, cannot reproduce this, because it should resolve correctly: https://github.com/vuejs-templates/webpack/blob/dist/template/build/webpack.base.conf.js#L16 (`.vue` extension is included)

Can you provide the OS/Node/npm/webpack versions?

**Comment by chrisvfritz** [comment]
@jaschweder This is a known issue with the Airbnb linting config - is that what you're using? It's actually a bug on their end (and frankly, I think an overreach, since module bundlers already report errors if they can't find a module).

**Comment by jaschweder** [comment]
@yyx990803 
OS: **Ubuntu 14.04 LTS**
Node: **v4.4.3 (stable)**
Webpack: **latest (cloned from branch master)**

@chrisvfritz 
yes I'm using Airbnb

**Comment by chrisvfritz** [comment]
Duplicate #144.
