### ISSUE TITLE
[Question] – Sass @import globally available

### ISSUE THREAD

**Issue by silvestreh** [vuejs-templates/webpack#149]
Say I have a main `app.scss` which imports other things like color variables, a CSS reset, and [Animate.css](https://daneden.github.io/animate.css/).

```scss
// app.scss
@import 'partials/colors';
@import 'vendor/normalize';
@import 'vendor/animate';
```

I then use this `app.scss` file in my main `App.vue` component.

```vue
<!-- App.vue -->
<template>
    <my-component></my-component>
</template>
<style lang="scss" src="./app.scss"></style>
<script>…</script>
```

How can I use those color variables and `@extend` Animate.css classes from within other components? For now I've resorted to `@import`ing them all over again, but it's not a nice solution and (I *think*) it duplicates the code.

```vue
<!-- myComponent.vue -->
<template>…</template>
<style lang="scss">
.myComponent {
    @extend .animated; // fails unless I @import animate.css again.
}
</style>
<script>…</script>
```

**Comment by chrisvfritz** [comment]
[The forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue) are actually better places for questions like this, as we try to reserve the issues for feature requests and bug reports.

**Comment by silvestreh** [comment]
@gazpachu Nope, I ended up not worrying too much about it, especially with the partials that don't produce CSS output (like variables), I include those over and over again.

In the case of third party stuff, like `Animate.css`, or partials that do produce CSS output, I avoid `@import`ing them within scoped styles because I'll end with duplicated code.

If you include partials that do produce CSS output, or third party stuff, within a regular `<style>` tag in your `.vue` component, duplicate code will be removed upon minification when you build your app for production environments.

**Comment by hal0gen** [comment]
Apparently this looks like the only solution available, a long discussion about the same issue can be found here: https://github.com/vuejs/vue-loader/issues/328

**Comment by hal0gen** [comment]
@gazpachu That's fantastic, I confirm it works! 

This is a common problem for people using vue-cli, I think it should be mentioned in the documentation. From what I understand, your answer is very relevant for the following issues:
- https://github.com/vuejs/vue-loader/issues/356
- https://github.com/vuejs/vue-loader/issues/326
- https://github.com/vuejs/vue-loader/issues/110
- https://github.com/vuejs/vue-loader/issues/95

You might also want to answer the following questions/issues (I'd do it myself but **you** solved the puzzle):
- [vue.js: always load a settings.scss file in every vue style section](http://stackoverflow.com/questions/38928380/vue-js-always-load-a-settings-scss-file-in-every-vue-style-section)
- [vue-cli webpack with scss undefined scss variable in component style](https://forum-archive.vuejs.org/topic/5113/vue-cli-webpack-with-scss-undefined-scss-variable-in-component-style/2)

**Comment by gazpachu** [comment]
@hal0gen thanks. I've updated the stackoverflow thread but in the Vuejs forum, I can't sign-up/login, so if you can, please post it there. Thanks

**Comment by Fleeck** [comment]
@gazpachu amazing, big thanks for this!

**Comment by grantcarthew** [comment]
Hi, I just want to add to @gazpachu answer above. I used a different syntax for my build/utils.js file like so:

```js

  let sassOptions = {
    indentedSyntax: true
  }
  let scssOptions = {
    includePaths: [
      '~src/styles'
    ],
    data: '@import "~src/styles/_main";'
  }

  // http://vuejs.github.io/vue-loader/en/configurations/extract-css.html
  return {
    css: generateLoaders(),
    postcss: generateLoaders(),
    less: generateLoaders('less'),
    sass: generateLoaders('sass', sassOptions),
    //  Make custom SASS available to all components https://github.com/webpack-contrib/sass-loader
    scss: generateLoaders('sass', scssOptions),
    stylus: generateLoaders('stylus'),
    styl: generateLoaders('stylus')
  }

```

**Comment by alexmccabe** [comment]
@grantcarthew for me this didn't work, but if it were to work, would this make variables defined in `/styles/main` global to be accessed by any `.vue` component?

I guess I need to play around more with my config.

**Comment by grantcarthew** [comment]
@alexmccabe When I posted that snippet above I didn't post the `generateLoaders` function. Checkout [vue-foundation](https://github.com/hal0gen/vue-foundation) for a better example.

**Comment by lehni** [comment]
@grantcarthew how do you get the `~` to work in your example? It doesn't work for me. The only way can get this to work currently is by doing this:

```js
  var sassOptions = {
    includePaths: [
      // '~src/styles'
      path.resolve('./src/styles')
    ],
    // data: '@import "~src/styles/_setup";'
    data: `@import "~${path.resolve('./src/styles/_setup')}";`
  }
```

**Comment by grantcarthew** [comment]
Hi @lehni. As stated in my last comment, see the vue-foundation template for reference. Here is the file with the answer for your question:

https://github.com/hal0gen/vue-foundation/blob/master/build/utils.js

**Comment by woshi82** [comment]
I have found that the symbol     **;**    is really important in ``@import "~${path.resolve('./src/styles/main')}";``

**Comment by ppozniak** [comment]
Here's how I managed to get it work:
```javascript
scss: generateLoaders('sass', {
      includePaths: ['./src/styles'],
      data: '@import "_main.scss";'
    }),
```

`includePaths` is an array of paths that will be looked at when you are doing `@import`
`data` is a thing, that will be inserted into every sass scope

**Comment by l2aelba** [comment]
For less, I would do something like :

```html
<style src="@/libs/css/global.less" lang="less"></style>
<style lang="less">
  @import (reference) "libs/css/global.less";
  #app {
    .my-custom();
  }
</style>

This will **not be duplicate** even `.my-class` or `.my-class()` on Less, Its will use just **as reference**
```

**Comment by lehni** [comment]
Here's how I have this working now for both Sass and Stylus:
```js
  var sassOptions = {
    includePaths: ['./src/styles'],
    data: '@import "_main.scss";'
  }

  var stylusOptions = {
    paths: [path.resolve('./src/styles')],
    import: ['_main.styl']
  }

  // https://vue-loader.vuejs.org/en/configurations/extract-css.html
  return {
    css: generateLoaders(),
    postcss: generateLoaders(),
    less: generateLoaders('less'),
    sass: generateLoaders('sass',
        Object.assign({ indentedSyntax: true }, sassOptions)),
    scss: generateLoaders('sass', sassOptions),
    stylus: generateLoaders('stylus', stylusOptions),
    styl: generateLoaders('stylus', stylusOptions)
  }
```

**Comment by Love-the-fish-cat** [comment]
this way will create more css code,i use cssnano plugin and run npm run dev can't delete more css code.

**Comment by anish000kumar** [comment]
https://stackoverflow.com/a/46015906/5013932

**Comment by percy507** [comment]
See this one

https://badacadabra.github.io/Using-global-style-rules-in-a-Vue-js-app/
