### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by vird** [vuejs-templates/webpack#151]
Just a clean install

    npm install -g vue-cli
    vue init webpack project
    cd project
    npm install
    npm run dev

process.env.NODE_ENV entities are not replaced by 

    new webpack.DefinePlugin({
       'process.env': config.dev.env
    }),

node -v
v6.2.1

possibly related
https://github.com/webpack/webpack/issues/2312

**Comment by chrisvfritz** [comment]
@vird Thanks for reporting this. I believe this may be an intermittent issue caused by https://github.com/vuejs-templates/webpack/pull/122, which I just reverted. Can you confirm that the problem no longer exists for you on a fresh project?

**Comment by vird** [comment]
Problem solved.
