### ISSUE TITLE
Vue with dynamics.js in dev mode

### ISSUE THREAD

**Issue by sean-nicholas** [vuejs-templates/webpack#161]
I'm running npm run dev and created this component: https://gist.github.com/sean-nicholas/0d180a5be1c0422955ebb04d3f58277e to recreate this effect: http://dynamicsjs.com/examples/loader.html

When I'm refreshing the page (F5) the dots don't move. If I change translateY in line 20 the hotreload gets triggered and the animation works. When I'm changing back to the original value it stops again. npm run build -> the dots move directly on startup (thats how it should work in dev, too).

**Comment by chrisvfritz** [comment]
The component you linked to seems to work fine in a fresh project, so something else may be going on. Are you getting any warnings/errors in the JS console?

**Comment by chrisvfritz** [comment]
Closing this, as I'm guessing you may have resolved it and it also sounds likely to be an issue with the specific project, not the template.
