### ISSUE TITLE
"Uncaught RangeError: Invalid array length" when use string "attributes" in <input>

### ISSUE THREAD

**Issue by mul14** [vuejs-templates/webpack#162]
I am not sure this is webpack template bug or else.

Here how to reproduce the error:

```
vue init webpack-simple anything
```

> This is also happens when using `vue init webpack`

Edit `App.vue` file, and add this inside `<template>` tag

```html
<form method="POST">
  <input type="text" name="attributes">
</form>
```

Run `npm run dev`. You can't see the text box. Instead you will get an error message on console. Something like this on Chrome and Firefox `Uncaught RangeError: Invalid array length`. And `RangeError: Array size is not a small enough positive integer` on Safari.

This only happen when use "attributes" as `name` or `id` attribute in `<input>` and `<textarea>`.

**Comment by chrisvfritz** [comment]
@mul14 It looks like you found a bug in Vue itself! I just [opened an issue](https://github.com/vuejs/vue/issues/3079) for you there.
