### ISSUE TITLE
npm run bulid missing Semi-colon

### ISSUE THREAD

**Issue by liuyangzuo** [vuejs-templates/webpack#167]
dist/index.html  file missing all Semi-colon

**Comment by simplesmiler** [comment]
To my knowledge, there are no semicolons in HTML.
Can you please give more details?

**Comment by liuyangzuo** [comment]
<img width="971" alt="2016-06-21 10 07 43" src="https://cloud.githubusercontent.com/assets/8985760/16215846/2ad7f3f2-3798-11e6-8064-3fc9ad10adaa.png">

link tag,script tag..etc missing semicolons.

**Comment by chrisvfritz** [comment]
Ahh, those are called __quotes__. A semicolon is this: `;`. HTML without quotes is [actually valid](https://www.w3.org/TR/html-markup/syntax.html#attr-value-unquoted) in certain contexts and we [strip the quotes in production](https://github.com/vuejs-templates/webpack/blob/dist/template/build/webpack.prod.conf.js#L54) to minimize the size of the HTML.
