### ISSUE TITLE
sourcemap dons't work with chrome(51.0.2704.84 m (64-bit))

### ISSUE THREAD

**Issue by 178220709** [vuejs-templates/webpack#172]
my os is win7 x64.
when i use dev Mode ,  i can see the source code in vue file. but i cant hit the break point.
and sometime the hot bundle is not work , i must try several times .
then i build it . the site is work will ,but the sourceMap is still bad,
sometime it is not my source code.
some time the console report a error :Failed to parse SourceMap: http://localhost:6589/static/js/app.aed1015bb27a43cd2293.js.map

is there anyone see the problem too ? 

i will reinstrall my chrome(v50) first,
and  try this in my other pc(win10)

**Comment by chrisvfritz** [comment]
Thanks for the report @178220709. I was unable to reproduce this on my OS X system, but please let me know what other information you're able to gather as you do further testing!

**Comment by 178220709** [comment]
I try in win10 .
still same problem .
the only way to hit break point is
 `
 if (window.globalDebugger) {
        debugger
      }
`

**Comment by chrisvfritz** [comment]
@178220709 Any progress resolving this? I unfortunately still haven't been able to reproduce the issue. 😕

**Comment by 178220709** [comment]
I find other boilerplate can work will.
[https://github.com/178220709/SpiderShow/blob/master/package.json](url)
I try to find the problem, but I failed.
I will continuous report this problem.

**Comment by baggsie** [comment]
Changing `devtool: '#eval-source-map'` to `devtool: '#source-map'` in \build\webpack.dev.conf.js fixed this for me (win 10/ Chrome 55).
