### ISSUE TITLE
i'm using vue-cli@2.1.0, but i can't pull the dist branch

### ISSUE THREAD

**Issue by ihaichao** [vuejs-templates/webpack#174]
i fork this repo and create my own boilerplate on the dist branch, but i can't pull it using vue-cli@2.1.0.

**Comment by chrisvfritz** [comment]
Why not delete the master branch and rename dist to master?

**Comment by chrisvfritz** [comment]
If you do really need another branch though, you can reference it with my-username/webpack#dist

**Comment by ihaichao** [comment]
Thanks, add #dist worked, but delete the master branch and rename dist to master would be better
