### ISSUE TITLE
Not compatible with IE9

### ISSUE THREAD

**Issue by KingMario** [vuejs-templates/webpack#184]
The page can't display with the same style in IE 9 with other browsers.
1. The V icon doesn't appear.
2. The page is aligned top-left instead of being aligned center.

What's more, a practice generated with a previous version of this template - https://github.com/KingMario/Vuejs-cnodejs-example - can't work in IE9.

**Comment by chrisvfritz** [comment]
Since the welcome page uses a flexbox layout and all versions of IE have a large number of flexbox bugs, that probably explains the alignment being off. Can you investigate why the icon isn't appearing?

**Comment by yyx990803** [comment]
The default components never intend to work with IE9. You are responsible for whatever content you create yourself.

**Comment by KingMario** [comment]
When talking about **default components**, what does that mean?

**Comment by yyx990803** [comment]
@KingMario the components you see when you scaffold a new project. They are meant to be replaced by your code, so it doesn't matter what browsers they support.

**Comment by KingMario** [comment]
@yyx990803 got it. Thanks.
