### ISSUE TITLE
Disabling hash for css

### ISSUE THREAD

**Issue by ttoinou** [vuejs-templates/webpack#186]
Hi !

First thank you for this boilerplate code it's very useful for VueJS development :) .

I would like to disable hash in filenames in the dist folder. I suceeded for the .js by changing `filename: utils.assetsPath('[name].[chunkhash].js'),`  to `filename: utils.assetsPath('[name].js')` in webpack.prod.conf.js.

But changing `new ExtractTextPlugin(utils.assetsPath('/[name].[contenthash].css')),` to `new ExtractTextPlugin(utils.assetsPath('/[name].css')),` produces an error : 

```
shell.js: internal error
Error: EPERM: operation not permitted, mkdir 'MYREPERTORY\dist\pepin'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at mkdirSyncRecursive (MYREPERTORY\node_modules\shelljs\src\mkdir.js:11:8)
    at MYREPERTORY\node_modules\shelljs\src\mkdir.js:63:7
    at Array.forEach (native)
    at _mkdir (MYREPERTORY\node_modules\shelljs\src\mkdir.js:48:8)
    at MYREPERTORY\node_modules\shelljs\src\common.js:240:23
    at Object.<anonymous> (MYREPERTORY\build\build.js:25:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

Do you have any idea ?

Thanks in advance!

**Comment by yyx990803** [comment]
Remove the leading slash: `/[name].css` will cause webpack trying to create the file at the root directory of your entire system.

**Comment by ttoinou** [comment]
Hi, thanks for the answer.
I am not removing the leading slash. The line `new ExtractTextPlugin(utils.assetsPath('/[name].[contenthash].css'))` actually works (but not without `.[contenthash]`)

**Comment by ttoinou** [comment]
Remember that i'm calling `utils.assetsPath` so even without the leading slash it won't pont to the root directory.
This issue is not closed ; however it might be an issue with `webpack ` and not `vuejs-webpack`

**Comment by chrisvfritz** [comment]
@ttoinou May I ask, why would you want to disable the hash?

**Comment by ttoinou** [comment]
@chrisvfritz Hi, yes of course. I'm using the vuej-webpack for developing a library and I would like the build script to update the dist folder with everything that is needed in order for someone to include my library easily.

**Comment by chrisvfritz** [comment]
@ttoinou Ah, I see. In general, `webpack-simple` may be a better template for library work, as there's a lot in this template that assumes one is building a SPA.
