### ISSUE TITLE
Chromedriver 502 bad gateway

### ISSUE THREAD

**Issue by douggrubba** [vuejs-templates/webpack#187]
Is anyone else getting a 502 (bad gateway) error on "https://registry.npmjs.org/chromedriver/-/chromedriver-2.21.2.tgz"

https://registry.npmjs.org/chromedriver/-/chromedriver-2.21.1.tgz seems to work fine.  Maybe just a short term npm issue?

**Comment by chrisvfritz** [comment]
Yeah, NPM is having some issues right now. We just have to wait. 😕

**Comment by douggrubba** [comment]
Figured, thanks for the update.

**Comment by mhart28** [comment]
i've encountered the same issue with chromedriver-2.21.4 version
http://chromedriver.storage.googleapis.com/index.html?path=2.24/
