### ISSUE TITLE
Can't exclude directory for coverage

### ISSUE THREAD

**Issue by jenow** [vuejs-templates/webpack#194]
Hello,
We tried to exclude a directory for coverage but without success. We used the cli to generate a scaffolding, tried to add an exclude into the karma.conf.js, webpack.base.conf.js and unit/config.js with the regexp (find it dirty tho).
In this project we would like to exclude src/routes/subRoutes/ directory:
[https://github.com/kuzzleio/kuzzle-backoffice/tree/global-layout](https://github.com/kuzzleio/kuzzle-backoffice/tree/global-layout)
Is there an easy way to do it?
Thanks!

**Comment by AnthonySendra** [comment]
Hello,

Juste in addition, we tried in karma.conf.js

```
config.set({
    // to run in additional browsers:
    // 1. install corresponding karma launcher
    //    http://karma-runner.github.io/0.13/config/browsers.html
    // 2. add it to the `browsers` array below.
    browsers: ['PhantomJS'],
    frameworks: ['mocha', 'sinon-chai'],
    reporters: ['spec', 'coverage'],
    files: ['./index.js'],
    preprocessors: {
      './index.js': ['webpack', 'sourcemap']
    },
    webpack: webpackConfig,
    webpackMiddleware: {
      noInfo: true
    },
    coverageReporter: {
      dir: './coverage',
      reporters: [
        { type: 'lcov', subdir: '.' },
        { type: 'text-summary' }
      ]
    },
    exclude: [
      'src/routes/subRoutes/**/*.js'
    ]
  })
```
And

```
config.set({
    // to run in additional browsers:
    // 1. install corresponding karma launcher
    //    http://karma-runner.github.io/0.13/config/browsers.html
    // 2. add it to the `browsers` array below.
    browsers: ['PhantomJS'],
    frameworks: ['mocha', 'sinon-chai'],
    reporters: ['spec', 'coverage'],
    files: ['./index.js'],
    preprocessors: {
      './index.js': ['webpack', 'sourcemap']
    },
    webpack: webpackConfig,
    webpackMiddleware: {
      noInfo: true
    },
    coverageReporter: {
      dir: './coverage',
      reporters: [
        { type: 'lcov', subdir: '.' },
        { type: 'text-summary' }
      ]
    },
    exclude: [
      path.resolve(projectRoot, 'src/routes/subRoutes/**/*.js')
    ]
  })
```

Without success

**Comment by chrisvfritz** [comment]
All you should need to do is [update `test/unit/index.js`](https://github.com/vuejs-templates/webpack/blob/dist/template/test/unit/index.js#L9-L11). This is probably the regex you're looking for:

``` js
/^\.\/(?!main\.js$|routes\/subRoutes).+\.(js|vue)$/i
```

**Comment by AnthonySendra** [comment]
Hello,

Thanks for your answer but it's doesn't work. My `test/unit/index.j`s looks like this now:

```js
// Polyfill fn.bind() for PhantomJS
/* eslint-disable no-extend-native */
Function.prototype.bind = require('function-bind')

// require all test files (files that ends with .spec.js)
var testsContext = require.context('./specs', true, /\.spec$/)
testsContext.keys().forEach(testsContext)

// require all src files except main.js for coverage.
// you can also change this to match only the subset of files that
// you want coverage for.
var srcContext = require.context('../../src', true, /^\.\/(?!main\.js$|routes\/subRoutes).+\.(js|vue)$/i)
srcContext.keys().forEach(srcContext)
```

But in my test coverage, the list still includes the path `src/routes/subRoutes/` with my file `security.js` in it.
There is no easy way to exclude a path? Like with only karma with a configuration?

**Comment by chrisvfritz** [comment]
@AnthonySendra If that isn't working, the only explanation I can think of is you're requiring `security.js` through a test (even if indirectly). For an exclude through a karma config, you'll have to research that. It sounds like there's nothing specific to Vue or this template here, so closing.

**Comment by dkpalmer** [comment]
@jenow @AnthonySendra Did you have any luck with this?
