### ISSUE TITLE
Can I disabled the hot-reload?

### ISSUE THREAD

**Issue by Coffcer** [vuejs-templates/webpack#196]
I wan't to use [inline-mode](http://webpack.github.io/docs/webpack-dev-server.html#inline-mode), but I failed, can't reload the page when I change the code. How can I do that?

**Comment by chrisvfritz** [comment]
@Coffcer I don't think I understand. Is the template not working as it should out of the box or are you looking for help modifying the template?

**Comment by Coffcer** [comment]
@chrisvfritz Sorry, my English not good. I just wan't to disabled the webpack hot-reload.  How should I do that

**Comment by chrisvfritz** [comment]
I'm still not sure why you'd want to, but you can disable it by removing any lines that mention `hotMiddleware` in [build/dev-server.js](https://github.com/vuejs-templates/webpack/blob/dist/template/build/dev-server.js).
