### ISSUE TITLE
如何解决 eslint 不支持 async/await 语法呢？

### ISSUE THREAD

**Issue by ickeep** [vuejs-templates/webpack#201]
eslint 不支持 async/await 通过插件安装也不支持！
官方建议是：换 babel-eslint or  espree
做过的尝试：eslint-plugin-async-await 失败

配置 
#
env: {
    "es6": true,
    "browser": true,
    "amd": true,
    "node": true
  },
  "parserOptions": {
    "ecmaVersion": 7,
    "ecmaFeatures": {
      "esversion": 6,
      "destructuring": true,
      "generators": true,
      "superInFunctions": true,
      "experimentalObjectRestSpread": false
    },
    "sourceType": "module"
  }

有没有办法通过配置让 eslint 支持 async/await ?
如果需要改成 babel-eslint or  espree 应当如何配置？

**Comment by chrisvfritz** [comment]
This was fixed in #198.

**Comment by CatsAndMice** [comment]
ecmaVersion修的成8以上 ，使用babel-eslint
