### ISSUE TITLE
Coffeescript code coverage

### ISSUE THREAD

**Issue by aristidesfl** [vuejs-templates/webpack#203]
Is code coverage for coffeescript contemplated in the current karma config?
Any ideas on the best way to integrate that?

**Comment by chrisvfritz** [comment]
Any files required [here](https://github.com/vuejs-templates/webpack/blob/dist/template/test/unit/index.js#L9-L13) are included for test coverage. See the [`require.context` docs](https://webpack.github.io/docs/context.html) for more information about requiring groups of files.

**Comment by aristidesfl** [comment]
The problem are .vue with lang="coffee" no coverage for that code

**Comment by chrisvfritz** [comment]
[https://github.com/benbria/karma-coffee-coverage](https://github.com/benbria/karma-coffee-coverage)

**Comment by aristidesfl** [comment]
@chrisvfritz any example on how to use it with vueloader and .vue files?

**Comment by chrisvfritz** [comment]
@aristidesfl No unfortunately. 😕  I haven't personally used CoffeeScript in a Vue project.
