### ISSUE TITLE
HTML linting

### ISSUE THREAD

**Issue by ianwalter** [vuejs-templates/webpack#210]
I think adding an HTML linter like [htmlhint-loader](https://github.com/mattlewis92/htmlhint-loader) would be helpful in the same way that eslint is helpful while developing. Thoughts?

**Comment by chrisvfritz** [comment]
@ianwalter This might be useful with an extremely limited set of rules to catch common errors, such as an [unpaired tag](https://github.com/yaniswang/HTMLHint/wiki/Tag-pair). I think I'd like to stay away from any stylistic rules for now though.

**Comment by ianwalter** [comment]
Yea, thats precisely what I was thinking too.

**Comment by chrisvfritz** [comment]
We'd consider a PR then. 🙂

**Comment by Aladdin-ADD** [comment]
now we have eslint-plugin-vue, is this still worthy? @chrisvfritz

**Comment by chrisvfritz** [comment]
@Aladdin-ADD Once eslint-plugin-vue is stable, it'll solve this problem. 🙂

**Comment by LinusBorg** [comment]
I will close this, eslint-plugin-vue is practically around the corner.
