### ISSUE TITLE
Included files don't trigger change.

### ISSUE THREAD

**Issue by FranzSkuffka** [vuejs-templates/webpack#211]
When including something in a pug file or importing something in a sass / stylus file, the respective included files don't trigger a build.

1. git clone https://github.com/FranzSkuffka/pug-html-loader-bug
2. npm i
3. npm run dev
4. change https://github.com/FranzSkuffka/pug-html-loader-bug/blob/master/src/yo.pug
5. ???
6. no profit

**Comment by yyx990803** [comment]
Imo it's not a good idea to mix pug includes with Vue's own component composition. If you need composition, just make them components instead. This is why vue-loader's template part don't support pre-processor imports.

If you really want it, you'll have to use `pug-loader` and configure vue-loader to use `pug-loader` per (docs here)[http://vue-loader.vuejs.org/en/configurations/advanced.html]. In addition, `pug-loader` returns a compiled template function, not the raw HTML, so you need to chain a custom loader after `pug-loader` to invoke that function and return the value.

**Comment by FranzSkuffka** [comment]
Thank you for this info.
