### ISSUE TITLE
I can't import github-colors

### ISSUE THREAD

**Issue by SidKwok** [vuejs-templates/webpack#214]
github-colors: 2.2.6
npm: 3.9.6
node: 4.4.5
OS X 10.11.6

vue-cli can't find these two files:
node_modules/.npminstall/github-colors/2.2.6/github-colors/lib/extensions.json
node_modules/.npminstall/github-colors/2.2.6/github-colors/lib/colors.json

But when I check the files, they exist.
Is it the personal problem?

**Comment by yyx990803** [comment]
You need https://github.com/webpack/json-loader
