### ISSUE TITLE
Assets Naming Convention

### ISSUE THREAD

**Issue by aristidesfl** [vuejs-templates/webpack#217]
The component names (`App.vue`, `Hello.vue`) don't match to the [Assets Naming Convention](https://vuejs.org/guide/components.html#Assets-Naming-Convention) described in the docs.

Should be lowercase `app.vue` and `hello.vew` right?

**Comment by chrisvfritz** [comment]
@aristidesfl No, PascalCase is one of the acceptable options and either way, those conventions do not apply to file names.

**Comment by aristidesfl** [comment]
@chrisvfritz the documentation has kebab-case file names and doesn't say the convention doesn't apply to them.

**Comment by chrisvfritz** [comment]
The documentation explains why the conventions exist and what Vue is doing, so that if you think about it, there would be no reason for them to apply to file names. And as I said before, it's a moot point anyway. Even if you chose to interpret file names as having to conform to the same conventions, PascalCase IS one of the acceptable options listed.

**Comment by aristidesfl** [comment]
Vue explains the technical reasons why the convention exists, but that is not the only reason a convention might exist.

If the section of the documentation which talks about technical enforced conventions exemplifies naming of related things (file names) which could also benefit from a convention they are relevant even if for a different reason.

PascalCase does NOT seem to appear in any of the examples of the section. Many other naming conventions would also be acceptable. But maybe using case insensitive file names isn't such a bad idea because of file system incompatibility and version control.

Nevertheless, maybe it is not a good idea for the documentation to promote a different convention than the one used in the official templates, one way or another.
