### ISSUE TITLE
Bump to use Vue 2.0.

### ISSUE THREAD

**Issue by zigomir** [vuejs-templates/webpack#219]
Most official vuejs-templates already have a 2.0 PR ready. I think we can merge them as soon as new `vue-cli` is released with [support to specify a branch on official templates](https://github.com/vuejs/vue-cli/pull/145).

Now I'm mostly familiar with `browserify` and simpler templates :) I know you @chrisvfritz have a [gist](https://gist.github.com/chrisvfritz/6b5c121b15f9c54478953ee5cd74b58c) on how to update this template to work with 2.0.

Before merging 2.0 PR, please create and push branch named `1.0` from current ... um, `dist` branch. What's up with master here? :)

**Comment by chrisvfritz** [comment]
@zigomir I'm happy to take care of this. Since this is the most-used template, I think it might also be helpful to display a little message reminding people that this is Vue 2.0, with a link to the 2.0 docs and instructions for using the 1.0 template instead. Beyond that, is there anything else you can think of beyond just making the minimal updates to things working?

**Comment by zigomir** [comment]
No, not really. You mean Vue 2.0 docs or webpack-template specific 2.0 docs?
Please see this PR: https://github.com/vuejs-templates/webpack/pull/225. Minimal(istic) note about version is already there.

**Comment by chrisvfritz** [comment]
Ah, got it - sorry for missing that.

**Comment by aristidesfl** [comment]
> ... um, dist branch. What's up with master here? :)

+1 What is the logic behind this naming scheme?

**Comment by niallobrien** [comment]
I'm confused, I switched to the 2.0 branch and followed the instructions in the Readme, and it installs 1.0.21. I'm guessing the Readme hasn't been updated.
Is there a way to install 2.0 (and all related scaffolding) using Vue-cli?

**Comment by niallobrien** [comment]
Ah, `vue init webpack#2.0 my-project`.

**Comment by zigomir** [comment]
@niallobrien yes :) and that's because 2.0 isn't merged yet. See https://github.com/vuejs-templates/webpack/pull/225

**Comment by niallobrien** [comment]
Thanks @zigomir

**Comment by LinusBorg** [comment]
the default branch now uses Vue 2.0, so we can close this I think :)
