### ISSUE TITLE
Wrong static path for production

### ISSUE THREAD

**Issue by KillianKemps** [vuejs-templates/webpack#22]
Hello,
I'm just trying this boilerplate and tested to build the project with `npm run build`. However, once built and opened in the browser, it seems it doesn't find static files. So, the webapp doesn't work even when served by `http-server`.

Finally, I changed the publicPath in webpack.conf.js from `/static/` to `./static/` and it seems to work now.

**Comment by yyx990803** [comment]
The built file needs to be served over HTTP.

**Comment by KillianKemps** [comment]
Alright, my mistake. I ran `http-server` at the root project instead of the `dist` folder
