### ISSUE TITLE
Mocking the network

### ISSUE THREAD

**Issue by callumacrae** [vuejs-templates/webpack#227]
Hello!

I have an app that makes a couple API calls. I'd like to mock them so that the tests don't hit the real network.

The way I would do that client-side is by adding an interceptor to vue-resource responding with JSON from files instead, but the tests are set up client-side, so I can't do that.

What's the easiest way to do it when using this template?

**Comment by blake-newman** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests.

This issue will now be closed. If you feel that this should be further triaged please reopen with more information on the bug or feature request, please reopen, following the [Vue.js issue template](https://github.com/vuejs/vue/edit/dev/issue_template.md).

Thanks.
