### ISSUE TITLE
Webpack freezes at `Listening at`

### ISSUE THREAD

**Issue by CinKon** [vuejs-templates/webpack#230]
I made a fresh install with `vue init webpack` and it freezes at `Listening at http://localhost:8080`

node v6.3.0
npm 3.10.5
vue-cli 2.2.0

**Comment by andre-dw** [comment]
Same here. Only got one step further.
Freezes at:
Listening at http://localhost:8080
webpack: wait until bundle finished: /index.html

**Comment by awhittington-magari** [comment]
I can confirm. We have the same problem in both Ubuntu and OS X.

**Comment by frieser** [comment]
Same here. Fedora 24.

**Comment by CinKon** [comment]
OK, now it works again, after a new `npm install`
Looks like the responsible node-module fixed itself...
