### ISSUE TITLE
multiple html files.

### ISSUE THREAD

**Issue by andre-dw** [vuejs-templates/webpack#231]
Is it possible to create multiple html files?
So i can have a web.html and a dashboard.html and inject different files in that like web.js and dashboard.js instead of main.js?

I will use vue-router for routing on those pages but i want completely different build files for performance but still want to reuse some components.

**Comment by chrisvfritz** [comment]
@andre-dw If your primary concern is limiting the size of the build, [Webpack's code splitting](https://webpack.github.io/docs/code-splitting.html) should be what you want.

**Comment by reverland** [comment]
https://github.com/ampedandwired/html-webpack-plugin can help you with create html files

**Comment by chrisvfritz** [comment]
A few solutions have been provided there's been no further discussion, so closing.
