### ISSUE TITLE
`vue init webpack my-project` is failing

### ISSUE THREAD

**Issue by crswll** [vuejs-templates/webpack#233]
I'm getting the error:

```
vue-cli · Template does not exist: vuejs-templates/webpack
```

Not sure if this is a problem with vue-cli or something else. Let me know if you need any more info and how to get it. A few people on gitter got the same error when they tried.

**Comment by yyx990803** [comment]
GitHub probably had internal server errors during that period - seems to be working fine now.

**Comment by crswll** [comment]
Yes, working for me now. I just updated vue-cli to 2.2.0 so the timing was just too perfect.

Thanks!
