### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by Jordy-A** [vuejs-templates/webpack#235]
HMR is not working for me. Launching the application is working fine, but it can't connect to the __webpack_hmr. It's always a timeout.

(I'm using newest Nodejs and NPM on Windows 10 machine, tried both Firefox and Chrome). Direct access to http://localhost:8080/__webpack_hmr is working.

See this screenshot: (and the list goes on and on)

![webpack](https://cloud.githubusercontent.com/assets/16955494/18109903/ccd8b3cc-6f14-11e6-9b64-dbd9384fc772.png)

**Comment by chrisvfritz** [comment]
Is this a fresh project install? And are you getting any errors in the terminal?

**Comment by Jordy-A** [comment]
Yes, it's a fresh install. And no errors. Really strange.

**Comment by Jordy-A** [comment]
Tried it on other Windows 10 machine (fresh Windows 10.1 install, 64 bit), it's not working there too:

- Installed node v4.5.0.
- npm install -g vue-cli
- vue init webpack my-project
- cd my-project
- npm install
- npm run dev
- running localhost:8080
- hmr not working

**Comment by Jordy-A** [comment]
I finally found the problem. It's Bitdefender Antivirus that is blocking webpack. I think I have to completely de-install my Anti Virus because whitelisting is not working...

So for everyone that has the same issue: if you have Bitdefender it doesn't work with this template. You can either use another Vue Cli template or deinstall the Antivirus -_-

**Comment by chrisvfritz** [comment]
Thanks for reporting back! It doesn't sound like anything we can do in our end, so I'll close this for now.
