### ISSUE TITLE
app tag usage?

### ISSUE THREAD

**Issue by borestad** [vuejs-templates/webpack#24]
Hi. I've been looking around the source code of Vue and a ton of examples, and there's a thing that I just don't find documented anywhere.

When/Why should I use the ```<app>`</app>`` tag?
https://github.com/vuejs-templates/webpack/blob/master/template/src/index.html#L8

... the lack of this tag in my template caused me a 2 hour debugging marathon yesterday, since my Vue app didn't render.

Thanks!

**Comment by yyx990803** [comment]
In https://github.com/vuejs-templates/webpack/blob/master/template/src/main.js#L7 we are mounting the root instance onto `<body>`, with a child component named `App` - which will be rendered into the `<app></app>` tag.
