### ISSUE TITLE
把业务逻辑拆分到独立的JS文件中时，import语句会出现错误

### ISSUE THREAD

**Issue by hstarorg** [vuejs-templates/webpack#240]
需要在.babelrc文件中增加如下配置："passPerPreset": true。

```javascript
{
  "passPerPreset": true,
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```

**Comment by chrisvfritz** [comment]
`passPerPreset` can also break other configurations, so it's good to know about that fix for this case, but we have to leave it out of the template for now.
