### ISSUE TITLE
Hardcoded url port breaks e2 tests when devServer port is changed in /config.

### ISSUE THREAD

**Issue by aristidesfl** [vuejs-templates/webpack#241]
The server port is [configurable](https://github.com/vuejs-templates/webpack/blob/1.0/template/build/dev-server.js#L11) by environment variables and config files.
However the e2e tests have a [hardcoded port](https://github.com/vuejs-templates/webpack/blob/1.0/template/test/e2e/specs/test.js#L7), so they break when the port is changed. 

Any ideas on how to use the same port without repeating the logic from the configuration?

**Comment by chovy** [comment]
```
var port = process.env.PORT || 8000;
...
.url(`http://localhost:${port}`)
...
```

**Comment by aristidesfl** [comment]
@chovy that doesn't use the port from the configuration, only from the environment variables.

**Comment by LinusBorg** [comment]
import the config module just like in the webpack files, and read the port from it.

**Comment by aristidesfl** [comment]
So, no ideas on how to do it without repeating the logic. Should we fix this in the template?

**Comment by LinusBorg** [comment]
Yeah we should probably do that.

**Comment by LinusBorg** [comment]
added PR #255 / #257

**Comment by LinusBorg** [comment]
Merged
