### ISSUE TITLE
[2.0] Add init option to select between standalone and runtime-only

### ISSUE THREAD

**Issue by LinusBorg** [vuejs-templates/webpack#242]
I see many people in gitter and the forums stumbling over the fact that importing the standalone version like `import vue from 'vue/dist/vue'` will screw up vue-loader / vueify.

We already explained why and how to prevent that here in the Vue Wiki:

https://github.com/vuejs/vue/wiki/Vue-2.0-RC-Starter-Resources#standalone-vs-runtime-builds

But of course this information is not reaching everyone out there.

I think we should therefore add a warning comment ion main.js with either a link to the wiki section above or short instuctions how to add an alias in the conf for webpack/vueify.

Will work on this.

Sibling ticket for the browserify template [#12](https://github.com/vuejs-templates/browserify/issues/12)

**Comment by LinusBorg** [comment]
Idea: Maybe we should even add it as an option to the install process: 

`"Use standalone instead of runtime-only build?" yN`

**Comment by chrisvfritz** [comment]
Having all the templates pre-compiled will also offer better performance.

**Comment by LinusBorg** [comment]
added PR #256
