### ISSUE TITLE
webpack-vue-express template

### ISSUE THREAD

**Issue by connor11528** [vuejs-templates/webpack#245]
I am looking to get started building a fullstack app with an express backend and vuejs on frontend. It seems like webpack is the best way to manage frontend (client side) dependencies. Is there any example of app config for having an express server and vue.js frontend?

A template or link to other sources would be very helpful! Also realize this is not an issue with this codebase persay, so direction about where to start template discussion or feature request also appreciated

Thank you

Question is: Do we have a template for webpack-express-vuejs apps?

**Comment by niallobrien** [comment]
You're best to keep these two concerns separate. There are plenty of Express examples & starter projects for building REST APIs.

**Comment by connor11528** [comment]
Okay noted. So deploy the server using something like digital ocean or heroku and deploy my Vue app to something like github pages or S3? Thank you

**Comment by LinusBorg** [comment]
Exactly

**Comment by chrisvfritz** [comment]
@connor11528 When you run both servers locally for development, you'll also want to make sure to [proxy to your development API](http://vuejs-templates.github.io/webpack/proxy.html).

You don't necessarily _have_ to keep them separate though. You could use something similar to these [Express](https://github.com/chrisvfritz/node-web-server-demos/blob/master/examples/express/02.%20rest-api/server.js) or [Hapi](https://github.com/chrisvfritz/node-web-server-demos/blob/master/examples/hapi/02.%20rest-api/server.js) configurations, where the frontend is served out of a `frontend` directory.

**Comment by connor11528** [comment]
Thank you very much!

**Comment by kim366** [comment]
Really, do you need to separate? Because I've now been using jQuery for my frontend and the only server I had was Express. Now, when I want to switch from jQuery to Vue, I suddenly need another server?
