### ISSUE TITLE
[docs] Where should the css files (framework?) be placed?

### ISSUE THREAD

**Issue by italomaia** [vuejs-templates/webpack#253]
Where is the proper path to place a css framework (or css files in general)?
Installing semantic-ui with npm, it is placed in a subfolder of root. Seems like a bad idea, somehow.

**Comment by chovy** [comment]
typically `/vendor/semantic-ui/semantic-ui.min.css` from the public directory.

**Comment by chrisvfritz** [comment]
If you're installing from NPM, you can do [something like this](https://github.com/jtangelder/sass-loader/issues/40#issuecomment-70269553) to reference the file in `node_modules`, which is absolutely fine.
