### ISSUE TITLE
How to integrate Foundation 6

### ISSUE THREAD

**Issue by nueverest** [vuejs-templates/webpack#254]
I'm having difficulties getting Foundation 6 [sticky nav](http://foundation.zurb.com/sites/docs/sticky.html#sticky-navigation) to work. First I should point out that I was having no issue with the sticky nav until I started using vue-cli, vue-loader, and webpack.

Before that I put the following inside index.html and the sticky nav worked fine.

``` html
<!--External Libraries-->
<script src="../js/vendor/jquery.js"></script>
<script src="../js/vendor/what-input.js"></script>
<script src="../js/vendor/foundation.js"></script>
<script src="../js/vendor/vue.js"></script>

<!--Vue component-->
<script src="../js/app.js"></script>

<!--Call foundation last. Otherwise stickiness doesn't work. 
    Only contains one line $(document).foundation()-->
<script src="../js/init-foundation.js"></script>
```

Unfortuately, the loader system used with webpack is preventing me from placing `<script src="../js/init-foundation.js"></script>` last. This file only contains one line `$(document).foundation()`.  So I tried importing the JS inside of main.js. This [stackoverflow post](http://stackoverflow.com/a/35373347/1783439) helped me get core foundation features working, but sticky nav will not work unless `$(document).foundation()` is called to reflow everything.

My main.js currently looks like this.

``` javascript
// Vue
import Vue from 'vue'

// Components
import { default as App } from './App'

// CSS
import './css/foundation.css'
import './css/blowdry.css'

// Global JS ref: http://stackoverflow.com/a/35373347/1783439
import 'script!jquery'
import 'script!what-input'
import 'script!foundation-sites'

// I tried both of these lines separately without using `ready ()`. 
//$(document).foundation()
//import 'script!./vendor/init-foundation'    // Initialize foundation last. Otherwise stickiness doesn't work.

/* eslint-disable no-new */
new Vue({
  el: 'body',
  components: {
    app: App
  },
  ready () {
    // I tried these separately.
    $(this.$el).foundation()
    //$(document).foundation()
  }
})
```

Inside App.vue

``` html
<template>
  <div data-sticky-container>
    <div class="title-bar" data-sticky data-options="marginTop:0;" style="width:100%">
      <div class="title-bar-left">Left side</div>
      <div class="title-bar-right">Right side</div>
    </div>
  </div>
</template>
```

I've tried the `ready ()` solution suggested on the [vue.js forum](https://forum.vuejs.org/topic/893/vue-js-foundation-6/3).

Obviously, calling `$(document).foundation` or `$(this.$el).foundation()` is necessary, but I'm getting an Uncaught TypeError.  What is weirder is that those calls appear to succeed on the console. Somehow `ready ()` can't see globally scoped javascript. 

![image](https://cloud.githubusercontent.com/assets/2917370/18411518/ac36f1f8-772d-11e6-8658-aec11f222393.png)

**Comment by nueverest** [comment]
Solved by adding this to webpack.conf.

``` javascript
  externals: {
    foundation: 'Foundation'
  },
```

References:
http://stackoverflow.com/a/34611081/1783439 

https://forum.vuejs.org/topic/3567/foundation-6-vue-cli-with-vue-routing/3

**Comment by scottsawyer** [comment]
So, I've been reading this and many other posts for two days and I can't get $(document).foundation() to work.  Assistance is greatly appreciated.

I am using the vue-cli webpack template, if that makes a difference.

webpack.base.conf.js:

`var path = require('path')
var config = require('../config')
var utils = require('./utils')
var projectRoot = path.resolve(__dirname, '../')

var env = process.env.NODE_ENV
// check env & config/index.js to decide whether to enable CSS source maps for the
// various preprocessor loaders added to vue-loader at the end of this file
var cssSourceMapDev = (env === 'development' && config.dev.cssSourceMap)
var cssSourceMapProd = (env === 'production' && config.build.productionSourceMap)
var useCssSourceMap = cssSourceMapDev || cssSourceMapProd

var ExtractTextPlugin = require("extract-text-webpack-plugin")

//var css = require("!raw-loader!sass-loader!./file.scss");
//var css = require("./sass/styles.scss");

var pathToFoundation = path.resolve(__dirname, '../node_modules/foundation-sites/scss')

module.exports = {
  entry: {
    app: './src/main.js',
    vendor: ['foundation-sites']
  },
  output: {
    path: config.build.assetsRoot,
    publicPath: process.env.NODE_ENV === 'production' ? config.build.assetsPublicPath : config.dev.assetsPublicPath,
    filename: '[name].js'
  },
  resolve: {
    extensions: ['', '.js', '.vue', '.json'],
    fallback: [path.join(__dirname, '../node_modules')],
    alias: {
      'vue$': 'vue/dist/vue.common.js',
      'src': path.resolve(__dirname, '../src'),
      'assets': path.resolve(__dirname, '../src/assets'),
      'components': path.resolve(__dirname, '../src/components'),
      //'foundation': path.resolve(__dirname, 'foundation-sites/js/foundation.core')
      'foundation': path.resolve(__dirname, 'foundation-sites/dist/js/foundation.min')
    }
  },
  resolveLoader: {
    fallback: [path.join(__dirname, '../node_modules')]
  },
  externals: {
    foundation: 'Foundation'
  },
  module: {
    loaders: [
        { 
            test: /\.css$/, loader: ExtractTextPlugin.extract({
            fallbackLoader: "style-loader",
            loader: "css-loader"
            })
      },
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      //{ test: /\.scss$/, loader: "style!css!sass?outputStyle=expanded&includePaths[]=" + getDir('node_modules', 'foundation', 'scss')},
      { 
        test: /\.scss$/,
        loader: ["style-loader", "css-loader", "sass-loader"]
      },
      {
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  },
  vue: {
    loaders: utils.cssLoaders({ sourceMap: useCssSourceMap }),
    postcss: [
      require('autoprefixer')({
        browsers: ['last 2 versions']
      })
    ]
  },
  sassLoader: {
    includePaths: [pathToFoundation]
  }
}`

main.js:
`
import Vue from 'vue'
import App from './App'
import VueRouter from 'vue-router'
import axios from 'axios'
import VueAxios from 'vue-axios'
import * as CONFIG from '../config/appConfig.js'
import router from './router'
import TopBar from './components/TopBar'
import Clients from './components/Clients'
import About from './components/About'
import Blog from './components/Blog'
import BlogItem from './components/BlogItem'
import Add from './components/Add'
import ClientDetails from './components/ClientDetails'
import ServicesOverview from './components/ServicesOverview'
import Service from './components/Service'

//import { jQuery, $ } from 'jquery'
var $ = require('jquery')

window.$ = $
window.jQuery = jQuery

require('foundation-sites')

Vue.use(VueAxios, axios)
Vue.use(VueRouter)

new Vue({
	router,
	render: h => h(App),
	mounted: function() {
    //$(document).foundation();
	},   
}).$mount('#app')
`

I've commented out $(document).foundation();, but I get the same $(...).foundation() is not a function error, regardless if it's in mounted, called right after it's required, or anywhere else in my app.

Here's a weirder part.  In one of my components, I am building a sticky topbar, and I can get it to initialize like this:

./components/TopBar.vue:
`export default {
  name: 'topbar',
  mounted: function() {
      var stickyOptions = {
        stickTo: 'top',
        stickyOn: 'small',
        marginTop: 0,
        topAnchor: 'header:top',
        btmAnchor: 'main',
        stickyClass: 'is-stuck'
      }
      var stickyHeader = new Foundation.Sticky($('.title-bar'), stickyOptions);
    this.$nextTick(function(){       
      $(".overlay-menu a, .toggle-menu").on("click", function(){
        if ($(".toggle-menu").hasClass("is-open")) {
          $(".toggle-menu").removeClass("is-open");
          $(".overlay-menu").removeClass("is-open");
        }
        else {
          $(".toggle-menu").addClass("is-open");
          $(".overlay-menu").addClass("is-open");
        }
      });
    });
  }  
}
</script>`

jQuery works, the Foundation object is loaded, Foundation.Sticky is working.  

But in another component, I am trying to use the Equalizer plugin.  I see the equalizer data attribute on the elements, but it doesn't do anything.  

anotherComponent.vue ( just the mounted portion ):
`  mounted: function() {
    var equalizerOptions = {
      equalizeOn: 'small',
      equalizeByRow: true,
      equalizeOnStack: true,
    }
    var clientHeights = new Foundation.Equalizer($('.client-list'), equalizerOptions);
    console.log(clientHeights);
    clientHeights.getHeights(function(f) {
      console.log(f)
    })
    this.$nextTick(function(){
      var clientHeights = new Foundation.Equalizer($('.client-list'), equalizerOptions);
      console.log(clientHeights);
    })
  },`

the console.log of clientHeights has my Equalizer object, but I don't get the actual heights ( empty array ).

So, Foundation object exists, but I can't do anything with foundation().

**Comment by philliskiragu** [comment]
@scottsawyer Did you manage to make the equalizer work?

**Comment by grantcarthew** [comment]
There should be a reference to [vue-foundation](https://github.com/hal0gen/vue-foundation) here. You don't have to use the template if you don't want to. I created my project using the vue-cli and then copied the relevant parts from the template.

**Comment by monoc44** [comment]
@grantcarthew Awesome! Sadly, the grid framework doesn't seem working properly. This code displays 3 lines instead of one:

```
<div class="row">
  <div class="small-2 large-4 columns">1</div>
  <div class="small-4 large-4 columns">2</div>
  <div class="small-6 large-4 columns">3</div>
</div>
```

**Comment by albertvolkman** [comment]
@monoc44 I hope you've already discovered this, but in case you haven't (or if someone else comes across this) you'd want to point to `foundation-float.min.css` instead of `foundation.min.css` to use float instead of grid.
