### ISSUE TITLE
[2.0] Add a prompt that this template uses version 2.0

### ISSUE THREAD

**Issue by LinusBorg** [vuejs-templates/webpack#258]
As mentioned in #225 discussion, this should be done before we make 2.0 the "master" version.

Something like;

    "This template uses Vue 2.0. If you want the version that uses Vue 1.0.*, do this:\n\r vue init webpack#1-.0"

**Comment by zigomir** [comment]
@LinusBorg I think it's safe to close this one, right?

**Comment by LinusBorg** [comment]
Yep
