### ISSUE TITLE
Webpack server won’t start with npm run dev

### ISSUE THREAD

**Issue by getflourish** [vuejs-templates/webpack#261]
I tried to create a fresh new project, but the server fails to start… any ideas? Worked fine a few days ago…

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle test@~predev: test@
6 silly lifecycle test@~predev: no script for predev, continuing
7 info lifecycle test@~dev: test@
8 verbose lifecycle test@~dev: unsafe-perm in lifecycle true
9 verbose lifecycle test@~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/florians/Sites/vue-test/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle test@~dev: CWD: /Users/florians/Sites/vue-test
11 silly lifecycle test@~dev: Args: [ '-c', 'webpack-dev-server --inline --hot' ]
12 silly lifecycle test@~dev: Returned: code: 1  signal: null
13 info lifecycle test@~dev: Failed to exec dev script
14 verbose stack Error: test@ dev: `webpack-dev-server --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid test@
16 verbose cwd /Users/florians/Sites/vue-test
17 error Darwin 15.2.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error test@ dev: `webpack-dev-server --inline --hot`
22 error Exit status 1
23 error Failed at the test@ dev script 'webpack-dev-server --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the test package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --inline --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs test
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls test
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by getflourish** [comment]
Personal issue. `killall node` fixed this

**Comment by agstover** [comment]
Just dropping a note for posterity. I was having an issue with "npm run dev" command as well, and the killall node fixed it for me as well.
