### ISSUE TITLE
Need run build --watch mode

### ISSUE THREAD

**Issue by netroby** [vuejs-templates/webpack#269]
I am using vuejs + webpack with Golang, The real webserver was nginx + golang. so i need run build --watch mode

while i change some files. i need it rebuild for me .

**Comment by chrisvfritz** [comment]
You can use watch mode as a [configuration setting](https://webpack.github.io/docs/configuration.html#watch). This is a Webpack usage issue, rather than specific to this template.

**Comment by jakobrosenberg** [comment]
Is there an example of this in action?

**Comment by pietrovismara** [comment]
@jakobrosenberg what worked for me:
Copied `build/build.js` in a new file named `build/watch.js`, then changed it as following:

```
const webpackConfig = require('./webpack.prod.conf')

const spinner = ora('building for production...')
spinner.start()

const watchConfig = Object.assign(webpackConfig, { watch: true })

rm(path.join(config.build.assetsRoot, config.build.assetsSubDirectory), err => {
  if (err) throw err
    webpack(watchConfig, (err, stats) => {
```

basically adding the `watch` property to the existing webpackConfig.

**Comment by romans127** [comment]
Not sure if this is related or not but you can also pass --watch in your npm scripts.
I have build and build:watch. And call build:watch in development from another script to roll everything together.
