### ISSUE TITLE
Is possible to use a simple Config json file?

### ISSUE THREAD

**Issue by alejogutierrez** [vuejs-templates/webpack#271]
I don't know if the usage of multiple config files is important, but it would be awesome to use one config.json file instead for simplicity.
Right now I'm using sequelize-cli that creates a config.json file for db config, so I needed to configure the template that way.
Anyway just a suggestion, thanks.

**Comment by chrisvfritz** [comment]
Unfortunately, moving all the config to a JSON file wouldn't be possible, as we need JavaScript features that aren't part of JSON.
