### ISSUE TITLE
coverage report include node_modules

### ISSUE THREAD

**Issue by xiaoyunchen** [vuejs-templates/webpack#272]
append below to the karma.config.js , but it didnot work
So, how to fix this problem

    exclude: [
      path.resolve(projectRoot, 'node_modules')
    ]

**Comment by xiaoyunchen** [comment]
@yyx990803 麻烦给看下  3Q

**Comment by chrisvfritz** [comment]
This is a usage question that would be best suited to either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue). Or since it's Karma-specific, rather than to do specifically with Vue, you could use resources in that ecosystem.
