### ISSUE TITLE
video tag not transforming sources

### ISSUE THREAD

**Issue by rodzzlessa24** [vuejs-templates/webpack#277]
So when running the development server if I load in an image let's say `../assets/myimage.png` when I inspect element I see the path gets transformed to `/static/img/myimage.png`; however, when I do the same thing with a video tag 

``` html
<video src="../assets/image2.png">
    <source src="../assets/myvid.mp4" type="video/mp4"  />
</video>
```

Neither the video src not the actual video source get's transformed to the correct path

**Comment by chrisvfritz** [comment]
There aren't currently any loaders set up for video extensions, [only images and fonts](https://github.com/vuejs-templates/webpack/blob/dist/template/build/webpack.base.conf.js#L63-L78). A PR would be welcome though.

**Comment by chovy** [comment]
I am about to start using vue.js for a video app, hopefully this gets resolved soon.

**Comment by chrisvfritz** [comment]
@chovy You're welcome to submit a PR if it's urgent for you. Videos (or any other file type) can also still be referenced as static assets.

**Comment by chovy** [comment]
I'd be happy to when I get to that part. I haven't started yet so I don't know what the PR would contain.

**Comment by LinusBorg** [comment]
@chrisvfritz wouldn't it be enough to add this to the loaders config:
```js
{
  test: /\.mp4$/,
  loader: 'file',
}
```

**Comment by rodzzlessa24** [comment]
@LinusBorg It seems to be working only issue is now it throws errors trying to load scss files

**Comment by LinusBorg** [comment]
Yeah, my code was a bit thrown together from the top of my head, but the assignment inside of an object definition was not a bright moment.

You have to do something that looks more like this I think:
```js
// all of those requires for the webpack configs 
// at the top of the file are here. Insert this right after:
var vue-loaders = utils.cssLoaders().html = 'html?attrs[]=img:src&attrs[]=video:src&attrs[]=source:src'

module.export = {
  // other weboack configs
  vue: {
    // the template auto-generates the css loaders. 
    // since we want to change the default loader for HTML,
    // we have to add it to that object.
    loaders: vue-loaders,
    postcss: [
      require('autoprefixer')({
        browsers: ['last 2 versions']
      })
    ]
  }
}
```

**Comment by rodzzlessa24** [comment]
@LinusBorg Still loading scss error. Here is how my webpack config file looks like:
https://gist.github.com/rodzzlessa24/035bcc241b3974bccc3970d291ffa446

**Comment by LinusBorg** [comment]
That's strange error. Can I see the component? Are you linking to a scss file in the template or something?

can you console.log the "vue-loader" variable?

**Comment by rodzzlessa24** [comment]
vue-loader log:

`html?attrs[]=img:src&attrs[]=video:src&attrs[]=source:src
Listening at http://localhost:8080`

And I am importing a `.scss` file in most my components but even the ones that I'm not I still get the error:

Component:

```vue
<script>
    export default {
        name: 'FooterBar'
    }
</script>

<template>
  <div class="cc-footer">
    <div class="cc-container">
      <div class="footer-title">
        HONOR THE CRAFT.DRINK RESPONSIBLY.
      </div>
      <div class="nav">
        Terms of Use | Privacy Policy | Linking Policy | Contact Us
      </div>
      <div class="legals">
        Lorem ipsum dolor sit amet
      </div>
    </div>
  </div>
</template>


<style lang="scss" scoped>
    .cc-footer {
        padding: 70px 30px;
    }
</style>
```

Error pertaining to that component:

```bash
ERROR in ./src/components/FooterBar.vue
Module not found: Error: Cannot resolve module 'scss' in /Users/rodrigo/work/src/gitlab.fg/brownforman/tourapp/src/components
 @ ./src/components/FooterBar.vue 2:0-219
```

**Comment by LinusBorg** [comment]
I see. My code was junk, sorry My Javascript missed some brackets I think.
```js
var vue-loaders = (utils.cssLoaders()).html = 'html?attrs[]=img:src&attrs[]=video:src&attrs[]=source:src'
```
If that does not work, do the long way:
```js
var vue-loaders = utils.cssLoaders())
vue-loaders.html = 'html?attrs[]=img:src&attrs[]=video:src&attrs[]=source:src'
```

**Comment by LinusBorg** [comment]
What the hell, I realized my one-liner was crap, but why is that last thing not working?

Maybe rename it to "vueLoaders" - bad idea to use hyphens in variable names

**Comment by rodzzlessa24** [comment]
So I tried the one-liner did not work then I did this

```javascript
var vueLoaders = (utils.cssLoaders())
vueLoaders.html = 'html?attrs[]=img:src&attrs[]=video:src&attrs[]=source:src'
```

and now I'm getting these errors lol

```bash
ERROR in ./src/components/FooterBar.vue
Module not found: Error: Cannot resolve module 'html' in /Users/rodrigo/work/src/gitlab.fg/brownforman/tourapp/src/components
 @ ./src/components/FooterBar.vue 8:19-247
```

**Comment by Zhangdroid** [comment]
@rodzzlessa24 
You can just add transformToRequire option like this:

```js
  vue: {
    loaders: utils.cssLoaders({ sourceMap: useCssSourceMap }),
    postcss: [
      require('autoprefixer')({
        browsers: ['last 2 versions']
      })
    ],
    transformToRequire: {
      video: 'src',
      source: 'src'
    }
  }
```
See there: http://vue-loader.vuejs.org/en/options.html

**Comment by gabrielstuff** [comment]
The latest solution proposed by @Zhangdroid works perfectly. Thanks !
