### ISSUE TITLE
My forked version doesn't provide the same files?

### ISSUE THREAD

**Issue by junerockwell** [vuejs-templates/webpack#280]
Hello! I forked this repo then I added a `router.js` file inside the `template/src` directory. When I type the command `vue init junerockwell/webpack my-project`, the `router.js` file isn't created and the prompt doesn't ask me the same prompts as the original webpack template.

For example, in the original webpack template, I don't get prompted for the version name. But on my forked copy, I get prompted and I didn't even change the `meta.json`. I only modified the `template/src` folder by adding 1 file. On my forked copy, I don't get prompted if I want to use ESLint, unit tests with Karma + Mocha and e23 test with Nightwatch. I only get prompted if this project is private or not. Most importantly I don't get the `router.js` file inside the `src` directory. But in the github.com, the `router.js` is there inside the `template/src`

This is the prompt from my forked version:

![screenshot 2016-09-27 11 01 24](https://cloud.githubusercontent.com/assets/5051574/18885745/d63618cc-84a1-11e6-87c9-5be19ff0c550.png)

And this is the prompt from the original webpack version:
![screenshot 2016-09-27 11 01 36](https://cloud.githubusercontent.com/assets/5051574/18885753/e0cbbb34-84a1-11e6-8026-3891c553031e.png)

Did I forget to do something?

**Comment by chrisvfritz** [comment]
This will be simplified when we release Vue 2.0, but in the meantime for 3rd-party templates, `master` is the default directory while your changes are on `dist`. So you'll want to:

```
git checkout master
git reset --hard dist
git push origin master
```
