### ISSUE TITLE
vue-style-loader dependency missing?

### ISSUE THREAD

**Issue by plrenaudin** [vuejs-templates/webpack#283]
Hello,
I had this error running `npm test` on a vanilla webpack template install:
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Error: Cannot find module "!!vue-style-loader!css-loader!vue-loader/lib/style-rewriter?id=data-v-1&scoped=true!vue-loader/lib/selector?type=styles&index=0!./Hello.vue"
  at /home/plrenaudin/projects/VueWebpack/test/unit/index.js:5690 <- webpack:///src/components/Hello.vue:4:0
```

I had to add the vue style loader manually
```
npm i --save-dev vue-style-loader
```
It ran successfully afterwards

**Comment by LinusBorg** [comment]
what node and npm version are you using?

**Comment by plrenaudin** [comment]
You're right, I'm using 
```
$ npm --version
2.15.9
```

**Comment by siempay** [comment]
` ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* !!vue-style-loader!css-loader!./../node_modules/vue-loader/lib/style-rewriter?id=data-v-53c6d8e7&scoped=true!sass-loader?indentedSyntax!./../node_modules/vue-loader/lib/selector?type=styles&index=0!./App.vue

Did you forget to run npm install --save for it?
> Listening at http://localhost:8080`

`$ npm -v
4.0.5`

how to fix this? I  installed css-loader with --save-dev and installed vue-style-loader too but nothing

**Comment by LinusBorg** [comment]
Please use the forum for usage questions and support, not old, closed bug issues.

forum.vuejs.org
