### ISSUE TITLE
dev-server is accessible externally

### ISSUE THREAD

**Issue by zdunczyk** [vuejs-templates/webpack#284]
Fantastic project.

One small issue I found so far is that when you start dev-server with default configuration it starts listening on external port 8080, which is accessible from the outside of localhost. I believe that it's not common to use external IP while developing things locally. I would opt to limit it to 127.0.0.1, to prevent unintended code/assets leaking.

Simple solution would be to add 2nd argument for app.listen call:
`module.exports = app.listen(port, '127.0.0.1', function (err) {`

**Comment by Sarke** [comment]
It's not that uncommon I think. Personally I code in one VM and view in another. I think locking down ports is on the user, but an option for which host/ip to listen on would be useful.

**Comment by chrisvfritz** [comment]
I also know dozens of people personally (including myself) who use this kind of setup to test on external devices and also to share prototypes with other people on a team, especially during meetings. It's a feature, not a bug. 😉  For those who are very worried about accidentally leaking something in a coffee shop, I think it's up to them to take their own security measures. For example, it's not uncommon for companies require all remote development work to be done on a secure VPN.
