### ISSUE TITLE
Can't get it to work with Stylus: Module build failed: TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by cho-is** [vuejs-templates/webpack#286]
I am trying to upgrade to Vue 2 and can't get it to work with Stylus:

`Module build failed: TypeError: path must be a string or Buffer`

I know it was a bug with node 6 but `stylus-loader` has been fixed. 

Does anyone have any clue please?
```
"stylus": "^0.54.5",
"stylus-loader": "^2.3.1",

node v6.7.0
npm 3.10.7
```

**Comment by chrisvfritz** [comment]
Please provide a minimal example that demonstrates the issue. Stylus is working fine for me. 😕

**Comment by cho-is** [comment]
Oh, I have uninstalled `npm` with `brew` and install it again with `n` and it seems to be ok now!

Closing this for now. It's being really annoying me for a day. I will reopen with a repro if comes back.
