### ISSUE TITLE
Using vue 2.0, Error Cannot resolve module 'vue-style-loader'

### ISSUE THREAD

**Issue by junerockwell** [vuejs-templates/webpack#288]
I have node v4.2.2 on the latest MacOS. Vue-CLI version 2.4.0.

I wanted to test webpack using VueJS 2.0: `vue init webpack testV2`

After I did `npm install`, I did `npm run dev` which results in the error on my terminal.

````
ERROR in ./src/App.vue
Module not found: Error: Cannot resolve module 'vue-style-loader' in /Users/[username]/Documents/testingVue/vtwo/src
 @ ./src/App.vue 4:0-136

ERROR in ./src/components/Hello.vue
Module not found: Error: Cannot resolve module 'vue-style-loader' in /Users/[username]/Documents/testingVue/vtwo/src/components
 @ ./src/components/Hello.vue 4:0-150
````
So I looked at the `package.json` to see if `vue-style-loader` is in the `devDependencies`. I also compared it to the `package.json` of my VueJS version 1 projects. `vue-style-loader` is in VueJS version 1 but it's not when using VueJS 2.0.

Is `vue-style-loader` supposed to be missing? What is the correct work-around for this?

**For now, I copied `"vue-style-loader": "^1.0.0",` from the `package.json` of my older projects using VueJS 1.0 and pasted to the `package.json` of my new project created with VueJS 2.0.

**Comment by pksunkara** [comment]
`vue-style-loader` is a dependency of `vue-loader`, so, it should work as it is.

**Comment by chrisvfritz** [comment]
@zigomir Do you know what's going on here? Did something change since [this commit](https://github.com/vuejs-templates/webpack/pull/225/commits/3d2098bcedb0f007488be3e6e56f182a25d1fb02)?

**Comment by andreixk** [comment]
@junerockwell  I had the same problem, adding `"vue-style-loader": "^1.0.0"` to the package.json and runing `npm install` fixed the issue. Thanks!

**Comment by shagflak** [comment]
Hello when i am adding lang="sass" i get the following error...

```
<style lang="sass" >
  #app {
    font-family: 'Avenir', Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
  }
</style>
```

Resulting on this error
```
This dependency was not found:

* !!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../node_modules/vue-loader/lib/style-compiler/index?{"id":"data-v-005435fc","scoped":false,"hasInlineConfig":false}!sass-loader?{"s
ourceMap":false}!../node_modules/vue-loader/lib/selector?type=styles&index=0!./App.vue in ./src/App.vue

To install it, you can run: npm install --save !!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../node_modules/vue-loader/lib/style-compiler/index?{"id":"data-v-005435fc","scoped":f
alse,"hasInlineConfig":false}!sass-loader?{"sourceMap":false}!../node_modules/vue-loader/lib/selector?type=styles&index=0!./App.vue
> Listening at http://localhost:8080
```

I did what @andreixk said about adding vue-style-loader: "1.0.0" but i am still unsuccesful on that matter.

**Comment by andreixk** [comment]
@shagflak you also have to run `npm install` in that directory to actually get the package installed

**Comment by shagflak** [comment]
@andreixk i ran "npm install" on the root of my project the thing i havent't tried it's change the version of vue-style-loader directly on the package.json of the vue-loader subpackage and run npm install from there to see if it helps.

On the other hand you mean updating the vue-loader to the 3.0.1 version?

my package.json overall looks like this:

```
{
  "name": "acc-test",
  "version": "1.0.0",
  "description": "Test Project for MyAccounts",
  "author": "Altaflux <pabloloz@gmail.com>",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "node build/build.js",
    "unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",
    "e2e": "node test/e2e/runner.js",
    "test": "npm run unit && npm run e2e",
    "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs"
  },
  "dependencies": {
    "axios": "^0.16.1",
    "bootstrap-sass": "^3.3.7",
    "css-loader": "^0.28.3",
    "vue": "^2.2.6",
    "vue-resource": "^1.3.1",
    "vue-router": "^2.3.1",
    "vue-style-loader": "^1.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^3.19.0",
    "eslint-friendly-formatter": "^2.0.7",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.11.1",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "webpack-bundle-analyzer": "^2.2.1",
    "cross-env": "^4.0.0",
    "karma": "^1.4.1",
    "karma-coverage": "^1.1.1",
    "karma-mocha": "^1.3.0",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-phantomjs-shim": "^1.4.0",
    "karma-sinon-chai": "^1.3.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.30",
    "karma-webpack": "^2.0.2",
    "lolex": "^1.5.2",
    "mocha": "^3.2.0",
    "chai": "^3.5.0",
    "sinon": "^2.1.0",
    "sinon-chai": "^2.8.0",
    "inject-loader": "^3.0.0",
    "babel-plugin-istanbul": "^4.1.1",
    "phantomjs-prebuilt": "^2.1.14",
    "chromedriver": "^2.27.2",
    "cross-spawn": "^5.0.1",
    "nightwatch": "^0.9.12",
    "selenium-server": "^3.0.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.2.0",
    "rimraf": "^2.6.0",
    "url-loader": "^0.5.8",
    "vue-loader": "^11.3.4",
    "vue-style-loader": "^2.0.5",
    "vue-template-compiler": "^2.2.6",
    "webpack": "^2.3.3",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.18.0",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

**Comment by bencarter78** [comment]
I am also getting this error on a fresh install. I amended App.vue to include my sass file and I now get the following error...

```
This dependency was not found:

* !!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-544e619c","scoped":false,"hasInlineConfig":false}!sass-loader?{"sourceMap":false}!./assets/sass/app.scss in ./src/App.vue
```

I've run npm install, can't figure out what's wrong. Any help would be greatly appreciated!

**Comment by bencarter78** [comment]
Actually, the message in the terminal didn't really help me, but the error showing where the app would be (loading http://localhost:8080) said it couldn't find sass-loader, and then node-sass. Added them and now it works!

**Comment by robertjchristian** [comment]
Could be conflicts in node_modules folder.  Good idea to make sure it's clean.

Try:

`rm -rf node_modules && npm install`

**Comment by a459295360** [comment]
npm i sass-loader or yarn add sass-loader

**Comment by NodiraIbrogimova** [comment]
After getting update from my teammates in git, I had the same issue in vuejs app. 
1. Deleting package-lock and node_modules
2. And reinstalling my dependencies (npm install) worked for me

**Comment by Angular-injector-progeny** [comment]
> Actually, the message in the terminal didn't really help me, but the error showing where the app would be (loading http://localhost:8080) said it couldn't find sass-loader, and then node-sass. Added them and now it works!





https://lnkr.fun/5b0f034
