### ISSUE TITLE
running tests

### ISSUE THREAD

**Issue by ninjabunny** [vuejs-templates/webpack#289]
`npm run unit  ` gives me this error:
```
30 09 2016 20:05:18.707:ERROR [plugin]: Error during loading "my-project/node_modules/karma-phantomjs-launcher" plugin:
  Path must be a string. Received null.
```
Tried npm install karma related stuff. Not sure what to do... Thanks for the help.

**Comment by chrisvfritz** [comment]
Can you please provide more information about your system (e.g. OS, node version), as well as a minimal example project that reproduces the issue? If you changed any configuration after generating the project, that's also important.

**Comment by chrisvfritz** [comment]
Haven't heard anything, so assuming this is resolved.
