### ISSUE TITLE
make a standalone build package (like create-react-app project)

### ISSUE THREAD

**Issue by yegor-sytnyk** [vuejs-templates/webpack#298]
In [create-react-app](https://github.com/facebookincubator/create-react-app) all client build configurations are encapsulated in separate package, which is easy to update and all client build complexity is kept outside of the client app. 

That limits configuration options, but out of the box works well for most apps.

Would be great to have something similar for Vue.

**Comment by chrisvfritz** [comment]
This is something we've been considering. In the meantime you may enjoy [vbuild](https://github.com/egoist/vbuild), which was developed by a member of the Vue team.

**Comment by kazupon** [comment]
support `build` command of `vue-cli` at v2.8.0
