### ISSUE TITLE
When to support the webpack 2.x

### ISSUE THREAD

**Issue by zce** [vuejs-templates/webpack#299]
When to support the webpack 2.x?

**Comment by chrisvfritz** [comment]
Probably after it's officially released. It's still in beta right now.

**Comment by zce** [comment]
@chrisvfritz

**Comment by chrisvfritz** [comment]
No problem. We are actually using v2 in the `webpack-simple` template by the way. It's a bit safer, since it's a much less complex configuration, but even that we had to lock down to a specific version because of breaking changes.

**Comment by boustanihani** [comment]
Any updates on this ?

Webpack is at v2.2.0-rc.7 right now (https://github.com/webpack/webpack/releases) and they also offer links for documentation and tutorials on the official site :)
