### ISSUE TITLE
Is seems that url is incorrect in teminal when run npm run dev.

### ISSUE THREAD

**Issue by Vazgen7788** [vuejs-templates/webpack#3]
![2016-01-06_1617](https://cloud.githubusercontent.com/assets/8538941/12142449/9918f440-b491-11e5-8e33-860f782582cd.png)

When i run `npm run dev` on windows 7 os in git bush terminal webpack says that the url is `http://0.0.0.0:8080/` but it doesn't work.It works on `localhos:8080`.

**Comment by yyx990803** [comment]
This is intended - 0.0.0.0 listens to localhost and in addition exposes the app over the local network so that you can test it with mobile devices etc.
