### ISSUE TITLE
can not access src/assets by relative path

### ISSUE THREAD

**Issue by airyland** [vuejs-templates/webpack#30]
I have to add  `app.use('/assets',express.static('./src/assets'))` to make it work.
 https://segmentfault.com/q/1010000004479605

**Comment by hanai** [comment]
css 是由js里require的，而不应该这样写到html里。

**Comment by yyx990803** [comment]
You should think of css as module dependencies when using webpack. You can import css or sass directly inside `*.vue` files using `<style src="..." lang="..."></style>`.

**Comment by airyland** [comment]
But how can I include a image using `<img src=""/>` or include a common js like `zepto`?

**Comment by yyx990803** [comment]
`<img>` inside Vue templates will be processed by `vue-html-loader` which will serve the target file correctly on the dev server (and inline/copy the file during production build).

For JavaScript you should really install them through npm and just import instead of thinking about script tags.
