### ISSUE TITLE
Is possible minify files in static directory?

### ISSUE THREAD

**Issue by plcosta** [vuejs-templates/webpack#304]
Hi there!

"Real" static assets are directly copied to their final destination as-is, with the same filename. Is possible to minify css and js files in static directory and copy only a single file?

Anyway just a suggestion. Thanks!

**Comment by jbruni** [comment]
In my opinion, this sounds like a very particular need that may be configured for an individual project, rather than a general use case to be applied for everyone by changing the vuejs-webpack template itself.

**Comment by chrisvfritz** [comment]
@plcosta That's what the `src` directory is for. The `static` directory is only for files that you specifically _don't_ want to go through your build process.

**Comment by plcosta** [comment]
Right @chrisvfritz, thanks!
