### ISSUE TITLE
rename: vuejs-boilerplates

### ISSUE THREAD

**Issue by ryandeussing** [vuejs-templates/webpack#305]
Given what templates mean within Vue, and the search results you get for `vue templates`, it might be a good idea to rename this org to `vuejs-boilerplates`

**Comment by jbruni** [comment]
Sounds good, in my opinion. I regret the suggestion didn't come earlier... I wonder how many changes to tooling is necessary to support this name change...

**Comment by chrisvfritz** [comment]
I can understand the reasoning, but I'm not sure it causes enough pain currently to be worth the pain of the transition (for both maintainers and users). When I search for `vue templates` in Google (with no user signed in, in incognito mode), the first 3 links are this organization, then the components guide, then the syntax guide. That seems pretty ideal to me. No matter what people actually have in their heads, they can find it in the first 3 results.

Also to some extent, "what's done is done" - even if boilerplates might have been a better name to start with, current users may search for `vue templates` expecting to find this organization, but then end up confused when it stops appearing in search results.

**Comment by ryandeussing** [comment]
All good points.
