### ISSUE TITLE
Data URL for asset not generated when a variable is used

### ISSUE THREAD

**Issue by benjamincrozat** [vuejs-templates/webpack#307]
When there's a variable in a src attribute (for example), the data URL for the asset isn't generated anymore. Here's an example:
```html
<img :src="`../../assets/img/filters/${preview}`" width="80" height="80" :alt="name">
```

Same thing if I do it this way:
```html
 <img src="../../assets/img/filters/{{ preview }}" width="80" height="80" :alt="name">
```

**Comment by LinusBorg** [comment]
If you have a limited number of assets that you later want to dynamically require, you will have to use webpack's [require.context](https://webpack.github.io/docs/context.html) feature to make that possible.
