### ISSUE TITLE
Why alias Vue default export?

### ISSUE THREAD

**Issue by guidobouman** [vuejs-templates/webpack#309]
The default Vue export is aliased in https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js#L23 

Do we really want this? For the standalone build this makes sense of course. But the runtime build should not be aliased, right? This is just another possible point of failure without adding a specific gain.

**Comment by LinusBorg** [comment]
We were considering switching the default export to the standalone build shortly before the 2.0 release, and to prepare for either situation, we added aliases for both.

the runtime-only one can be removed now, that's correct. I will push the change soon, have some  other fixes/tweaks in the works to go with that.

**Comment by guidobouman** [comment]
Cool, I can work on some enhancements as well. As I'm working with this template on a regular basis nowadays.

Is there a specific list of items to pick up, or is that just the Github issue list? Maybe add a github project to make contributing a bit easier?

**Comment by LinusBorg** [comment]
this was solved with #314
