### ISSUE TITLE
how to add another html page?

### ISSUE THREAD

**Issue by KrishnaPG** [vuejs-templates/webpack#316]
I am using this template, and it is working fine with the index.html. 

Now, I have added another `person.html` page next to the `index.html` page (in the same folder) and when run `npm run dev` the location `localhost:8080/person.html` is not being resolved (getting `Cannot GET /person.html` error).

Added a link to the `person.html` inside the `index.html` - did not help.

Please inform, how to have multiple top level pages (at the same level as the index.html)?

**Comment by moonou** [comment]
umm...., this is a single page application, logic code write in `*.vue` file, if you need add another html file, add html file to `static` folder, that location like `localhost:8080/static/*.html`, but  this has no meaning. maybe you need [vue-router](https://github.com/vuejs/vue-router)

**Comment by chrisvfritz** [comment]
Yes, as this template is for single-page applications, [Vue Router](http://router.vuejs.org/) would be the correct option to achieve multiple routes.

**Comment by KrishnaPG** [comment]
Thanks. Wondering, how is the `index.html` got copied to the output (even though it is not inside the `static` folder) ?

**Comment by LinusBorg** [comment]
`HtmlWebpackPlugin` does that: 

https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.prod.conf.js#L45-L60

(Don't let the template strings (`{{#...}}`) from the template install options don't confuse you).
