### ISSUE TITLE
Accessing Vue instance in "non-vue" files.

### ISSUE THREAD

**Issue by dejan7** [vuejs-templates/webpack#317]
I've created a simple JS module 'AuthService' which is not related to Vue in any way. I'm just importing the module in my Vue components and using it's methods. E.g.:

```
//Sidebar.vue
<script>
    import Auth from 'src/services/AuthService.js';

    export default {
        name: 'sidebar',
        ....
        methods: {
            logout: function() {
                Auth.logout();
                this.$router.push('/auth/login');
            }
        }
        ...
    }
</script>
```

However my issue is that i would like to somehow access my app's Vue instance because i want to dispach Vuex commits. Ideally, my AuthService would look like this:

```
//AuthService.js
export default {
   ....
    logout: function () {
        localStorage.removeItem('authToken');
        Vue.$store.commit('clearCurrentUser');
    },
   ...
}
```

But i don't know what to import here to make this work - is it even possible? What would be the best way to go about this?

I apologize if this is not the place for such questions. Thanks.

**Comment by chrisvfritz** [comment]
Since this is a usage/support question, rather than a bug report or feature request, I recommend posting this on either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue).

**Comment by zxc23** [comment]
@dejan7 
You can access Vuex without going through the Vue instance, e.g.:

`import store from './vuex/store'
import * as actions from './vuex/actions'

actions.someAction(store, 123)`

or equivalent with require(). You can probably skip actions as well if you wanted to.
