### ISSUE TITLE
Add additional directories to hot reload

### ISSUE THREAD

**Issue by ahopkins** [vuejs-templates/webpack#318]
I am trying to extend my file structure from the default, and having troubles getting hot reload to track those changes. I am not 100% sure where I need to point webpack to listen to additional directories.

For instance, with the following structure ...

    /components
        /sub
            Goodbye.vue
        Hello.vue
    /views
        HowAreYou.vue

If I make a change to `Hello.vue`, voila, as expected, HMR gets my changes and makes the refresh in the browser.

However, if I make a change to `Goodbye.vue` or `HowAreYou.vue`, HMR does not catch these and nothing changes. In order to see my edits, I need to stop `npm run dev` and restart it, thus opening a new browser tab, etc, etc. This is not a very friendly workflow. I must be missing something. 

Is there someway to specify additional folders, or some way to tell it to start in the root `src` directory and wath everything underneath?

**Comment by chrisvfritz** [comment]
I have not experienced this - hot reload works no matter where I put files. Could you provide an example repo?

**Comment by LinusBorg** [comment]
Also can't reproduce this, I use components in various places and HMR works correctly.

**Comment by ahopkins** [comment]
Wow. Hmm.... Sure. I'll upload my repo and send you link when I am back at a computer. If not today, it might be a couple days. Sorry for delay.

**Comment by ahopkins** [comment]
Okay I am closing this. Seriously, I did absolutely NOTHING to my environment except walking away for 24 hours. Seems to be working fine. Closing. Sorry :-(

**Comment by jkehler** [comment]
I am encountering the exact same issue you were. As soon as I put my Components inside a nested folder they no longer are being picked up by the hot module reloader. I have no idea how to resolve it.

I'm using VIM under Linux.

**Comment by jkehler** [comment]
I can confirm it's not VIM as I just tried opening Sublime Text and saving a file under a nested folder and HMR did not pick it up. So it must be something with the Linux file watcher.

**Comment by ahopkins** [comment]
@jkehler I know you will likely not like my answer, but I scrapped my project folder and started again. Incrementally adding packages back and components to see that nothing broke. The annoying thing is that my two folders (`new_project` and `legacy_project`) are identical. One works as expected, the other is the problem above. 

Frustrating? Yes.

**Comment by holic-cl** [comment]
i had same issue, but @jkehler answer solve my problem.
