### ISSUE TITLE
babel-runtime not installed by default prevent webpack to build the bundle properly (ie. when using the 'typeof' keywork in the source code) when using an old version of npm (v1.4.21)

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuejs-templates/webpack#325]
I created a new project with the following command line : `vue init webpack my-project-name`.

Everything looked fine and webpack could compile my ES6 code without problem.

However, as soon as I added the `typeof` keyword in my code, or used an external library (ie. d3.js), webpack/babel output lots of errors like :
```
» npm run dev
 
> cdz@1.0.0 dev /home/user/dev/vuejs
> node build/dev-server.js
 
Listening at http://localhost:8080
 
webpack: wait until bundle finished: /index.html
webpack: wait until bundle finished: /__webpack_hmr
webpack: wait until bundle finished: /__webpack_hmr
webpack: wait until bundle finished: /index.html
webpack built a6f3de609bff15fc99ae in 36500ms
Hash: a6f3de609bff15fc99ae
Version: webpack 1.13.2
Time: 36500ms
Asset     Size  Chunks       Chunk Names
app.js  3.24 MB       0       app
 
ERROR in ./src/js/utils.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/slicedToArray' in /home/user/dev/vuejs/src/js
@ ./src/js/utils.js 1:296-342
 
ERROR in ./src/js/utils.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/typeof' in /home/user/dev/vuejs/src/js
@ ./src/js/utils.js 1:416-455
 
ERROR in ./src/js/utils.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/array/from' in /home/user/dev/vuejs/src/js
@ ./src/js/utils.js 1:512-555
 
ERROR in ./src/js/utils.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/set' in /home/user/dev/vuejs/src/js
@ ./src/js/utils.js 1:606-642
 
ERROR in ./src/lib/d3/d3.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/math/sign' in /home/user/dev/vuejs/src/lib/d3
@ ./src/lib/d3/d3.js 1:23-65
 
ERROR in ./src/lib/d3/d3.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/math/log2' in /home/user/dev/vuejs/src/lib/d3
@ ./src/lib/d3/d3.js 1:116-158
 
ERROR in ./src/lib/d3/d3.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/math/log10' in /home/user/dev/vuejs/src/lib/d3
@ ./src/lib/d3/d3.js 1:208-251
 
ERROR in ./src/lib/d3/d3.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/json/stringify' in /home/user/dev/vuejs/src/lib/d3
@ ./src/lib/d3/d3.js 1:307-354
 
ERROR in ./src/lib/d3/d3.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/create' in /home/user/dev/vuejs/src/lib/d3
@ ./src/lib/d3/d3.js 1:418-464
 
ERROR in ./src/lib/d3/d3.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/typeof' in /home/user/dev/vuejs/src/lib/d3
@ ./src/lib/d3/d3.js 1:523-562
Child html-webpack-plugin for "index.html":
Asset     Size  Chunks       Chunk Names
index.html  1.46 MB       0
webpack: bundle is now VALID.
```

Not recognizing `typeof` is astonishing isn't?

Well, after searching for too long, I found out that the base webpack skeleton lacks a very basic thing ; the `babel-runtime` package!

So, to fix those errors, you just have to do `npm install --save-dev babel-runtime`.

I therefore think that `babel-runtime` should be added to this template.

**Comment by LinusBorg** [comment]
``babel-runtime` does *not* have to be defined as a devDependency. 

This template works as it should for me. Please provide the following information:
1. node version
2. npm version
3. Is there a `.babelrc` file in your project's root directory, and does it look like this:
```js
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```

**Comment by AlexandreBonneau** [comment]
Well, I first asked in the babeljs slack channel, and it's the only [answer](https://babeljs.slack.com/x-92541935527-92546509412/archives/discussion/p1476743509004931) that did fix the problem for me.

Here is the needed info :
```
» npm --version
1.4.21
» nodejs --version
v4.3.1
» uname -a
Linux Host 4.7.0-1-amd64 #1 SMP Debian 4.7.5-1 (2016-09-26) x86_64 GNU/Linux
» lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux testing (stretch)
Release:        testing
Codename:       stretch
» cat .babelrc 
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```
Note:  my OS install is fresh from a few days, so this bug might arise only if you haven't previously `npm -g install babel-runtime`?

**Comment by LinusBorg** [comment]
You run on npm 1.4 ?

that might probably be the problem. you should be using version 3.

As explained in the readme, this template is not tested with npm <3

**Comment by AlexandreBonneau** [comment]
Ok, the `npm` version shipped by Debian is very, very old (cf. [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794890)).

I updated `npm` to 3.* by using `npm -g install npm`, created a new project with the webpack template, and indeed, I can now use `typeof` in the component files.

Note : when using `vue-cli`, perhaps a warning could be shown when the user is using an old npm version?

**Comment by chrisvfritz** [comment]
We could add this to the template's `package.json`. That way, people would be warned if they're not using at least Node 4.

``` js
{ "engines" : { "node" : ">=4.0.0" } }
```

**Comment by AlexandreBonneau** [comment]
Or, for people using debian-based system, tell them they could 'fix' the problem by manually installing `babel-runtime` as a dev dependency, if they do not want to update npm?

@chrisvfritz this would not change anything since by default on Debian, node version is currently the v4.3.1, it's the npm version that needs to be checked to be `>=3.0.0`.

**Comment by LinusBorg** [comment]
I closed this as it is not a problem of this template.

We can't cater towards any problem that (hightly) outdated tools may have with this setup.

**Comment by AlexandreBonneau** [comment]
I understand, on the other hand, Debian has many users, and is the base of many popular distros, which means lots of users are by default running that highly outdated tool.

A simple warning could help those users understand why they get those error messages, and save them the hours I put in finding out their cause.

**Comment by chrisvfritz** [comment]
I'll put together a preinstall script to check versions of Node and NPM.
