### ISSUE TITLE
Hot reloading stops when changing styles in a .vue file. 

### ISSUE THREAD

**Issue by n15e** [vuejs-templates/webpack#334]
**What did I do ?**

```
$ npm install -g vue-cli
$ vue init webpack my-project
$ cd my-project
$ npm install
$ npm run dev
```

Then I went inside the `src` directory and changed the `src/components/Hello.vue`  file. Hot reloading was working fine. But then I added

```
*{
    font-weight:bold;
}

```
to the styles. And then on line 35 I changed it from `<style scoped>` to `<style >` and then back to  `<style scoped>` . Repeated this a few times.

**What happened?**

Hot reloading stopped working. 

**Additional Info.**

I had the network tab in the firefox inspector on, and after playing around with `style` it shows no new connections.

On reloading the page by pressing F5 shows the changes. 

On the command line webpack shows that it successfully bundled everything even when hot reloading stops working.

**Comment by chrisvfritz** [comment]
This is a known limitation unfortunately - added or removed styles won't trigger a hot reload. There's an [issue open](https://github.com/vuejs/vue-loader/issues/166) for it if you'd like to add anything or take a stab at a PR.
