### ISSUE TITLE
manually including vue-resource?

### ISSUE THREAD

**Issue by gkatsanos** [vuejs-templates/webpack#335]
I'm not a webpack expert (and by the look of it I won't becoming one any day soon..:/ ) 

I'm trying to include vue-resource, and setting the configuration [as described in their documentation](https://github.com/vuejs/vue-resource/blob/master/docs/config.md): 

> Webpack/Browserify
> 
> Add vue and vue-resource to your package.json, then npm install, then add these lines in your code:
> 

```
var Vue = require('vue');
var VueResource = require('vue-resource');

Vue.use(VueResource);
```

But by looking at `build/webpack.base.conf.js` , I can't figure out how to include it.. 

That was my attempt:

```
    alias: {
      'vue$': 'vue/dist/vue',
+     'vue-resource': 'vue/dist/vue-resource',
      'src': path.resolve(__dirname, '../src'),
```
Would be pretty cool if someone pointed me to a doc that explains how this conf is setup and how to extend it?

**Comment by chrisvfritz** [comment]
Adding new packages usually won't involve touching Webpack (and shouldn't in this case). It's the same as any NPM-managed project. For further assistance on using NPM or Webpack though, I recommend posting your question on either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue), as we try to reserve the issues for bugs and feature requests.

**Comment by gkatsanos** [comment]
@chrisvfritz would you mind adding some example or documention on how to include a vue related package and import it with the vuejs-templates?

**Comment by chrisvfritz** [comment]
As I said, adding and using another package (Vue-related or not) does not involve anything unique to Vue or Webpack and we simply don't have to capacity to teach people how to use all the technologies in the JavaScript ecosystem. Here are some external resources you may find helpful:

- [Installing packages with NPM](https://docs.npmjs.com/getting-started/installing-npm-packages-locally)
- [Importing modules with Babel](https://babeljs.io/docs/learn-es2015/#modules)

**Comment by gkatsanos** [comment]
Hold on, I know how to add a package with npm and import it with Babel, but I thought it could be vue-cli's responsibility to help you with bootstrapping the project to have an option to include vue-router or vue-resource (together with the necessary configuration..?)

**Comment by chrisvfritz** [comment]
Nope. See [this template's docs](http://vuejs-templates.github.io/webpack/) for everything it handles.

**Comment by gkatsanos** [comment]
Thanks a lot for this link! I have a question regarding http://vuejs-templates.github.io/webpack/proxy.html - should I make an issue here or in http-proxy-middleware ?

**Comment by gkatsanos** [comment]
Uhm, hold on, I guess my question should be at least towards vue-cli which
is bootstrapping a Vue.js project and should normally give the possibility
to choose whether you want a router or a resource?

**Comment by chrisvfritz** [comment]
Usage questions are best suited to either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue), as we try to reserve issues for bugs and feature requests.
