### ISSUE TITLE
Build command does not extract images into external files

### ISSUE THREAD

**Issue by domhadfield** [vuejs-templates/webpack#336]
In preparation for this ticket, I remove the vue-cli and reinstalled it.

When running the build command on a project with all default settings, the logo.png (ROOT/src/assets/logo.png) image is bundled into the javascript (ROOT/dist/static/js/app.{hash}.js) as a base64.

I have peeked into the webpack configs and I do not believe that this behaviour is intended and that the assets are meant to be extracted.

**Comment by chrisvfritz** [comment]
This is a feature, not a bug. 😉  See [the docs](http://vuejs-templates.github.io/webpack/static.html).
