### ISSUE TITLE
hot reload problem

### ISSUE THREAD

**Issue by rongself** [vuejs-templates/webpack#338]
I use 1.x version ,while i change the code,the hot reloader doesn't reload program sometimes,any one meet this problem?
英文太差写下中文,我用的是1.x版本,我发现代码热更新不是很灵敏,有时候改了代码也没反应,不知道有没有遇到这个问题?

**Comment by chrisvfritz** [comment]
Can you please provide more information about when this happens for you and on what kind of system? It's also worth looking through [closed issues](https://github.com/vuejs-templates/webpack/issues?q=hot+reload+is%3Aclosed) to see if what you're noticing is reolved there.

**Comment by rongself** [comment]
Thanks for remind,I'v found the [relate issue](https://github.com/vuejs-templates/webpack/issues/17) in closed issues,this can be closed
