### ISSUE TITLE
Is this line correct?

### ISSUE THREAD

**Issue by rhysburnie** [vuejs-templates/webpack#341]
Hi just out of interest for [dev-server.js](https://github.com/vuejs-templates/webpack/blob/master/template/build/dev-server.js)

Shouldn't this line:

```
if (!process.env.NODE_ENV) process.env.NODE_ENV = config.dev.env
```

Be:

```
if (!process.env.NODE_ENV) process.env.NODE_ENV = config.dev.env.NODE_ENV
```

Since `config.dev.env` is an object or does node use some magic to detect to us the NODE_ENV prop if an object has it?

This is also happening in other files like `webpack.prod.conf`

**Comment by jamesjieye** [comment]
Yes, it is correct.

`JSON.parse()` will return a string if the input is a string. Checkout the doc of [JSON.parse()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) here.
