### ISSUE TITLE
`vue init webpack#1.0 vue-demo1`not work

### ISSUE THREAD

**Issue by muwenzi** [vuejs-templates/webpack#342]
hi, I want to use Vue1.x and install vue-cli(2.4.0) 
but `vue init webpack#1.0 vue-demo1` is not work
![image](https://cloud.githubusercontent.com/assets/12554487/19791855/8c167156-9cf7-11e6-8426-e580c5f0e745.png)

`npm i vue-cli@1 -g` and `vue init webpack#1.0 vue-demo1` is also not work

thanks! it maybe a simple issue, but it confuses me a lot.

**Comment by moonou** [comment]
I can't reproduce this issue, 
![image](https://cloud.githubusercontent.com/assets/6938877/19877737/c1e18cc6-a01c-11e6-8191-e3a4b308c941.png)
if me enter a template of error, vue-cli will return `404`
![image](https://cloud.githubusercontent.com/assets/6938877/19877771/11082e72-a01d-11e6-971a-8657a33f8476.png)

**Comment by ca01ei** [comment]
I have the same problem here 
![pics](https://cloud.githubusercontent.com/assets/826773/20796640/0234bb4c-b812-11e6-8e33-37546117a0e1.png)

**Comment by ca01ei** [comment]
Hi, it seems to be a bug of zsh, try to use bash instead.
