### ISSUE TITLE
no-extraneous-dependencies warning

### ISSUE THREAD

**Issue by rhysburnie** [vuejs-templates/webpack#343]
The airbnb style will tell you some packages should be in "dependencies" not "devDependencies"
This was happening in the test script in regards to function-bind.

Setting the following will allow continued use of dependencies like that in devDependencies which seems to be your preference as is mine

_.eslintrc.js_

```
'rules': {
   'import/no-extraneous-dependencies': ['error', {
      devDependencies: true,
      optionalDependencies: false,
    }],
```

**Comment by shailendher** [comment]
This is fixed by #351 .

Please close this ticket.
