### ISSUE TITLE
Question: Runtime vs standalone default in templates vs NPM

### ISSUE THREAD

**Issue by pholly** [vuejs-templates/webpack#344]
I'm new to vuejs. I understand the difference between runtime-only build and standalone thanks to the excellent [documentation](http://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-Build).

This is what's confusing:

### Standalone

- is [recommended for most users](https://github.com/vuejs-templates/webpack/blob/master/meta.js#L32)
- is the default option in the CLI for [this template](https://github.com/vuejs-templates/webpack/blob/master/meta.js#L32) and [browserify template](https://github.com/vuejs-templates/browserify/blob/master/meta.json#L23)
- is configured in [webpack-simple template](https://github.com/vuejs-templates/webpack-simple/blob/master/template/webpack.config.js#L34)
- is pointed to in [simple template](https://github.com/vuejs-templates/simple/blob/master/template/index.html#L5)

### Runtime only

- is the default NPM build
- is used in [browserify-simple](https://github.com/vuejs-templates/browserify-simple/blob/master/template/package.json)

I think it would be less confusing if the default NPM build and default for all templates is standalone.

**Comment by chrisvfritz** [comment]
Agreed. A PR is definitely welcome in browserify-simple. We've also discussed changing the default build and that's still on the table. It's just a tricky transition to manage.

**Comment by chrisvfritz** [comment]
Since there's nothing we can do in this repo however, I'll close this. You're welcome to open a new issue (or just submit a PR at browserify-simple).
