### ISSUE TITLE
About config file,index.js

### ISSUE THREAD

**Issue by hezhongfeng** [vuejs-templates/webpack#346]
in the index.js,the assetsPublicPath is
``` 
assetsPublicPath: '/',
```
when we run build or dev
the index.html is like this 
```
src=/static/js/manifest.56c973f9e26fce93e7be.js
``` 
but It will not work in some OS
so,can we change the assetsPublicPath to `assetsPublicPath: './',`?

**Comment by LinusBorg** [comment]
> but It will not work in some OS

please be more specific. an absolute path should work with every browser and HTTP server.

If you mean it doesn't work if you open the file locally - that's expected and mentioned in the console output during the build process.

**Comment by myst729** [comment]
I have the same issue. I always change `config.build.assetsPublicPath` to `'./'`. But I don't think it's OS related. It's because `/static/js/manifest.[hash].js` is an absolute path.

It's OK in dev environment because the dev server runs at `http://localhost:8080/`, which is the domain root. In such case absolute path and relative path constructs the same URL.

```
http://localhost:8080/index.html

/static/js/manifest.[hash].js   -> http://localhost:8080/static/js/manifest.[hash].js
./static/js/manifest.[hash].js  -> http://localhost:8080/static/js/manifest.[hash].js
```

However, say, your production is served **under a sub-directory** of your domain, things go wrong. Absolute path tries to construct the URL from domain root, which is 404.

```
http://example.com/vue-app/index.html

/static/js/manifest.[hash].js   -> http://example.com/static/js/manifest.[hash].js
./static/js/manifest.[hash].js  -> http://example.com/vue-app/static/js/manifest.[hash].js
```

**Comment by LinusBorg** [comment]
> However, say, your production is served under a sub-directory of your domain

...then you change the assetsPath to that sub-directory.

That's how webpack works, it has hardly anything to do with this template.

**Comment by myst729** [comment]
@LinusBorg Not the best solution, in my opinion.

For example, I'm developing an [open source app](https://github.com/myst729/Vuelog/). If anyone forks the repo and made their own change, that's fine. For people who are not familiar with code, or don't want to customize, they could also grab the build package. In the latter case, I cannot ensure how they serve their deployment. So `'./'` is my choice.

**Comment by LinusBorg** [comment]
The problem with relative paths is that they don'T work well with code-splitting.

**Comment by myst729** [comment]
It does. The app I mentioned uses vue-router. I also enabled code-splitting (but turned off in a later version) and works fine.

**Comment by LinusBorg** [comment]
Hm, in that case i might have to re-test this. In my experience, .lazy-loading a Route component from a route like `/users`  (instead of `/`) will fail, because webpack will try to load the file from `/users/static/js....`
