### ISSUE TITLE
watch is not working in windows

### ISSUE THREAD

**Issue by Pines-Cheng** [vuejs-templates/webpack#349]
when I change  the file under components or other file under src ,the auto watch and Compile in not working on Windows. but it is working well on Mac OS.  Do you have some prompt ?

The environment
node : v6.9.1
npm : v3.10.8

**Comment by yisibl** [comment]
I also encountered such a situation.

**Comment by shah-newaz** [comment]
Not working for me on Mac either. Didn't work on Windows on a vagrant box previously

**Comment by shah-newaz** [comment]
Could it be an issue with Vagrant?

**Comment by Pines-Cheng** [comment]
I found a solution，It is the reason of Webstorm.
Just like the picture under. cancel the last checkbox.
![image](https://cloud.githubusercontent.com/assets/9441951/20048340/e233e5d0-a4f6-11e6-9399-912e2a91375e.png)

**Comment by shah-newaz** [comment]
Hi @Pines-Cheng , Thanks for the suggestion! However, I don't use Webstorm IDE. Sublime text here with no option as such.

**Comment by LinusBorg** [comment]
@shah-newaz dropbox and similar folders are a problem as well.

**Comment by duebbert** [comment]
This can be fixed by using the OldWatchingPlugin(). Add this line to the plugins section in `build/webpack.dev.conf.js`: `new webpack.OldWatchingPlugin(),`

Would be great to test if we're running on Windows and then add this plugin automatically.

**Comment by AndrewBogdanovTSS** [comment]
@Pines-Cheng thanks for your suggestion, but it didn't help. Still no hot reload, no change basically

**Comment by shah-newaz** [comment]
Hey @AndrewBogdanovTSS , What OS are you using ?
For MacOS and Windows, I had to add watch poll to webpack.

Can you try something like this on your webpack dev server config file?

```  const devMiddleware = require('webpack-dev-middleware')(clientCompiler, {
    publicPath: clientConfig.output.publicPath,
    stats: {
      colors: true,
      chunks: false
    },
    watchOptions: { 
      aggregateTimeout: 300, 
      poll: true 
    }
  })```

Check the,
```    watchOptions: { 
      poll: true 
    }```
Part. Hope that helps!

**Comment by AndrewBogdanovTSS** [comment]
@shah-newaz my OS is Win10
I've found what the problem was in my case. I used square brackets [] in the projects directory path. How stupid is that a person can't use brackets in the name of the folder? My path was
C:\Projects\Study\[Vue]\VueCLI\my-app
when I've changed it to
C:\Projects\Study\Vue\VueCLI\my-app
it magically started working
it definitely looks like a bug that should be addressed by a webpack team.

**Comment by sumtui** [comment]
For any late arrivers here then I had this same issue on Linux and I spent hours trying to resolve it trying all solutions above to no avail. Then I rebooted and all works fine now. Very strange.

**Comment by CarlosVillasenor** [comment]
In my case the It worked for me Increasing the amount of inotify watchers:
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by boka18** [comment]
@CarlosVillasenor you the man!

**Comment by leonelsalazar** [comment]
@CarlosVillasenor Super! That works for me. Te rallaste, camarada!
