### ISSUE TITLE
Why is vue-html-loader not set by default?

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs-templates/webpack#35]
Hi,

I have spent some time to figurate out I need the `vue-html-loader' to import well html files with vue template code. Otherwise the syntax as '@click' for example would give some troubles. But I don't see the loader is set by default for html files and wondering if there is any reason?

I'm sure many other users would also split their templates into partials and would get into this difficult to debug issue. I could send a PR if clarified. Thanks.

**Comment by yyx990803** [comment]
Hmm, I just personally never had the need to import html snippets when using Vue. But it doesn't hurt to have it pre-configured.

**Comment by miljan-aleksic** [comment]
Thanks :)
