### ISSUE TITLE
Loader required for vue-formular

### ISSUE THREAD

**Issue by davewallace** [vuejs-templates/webpack#350]
Hi,

I receive the webpack build error: "You may need an appropriate loader to handle this file type." when dropping code from the vue-formular jsfiddle example here, into a mostly bare-bones project (based on vue-cli): https://jsfiddle.net/matfish2/fjurzoLj/

Full error output here: https://gist.github.com/davewallace/0490cb0f7c9afdf735aacff6c182723d

After some googling, so far I have tried adding the following devDependencies to package.json of the vue-cli init output:

```
    "vue-formular": "^1.0.16",
    "vue-resource": "^1.0.3",
    "vue-html-loader": "^1.2.3",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-vue-jsx": "^3.1.2",
    "babel-helper-vue-jsx-merge-props": "^2.0.1"
```

And also adding this to `./config/index.js` of the sane vue-cli init output:

```
  module: {
    loaders: [
      { test: /\.html$/, loader: 'vue-html' },
      { test: /\.vue$/, loader: 'vue-html' }
    ]
  },
```

I don't have a great deal of experience hooking up loaders and juggling lots of dependencies, I'm just trying to get vue-formular up and running using webpack.

Any help appreciated!

**Comment by LinusBorg** [comment]
Please use our forum or ask in the epo for vue.formular. 

We can't provide support for individual plugins in this repository.
