### ISSUE TITLE
NODE_ENV is set to '[object Object]' in the development environment

### ISSUE THREAD

**Issue by kemar** [vuejs-templates/webpack#355]
It took me some time to understand [why string variables need to be wrapped into single and double quotes](https://github.com/vuejs-templates/webpack/commit/db54a924ac2511753a30f53c19a93dd265916fec#diff-eed3c9cd8ce5593f9de87fdeab03be11R27) but I wasn't familiar with [`webpack.DefinePlugin`](https://webpack.github.io/docs/list-of-plugins.html#defineplugin) and its [wrap everything in JSON.stringify](https://stackoverflow.com/q/39564802)!

Anyway, [the actual value of `NODE_ENV`](https://github.com/vuejs-templates/webpack/blob/94e921d0603cb3ec94b05e7a98706f0a38d0a9f0/template/build/dev-server.js#L3) in the `development` environment is set to `'[object Object]'`.

```javascript
$ node

> var config = { env: require('./config/dev.env.js') }
undefined

> config
{ env: { NODE_ENV: '"development"' } }

> process.env.NODE_ENV = config.env
{ NODE_ENV: '"development"' }

> process.env.NODE_ENV
'[object Object]'
```

This could be fixed by using `JSON.stringify` and `JSON.parse` in config files.

E.g. changing `config/dev.env.js`…

```javascript
module.exports = merge(prodEnv, {
  NODE_ENV: JSON.stringify('development')
})
```

…and changing `build/dev-server.js`:

```javascript
if (!process.env.NODE_ENV) process.env.NODE_ENV = JSON.parse(config.dev.env.NODE_ENV)
```

Maybe there is a better way?

**Comment by LinusBorg** [comment]
Oh, that's my mistake, seems i didn't test this thoroughly enough in a recent commit. 

I'll fix it later.

Thanks!

**Comment by LinusBorg** [comment]
it's fixed some time already, forgot to close.
