### ISSUE TITLE
Postcss doesn't compile code

### ISSUE THREAD

**Issue by lavezzi1** [vuejs-templates/webpack#359]
Hello community. I faced the problem with https://github.com/vuejs-templates/webpack

```
  vue: {
    loaders: utils.cssLoaders({ sourceMap: useCssSourceMap }),
    postcss: [
        require('postcss-import')({
            addDependencyTo: webpack
        }),
        require('postcss-nested')(),
        require('postcss-cssnext')({
            warnForDuplicates: false,
            features: {
                customProperties: {
                    variables: require('../src/variables/custom-properties.json')
                },
                customMedia: {
                    extensions: require('../src/variables/custom-media.json'),
                    appendExtensions: true
                }
            }
        }),
        require('postcss-calc'),
    ]
    },
```

My list of postcss plugins. Works perfect if I write var(--red) variables like this in css and then require this css in vue file or even write css directly in vue file. But when I just require css code in my main.js (third part framework) postcss doesn't compile code properly. I got var(--red) in my output css. 

How to fix that?

**Comment by LinusBorg** [comment]
well, the config you showed is only for vue-loader, which only takes care of `.vue` files.

You will have to add the same kind of config to the `module: { loaders:` config for `/\.css$/` files.

See postcss-loader docs: https://github.com/postcss/postcss-loader

Please ask in our forum.vuejs.org for further support - github issues are for bug & feature requests.
