### ISSUE TITLE
Parse Error if use image in html template files.

### ISSUE THREAD

**Issue by zhangxin840** [vuejs-templates/webpack#361]
If I add an IMG to the HtmlWebpackPlugin template file like this:
`<img class="logo" src="src/assets/tomato.svg">`
There will be a parse error:
`
Error: Parse Error: <img class=logo src=data:image/svg+xml;base64,PD  94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pg0KP
htmlparser.js:236 new HTMLParser
[test]/[html-webpack-plugin]/[html-minifier]/src/htmlparser.js:    236:13
`

Turn off minify (in production config) in HtmlWebpackPlugin will fix this problem.
According to this [post](https://github.com/ampedandwired/html-webpack-plugin/blob/master/docs/template-option.md), the HTML will still be minified by the loader even if you turn off the minify option.
So this minify option seems useless, only causing parse errors.

**Comment by LinusBorg** [comment]
> According to this post, the HTML will still be minified by the loader even if you turn off the minify option.

I don't think that's what the README says. minification would only be activated if we had an HTML loader specified, which we don't.

The issue should be something else.

**Comment by Marshane** [comment]
specify the minimize property in the loader's options in your webpack.conf.js
`{
                test: /\.(html|htm)$/,
                loader: 'html?minimize=false'
   }`
