### ISSUE TITLE
Better clear the whole dist folder before building.

### ISSUE THREAD

**Issue by zhangxin840** [vuejs-templates/webpack#362]
In build/build.js:
`rm('-rf', assetsPath)`
The will only clear the static folder. The dist folder will not be clean if you have once changed the HTML files.
It will be better that all the things in dist folder are generated by the building process and remove all the old ones.

**Comment by myst729** [comment]
Yep. I removed that line too, and added `rm('-rf', config.build.assetsRoot)` right after `spinner.start()`.
