### ISSUE TITLE
Unit tests in src/**/*.spec.js

### ISSUE THREAD

**Issue by desjoerd** [vuejs-templates/webpack#364]
Currently tests/specs must be in the test/unit/specs folder. What is the reason for this decision? Create-react-app puts the *.test.js files next to the src files in the src/ folder.

Looking at the boilerplate the only thing holding this back is test/unit/index.js which includes all /src files for code coverage. Is adding an exclude to *.spec.js enough to include my tests in the /src folder?

**Comment by LinusBorg** [comment]
> What is the reason for this decision?

We like it this way.

> Create-react-app puts the *.test.js files next to the src files in the src/ folder.

some prefer it this way, no problem.

> Looking at the boilerplate the only thing holding this back is test/unit/index.js which includes all /src files for code coverage. Is adding an exclude to *.spec.js enough to include my tests in the /src folder?

... it would apper so, yes. Have you had any problems with this?

**Comment by rmartins90** [comment]
Have anyone achieved this? I can exclude other files from coverage but not .spec files. I'm using the following regex:

`/^\.\/(?!app(\.js)?$)(?!cj-docs.*)(?!.+\.json$)(?!.+\.spec(\.js)?$)/`

**Comment by rmartins90** [comment]
I can't make this work adding *.spec.js to regex. Someone got this working?
