### ISSUE TITLE
Provide instructions for including this as a subfolder of existing project?

### ISSUE THREAD

**Issue by mcallan83** [vuejs-templates/webpack#366]
I recently attempted (and failed) to include this as a subfolder of an existing Laravel project, merging the package.json file with the Laravel project, but having everything in a"frontend" folder off the project root.

Is there an easy and clean way to do this? It would be great to have this in the docs so this could we included with existing projects.

**Comment by LinusBorg** [comment]
This template is not meant o be tightly integrated into a Laravel project. For a tight integration, there's e.g. [laravel-elixir-vue-2](https://github.com/vuejs/laravel-elixir-vue-2).

If you simply want to have it in a subfolder, just put it there, I'm not sure what guide is nessessary for this.

If you want to use the laravel app as the API server, make sure to [proxy requests](https://vuejs-templates.github.io/webpack/proxy.html) to it from the devServer.

**Comment by mcallan83** [comment]
Thanks. I was trying to avoid the elixir setup in favor of this one because it offers a lot more out of the box. I settled on keeping this as a separate repo and merging with Laravel on deploy. Thanks for your help!

**Comment by 58bits** [comment]
https://github.com/codecasts/spa-starter-kit

**Comment by mcallan83** [comment]
Thanks... that is just what I am looking for :)
