### ISSUE TITLE
Detect homepage in package.json to serve from github pages

### ISSUE THREAD

**Issue by marcosfede** [vuejs-templates/webpack#367]
Hi! I'm currently using the webpack app generated using the vue-cli.

When I make an app and want to serve it from github pages, the js and css resources can not be found because the route starts with /static/...

with react-create-app , you could specify a "homepage: " in the package.json, and webpack modifies the assetsPublicPath appropriately so your app works when deployed.

it would be nice if the vue-cli generated project looked for an option like that to ease deployment.

**Comment by LinusBorg** [comment]
check out /config/index.js, please. ou can change the publicPath there easily.
