### ISSUE TITLE
npm i warning about eslint-plugin-promise version

### ISSUE THREAD

**Issue by KingMario** [vuejs-templates/webpack#368]
eslint-config-standard@6.2.1 requires a peer of eslint-plugin-promise@>=3.3.0 but none was installed.
in package.json, the version of eslint-plugin-promise is set to _^2.0.1_

Is it necessary or possible to set the version of such dependencies to _latest_?

**Comment by LinusBorg** [comment]
> eslint-config-standard@6.2.1 requires a peer of eslint-plugin-promise@>=3.3.0 but none was installed.
in package.json, the version of eslint-plugin-promise is set to ^2.0

Then we should adjust the dependencies in package.json and test weither that breaks anything.

> Is it necessary or possible to set the version of such dependencies to latest?

This might work in this specific case, but generally this is a very shaky subject, can make builds ver unreliable.
