### ISSUE TITLE
is it possible to support relative static path?

### ISSUE THREAD

**Issue by TennyZhuang** [vuejs-templates/webpack#370]
I really want some page can work on the project gh-pages, such as [xxxx.github.io/repo/]()

**Comment by LinusBorg** [comment]
I don't understand whan the problem is, exactly. Can you explain please?

**Comment by TennyZhuang** [comment]
suppose that the page is `tennyzhuang.github.io/repo1`
the path in dist are all like `/static/js/xxxx`
then browser will request `tennyzhuang.github.io/static/js/xxx` to find the resource.
but the really path is `tennyzhuang.github.io/repo1/static/js/xxx`
so it will display a white page on `tennyzhuang.github.io/repo1`
I think the better path is `static/js/xxx`

**Comment by LinusBorg** [comment]
Wouldn't this setting solve this?

https://github.com/vuejs-templates/webpack/blob/master/template/config/index.js#L10

Just change it to either `''` (relative path), or `'/repo1/'`

**Comment by TennyZhuang** [comment]
`'/repo1/'` worked, thanks.

`''` will make the resource in `assets` not found, it will be better if this will fix (
