### ISSUE TITLE
server-side rendering really is not working 

### ISSUE THREAD

**Issue by anlexN** [vuejs-templates/webpack#373]
Hello , Vuejs Engineers! Could you please tell me why i can't see "server-rendered="true""?
i make sure that correctly use your webpack template ! "npm install" is ok! "npm run dev" is ok !
![ssr](https://cloud.githubusercontent.com/assets/8686739/20456104/57c9a0fe-aea8-11e6-9702-88893bc69d5c.PNG)

**Comment by anlexN** [comment]
please reply me as soon as possible..... @jbruni @ianwalter @guidobouman @pksunkara @anvaka @everyone

**Comment by jamesjieye** [comment]
First of all, this template `webpack` doesn't support server side rendering. What you were running is webpack's dev server.

Second, if you want to check out server side rendering, use this example https://github.com/vuejs/vue-hackernews-2.0.

Third, the correct way to check if the page is server-rendered is 

> Once you have it running locally, you can confirm that server-side rendering really is working by right-clicking on the page and selecting View Page Source (or similar). You should see this in the body: ```<div id="app" server-rendered="true">You have been here for 0 seconds&period;</div>``` instead of: ```<div id="app"></div>```

As it is said here https://vuejs.org/v2/guide/ssr.html#Simple-SSR-with-the-Express-Web-Server.

**Comment by ianwalter** [comment]
@anlexN I'm not a maintainer of this project. For future reference, It's inappropriate to just mention random contributors to help you with a problem.

**Comment by yyx990803** [comment]
This template doesn't include server-side rendering - I'm not sure where you got the impression that it does.

There is currently no official template for server-side rendering, because SSR has a lot to do with your server setup and how your app is structured. The official reference implementation is https://github.com/vuejs/vue-hackernews-2.0

**Comment by anlexN** [comment]
@yyx990803  @jamesjieye ，   because of vue-hackernews-2.0 's diffcults, i don't like it! Could you please tell me how to do that this template webpack does support server side rendering?

**Comment by moonou** [comment]
因为这个项目只是一个vue单页项目的模板，服务器渲染更多需要服务器端的代码去配合，并不适合做一个生成模板。如果需要项目的架构可以去参考vue-hacknews-2.0。
