### ISSUE TITLE
what is the " {{#unit}} "?

### ISSUE THREAD

**Issue by linweiwei123** [vuejs-templates/webpack#379]
![image](https://cloud.githubusercontent.com/assets/11659687/20519902/bdc0b1de-b0df-11e6-9219-1a1bc574c958.png)

**Comment by simplesmiler** [comment]
See [prompts](https://github.com/vuejs-templates/webpack/blob/master/meta.js#L11). Depending on your answer during the initialization of the project, `vue-cli` may include the `{{#unit}}...{{/unit}}` section (and other sections alike) into your package.json.
