### ISSUE TITLE
How to remove Hash for breakpoint debugging?

### ISSUE THREAD

**Issue by think2011** [vuejs-templates/webpack#386]
![137bdf34-39ca-40d0-a900-4e47e9ff9942](https://cloud.githubusercontent.com/assets/3961388/20660893/d5cc247e-b586-11e6-84fc-1d917c2eecb3.png)

I want breakpoint debugging, but this Hash always change when I edit my code. please help me :)

**Comment by CodinCat** [comment]
Update your webpack config, change
```js
devtool: '#eval-source-map',
```
to
```js
devtool: '#source-map',
```
this may help.

**Comment by LinusBorg** [comment]
I will close this assuming @CodinCat's suggestion resovles this. Please open another issue if you still have probelms.

**Comment by think2011** [comment]
tks!
