### ISSUE TITLE
"srcset" doesn't seem to be working

### ISSUE THREAD

**Issue by dfdgsdfg** [vuejs-templates/webpack#396]
Here is my file structure.
```
component > subcomponent > Example.vue
component > subcomponent > assets > photo.jpg
component > subcomponent > assets > photo@2.jpg
```

Below is what I am trying to.
```html
<!-- Example.vue -->
<img src="./assets/photo.jpg" srcset="./assets/photo@2.jpg 2x">

<!-- Renderd -->
<img src="/static/img/photo.jpg" srcset="./assets/photo@2.jpg 2x">

<!-- Expected -->
<img src="/static/img/photo.jpg" srcset="/static/img/photo@2.jpg 2x">
```

Maybe [html-loader](https://github.com/webpack/html-loader) support [srcset](https://github.com/webpack/html-loader/search?q=srcset&type=Issues&utf8=✓), but [vue-html-loader](https://github.com/vuejs/vue-html-loader) does not support it?

Looks like same problem here.
https://stackoverflow.com/questions/40733102/vue-webpack-project-img-cannot-load-static-src

**Comment by LinusBorg** [comment]
you have to tell vue-html loader to parse these attributes.

How to do this is explained [here](https://github.com/vuejs/vue-html-loader#config), and you have to insert those options in your wenpack files after [this line](https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js#L92):

Not tested but should look something like this:
```javascript
vue: {
  html: {
    query: {attrs: "img:src img:srcset"}
  }
  loaders: //....
}

```

**Comment by dfdgsdfg** [comment]
I try to your recipe. Unfortunately it does not work.

```javascript
<!-- Example.vue -->
<img src="./assets/photo.jpg" srcset="./assets/photo.jpg 1x, ./assets/photo@2.jpg 2x">

<!-- Renderd -->
<img src="/static/img/photo.jpg" srcset="./assets/photo.jpg 1x, ./assets/photo@2.jpg 2x">
<img src="data:image/png;base64,..." srcset="./assets/photo.jpg 1x, ./assets/photo@2.jpg 2x">

<!-- Expected -->
<img src="/static/img/photo.jpg" srcset="/static/img/photo@2.jpg 2x">
<img src="data:image/png;base64,..." srcset="data:image/png;base64,... 1x, data:image/png;base64,... 2x"> <!-- really? -->
```
Also I found it related base64 encoding loader(probably url-loader?). But I am not sure `srcset` attirbute can parse base64 encoding with multiple image target such as `1x` or `2x`.

**Comment by LinusBorg** [comment]
It seems that `srcset` specifically is not currently supported by HTML-loader. There was an attempt to add this as a feature, but it was reverted: webpack/html-loader#79

So I guess you have to do this manually, by importing the impages in the Javascript and using a templatze literal:
```javascript
var photos = {
  1: require('./assets/photo.jpg'), 
  2: require('./assets/photo@2.jpg')
}

export default {
  // ...component stuff
  computed: {
    photos() { return photos }
  }
}
```
```html
<img src="/static/img/photo.jpg" v-bind:srcset="`${photos.1} 1x, ${photos.1} 2x`">
```

If your webpack config has a `limit` for the url-loader and you want to prevent inline data-urls, you may have tooverwrite the loader:
```javascript
require('!!url-loader?limit=0!./assets/photo.jpg')
```

**Comment by AndreKR** [comment]
I made a PR. (https://github.com/vuejs/vue-loader/pull/953)

**Comment by assembledadam** [comment]
Would love for this PR to be merged...
