### ISSUE TITLE
Fresh installation fails to complete e2e tests. Times out because #app is not found.

### ISSUE THREAD

**Issue by benjamincrozat** [vuejs-templates/webpack#397]
Chrome launches fine and the test project seems to work fine too. I just can't figure out what's wrong. Does any of you would be kind enough to help me?

<img width="966" src="https://cloud.githubusercontent.com/assets/3613731/20865712/29788850-ba1a-11e6-9e1e-c49cd52cb972.png">

**Comment by LinusBorg** [comment]
@benjamincrozat is this still an issue? I know that for me, that nightwatch / selenium has problems with timeouts every once in a while, but nothing I could pin to this template.

**Comment by benjamincrozat** [comment]
Seems like I'm doing ok now. I have absolutely no idea why though.

**Comment by LinusBorg** [comment]
Okay, will close this then.
