### ISSUE TITLE
Default project builds itself in the dist folder instead of the root

### ISSUE THREAD

**Issue by Nicolapps** [vuejs-templates/webpack#405]
When I create a project with `vue init webpack`, I `npm install` then I build the project with `npm run build`, the project is built in a _dist_ folder, instead of at the root of my project.

<img width="493" alt="Project structure" src="https://cloud.githubusercontent.com/assets/7029582/21075871/6f37588c-bf1d-11e6-88c2-d0dbbc72db7c.png">

I'm using vue-cli 2.5.1 and macOS 10.12.1. I was able to reproduce the bug twice.

Here's the configuration I'm using : 

_? Generate project in current directory? **Yes**
? Vue build **standalone**
? Use ESLint to lint your code? **Yes**
? Pick an ESLint preset **AirBNB**
? Setup unit tests with Karma + Mocha? **No**
? Setup e2e tests with Nightwatch? **No**_

**Comment by LinusBorg** [comment]
That's how it is supposed to work. The `/dist` folder is supposed to be deployed. This is practically "default" behaviour for frondend builds in the industry right now.

I don't see any issue with that. Do you have a specific problem with it?

**Comment by Nicolapps** [comment]
OK, now I understand. I was confused because the docs are not very clear (the dist/ folder is not mentioned in the project structure : http://vuejs-templates.github.io/webpack/structure.html). 

I would like to compile the assets directly in the project root (because I'm using GitHub Pages). How could I modify the config files to do so ?

**Comment by LinusBorg** [comment]
I would rather change [this line](https://github.com/vuejs-templates/webpack/blob/master/template/config/index.js#L8):
```javascript
  assetsRoot: path.resolve(__dirname, '../dist'),
//to:
  assetsRoot: path.resolve(__dirname, '../docs'),
```

and then use this option for github pages:

![image](https://cloud.githubusercontent.com/assets/1444526/21106409/4daf2efc-c08e-11e6-8349-ffe172cc8ef4.png)

**Comment by Nicolapps** [comment]
I'll use [Surge](https://surge.sh), it will be a lot easier ! 😄

I think it would be worth mentioning the `dist/` folder in the documentation.
