### ISSUE TITLE
dots in url segment

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [vuejs-templates/webpack#407]
while "npm run dev"
can not use dots in url segments like: http://localhost:6655/app/accounts/avagram.ru/checkpoint
error: "Cannot GET /app/accounts/avagram.ru/checkpoint"
running on real server - no problem.
screen: http://joxi.ru/a2XVPqWf1lXwxr

**Comment by LinusBorg** [comment]
I assume you use vue-router? Anyway, you provide too little information.

**Comment by Vasiliy-Bondarenko** [comment]
yes. i use vue-router. what else can i provide? let me know. i'm not professional in JS/Node.

**Comment by LinusBorg** [comment]
Well, some code would be helpful. Also, you should see error messages in your Terminal if the devserver can't serve what you request.

Or maybe you are just using the router in history mode and tr to access an url by hand through the adress bar? 

I just tested this with a fresh project and had no problems:

![bildschirmfoto 2016-12-12 um 22 02 22](https://cloud.githubusercontent.com/assets/1444526/21119139/7de26642-c0c1-11e6-91cc-23caf1ceacdd.png)

**Comment by LinusBorg** [comment]
Close because OP didn't reply and I couldn'T reproduce the issue.

**Comment by LinusBorg** [comment]
Ah, just remembered something: The devServer uses connect-history-api-fallback to serve `index.html` for any route.

This package doesn't like dots in paths:
