### ISSUE TITLE
How upgrade vue to 2.1

### ISSUE THREAD

**Issue by chs97** [vuejs-templates/webpack#409]
I used install it 2.0, but I upgrade vue and vue-loader , the webpack doesn't work.

**Comment by LinusBorg** [comment]
1. Update your dependencies in package.json to these values:

https://github.com/vuejs-templates/webpack/blob/master/template/package.json#L16
and
https://github.com/vuejs-templates/webpack/blob/master/template/package.json#L85-L87

2. delete `/node_modules`

3. `npm install`
