### ISSUE TITLE
extract-text-webpack-plugin fails to resolve on Fedora during npm run build

### ISSUE THREAD

**Issue by yyx990803** [vuejs-templates/webpack#41]
Moved from https://github.com/vuejs/vue-cli/issues/19

It seems [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin) fails to resolve on Linux (works fine on OSX).

Would appreciate anyone with experience with Webpack on Linux look into this.

**Comment by chrisvfritz** [comment]
I'll try to reproduce and fix this in the next few days on my Linux box.

**Comment by yyx990803** [comment]
@chrisvfritz awesome, thanks in advance! :D

**Comment by chrisvfritz** [comment]
@yyx990803 Wasn't able to reproduce this, unfortunately.

- ubuntu 15.10 64-bit
- linux 4.2.0-16-generic
- npm 3.7.3
- node 5.8.0

I'm happy to dig in further though, with more information about the systems this fails on.

**Comment by cnicodeme** [comment]
I don't have much experience on Webpack but since I'm having this issue I can help.
I'm running Fedora 22, with Node v5.3.0 and NPM v3.3.12 and I'm having the following issue : 

> Uncaught Error: Cannot find module "-!./../../../../..!./../../../node_modules/vue-loader/lib/style-rewriter.js!./../../../../../../../../project/manager/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!vue-style-loader!css-loader!./../../../node_modules/vue-loader/lib/selector.js?type=style&index=0!./login.vue"

If you need more info, I'll be happy to provide them :)

**Comment by chrisvfritz** [comment]
Thanks @cnicodeme! :smiley: I'll try to replicate this in a Docker container and see what happens. In the meantime though - can you try deleting the `extract-text-webpack-plugin` in your `node_modules`, then re-running `npm install`? Knowing if that fixes the problem could be useful.

**Comment by cnicodeme** [comment]
For information, I'm working on my project on two different computer, the second one is an Ubuntu installation : 

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

And the `npm run build` works correctly.
On that computer, here's the different versions : 

```bash
$ node -v
v4.1.1
$ npm -v
v2.14.4
```

**Comment by cnicodeme** [comment]
(I wrongly posted this in the old tickets, so I'm copying it here) :

Hi tested something on my installation : 

I initiated a new project using vue-cli and webpack, and did `npm install && npm run build` and I got this error : 

> ERROR in ./src/App.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../../test/node_modules/extract-text-webpack-plugin/loader.js in /var/www/html/test/src
 @ ./src/App.vue 2:0-321
Child html-webpack-plugin for "../index.html":

I had this issue without modifying anything.

Maybe that would help, but despite the fact that I've installed vue-cli as root using npm install -g vue-cli, I don't have any `vue` command in my $PATH so I did the following : 

> /opt/node/5.3.0/lib/node_modules/vue-cli/bin/vue init webpack test

And odly, it correspond to the number of .. in the above error message.
Hoping that this could help! :)

**Comment by cnicodeme** [comment]
(I wrongly posted this in the old tickets, so I'm copying it here) :

I updated Node & NPM : 

```bash
$ node -v
v5.8.0
$ npm -v
3.8.1
```

And retried a build on my app, without any luck. The problem remain.

**Comment by cnicodeme** [comment]
Since I tested a fresh installation on vuejs, I seriously doubt removing the `extract-text-webpack-plugin` in `node_modules` will fix the issue, but to be sure, I'll try.

...

And it did not fixed the issue, unfortunately.
I'll see if I can find more details, but for now, I'd say it's related to Fedora

**Comment by chrisvfritz** [comment]
@cnicodeme Wow, that's great information and should definitely help narrow it down! I'll let you know if I'm still not able to reproduce it or have any other questions.

**Comment by cnicodeme** [comment]
Feel free to ask, I'm concerned about this problem :)

I'm sorry I can be of mutch help regarding the package in question, I'm quite new to Node and I couldn't narrow where the problem is in `extract-text-webpack-plugin`.

**Comment by chrisvfritz** [comment]
No worries - you've already been a huge help!

**Comment by chrisvfritz** [comment]
Darn, I'm still having difficulty reproducing this, even on Fedora. :confused: I've run out of ideas currently, but I'll leave this open to see if someone else might be able to find a solution. @cnicodeme Thank you again for all your help narrowing it down! If you haven't already, I'd also open an issue in [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin/issues), now that we have more information.

**Comment by cipas** [comment]
same issue as @cnicodeme

**Comment by chrisvfritz** [comment]
@cipas @cnicodeme I'd [open an issue in extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin/issues/new) detailing your issue. If you find a solution to your problem, please let us know back here!

**Comment by pratyushbarik** [comment]
The error seems to occur due to 

    if (options.extract) {
      return ExtractTextPlugin.extract('vue-style-loader', sourceLoader)
    } else {
      return ['vue-style-loader', sourceLoader].join('!')
    }

in `css-loaders.js`.
Specifically in `return ExtractTextPlugin.extract('vue-style-loader', sourceLoader)`.
Without it `npm run build` executes without any issues. If you set `extract` to `false` in `webpack.base.conf.js`, it works fine.

I am on eOS Freya.

**Comment by chrisvfritz** [comment]
@pratyushbarik Thanks for adding new information. If you happen to find a way to get the plugin to work without disabling it, please do post back here. :smiley:

**Comment by funkyLover** [comment]
@chrisvfritz  same issue, and unfortunately, on `OSX El Capitan 10.11.4`
```
~ node -v
v4.4.0
~ npm -v
3.8.2
```
but someting weird
I have tried create two project with `vue-cli`
`vue init webpack haha` & `vue init webpack html`
and within project `haha`
```
npm install
npm run build
```
it work fine!
but in project `html`, it will get error
 ```
ERROR in ./src/App.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../../node_modules/extract-text-webpack-plugin/loader.js in /Users/funkyLover/Desktop/html/src
 @ ./src/App.vue 2:0-297

ERROR in ./src/components/Hello.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ./../.. in /Users/funkyLover/Desktop/html/src/components
 @ ./src/components/Hello.vue 2:0-338
```
is it possible caused by the folder name? 😂

**Comment by funkyLover** [comment]
i find out all the error report have `html` with their project path 😂
[issue by @sunny-rajkotiya](https://github.com/vuejs/vue-cli/issues/19#issue-127014316)
[issue by @cnicodeme](https://github.com/vuejs-templates/webpack/issues/41#issuecomment-196744276)
[issue by @voigt](https://github.com/vuejs/vue-cli/issues/19#issuecomment-182891406)
[issue by @2eron](https://github.com/vuejs/vue-cli/issues/19#issuecomment-195166949)

and i try `vue init webpack haha` in a `html` folder and `npm run build`

the error again 😂

**Comment by yyx990803** [comment]
Wow, we're on to something, finally

**Comment by cnicodeme** [comment]
Yeah nice! :)

**Comment by chrisvfritz** [comment]
@funkyLover, I love your funk! Thank you for putting that together like a master detective. 😄 I'll investigate this and see if I can figure out what's going on.

**Comment by oaleynik** [comment]
@yyx990803 @funkyLover https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L14 - this regex matches `html` word. So, if project path contains `html` word somewhere - https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L99 will separate path with bang right after the html word

**Comment by yyx990803** [comment]
@oaleynik ooohhhhh ok I'll look into it!

**Comment by oaleynik** [comment]
@yyx990803 https://github.com/vuejs/vue-loader/pull/205

**Comment by yyx990803** [comment]
Thanks to everyone who helped out locating the issue! It's fixed in `vue-loader@8.2.3`.

**Comment by camoth** [comment]
尤大，能不能帮忙看一下，我运行npm run build就报错，一直不找到原因，只能在这里给你留言了！
![98d543e4-273e-4486-a7e9-22ad52780489](https://cloud.githubusercontent.com/assets/14108724/15278964/b94a01c4-1b51-11e6-92ed-6030d607d893.jpg)

package.json

{
  "name": "joylife",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "camoth &lt;669762172@qq.com&gt;",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js",
    "test": "",
    "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs"
  },
  "dependencies": {
    "vue": "^1.0.21",
    "babel-runtime": "^6.0.0"
  },
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "connect-history-api-fallback": "^1.1.0",
    "css-loader": "^0.23.0",
    "eslint": "^2.0.0",
    "eslint-config-standard": "^5.1.0",
    "eslint-friendly-formatter": "^1.2.2",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-html": "^1.3.0",
    "eslint-plugin-promise": "^1.0.8",
    "eslint-plugin-standard": "^1.3.2",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.13.3",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.4",
    "function-bind": "^1.0.2",
    "html-webpack-plugin": "^2.8.1",
    "http-proxy-middleware": "^0.12.0",
    "json-loader": "^0.5.4",
    "lib-flexible": "^0.3.2",
    "normalize.css": "^4.1.1",
    "ora": "^0.2.0",
    "shelljs": "^0.6.0",
    "url-loader": "^0.5.7",
    "vue-hot-reload-api": "^1.2.0",
    "vue-html-loader": "^1.0.0",
    "vue-loader": "^8.3.0",
    "vue-resource": "^0.7.0",
    "vue-router": "^0.7.13",
    "vue-style-loader": "^1.0.0",
    "vuex": "^0.6.3",
    "webpack": "^1.12.2",
    "webpack-dev-middleware": "^1.4.0",
    "webpack-hot-middleware": "^2.6.0",
    "webpack-merge": "^0.8.3"
  }
}

**Comment by YasuoSop** [comment]
@yyx990803 尤大大 请问iview怎么集成到asp.net项目中？
