### ISSUE TITLE
post-css-next `custom-media` doesn't work with @import or inheritance

### ISSUE THREAD

**Issue by dfdgsdfg** [vuejs-templates/webpack#413]
I am not sure, it's problem of vuejs-templates, but maybe it worth to report for some user.

Anyway, here is my structure.

```
project-root > src > App.vue
project-root > src > variables.css
project-root > src > components > Header.vue
```

### Working Case
At this case, vue file has `@custom-media` and it's consumer `@media`, works just fine.
```vue
<style>
@custom-media --md (width >= 768px) and (width <= 991px);
.title {
  font-size: 2rem;
  @media (--md) {
    font-size: 1.5rem;
  }
}
```

### @import Case
```css
/* variables.css */
@custom-media --md (width >= 768px) and (width <= 991px);
```

```vue
// App.vue

<style>
@import "./variables.css"

.title {
  font-size: 2rem;
  @media (--md) {
    font-size: 1.5rem;
  }
}
</style>
```
If I try `@custom-media` to outside file then import in the vue file, it does not work. There is no error message neither browser nor console. In the browser, seems not to render whole `@media` phrase.

### Inheritance Case
```vue
// App.vue
<template>
  <header></header>
</template>

<style>
@custom-media --md (width >= 768px) and (width <= 991px);
</style>
```

```vue
// Header.vue
.title {
  font-size: 2rem;
  @media (--md) {
    font-size: 1.5rem;
  }
}
```

Expect to render `@media(width >= 768px) and (width <= 991px)` but same as `@import` case.

Any clues here?

**Comment by crswll** [comment]
A couple things:

* CSS variables should to be set in `:root { }` http://cssnext.io/features/#custom-properties-var (that won't help your situation though)
* `Header.vue` and `App.vue` aren't exactly aware of each other. What I do is have a `shared.css` that I `@import` in components that need access to the same variables (I just have a strict rule not to allow anything to actually output anything in here).

Here's my vue-cli template that sounds like it's set up very similar to what you'd like: https://github.com/crswll/vue-starter/ might be easier to just `vue init crswll/vue-starter whatever` and take a look at what it outputs.

**Comment by carlohcs** [comment]
I had the same problem! So, i just tried to put this plugin with the others: https://github.com/postcss/postcss-import
And in my code, I do:

```
<style>
@import 'shared.css';

@media (--phone) {
... code
}
</style>
```

And works!
