### ISSUE TITLE
where to add postcss-sprites:fire:

### ISSUE THREAD

**Issue by RunningV** [vuejs-templates/webpack#417]
I want to extend webpack config to realize css sprite, the full webpack template config to so complicated. I tried many times to config it ,i have no idea how to realise the function. below is I add codes to `webpack.base.conf.js`:

   ```
 ....
 postcss: [
      require('autoprefixer')({
        browsers: ['last 4 versions']
      }),
      require('postcss-sprites')({
        padding: 3,
      })
    ]
  },
  vue: {
    loaders: utils.cssLoaders({ sourceMap: useCssSourceMap }),
    postcss: [
      require('postcss-sprites')({
        padding: 3,
      }),
      require('autoprefixer')({
        browsers: ['last 4 versions']
      })
    ]
  }
```

but no magic, anybody can help :question: :sos:

**Comment by kazupon** [comment]
Close (in-activity)

The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Thanks.
