### ISSUE TITLE
how do add vue-resource?

### ISSUE THREAD

**Issue by chovy** [vuejs-templates/webpack#424]
I have no idea how to make an http call, people tell me to use `vue-resource` but I'm unclear how to add it to my project. I used the `vue-cli webpack` template to generate my project.

**Comment by XC-Zhang** [comment]
1. Installing vue-resource via npm 
2. Add code in src/main.js
```
import Vue from 'vue'
import VueResource from 'vue-resource'
Vue.use(VueResource);
```
3. vue-resource is available in vue instance now: `this.$http`

**Comment by rukkiecodes** [comment]
THANKS

**Comment by ammar-fs** [comment]
Is this still valid? I m watching a tutorial from 2017 but I get Errors ` Can't resolve 'vue-resource;`
