### ISSUE TITLE
everytime I ran npm run dev, it opens browser

### ISSUE THREAD

**Issue by airyland** [vuejs-templates/webpack#425]
I don't need `unit e2e` so I did not select them when initializing the template.
But now every time it opens browser but I just rerun `npm run dev`, that's really annoying

I think there may be some wrong logic in dev-server:

``` js
var webpackConfig = {{#if_or unit e2e}}process.env.NODE_ENV === 'testing'
  ? require('./webpack.prod.conf')
  : {{/if_or}}require('./webpack.dev.conf')
```

``` js
if (process.env.NODE_ENV !== 'testing') {
    opn(uri)
  }
```

or if there is any option like disable-opening-browser?

**Comment by moonou** [comment]
umm..,that if judgment code is my pr, because e2e test will open browser #345 

actually. I think this template doesn't need to open browser, open browser should let developer to do

**Comment by airyland** [comment]
@moonou I agree.

**Comment by LinusBorg** [comment]
Feel free to remove these lines if you don't like this:

https://github.com/vuejs-templates/webpack/blob/master/template/build/dev-server.js#L74-L76

Personally, I like that starting the dev server brings me to the website immediately
