### ISSUE TITLE
Unnecessary vue-style-loader included in vendor chunk file

### ISSUE THREAD

**Issue by sirxemic** [vuejs-templates/webpack#427]
I wasn't sure if this is an issue with webpack or this project, but I noticed that when I run `npm run build`, the built `vendor.js` file includes vue-style-loader. This package is never imported/required in `app.js` nor `vendor.js`, basically making vendor.js unnecessarily bigger.

To me this looks like a bug, but it can also be the case that I'm overlooking something. Am I? What is going on here?

**Comment by yyx990803** [comment]
If you happen to use Webpack's code-split feature, all lazy-loaded components will need to dynamically inject their styles, which relies on `vue-style-loader`. If not then this may indeed be a bug.

**Comment by LinusBorg** [comment]
Seems resolved to me.
