### ISSUE TITLE
Adding custom attributes to injected scripts tags

### ISSUE THREAD

**Issue by ellipticaldoor** [vuejs-templates/webpack#429]
Hi,

Now webpack is injecting this in my index.html after **npm run build**

``` js
<script type="text/javascript" src="./static/js/manifest.0298f1f656f4d6c242e0.js"></script>
```

I want to add a **class** and  also change the attribute **src** to **data-src**, how I can do that?

**Comment by LinusBorg** [comment]
We use [HTMLWebpackPlugin](https://github.com/ampedandwired/html-webpack-plugin) to inject this into index.html, and as far as I know, this Plugin can't do what you ask.

So you can

* request this as a feature for this plugin, or:
* Make the changes manually

**Comment by ellipticaldoor** [comment]
Do you mean after the build to manually change that?

**Comment by LinusBorg** [comment]
Yep.

**Comment by myst729** [comment]
I got an approach, but not sure whether it meets your need.

You can remove **chunkhash** from `build/webpack.prod.conf.js`. So the bundled files will have fixed names (without the hash, e.g. `manifest.js`).

![image](https://cloud.githubusercontent.com/assets/519733/22010962/5beeadc6-dcc7-11e6-8261-f1246c4f9d61.png)

Then you could turn off injection in **HTMLWebpackPlugin** options. This way, bundled files will not be automatically inserted into `index.html`.

After that, modify `index.html` at project root, add these files like you wanted to.

```html
  <body>
    <div id="app"></div>
    <script type="text/javascript" data-src="./static/js/manifest.js"></script>
    <script type="text/javascript" data-src="./static/js/vendor.js"></script>
    <script type="text/javascript" data-src="./static/js/app.js"></script>
  </body>
```

**Comment by ellipticaldoor** [comment]
In the end I turned off the injection and used this approach:

``` javascript
function() {
	let _scripts = [
		<% for (key in htmlWebpackPlugin.files.js) { %>
			'<%= htmlWebpackPlugin.files.js[key] %>',
		<% } %>
	]

	createScriptTag()

	function createScriptTag() {
		// gets the first script in the list
		let script = _scripts.shift()

		// all scripts were loaded
		if (!script)
			return
		else {
			let js = document.createElement('script')
			js.src = script

			// loads the next script
			js.onload = (event) => { createScriptTag() }

			let s = document.getElementsByTagName('script')[0]
			s.parentNode.insertBefore(js, s)
		}
	}
}
```

**Comment by LinusBorg** [comment]
As a word of warning about @myst729'S idea: Without hashes in the filenames, cache-busting won't work

**Comment by myst729** [comment]
@LinusBorg Yep, that's what I meant by "not sure". 😃
