### ISSUE TITLE
building for production...cp: no such file or directory: static/*

### ISSUE THREAD

**Issue by vaske** [vuejs-templates/webpack#433]
I just followed up instructions written and tried to run `npm run build` and got this error 
    
      building for production...cp: no such file or directory: static/*

however I see generated output in console but files are not written on disk, I use OS.
Any ideas what might be wrong? Should I update config files or something?

**Comment by myst729** [comment]
Initially the folder is empty (except a `.gitkeep`). So that's correct - `*` matches nothing. Once you put something in it, images or whatever, the error may go away.

**Comment by posva** [comment]
duplicate of #401

**Comment by splosch** [comment]
I'm puzzled by the same behavior.

The console output suggests there are files generated, where are those files? I suppose they should be added to the static folder - right?

**Comment by ianwalter** [comment]
@vaske Upgrading `shelljs` to `0.7.6` fixed it for me.

**Comment by kazupon** [comment]
Close (in-activity)
