### ISSUE TITLE
2.1 dist file adjustments

### ISSUE THREAD

**Issue by graemetait** [vuejs-templates/webpack#445]
Some changes were made to the dist files in Vue 2.1.0 which seem to require a slight change to the webpack config.

https://gist.github.com/yyx990803/faebe22e8763f5b17572b35ed96f52fe#dist-files-adjustments

As you can see the alias for vue$ should now be set to vue.common. If this isn't done then the production build is left in development mode, which produces a warning in the console, a slightly larger file size, and apparently a performance hit.

I'd create a PR for this, as it's a very simple change, but I don't think it would be backwards compatible with earlier versions of Vue, so I'm not sure how to handle it.

**Comment by LinusBorg** [comment]
> As you can see the alias for vue$ should now be set to vue.common.

It is:

https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js#L27

Not sure what else can be done?

**Comment by graemetait** [comment]
Ah, maybe I was just looking in the wrong place then! I had to change this manually in my project in order to get it to work.

I'll close this now, as it looks like I must have made a mistake somewhere.

**Comment by LinusBorg** [comment]
I would assume that you worked on an older project that was created before we updated the template?

**Comment by graemetait** [comment]
Yes, that does seem to be the case. I had thought the project was started a couple of weeks ago, but checking the first commit it was actually started just before the above change. My mistake, sorry, and thanks for your time and patience! :)
