### ISSUE TITLE
A bad HTTP response code (404) was received when fetching the script.

### ISSUE THREAD

**Issue by gazpachu** [vuejs-templates/webpack#446]
<img width="419" alt="screen shot 2017-01-13 at 16 11 45" src="https://cloud.githubusercontent.com/assets/1721288/21934654/7c80b220-d9aa-11e6-9b35-21331e14fb9e.png">

Any idea of what's that??

**Comment by LinusBorg** [comment]
It seems you are using a service worker? 

That's not part of this template, so in don't see how this repository has anything to do with it.

**Comment by gazpachu** [comment]
Yes, this was probably a previous app running on the same port. Thx

**Comment by Nayir** [comment]
@gazpachu any idea for solve this ? How to kill the previous app service-worker ? Thanks

**Comment by gazpachu** [comment]
@Nayir somehow it stopped appearing. I'm not sure how it happened.

**Comment by gazpachu** [comment]
@LinusBorg @Nayir it actually keeps appearing, so it's really something that comes from this package

**Comment by davidmoshal** [comment]
I have this problem too. How does one kill it?

**Comment by Nayir** [comment]
Someone is using UIkit 3.0 ? Maybe the error comes from UIkit and not Vuejs.

**Comment by davidmoshal** [comment]
You kill it by unsubscribing the service worker from the local host port

**Comment by LinusBorg** [comment]
@davidmoshal I still have no idea where this service worker is coming from. Have you found out more?

**Comment by Nayir** [comment]
I run this is the console of my navigator (Chrome), and no error message anymore :

`navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  registration.unregister()
} })`

**Comment by Nayir** [comment]
@LinusBorg I think it's coming from Vue-Hacker-News example project. And then when you run a new webpack vue-cli project, the service worker is still running for this one.

**Comment by eyalcohen4** [comment]
Having the same problem hear. did anyone find a solution? @gazpachu

**Comment by LinusBorg** [comment]
Ah that would make sense :)

**Comment by wangdahoo** [comment]
@Nayir it works for me. thanks.

**Comment by maximelafarie** [comment]
I apologize for reopening, but I run into the same issue. 
I have an Angular project which use it. I have a OneSignal project for local dev (e.g.: localhost:4200), and another one for the production (e.g.: mywebsite.com).

I subscribed for the notifications on dev and all works well, but when I want to subscribe to the same notifications but in production environment, it fails with the errors mentioned above. And this is the same for all users who want to subscribe.

Do I need to kill anything on my server ? Or is there a conflict between my SDKs ? (in dev vs prod)

**Comment by LinusBorg** [comment]
I'm sorry but this repository has nothing to do with angular or OneSignal.

The only tipp I can give you is to check your chrome devtools under the "Application" tab when on localhost, and kill all service workers that may still be running.

**Comment by maximelafarie** [comment]
@LinusBorg Oh sorry I didn't look at the repo name... 😅 Thank you and sorry for the off-topic message.

**Comment by satyaram413** [comment]
If you're using a local repository then while specifying the URL or path of your file, don't specify the absolute path instead give an absolute path, for example, <img src="kitten.png"/>   is the correct way to do it, so <img src="http://www.foo.com/images/kitten.png"> this isn't the correct way to do it. Well, this worked out for me, hope force may be with you.

**Comment by evenfrost** [comment]
To remove previous service worker along with other cache, if using Chrome, open DevTools and long press on 'Refresh button' **&#x21bb;**, then select 'Empty Cache and Hard Reload' option.

**Comment by ignacio68** [comment]
Chrome=>Dev Tools=>Application=>Service Workers=>Update on reload (selected)

**Comment by paulmelero** [comment]
@ignacio68 that made it! Thanks

**Comment by migueldeguzman** [comment]
This error also occured in a reactjs project. same code above resolved it!

**Comment by migueldeguzman** [comment]
> I run this is the console of my navigator (Chrome), and no error message anymore :
> 
> `navigator.serviceWorker.getRegistrations().then(function(registrations) { for(let registration of registrations) { registration.unregister() } })`

thanks for this dude!

**Comment by LuisEspinosaB** [comment]
> > I run this is the console of my navigator (Chrome), and no error message anymore :
> > `navigator.serviceWorker.getRegistrations().then(function(registrations) { for(let registration of registrations) { registration.unregister() } })`
> 
> thanks for this dude!

It really works! Thank you!

**Comment by lilitatd** [comment]
> navigator.serviceWorker.getRegistrations().then(function(registrations) { for(let registration of registrations) { registration.unregister() } })

It works for me. Thanks!

**Comment by blogxkomo** [comment]
> navigator.serviceWorker.getRegistrations().then(function(registrations) { for(let registration of registrations) { registration.unregister() } })

thanks it's work for me :)

**Comment by sarink** [comment]
This happens when a previous app on the same url did utilize a service worker.

To fix:
`Chrome - devtools - Application - Clear storage - check Unregister Service Worker - then click Clear site data`

**Comment by echofrost38** [comment]
> I run this is the console of my navigator (Chrome), and no error message anymore :
> 
> `navigator.serviceWorker.getRegistrations().then(function(registrations) { for(let registration of registrations) { registration.unregister() } })`

hi friend, let me know more exactly , where can i use this command ?

**Comment by AndrewBogdanovTSS** [comment]
@timeworn I guess you can just paste it in your console window of Chrome dev tools. But for me that command, although executed, made no difference. Error still appears

**Comment by echofrost38** [comment]
> I run this is the console of my navigator (Chrome), and no error message anymore :
> 
> `navigator.serviceWorker.getRegistrations().then(function(registrations) { for(let registration of registrations) { registration.unregister() } })`

Hi friend, please let me know with screenshot more exactly, thanks

**Comment by shinya-tkhs** [comment]
![Screen Shot 2020-03-24 at 18 34 24](https://user-images.githubusercontent.com/62125052/77410507-4b42a100-6dfe-11ea-8224-dfe562762cd7.jpg)

**Comment by oimos** [comment]
![Screen Shot 2020-03-24 at 18 34 24](https://user-images.githubusercontent.com/8503343/77410590-7200d780-6dfe-11ea-87b1-3a927c93690d.jpg)

**Comment by quangtuyennguyen** [comment]
I have this problem too. How does one kill it?
Thanks all

**Comment by ishashankmi** [comment]
> <img alt="screen shot 2017-01-13 at 16 11 45" width="419" src="https://cloud.githubusercontent.com/assets/1721288/21934654/7c80b220-d9aa-11e6-9b35-21331e14fb9e.png">
> 
> Any idea of what's that??

for me, it was finding firebase-messaging-sw.js in my root dir, but i've created it inside the /var/www/html/test/ ........ just paste it 
sw.js file in root dir -> /var/www/html 

this worked for me ::)

**Comment by VigneshGetbiz** [comment]
Give production: false, in Angular Projects only it's working.
environment.prod.ts => production: false,
environment.ts => production: false,
