### ISSUE TITLE
Look forward to seeing the webpack 2 integration

### ISSUE THREAD

**Issue by undirectlookable** [vuejs-templates/webpack#449]
[Webpack 2 is finally released today](https://github.com/webpack/webpack/releases/tag/v2.2.0)

**Comment by thgh** [comment]
Nice work! I tried your repo using `vue init CodinCat/webpack#webpack2 project` and it seems work but couldn't get sass to work. I had to remove the sass imports and the style tags in vue components.

**Comment by LinusBorg** [comment]
closing in favor of #454
