### ISSUE TITLE
Vue-cli compile image src via dynamic property 

### ISSUE THREAD

**Issue by khaled0fares** [vuejs-templates/webpack#450]
When i reference the image source via the assets directory it works as expected and compile the image path to static one like this /static/img/img.1e7c8df.jpg

but when i use a dynamic property and pass the value of the property via the parent component,
the image path **doesn't** compile to /static/img/img.1e7c8df.jpg path

<img width="397" alt="screen shot 2017-01-18 at 7 26 35 pm" src="https://cloud.githubusercontent.com/assets/6291887/22075537/0779a144-ddb5-11e6-8e34-910bfc658832.png">

<img width="978" alt="screen shot 2017-01-18 at 7 30 49 pm" src="https://cloud.githubusercontent.com/assets/6291887/22075492/d64421d0-ddb4-11e6-8101-3834c8a68ffc.png">

**Comment by LinusBorg** [comment]
you have to actually import the image in JS. then webpack knows about it as a depenency and can manage the path.
```javascript
import Image from './assets/image.jpg'
// `Image` will not be a string, pointing to  '/static/img/img.1e7c8df.jpg'
```

**Comment by darkylmnx** [comment]
does this seem logical or even easy to reason about ? Let me explain : 
Assuming i have a team page on my web app, i have 50 teammates, it would be anoying to write 50 times a  div + h2 + img + some description.

So i would use a loop, my image would go from 1 to 50 so i would dynamically use **:src** with the index of the loop.

BUT those images would be in my assets, so are you expecting someone to write 50 times and import for his images ?

Knowing that we can't loop over an import
![image](https://user-images.githubusercontent.com/1426357/28697683-fffc134c-733d-11e7-99c4-3066c6066f12.png)
 
here's a fiddle of what i mean : https://jsfiddle.net/76sythpu/

i think we need to fin another solution, importing the asset isn't a good idea if you have many dynamic assets.

Copying a folder of assets to the dist folder maybe the only solution for now...

**Comment by LinusBorg** [comment]
Well, that's how webpack works for dynamic assets. You still have options, though.

1. use the `/static` folder as explained [here](https://vuejs-templates.github.io/webpack/static.html).
2. Use a dynamic require to make webpack require all images in one call, as explained [here](https://webpack.js.org/guides/dependency-management/#require-with-expression)

I won't go into much detail (for that we have forum.vuejs.org).

**Comment by maximilianfixl** [comment]
I hope that I get a answere here, though its closed.
I can‘t understand that I can load an image from the laravel /public/ images directory, but not from /storage/app/public!
If image file name and subfolder is dynamic. Could anybody explain it to me? Please!?

**Comment by LinusBorg** [comment]
Please use the forum, as I mentioned in my last reply. 

This is a closed isssue.

**Comment by maximilianfixl** [comment]
I did already

https://forum.vuejs.org/t/get-path-from-storage-directory-inside-vue-component-in-laravel-5-5/21646

**Comment by kaankucukx** [comment]
```javascript
<img :src="require(`@/assets/${posts.img}`)" alt="">
```
🥇

**Comment by david-saint** [comment]
Hi @kaankucukx ,
What if I want to add it to the style tag like 
`<div class="left" :style="backgroundImage: require(assets/img/${image}.png);">`
How should I go about this?

**Comment by kaankucukx** [comment]
@david-saint Hey,

Go with this.. ;)

```javascript
<div class="left" :style="`backgroundImage: require(assets/img/${image}.png)`">
```

Check this by Addy. https://developers.google.com/web/updates/2015/01/ES6-Template-Strings

**Comment by david-saint** [comment]
Thanks @kakahikari 
this worked
```javascript
<div class="left" :style="{backgroundImage: `url(${require(`../assets/img/${image}.png`)})`}">
```

**Comment by nicobaguio** [comment]
@kaankucukx may I ask what the $ sign means here? This also worked with my Vue app and I don't know what's happening.

**Comment by nfer** [comment]
@nicobaguio 
> Template Strings can contain placeholders for string substitution using the ${ }

you can get more info on link as kaankucukx mentioned: [https://developers.google.com/web/updates/2015/01/ES6-Template-Strings](https://developers.google.com/web/updates/2015/01/ES6-Template-Strings)

**Comment by kaankucukx** [comment]
@nicobaguio Hey,

its ES6 feature called Template Literals. you can check it from the link @nfer mentions. or below one!

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by ghost** [comment]
`<img :src="require(`@/assets/login.png`)" alt="">
`   
`<img src="@/assets/login.png" />
`
**same** but shorter

**Comment by rimiti** [comment]
@kaankucukx you saved my morning 🚀

**Comment by syntaxhacker** [comment]
hey! i need some help
here is the json object passed to component **slides.vue**

![carbon 2](https://user-images.githubusercontent.com/30970495/48198916-6edb8780-e380-11e8-8217-1db4284af93b.png)
and props were passed when i wanted to retrieve text it worked but for image retrieval `this.image.url `(used images[0 ] for tesing) it just displaying nothing 😭😭 but when i log `this.image.url `it displays 

> ../assets/img1.jpg

but when i pass actual path `<img src="../pathtoimg">` it works .
![carbon 4](https://user-images.githubusercontent.com/30970495/48199236-8d8e4e00-e381-11e8-8d6f-45982a42c42e.png)



 i dont know why it does not passing this computed return  value to the template

**Comment by revolter** [comment]
I keep getting the `Cannot find module` error, even though the path is correct.

**Comment by bigsee** [comment]
Note that you can also use the following syntax to avoid needing to remember the relative paths...

```js
<div
    class="picture"
    :style="{ backgroundImage: `url(${require(`@/assets/images/${image}`)})` }">
```

...where `@` signifies your `src` folder and `image` is the full filename.

**Comment by oelbaga** [comment]
OMG I've been researching this for 3 hours. Finally stumbled on this. Works! Thank you!

**Comment by aacassandra** [comment]
thank you @kaankucukx, your suggestion is to work with charm, but your code is not beautiful with vue framework

thank you @LinusBorg, your advice is to work very beautiful
```
import Image from "../../assets/img/services/s1.png";
export default {
   data () {
     return {
       myPic: Image;
     }
   }
}
```

```<img v-bind:src="myPic" />```

tested on vue cli 3

**Comment by kaankucukx** [comment]
@aacassandra Thank you!
And you mean importing all images is fine? :)

So good luck with that. I believe that is uglier :(

**Comment by aacassandra** [comment]
thank you @kaankucukx, you remind me. I just found out that the way it loads all the images.

**Comment by fralonra** [comment]
I did something like `<img :src="require(@/assets/logo.png)" > `
But it gave me an error that `Critical dependency: the request of a dependency is an expression`
Anyone can help?

I'm using:
webpack v4.28.4
vue v2.6.10
@vue/cli-service v3.6.0

**Comment by TotomInc** [comment]
@fralonra you are missing quotes on `@/assets/logo.png`.

Your `:src` attribute should looks like this `:src="require('@/assets/logo.png')"`.

**Comment by fralonra** [comment]
@TotomInc Thanks for your reply!
That's just a typo.
I tried `:src="require('@/assets/logo.png')"` and the warning still exists.

**Comment by routbiplab** [comment]
Try this:

file.html
`<img v-bind:src="image">`

file.js
`image:require('@/assets/tutorial/onWhite.jpg'),`

**Comment by fralonra** [comment]
@routbiplab 
It was my fault not pointing out what I want to do.
I want to load image dynamically, by setting image path in a variable like `logo`.

There is a trick can do it: `require('@/assets' + logo)`, but `logo` cannot start with '@/assets' in this way.

However, if all images are under a same folder like `@/assets`, I can set `logo` begin with '@/assets', and then remove this prefix in the require expression, like: `require('@/assets' + this.logo.split('@/assets')[1])`.

But I still wonder if there is a way to archive this goal without doing these tricks?

**Comment by baagi-rebel** [comment]
the alt attribute is working fine but src attrib. is not working. Can anybody explain?????? PLZ!!!
`<food-items itemPrice= 239 itemName="Desert"  image="./assets/images/desert.jpg"  altText="image here from app"></food-items>`// App.vue
` <img :src="image" :alt="altText">` //component food-item

**Comment by fralonra** [comment]
@baagi-rebel 
See here. https://github.com/vuejs-templates/webpack/issues/126.
In short, you should use `require` or `import` to tell webpack that this path should be treated as a module.

**Comment by hoainamcr** [comment]
Hi, I can't display image, this is my code.
`<img :src="require('@/assets/images/logo.png')" />`
but it just diplay after rendered 
`<img data-v-359d76e0="" src="[object Module]" class="">`
Do you know why it return [object Module]? please help me to resolve it :(

**Comment by hoainamcr** [comment]
> Hi, I can't display image, this is my code.
> `<img :src="require('@/assets/images/logo.png')" />`
> but it just diplay after rendered
> `<img data-v-359d76e0="" src="[object Module]" class="">`
> Do you know why it return [object Module]? please help me to resolve it :(

Oh, I found the solutiton. just install **url-loader** :( OMG, thank you guys so much.

**Comment by juniorknx** [comment]
This works for me!! thanks
