### ISSUE TITLE
proxyTable not working for npm run unit?

### ISSUE THREAD

**Issue by mu-yu** [vuejs-templates/webpack#451]
I have setted `proxyTable` in `/config/index.js`,

and then I get all my ajax response with status 404 when  I run `npm run unit`, but `npm run dev` is OK.

**Comment by LinusBorg** [comment]
can't reproduce this.

**Comment by mu-yu** [comment]
I made a [repo](https://github.com/mu-yu/questions/tree/master/VueUnit) to reproduce the issue:  

BTW, os: Windows 10 | npm: 3.10.10 | node: 7.3.0

**Comment by LinusBorg** [comment]
Looking back at this, it's obvious: during unit tests, no dev-server is running, so there's nothing to do the proxy-ing. You will have to either mock the requests or change the paths with some environment variable during unit tests.
