### ISSUE TITLE
How to use webpack 2 ?

### ISSUE THREAD

**Issue by myronliu347** [vuejs-templates/webpack#452]
If inscribe

**Comment by reverland** [comment]
https://github.com/vuejs-templates/webpack/blob/master/template/package.json#L90

you may prefer https://github.com/egoist/vuepack which use a rc version webpack2, however, webpack just release its first 2.x version, so the api may be a little different..

And,

if anyone implement the webpack2 template, can he/she take a look at https://github.com/vuejs-templates/webpack/pull/354 ?

I don't fully agree with how it devide deps/devdeps. but it helps when you start a ci without the need for hot-reload/express/http-proxy.

**Comment by myronliu347** [comment]
Thanks, Looking forward to...
