### ISSUE TITLE
CORS hassle free proxy

### ISSUE THREAD

**Issue by woozyking** [vuejs-templates/webpack#456]
If I'm missing something and/or wrong about this, please correct me, thanks!

I find the implementation using https://github.com/chimurai/http-proxy-middleware is convenient, except that it's not always so simple when facing `Access-Control` header restrictions, which often requires the API/Data/Backend server to configure CORS.

One sure way I can think of is to use an HTTP client library such as https://github.com/mzabriskie/axios or https://github.com/request/request to make the request through server side (which to my understanding isn't restricted by the cross-origin settings anymore) and pipe the retrieved response to the client, like `req.pipe(request({...API_OPTIONS...})).pipe(res)` for the simplest example inside the API tunneling/proxy middleware.

Again, maybe I'm missing something very obvious and dead simple to achieve the same through `http-proxy-middleware`, in which case please point out.

**Comment by LinusBorg** [comment]
Not tested, but wouldn't it be enough to add this to the middleware?
```javascript
// devServer.js

var devMiddleware = require('webpack-dev-middleware')(compiler, {
  headers: { "Access-Control-Allow-Origin": "*" } 
  // ... other options.
})

```

**Comment by woozyking** [comment]
@LinusBorg it doesn't work. Even if it does, I would still feel that a server-to-server based API tunneling is the most reliable choice (and equivalently trivial)

**Comment by LinusBorg** [comment]
Can we take a step back and re-evaluate the problem so I'm sure I don't miss something? I'm not sure that I understand your problem anymore. CORS is somethign that drives me nuts everytime I have to deal with it.

So: Where is the CORS requirement coming from?

>  except that it's not always so simple when facing Access-Control header restrictions, which often requires the API/Data/Backend server to configure CORS.

I'm not sure what your actual problem ishere. Does your backend API send a CORS header with its response that does not include `localhost:8080`? Or what exactly is causing the problem?

**Comment by woozyking** [comment]
Let's say the backend API server does not have explicit CORS header configured, and by default prevents any form of cross-origin client side request, rightly so. So the problem is that we would get complaint (and an error in browser) that says the request hit `localhost:PORT` but the response actually comes from `actual_backend_API_server.com`, with no explicit allowance through the CORS headers, no go.

That's why I'm proposing to have the default `dev-server.js` implementation to instead of using the proxy middleware, having a simple middleware to perform a "server-to-server" request from `dev-server` to the designated backend API server(s), retrieve the data stream, and pipe to the response that `dev-server` sends to the client side (in usual case, a browser). No more CORS configuration and meddling on any layer of the stack, because so long you have access (through authentication, VPN, or whatever other means of protection), a server-to-server HTTP request is never governed by the CORS headers.

And such simple middleware can be done through `request` library which nicely supports stream piping. But one can easily use `axios`, or even the raw HTTP module from node.js.

**Comment by woozyking** [comment]
Here's a simple example I used to replace the default one

```node.js
// one can easily make this work with the `proxyTable` object to handle multiple configs
app.all('/api/*', (req, res, next) => {
  return req.pipe(request({
    uri: req.path.replace(/^\/api/, ''),
    baseUrl: 'http://my.api.server.com',
    qs: req.query,
    method: req.method
  })).on('error', next).pipe(res).on('error', next)
})
// this is used to capture the stream errors
app.use((err, req, res, next) => {
  console.error(err.stack)
  res.sendStatus(500)
})
```

**Comment by asvae** [comment]
Not sure if that's related, but here's my dev-server config:

```
devServer: {
        historyApiFallback: true,
        noInfo: true,
        proxy: {
            '*': {
                target: 'http://my-site.local',
                changeOrigin: true, // applies 'host' header
                secure: false,
                cookieDomainRewrite: '',
                onProxyReq: function (request, req, res) {
                    request.setHeader('origin', 'http://my-site.local') // applies 'origin' header
                }
            },
        }
    },
```

Works with CORS and cookie authentication.

**Comment by woozyking** [comment]
Thanks for the pointer on the `onProxyReq` option @asvae. Unfortunately, I would still get browser complaining about CORS:

```XMLHttpRequest cannot load http://SOME_REMOTE_HOST/path/to/api. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.```

It's such a puzzle to me right now 😞

**Comment by asvae** [comment]
@woozyking could it be you're using absolute urls for you ajax?

They should look like this:
```
/api/user/create
```
And not like this
```
http://project.local/api/user/create
```
Because proxy proxies only requests to `localhost`.

**Comment by woozyking** [comment]
@asvae yes I certainly requested the intended proxy path as such on client side

`axios.get(`/api/campaigns?id=${...}...`).then(...)`

**Comment by asvae** [comment]
@woozyking check `baseURL` in axios config.

**Comment by woozyking** [comment]
@asvae I didn't even set it, literally just `axios.get(...)`

**Comment by asvae** [comment]
@woozyking then I don't get how browser would think you're making request to `http://SOME_REMOTE_HOST/path/to/api` and not `http://localhost:8080/path/to/api`. Given you're sitting on `http://localhost:8080`. 

Please check `Request URL` as well as `origin` and `host` headers.

**Comment by woozyking** [comment]
This is what I'm confused about too @asvae as I simply just request on `http://localhost:8080/path/to/api` it would "redirect" to the matching `http://SOME_REMOTE_HOST/path/to/api` specified in `proxyTable`.

Anyway the values are as the following:

```
⎢ Original URL: /api/endpoint?query=value
⎢ Host Name: localhost
⎢ Origin: undefined
```

It looks like the `origin` header is not set

**Comment by asvae** [comment]
Here are mine:
```
Request URL: http://localhost:8080/api/server/get-project-environment
Host: localhost:8080
Origin: http://localhost:8080
```

I wonder if axios thinks host is absent or something.

**Comment by woozyking** [comment]
@asvae thank you for all the help. I'll dive deeper later on this and report back any new findings.

**Comment by stcqu** [comment]
I'm not 100% sure if I understood your problem.  For me I have a dev server running for my backend api (django) and a the vue dev server running webpack hot reload (express).  The two had different ports and hostnames.  So I had to configure my webpack public path, my webpack hot reloader path and fix express to allow CORS.  Here are the changes I made.  I don't know the best way to close the issue, but I imagine this is a common use case. Is there already documentation for this issue?  If not maybe a comment in the template linking to some docs?

**To fix __webpack_hmr from not being found (checking the wrong hostname/port)**
build/dev-client.js
```
- var hotClient = require('webpack-hot-middleware/client?noInfo=true&reload=true')
+ var hotClient = require('webpack-hot-middleware/client?noInfo=true&reload=true&path=http://localhost:8080/__webpack_hmr')
```

**To fix hot-reload.json from not being found / loading an html page from my django server**
config/index.js
```
-    assetsPublicPath: '/',
+    assetsPublicPath: 'http://localhost:8080/',
```

**To fix the hot-reload.json CORS issue (No 'Access-Control-Allow-Origin' header is present on the requested resource.)**
build/dev-server.js
(npm install cors --save)
```
+ // allows cross domain requests on dev server so hot reload will work between django and vue dev servers
+ var cors = require('cors')
+ app.use(cors())
```

Some links to the issues you might find useful:
https://github.com/glenjamin/webpack-hot-middleware#client
http://webpack.github.io/docs/configuration.html#output-publicpath
https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#no-access-control-allow-origin-header-is-present-on-the-requested-resource
https://github.com/expressjs/cors

**Comment by stcqu** [comment]
@LinusBorg You know I just looked at your first comment and that may be simpler than adding the cors middleware express package?  I haven't tried it.

**Comment by woozyking** [comment]
Thanks @stcqu, I'll experiment with your suggestions and see if that would make things simpler.

At the end of the day this is a very minor part of the end product that one may ship. Right now we went as far as building the API proxy as part of the production server because the complexity kind of warrants this structure (especially that in our use case we handle sessions). We then factored the common logics out and have it imported by both the dev-server and production server as a shared middleware.

I think it comes down to how much logic is utilized and shared between dev server and production server environment (when applicable), as some, or many Vue projects are developed without a production server side.

I personally think that this issue could be closed as it only troubles a portion of the broader use cases that's not even `vuejs-templates/webpack` project's main concern (and frankly, shouldn't be).

**Comment by LinusBorg** [comment]
Since this issu eis quite old, and we will switch to webpack-dev-server in the coming days, I wil close this. If this still needs further discussion, please open a new issue with a reference to this one and we will see how to resolve this in the new envorinment with `webpack-dev-server`, if necessary.
