### ISSUE TITLE
run dev fails

### ISSUE THREAD

**Issue by con-ssc** [vuejs-templates/webpack#458]
I just initiated a new webpack template. Trying to run the dev server ends in failing node.
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev',
1 verbose cli   '--verbose' ]
2 info using npm@3.10.10
3 info using node@v7.3.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-time-tracking@1.0.0~predev: vue-time-tracking@1.0.0
6 silly lifecycle vue-time-tracking@1.0.0~predev: no script for predev, continuing
7 info lifecycle vue-time-tracking@1.0.0~dev: vue-time-tracking@1.0.0
8 verbose lifecycle vue-time-tracking@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue-time-tracking@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\repositories\git\vue-time-tracking\node_modules\.bin;C:\cygwin64\home\stefan.schneider\bin;C:\cygwin64\usr\local\bin;C:\cygwin64\bin;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Python27;C:\Python27\Scripts;D:\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.1;C:\Users\stefan.schneider\AppData\Roaming\npm;C:\Users\stefan.schneider\AppData\Roaming\npm\node_modules\phantomjs\lib\phantom;C:\Program Files\Java\jdk1.8.0_74\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Program Files (x86)\gtm;C:\Program Files\TortoiseGit\bin;C:\Program Files\dotnet;C:\WINDOWS\system32\config\systemprofile\vimfiles\bundle\ycmd;C:\Program Files\CMake\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Rust stable MSVC 1.11\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;D:\Programme (x86);C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio;C:\Program Files\Java\jdk1.8.0_112\bin;D:\chocolatey\bin;D:\chocolatey;C:\Program Files\Git\cmd;D:\CRMSDK;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs;C:\Users\stefan.schneider\.cargo\bin;C:\Users\stefan.schneider\.dnx\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\tools\gittfs;C:\ProgramData\chocolatey\lib\Git-TF\Tools\git-tf-2.0.3.20131219;C:\Users\stefan.schneider\AppData\Local\Microsoft\WindowsApps;C:\Users\stefan.schneider\AppData\Local\Yarn\.bin;C:\Users\stefan.schneider\AppData\Roaming\npm
10 verbose lifecycle vue-time-tracking@1.0.0~dev: CWD: D:\repositories\git\vue-time-tracking
11 silly lifecycle vue-time-tracking@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle vue-time-tracking@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle vue-time-tracking@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: vue-time-tracking@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue-time-tracking@1.0.0
16 verbose cwd D:\repositories\git\vue-time-tracking
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev" "--verbose"
19 error node v7.3.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error vue-time-tracking@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the vue-time-tracking@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-time-tracking package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-time-tracking
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-time-tracking
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by LinusBorg** [comment]
is this Windows 10?

**Comment by con-ssc** [comment]
Yes it is.

**Comment by LinusBorg** [comment]
Is your port 8080 already in use, perhaps?

**Comment by con-ssc** [comment]
No it is not. webpack-simple works for example.

**Comment by dragongears** [comment]
I am having a very similar experience running on Ubuntu 16.04

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle webpack@1.0.0~predev: webpack@1.0.0
6 silly lifecycle webpack@1.0.0~predev: no script for predev, continuing
7 info lifecycle webpack@1.0.0~dev: webpack@1.0.0
8 verbose lifecycle webpack@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle webpack@1.0.0~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/art/Dropbox/Projects/Vue/webpack/node_modules/.bin:/home/art/Dropbox/android-sdk-linux/tools:/home/art/Dropbox/android-sdk-linux/platform-tools:/home/art/bin:/home/art/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/art/.npm-global/bin
10 verbose lifecycle webpack@1.0.0~dev: CWD: /home/art/Dropbox/Projects/Vue/webpack
11 silly lifecycle webpack@1.0.0~dev: Args: [ '-c', 'node build/dev-server.js' ]
12 silly lifecycle webpack@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle webpack@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: webpack@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid webpack@1.0.0
16 verbose cwd /home/art/Dropbox/Projects/Vue/webpack
17 error Linux 4.4.0-59-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
19 error node v6.9.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error webpack@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the webpack@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the webpack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs webpack
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls webpack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by LinusBorg** [comment]
Please try moving the project out of the dropbox folder. 

Webpack watch mode / hot reloading often has issues with it.

**Comment by dragongears** [comment]
I moved it to my Documents directory. Same issue.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle webpack@1.0.0~predev: webpack@1.0.0
6 silly lifecycle webpack@1.0.0~predev: no script for predev, continuing
7 info lifecycle webpack@1.0.0~dev: webpack@1.0.0
8 verbose lifecycle webpack@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle webpack@1.0.0~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/art/Documents/webpack/node_modules/.bin:/home/art/Dropbox/android-sdk-linux/tools:/home/art/Dropbox/android-sdk-linux/platform-tools:/home/art/bin:/home/art/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/art/.npm-global/bin
10 verbose lifecycle webpack@1.0.0~dev: CWD: /home/art/Documents/webpack
11 silly lifecycle webpack@1.0.0~dev: Args: [ '-c', 'node build/dev-server.js' ]
12 silly lifecycle webpack@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle webpack@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: webpack@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid webpack@1.0.0
16 verbose cwd /home/art/Documents/webpack
17 error Linux 4.4.0-59-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
19 error node v6.9.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error webpack@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the webpack@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the webpack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs webpack
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls webpack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by neutt22** [comment]
You can try to use `npm3` package instead of `npm
`

**Comment by feiyang0117** [comment]
I have this issue when npm run build ,how to resolve it? thanks


ERROR in static/js/app.9e4894e7cc7d1cf43a4f.js from UglifyJs
Unexpected token: operator (>) [./common/chk.js:294,0][static/js/app.9e4894e7cc7d1cf43a4f.js:1474,65]

**Comment by Toilal** [comment]
@feiyang0117 this is probably because you have ES6 code inside your app sources, but for some reason babel didn't transpiled it to ES5. UglifyJS only supports ES5 code as input, so transpilling is required.

**Comment by LinusBorg** [comment]
Agreeing with Toilal, adjust the include paths for babel-loader to transpile the E6 code from the node_modules subdirectory in question.
