### ISSUE TITLE
How to deploy in Homestead

### ISSUE THREAD

**Issue by mistre83** [vuejs-templates/webpack#460]
Hi to all,
i've just installed the template and then run `npm run build`.

Now, i would like to run it in Homesteadn (or more simple, in nginx).

So, i have configured Homestead.yaml like so:

```
- map: my-app.local
      to: /home/vagrant/Code/my-app

```

when i visit http://my-app.local i see the index.html content ( with `<!-- built files will be auto injected -->`), but not the application (like with `npm run dev`)

What i did miss ?

**Comment by LinusBorg** [comment]
Please limit issues in this repo to stuff that is directly related to the template.

Feel free to ask broader questions on our forum at forum.vuejs.org

**Comment by mistre83** [comment]
Thanks a lot. I will post questions on the forum in future.
