### ISSUE TITLE
Typo in .vue template causes stuck?

### ISSUE THREAD

**Issue by wYhooo** [vuejs-templates/webpack#462]
I'm on: macOS v10.12.2, node v6.9.1, npm v3.10.10, webpack v1.14.0, vue-cli v2.8.0.
I used vue-cli to build a project with eslint disabled.

There was a typo in my HTML code:
`<template>`
 `...`
`<div class="swiper-slide" v-for="data in swiperData">`
 `    <a v-bind:href="data.link"><img v-bind:src="data.img">< /a>`
`</div>`
`...`
`</template>`

Note **a space** was inserted in the `</a>` tag.

After I ran `npm run dev` the terminal stuck at "Compiling...". About 30 seconds later the temperature and fan speed of my Mac was out of control. Then I killed the node process.
That occurred every time I ran `npm run dev` or `npm run build` until I found the typo in my .vue component.
Does anyone know the reason why it happens? Thanks in advance.

**Comment by wYhooo** [comment]
Missed one thing: if I disable all style loaders the above things won't happen.

**Comment by LinusBorg** [comment]
This is probably something that has to be addressed in the vue-loader repository, not here
