### ISSUE TITLE
Add environment variables to project without upload it to git repo.

### ISSUE THREAD

**Issue by holic-cl** [vuejs-templates/webpack#470]
Hi, thanks for this work!.

I was wondering what is the better way to add environment variables to the project without uploading it to the git repository.

I read at documentation about three files (in the config/ folder) to put configuration variables on it, but those files aren't ignored on git repo.

I will appreciate any suggestion.

Regards.

**Comment by thebrubaker** [comment]
dotenv is a good package to solve this problem

**Comment by holic-cl** [comment]
Cool, just what I needed.

Thanks
