### ISSUE TITLE
installing vue-cli for first time and got error

### ISSUE THREAD

**Issue by siempay** [vuejs-templates/webpack#472]
**my local env**
npm -v 3.9.5
node -v 6.2.2
os windows 10

Steps to reproduce

$ npm install -g vue-cli
$ vue init webpack my-project
$ cd my-project
$ npm install
$ npm run dev

What is Expected?

expect to see the page of vue-cli in my browser

What is actually happening?

localhost/:3 Uncaught SyntaxError: Unexpected token import at Object. (app.js:696) at webpack_require (app.js:556) at fn (app.js:87) at Object. (app.js:587) at webpack_require (app.js:556) at app.js:579 at app.js:582

**Comment by limichange** [comment]
Try again. The template has been updated.

**Comment by evorine** [comment]
This error still exists. I think the problem is about babel is not compiling our javascript codes. Because the unexpected token here is **import**. And as I know those codes should be compiled into a standard JS code by Babel?

**Comment by LinusBorg** [comment]
Is `.babelrc` in your projects root folder?

**Comment by siempay** [comment]
yes it is @LinusBorg

**Comment by LinusBorg** [comment]
What is `app.js` and where is it located? This file is not part of the template.

**Comment by LinusBorg** [comment]
Is this still a problem?

**Comment by siempay** [comment]
it is not , at list form me
