### ISSUE TITLE
Include babel pollyfill for npm run build

### ISSUE THREAD

**Issue by jan-thoma** [vuejs-templates/webpack#477]
Vuex and other stuffs needs a polyfill to work with <IE11, it would be nice to have it included by default in production env. 

If im changing the files like this

my webpack.base.conf.js:

```
entry: {
app: ['./src/main.js'],
 },
```
my webpack.prod.conf.js:

```
entry: {
  app: ['babel-polyfill', './src/main.js'],
},
```

I can't get it work

**Comment by myst729** [comment]
You could import babel-polyfill in your main.js

**Comment by LinusBorg** [comment]
1. The babel polyfill is *really* heavy, and polyfills much more than the `Promise` object required by vuex. I would rather use `es6-promise`.
2. Vuex is not included in this template, so why should we include a polyfill that it needs? Smae goes for "other stuff"
3. Not everyone develops for <IE11, many don't anymore.  I would rather have people developing for older browsers to include their polyfills themselves than forcing people developing for modern browsers to actively remove unnessessary polyfills.
