### ISSUE TITLE
Where are bower files supposed to be stored?

### ISSUE THREAD

**Issue by vabatta** [vuejs-templates/webpack#48]
Hi,

using this template, where are bower files supposed to be stored?
In `/static` or to `/src/assets`? How to you then access them? Will vue-loader affect them in some way?

Thanks and good bye

**Comment by yyx990803** [comment]
See https://webpack.github.io/docs/usage-with-bower.html

**Comment by vabatta** [comment]
And how should I import them? For example, I added jquery dependency into `bower.json`. Where should I add the script tag to import it?

**Comment by vabatta** [comment]
Solved. Using all through NPM modules :)
