### ISSUE TITLE
How to resolve this

### ISSUE THREAD

**Issue by shijunti19** [vuejs-templates/webpack#491]
`<style lang="sass" scoped>
...
@-webkit-keyframes rotate-forever
    0%
        transform: rotate(0deg)
    100%
        transform: rotate(360deg)`

![image](https://cloud.githubusercontent.com/assets/5392211/22633172/2bec412c-ec5a-11e6-9953-2938f16cd1ae.png)

![image](https://cloud.githubusercontent.com/assets/5392211/22633140/de4a1098-ec59-11e6-844a-2d7a3901c4c8.png)

There is no resolution to this
-webkit-keyframes rotate-forever

I should be how to solve it?

**Comment by limichange** [comment]
You need to config postcss.

```js
// build/vue-loader.conf.js

var utils = require('./utils')
var config = require('../config')
var isProduction = process.env.NODE_ENV === 'production'

module.exports = {
  loaders: utils.cssLoaders({
    sourceMap: isProduction
      ? config.build.productionSourceMap
      : config.dev.cssSourceMap,
    extract: isProduction
  }),
  postcss: [
    require('autoprefixer')({
      browsers: ['last 100 versions']
    })
  ]
}
```
