### ISSUE TITLE
请问,如果不进行特别的设置,能不能自动增加端口数呢

### ISSUE THREAD

**Issue by wenner** [vuejs-templates/webpack#493]
比如同时运行两个vue的项目 npm run dev , 因为都是默认的8080,所以会报错

以前用过类似的,不过忘记是什么了,应该是yo生成的..可以每次自增端口再运行....

现在每次都要关闭另外一个,再开始新的...有点麻烦...

不知道有没有这个功能,或者如何修改 dev-server.js 来实现类似功能呢?

**Comment by limichange** [comment]
```js
// config/index.js

dev: {
  port: 8080
}
```

**Comment by wenner** [comment]
..并不是想写死在config里面,而是要自动检查占用的端口,然后自增1...

下午找了一下..以前用ionic的就是自增的...实用的类似portfinder.js

我用portfinder.js试了一下....是可以的 , 类似这样

```
module.exports = (function(){
  //将basePort = port;
  portfinder.basePort = port;
  //将hosts加上 " :: "
  portfinder._defaultHosts.push("::");
  //查找一个未占用的端口
  portfinder.getPort({host:'127.0.0.1'} , function (err, port) {
    if (err){
      return;
    }
    var uri = 'http://localhost:' + port;
    devMiddleware.waitUntilValid(function () {
      console.log('> Listening at ' + uri + '\n')
    })
    app.listen(port, function (err) {
      if (err) {
        console.log(err)
        return
      }
      // when env is testing, don't need open it
      if (process.env.NODE_ENV !== 'testing') {
        opn(uri)
      }
    });
  });
})();
```

之所以有这个需求是因为运行好几个项目,运行起来时为了参考前面的项目...看看效果
而同时又运行着当前改的项目..

**Comment by limichange** [comment]
所以说这个问题你现在解决了 :D

**Comment by wenner** [comment]
算是吧...不过是修改dev-server.js的..如果再从官方的template创建的时候还要改一下...

不知道其他人有没类似需要

**Comment by limichange** [comment]
你可以Fork一个自己的模板项目然后改造，毕竟这属于少数的需求。

**Comment by wenner** [comment]
恩.我倒是知道fork...

可是fork后我修改了,然后fork的源也有更新了....我再更新的时候总有错误....然后就没这么操作过

谢谢啦..我再试试

**Comment by limichange** [comment]
😆

**Comment by birchb** [comment]
I, too, thought that this used to work automatically, but it seems to fail now. Thank you for looking into it.

我也，认为这用于自动工作，但现在似乎失败。 谢谢你看看它。
