### ISSUE TITLE
Error in production build: Unexpected token punc «(», expected punc «:»

### ISSUE THREAD

**Issue by Ivan-Feofanov** [vuejs-templates/webpack#497]
I try to build production version but UglifyJS throw this error:
```
ERROR in static/js/app.b786c2a0343b5284c845.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [static/js/app.b786c2a0343b5284c845.js:84,6]
```
It looks like production script doesn't transpile the code.

**Comment by myst729** [comment]
Looks like due to UglifyJS cannot deal with ES6 modules?

The project is currently migrating to use webpack 2.0, let's see what happens when they finish the migration.

**Comment by Ivan-Feofanov** [comment]
I am already using Webpack 2.2.1 and got this error

**Comment by limichange** [comment]
Do you use `module.exports` or `export.foo` now？

**Comment by Ivan-Feofanov** [comment]
@limichange in project files (`/src` folder) i use ES6 exports, in webpack config files - `modules.export`

**Comment by limichange** [comment]
Can you show `static/js/app.b786c2a0343b5284c845.js` to me ? give me a link.

**Comment by Ivan-Feofanov** [comment]
Here they are
```
module.exports = Component.exports


/***/ }),
/* 4 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
//
//
//
//
//
//

/* harmony default export */ __webpack_exports__["default"] = {
  name: 'app',
  data() {
    return {};
  }
};

/***/ })
```

**Comment by yyx990803** [comment]
Cannot reproduce on a fresh install. What's your Node version?

**Comment by Ivan-Feofanov** [comment]
Latest

**Comment by limichange** [comment]
Do you use the latest webpack template ? or changed some config ?

**Comment by Ivan-Feofanov** [comment]
I'm sorry. After update to latest template version ploblem was gone.
Thank you for help!

**Comment by rlog** [comment]
@Ivan-Feofanov 
what are you doing for that?   I have the same issue

**Comment by limichange** [comment]
@rlog Are you use the latest webpack template ?
