### ISSUE TITLE
Hot-reload is not working when square brackets is used in the path to a project's directory

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [vuejs-templates/webpack#499]
I'm using default setup with webpack-simple template. If I have [square brackets] in the folder name of my project or in the parent folder hot reloading stops working. So If I have such project structure: 
`C:\Projects\[Vue]\my-app`
hot reloading doesn't work. But if I change it to 
`C:\Projects\Vue\my-app` 
it starts working again. No errors, no notifications in the console, it just doesn't react to changes I make. I'm not sure if it's related just to vue, looks more like an overall wabpack issue. 
OS: Win10
Node: 6.9.5

**Comment by yyx990803** [comment]
I'd suggest simply avoid doing that then... as this seems to be very unconventional. And if it's a webpack issue this is not really the place to resolve it.
