### ISSUE TITLE
Hot reloading not working in bas install?

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs-templates/webpack#5]
Hi there,

Just to start: amazing work on vue-cli and the templates. Got everything up in literally 5 minutes.
I do run into an issue with Hot Reloading though.

When I check the console, I see HMR working when I save the basic `Hello.vue` file, but the console then says:
```
[HMR] Updated modules:
[HMR]  - 85
[HMR]  - 84
[HMR] App is up to date.
```

Nothing then changes, even though I've updated `Hello world!` to `Foo world!`.
Any thoughts?

BTW: it does work if I add HTML for example, just not when I update the JS.

**Comment by yyx990803** [comment]
It's explained in the comments in Hello.vue.

**Comment by TheDutchCoder** [comment]
I'm a complete moron. Sorry!
