### ISSUE TITLE
Broken js sourcemaps in production

### ISSUE THREAD

**Issue by presidenten** [vuejs-templates/webpack#500]
Javascript sourcemaps are not present when building even if `productionSourceMap` is set to `true`.

Check by:

Create new project. Verify `productionSourceMap: true` in `./config/index.js`.
Run: `npm install`, then `npm run build`.

Now only css sourcemaps are present.

Verify by running:
```shell
find ./dist -iname '*.map'
```

Or:
Add `console.log('hello world');` to `./src/App.vue`.
Run `npm run dev`. Then check console:
```console
Hello World               App.vue?affc:17hello
```

run `npm run build`, `npm install simple-autoreload-server -g`, `autoreload-server dist`, navigate to index.html  then check console:
```console
Hello World               app.7eb2363….js:1
```

**Comment by limichange** [comment]
https://github.com/shama/webpack-stream/issues/81#issuecomment-243436780

I will post a PR to fix it.
