### ISSUE TITLE
can't compress css

### ISSUE THREAD

**Issue by radicalviva** [vuejs-templates/webpack#502]
i use the latest template
when i run `npm run build`, but css doesn't compressed
how can i solve it 
thanks

**Comment by subic** [comment]
It seems that the code does not include the cssnano the documentation implies. You will have to add your own css compressor. You can for example manually add cssnano to your vue-loader-config postcss processors. 

`build/vue-loader-config.js`

```
module.exports = {
   ...
  postcss: [
    require('autoprefixer')({
      browsers: ['last 2 versions']
    }),
    require('cssnano')() //add this
  ]
}
```
Requiring the cssnano in postcss options will now compress your production CSS when running build. You can also pass the cssnano options as an object (same as the autoprefixer above).

See also:
- [Vue loader PostCSS docs](http://vue-loader.vuejs.org/en/features/postcss.html)
- [cssnano](http://cssnano.co/)

**Comment by limichange** [comment]
Look #484

**Comment by radicalviva** [comment]
I follow you suggestion, i install the `cssnanao`, and now my css looks like below
```
.hello[data-v-92426efa]{background-color:#f6f6f6;display:-ms-flexbox;display:flex;-ms-flex-direction:column;flex-direction:column}.hello p[data-v-92426efa]{color:#00a0b0}h2 {
  color: #ff3c4e; }

h1 {
  color: blue; }

/*# sourceMappingURL=site.e0104a2f410f57f26be4466bea0b1cfd.css.map*/
```
It means worked?

**Comment by radicalviva** [comment]
@limichange I add this plugin, but it doesn't worked, you can see my `prod.config.js`
```
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),
    new OptimizeCssAssetsPlugin({
      assetNameRegExp: /\.optimize\.css$/g,
      cssProcessor: require('cssnano'),
      cssProcessorOptions: { discardComments: {removeAll: true } },
      canPrint: true
    }),
    // extract css into its own file
    new ExtractTextPlugin(utils.assetsPath('[name].[contenthash].css')),
```

**Comment by limichange** [comment]
@radicalviva 🍻

**Comment by limichange** [comment]
@radicalviva If you have solved your problem, please close this issue :D
