### ISSUE TITLE
run dev occurred errors

### ISSUE THREAD

**Issue by TopGrd** [vuejs-templates/webpack#505]
I installed the lastest templates,  when i run command npm run dev, some errors occurred. Like follow picture.
![](http://p1.bpimg.com/567571/64fb1b4ccd302ff9.png)  
I try to reinstall, also have this problem.
Follow is my package.json  
![](http://i1.piimg.com/567571/b08e9dc12ea7f9a0.png)
I run command  `npm run build`, it's ok. 
OS: Windows 10  
node version:  6.9.1
npm version:  4.2.0
vue-cli: 2.8.1

**Comment by limichange** [comment]
Upgrade `extract-text-webpack-plugin` to `rc3`

**Comment by TopGrd** [comment]
@limichange  it's not work, the errors also occurred. But i found the reason. i print`process.env.NODE_ENV`,
that's `production`, so i change the dev script to `"set NODE_ENV=development&&node build/dev-server.js"`, now it's works well.

**Comment by limichange** [comment]
:D 
> it works well
 If you have solved your problem, please close this issue.
