### ISSUE TITLE
Feature Request: Allow config for multiple variables

### ISSUE THREAD

**Issue by Austio** [vuejs-templates/webpack#508]
Hello, I am wanting to create a PR for a small addition and wanted to make sure that it is something that is needed.

Currently the config/index.js only has a configurable ENV variable. This isn't ideal for running tests while having a dev server running b/c the ports collide.

Proposal: I would like to create a PR to update the cli to generate a config that merges the entire test/dev in config/index.js for the dev key. Also webpack will need to be updated to use the exports correctly.

Please let me know if this is wanted and i'll knock it out.

Thanks!

**Comment by LinusBorg** [comment]
How would that look from a usage perspective?

I don't see the advantage from how you describe it. Currently, you can add more than one variable to the `*.env.js` files if you need to. Wouldn't that be enough?

**Comment by Austio** [comment]
Benefit would be that you could specify different options that are not in the `dev.env` property of teh `index.js`.  A good example of things that could change which are not currently updatable are the dev.port or autoOpenBrowser.

For the setup, i would think it would be similar to the current setup only instead of requireing the environment under `dev.env` we would require it and then merge it on top of the index.js.

So, index.js would then really be more of defaults, and dev/prod/test would be extensions on top of that where you could specify different ports/etc as needed for the different envs.

**Comment by LinusBorg** [comment]
So this never went on, right? I'm in the last steps of merging #975 which will bring a few new config options for the things you mentioned. 

Have a look and open a a new issue if you still think this config can be improved.
