### ISSUE TITLE
Request: Migration Guide from Webpack v1 => v2

### ISSUE THREAD

**Issue by wcarron27** [vuejs-templates/webpack#509]
I've been using the boilerplate to build out an application, and recently thought I should migrate from the old, Webpack1 based boilerplate to Webpack2. I'm pretty deep into the application, so I can't very well ditch the current code.

I've sunk a lot of time into migrating my app onto webpack 2, but run into persistent issues. Mostly, I've been attempting to incorporate the code on the current master branch of this repository. Was hoping the authors could throw together a quick guide on moving an existing application over to v2, with some provided diffs, and explanations. Much appreciated.

**Comment by LinusBorg** [comment]
Did you change the webpack config that came with the template very much? 

Even if you did, the easiest way would probably be to simply create a new project, copy the build files over, and update

* webpack
* webpack-dev-middleware
* webpack-hot-middlewar
* extract-text-webpack-plugin

to their latest versions.

**Comment by wcarron27** [comment]
Will do! Appreciate it very much.
