### ISSUE TITLE
Hot reload very often fails to compile changes

### ISSUE THREAD

**Issue by cristijora** [vuejs-templates/webpack#512]
When running my app in development mode with the webpack based template, the hot reload often fails to compile when I modify something in my `vue files`. Unfortunately I cannot find a pattern of how it fails to detect the changes but it fails to compile when editing both `.js` or `.vue` files no matter if it's the template or the script part of it.  The command line doesn't show any errors or warnings.
Tried with an empty project (webpack template) and the same thing happens.

OS: Windows 10
Editor: Webstorm

**Comment by kazupon** [comment]
This issue is not webpack template.
I guess that this issue is vue-loader.

Please register it if you could reproduce.
https://github.com/vuejs/vue-loader/issues
