### ISSUE TITLE
Should `src` directory be in `resolve.modules`?

### ISSUE THREAD

**Issue by ktsn** [vuejs-templates/webpack#513]
This is a suggestion to remove `src` directory from `resolve.modules` in `webpack.base.conf.js`. I know the convenience of this configuration but users may confuse if they create some new directories in `src` and some of them conflict with npm packages' name.

For instance, there is a case that a user create `vuex` directory in `src`. So `import Vuex from 'vuex'` does not work at all. https://github.com/vuejs/vuex/issues/625

**Comment by LinusBorg** [comment]
> but users may confuse if they create some new directories in src and some of them conflict with npm packages' name.

Valid point ...

**Comment by kazupon** [comment]
I think so, we should remove `src` directory from `resolve.modules`.
@ktsn mentioned, users may confuse.

In generaly, I think users prefered that control app module code with own.

**Comment by simplesmiler** [comment]
I agree.

For convenience we could add something like `@` as an alias to the `src` directory, so that `@/somehting` would resolve to `path_to_src/something`.

**Comment by LinusBorg** [comment]
I think we already have an alias for `src`. That *could* also be a problem when someone uses a package named `src` (didn't check but I assume one exists :D).

**Comment by LinusBorg** [comment]
MAde a pr #516
