### ISSUE TITLE
SVG sprite 

### ISSUE THREAD

**Issue by julienchazal** [vuejs-templates/webpack#517]
Hello

Does anybody managed to implement SVG support ?
I tried to find something like [this](https://www.npmjs.com/package/vue-svg-directive) mixed with something like [this](https://github.com/mrsum/webpack-svgstore-plugin) but no success...

Any ideas please ?
Thx !

**Comment by kazupon** [comment]
The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). 

--- 

Maybe, you can resolve SVG spite the below loader:
https://github.com/kisenka/svg-sprite-loader

Thanks.

**Comment by julienchazal** [comment]
ok thanks
