### ISSUE TITLE
[Help Needed] /app/ child path using nginx

### ISSUE THREAD

**Issue by grantcarthew** [vuejs-templates/webpack#518]
Hi.

I'm using webpack for the first time and can not find a solution for my setup.

I have nginx configured with the following:

```sh

	server {
		listen 80 default_server;
		listen [::]:80 default_server;

		#root /opt/fm/fm-app;

		index index.html;

		server_name fm;

		client_max_body_size 100M;

		location /app {
    	proxy_pass http://localnode:2001;
			proxy_redirect off;
			proxy_buffering off;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}

		location /api {
    	proxy_pass http://localnode:2000;
			proxy_redirect off;
			proxy_buffering off;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}

		location / {
			root /opt/fm/fm-home;
		}
	}

```

The `location /app` config section above is redirecting port 80 traffic to my nginx server through to my new Vue.js webpack template.

The problem is I need webpack and Vuejs to know they are mounted on a child path. For example I am typing in this address in the browser:

`http://devnginxserver.com/app`

Which is directed by the above config to:

`http://devvuejswebpack.com:2001/`

I have tried a few configurations with no luck.

Can anyone point me in the correct direction please?

**Comment by kazupon** [comment]
The issue list only accepts bug reports and feature requests. Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Thanks.

**Comment by grantcarthew** [comment]
For reference if anyone else finds this issue, read here: #546
