### ISSUE TITLE
cant use spread operator in webpack2.2 template

### ISSUE THREAD

**Issue by yuu2lee4** [vuejs-templates/webpack#519]
![default](https://cloud.githubusercontent.com/assets/8046366/22962460/d4498d32-f387-11e6-90f7-ca1cb5b903d3.png)
It's ok in webpack1.x template. The babel configuration is same

**Comment by yuu2lee4** [comment]
already solved

**Comment by Naeemo** [comment]
@yuu2lee4 would you please tell me how you solved it? Thanks.

**Comment by yuu2lee4** [comment]
@Naeemo   just update template with vue-cli
