### ISSUE TITLE
Resolve: Opening index.html over file:// won't work.

### ISSUE THREAD

**Issue by guilhermefelipesilva** [vuejs-templates/webpack#521]
Inside the file config/index.js altere o `assetsPublicPath: '/'` para `assetsPublicPath: './'` in build object

**Comment by egoist** [comment]
Imagine that you're using history mode, and `./` will always load resource from relative path, eg: at url  '/user/egoist' the browser will load '/user/egoist/bundle.js' which will lead to 404 error.

So my suggestion is always using absolute path in publicPath

**Comment by asselin** [comment]
To be able to use this with cordova, you have to be able to use relative paths, because 1) it uses file://  2) the root is unpredictable.  I agree with @guilhermefelipesilva that this should be fixed.

**Comment by egoist** [comment]
@asselin you can always change it in the config file, that's why it exists.

**Comment by asselin** [comment]
Looking further, this is a dup of #200
