### ISSUE TITLE
Support "browserify" field

### ISSUE THREAD

**Issue by tiaod** [vuejs-templates/webpack#523]
I had intall a package which `package.json` contain a browserify field
```
npm install --save dnode
npm run dev
```

```
//https://github.com/substack/dnode/blob/master/package.json
{
"browserify" : "browser.js",
}
```

But after I import it:
```
import dnode from 'dnode'
```
Seems it require the `main` field instead of `browserify` field
```
 ERROR  Failed to compile with 2 errors                                 12:27:07

These dependencies were not found in node_modules:

* net
* fs

Did you forget to run npm install --save for them?
```

**Comment by tiaod** [comment]
https://webpack.js.org/configuration/resolve/#resolve-mainfields

**Comment by LinusBorg** [comment]
But `main` is already in the default value for resolve.mainFields. 

So I don't understand your request. Can you clarify?

**Comment by tiaod** [comment]
Some package has a browser version which specify by browserify field. And the main field is for node.js version.

**Comment by LinusBorg** [comment]
Well, `browserify` is not a standard field for that usage, and the next thing to a standard for this is the `browser` field:

https://github.com/defunctzombie/package-browser-field-spec

We can't support every strange vairation some projects may require, and this one won't make it into the template.
