### ISSUE TITLE
Warning when I use directive & template lang="pug"(also jade)

### ISSUE THREAD

**Issue by molysama** [vuejs-templates/webpack#524]
```bash
  
  # JS - a directive
  directives: {
    something: function (el) {
       ...
    }
  }

  # html
  # Warning, but work
  h2(v-something) Hello
```

  [Vue warn]: Property or method "v" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

  [Vue warn]: Property or method "something" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```
  # Well
  <h2 v-something >Hello</h2>

```

**Comment by mccxiv** [comment]
I tried [quoting the directive](https://pugjs.org/language/attributes.html#quoted-attributes) but it still shows the error in console. 

Anyone find a workaround?

By the way the directives still work, just that the console spam is annoying...
