### ISSUE TITLE
Production Server Code

### ISSUE THREAD

**Issue by Flaminator89** [vuejs-templates/webpack#527]
I'm experimenting with the webpack vuejs template and have a question regarding where production server code should go?  I'm assuming implementing it within the dev-server.js file would not be appropriate.  I could create it somewhere else and kick it off but I would want the same to get called/used during development as well.  I'm sure I'm missing something simple here, could someone help enlighten as to where this would go within this template?

**Comment by vkruoso** [comment]
With this template running `npm run build` will run webpack and create a production set of static files in the `dist` folder that you can serve in a common webserver, like Apache or nginx.

**Comment by Flaminator89** [comment]
I understand the production build for client code but where would the server code go?  Say I want to swrve my static files over express and do other things on the same port?

**Comment by Flaminator89** [comment]
I think I understand now.  You are saying that I should be using nginx or apache for a reverse proxy and keeping my server code as a separate package.  Thanks for the info, I will close this now.

**Comment by vkruoso** [comment]
That's right. This template will take care of generating all files relevant to the client application. If by server code you mean some API, that is a separate issue. You can serve the static files using express if you like, and proxy API requests somewhere or implement them right there. You can also have the reverse proxy you said with the client and API endpoints running on separate processes. There is lots of possibilities!
