### ISSUE TITLE
Using inject-loader to mock imports in .js files throws an error

### ISSUE THREAD

**Issue by Mark-de-Haan** [vuejs-templates/webpack#528]
When using inject-loader to require files like so:

`const actionInjector = require('inject-loader!src/store/actions')`

I get the following error:

 ```
Error: Module parse failed: src/store/actions.js 'import' and 'export' may only appear at the top level
  You may need an appropriate loader to handle this file type.
```

Issue with inject-loader was solved in this thread: https://github.com/plasticine/inject-loader/issues/24

Bug introduced with this commit: 56d0ad9e6356a48005afe8e0751dcfa4f6c15a2f

I fixed it by defining the presets for the test environment without modules=false in the _.babelrc_
```
{
  "presets": [
    ["es2015", { "modules": false }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "comments": false,
  "env": {
    "test": {
      "plugins": [ "istanbul" ],
      "presets": [ ["es2015"] ]
    }
  }
}
```

**Comment by gurghet** [comment]
I think this is right, you should be able to import other modules from karma .spec.js files, and since the injectors use the require syntax even in webpack 2 this is likely the only feasible workaround.

**Comment by LinusBorg** [comment]
Will add this to the default config.

**Comment by LinusBorg** [comment]
Change this after merging #501

**Comment by LinusBorg** [comment]
done.
