### ISSUE TITLE
Change publicPath from '/dist/' to './dist/' ?

### ISSUE THREAD

**Issue by FilipQL** [vuejs-templates/webpack#529]
I've started a thread about this on Vue-forum: https://forum.vuejs.org/t/vue-cli-webpack-production-images-vis-icons-are-not-loaded-where-to-import-css/6647/3

I am using **Vue-cli [Webpack]** and I have installed [Vis.js](http://visjs.org/). In **App.vue** I have added (imported) **vis.css**:

    <style>
        @import "../node_modules/vis/dist/vis.css";
        ...
    </style>

When I run `npm run dev` - everything works fine, all Vis icons are loaded (displayed), but when I run `npm run build` - when I open the app in the browser - Vis icons are missing and I am getting the following errors:

![ovs mesh google chrome 2017-02-16 23 27 34](https://cloud.githubusercontent.com/assets/18264428/23083570/a1b7a876-f55e-11e6-8ae5-20ccc8ba36ed.png)

In **webpack.config.js** when I changed `publicPath` from `'/dist/'` to `'./dist/'` - everything works fine.
Now, I'm not sure whether it is a good idea to have `publicPath: './dist/'` by default.

**Comment by asselin** [comment]
I think you might be using the webpack-simple template, not the webpack template.  If so, you should open an issue against that repo: https://github.com/vuejs-templates/webpack-simple

**Comment by FilipQL** [comment]
Yes, you're right. My bad.
