### ISSUE TITLE
[Feature request] integrate happypack

### ISSUE THREAD

**Issue by limichange** [vuejs-templates/webpack#533]
`vue-loader` can work with `HappyPack` now. `HappyPack` makes webpack builds faster.

https://github.com/vuejs/vue-loader/releases/tag/v11.0.0

**Comment by smith64fx** [comment]
This would be an awesome improvement cause large-scale apps really need a long time to compile after every save =/

**Comment by lionel-bijaoui** [comment]
It does not work reliably on Windows : https://github.com/amireh/happypack#does-it-work-under-windows
Also, this is "only" an improvement of build time that add a bit of code to the config, making it more difficult to understand (loader are referenced indirectly).
I have learned Webpack thanks to this template and I'm sure I'm not the only one.
If your project is so big that you need this kind of solution, I'm sure you can add it yourself.
Maybe the README could have a section about further enhancement like this one instead ?

Don't get me wrong, I'm all for speed and enhancement, but build time are mostly under 5min so this is kind of an overkill IMHO.

**Comment by Aladdin-ADD** [comment]
thoughts on this? 😄  @LinusBorg

**Comment by LinusBorg** [comment]
I think we will leave this to userland for now. I don't want to further complicate loader configurations at the moment. It's on the watchlist to re-evaluate at a later time, but off the table for now imho.
