### ISSUE TITLE
webpack alias 'vue'

### ISSUE THREAD

**Issue by zeroone001** [vuejs-templates/webpack#536]
`'vue': 'vue/dist/vue.js'` or `'vue$': 'vue/dist/vue.common.js'` Which one is right？

**Comment by limichange** [comment]
https://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by zeroone001** [comment]
I tested it.They're all right.@limichange

**Comment by LinusBorg** [comment]
The first version could lead to mismatche for this alias because it would also match `vue/src/...`

The second one is better because it *only* matches `require('vue`)`

**Comment by zeroone001** [comment]
Thanks @LinusBorg
