### ISSUE TITLE
cuts keyframes on production

### ISSUE THREAD

**Issue by slavikse** [vuejs-templates/webpack#539]
source <style scoped>
![image](https://cloud.githubusercontent.com/assets/2743951/23164222/2d2d30ca-f847-11e6-93db-3f80debd6687.png)

build
![image](https://cloud.githubusercontent.com/assets/2743951/23164230/38e1a2ca-f847-11e6-9f4b-e0b618266e82.png)

**Comment by LinusBorg** [comment]
If this is a bug related to the `scoped` feature, the vuejs/vue-loader  repo is probably a better place for it.

Also, a reproduction besides screenshots would be helpful.

**Comment by LinusBorg** [comment]
Hi there!

I close this issue because of inactivity. If you want to follow up on this issue, please open a new one, and provide the necessary information (a working reproduction etc.) in that issue.

**Comment by kazupon** [comment]
Close (inactivity)
