### ISSUE TITLE
static path after building should be 'static' instead of '/static'

### ISSUE THREAD

**Issue by airyland** [vuejs-templates/webpack#54]
```
GET file:///E:/static/app.a941263badf7da004771.js net::ERR_FILE_NOT_FOUND
```

Changing it to `./static` or `static` will fix.

**Comment by chrisvfritz** [comment]
Root-relative paths like this will work if you're visiting the page in the context of a real web server. For example, try this from your project folder:

```
npm install -g live-server
live-server dist
```
