### ISSUE TITLE
autoprefixer只能用于通过vue-loader解析的样式

### ISSUE THREAD

**Issue by zWingz** [vuejs-templates/webpack#544]
![image](https://cloud.githubusercontent.com/assets/13031838/23207938/2192bd74-f92e-11e6-9c6d-c1f8ddcaa460.png)
我暂时的做法是
添加postcss-loader,
并在根目录创建postcss.config.js
```javascript
module.exports = {
    plugins: [
        require('autoprefixer')({ browsers: ['last 5 versions', 'Android >= 2.0'] })
    ]
}
```

**Comment by cccRaim** [comment]
以前是数组然后map每个loader的，如['style', 'css']，可是不知道哪个版本开始就只能一个字符串了。

**Comment by cycold** [comment]
我也是碰到了这个问题 在单独的.scss文件中 autoprefix没有起作用

**Comment by anchengjian** [comment]
我的方法是在 app.vue 中引入公共 css
``` vue
...

<style src="./assets/css/style.css"></style>
<style>
  .full-container {
    width: 100%;
    height: 100%;
  }
</style>
```

**Comment by shalldie** [comment]
你太棒了，，，总算让我找到个可以解决的方式

**Comment by yoyo837** [comment]
@zWingz 你添加上去后，没有收到PostCSS Loader的警告吗？

Previous source map found, but options.sourceMap isn't set.  In this case the loader will discard the source map enterily for performance reasons.

**Comment by BelinChung** [comment]
@yoyo837 
```
var postcssLoader = {
    loader: 'postcss-loader',
    options: {
      sourceMap: true
    }
  }
```

**Comment by yoyo837** [comment]
@BelinChung 
```
var postcssLoader = {
    loader: 'postcss-loader',
    options: {
      sourceMap: true
    }
  }
```
The same warning...

look at this
commit:
https://github.com/postcss/postcss-loader/commit/159b66a

issues:
https://github.com/postcss/postcss-loader/issues/248

I switch to a low version postcss-loader@1.3.3

**Comment by SallyOne** [comment]
上述两个问题都碰到了

**Comment by flyher** [comment]
@yoyo837 
Thank you.
I change the version to  postcss-loader@1.3.3, the warning disappeared.
