### ISSUE TITLE
Separate index template for production build

### ISSUE THREAD

**Issue by daltonamitchell** [vuejs-templates/webpack#548]
Is it possible to specify a separate template for creating the `/dist/index.html`. We're currently using Vue to refactor some parts of a Symfony monolith that's quite complex. So instead of having one SPA, we've been building several smaller Vue app and including them in Twig partials.

I know it's possible to output a `.twig` file in the build step, but our problem is that the partial ends up looking very different from the index.html we use in development. So what I currently do is run the `npm run build`, open `/dist/index.html` and then manually cut and paste the proper asset tags into my final template.

It seems like the easiest fix would be to just specify a separate template that's only used for the build step. I'm happy to submit a PR for this if someone could provide a little guidance. I'm new to Webpack and I'm not really sure where to begin.

**Comment by LinusBorg** [comment]
Well, you could simply point to another template for the index.html file here:

https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.prod.conf.js#L54

**Comment by daltonamitchell** [comment]
Awesome, thanks @LinusBorg! 👍
