### ISSUE TITLE
jade coffee stylus

### ISSUE THREAD

**Issue by stephanedemotte** [vuejs-templates/webpack#55]
Hi,

Simple question, i have cloned the repo, and i don't understand why i can use by default
```
<template lang="jade">
</template>
```
but i have to install `stylus-loader` for
```
<style lang="stylus">
</style>
```
and

`coffee-script` + `coffee-loader` for 
```
<script lang="coffee">
</script>
```

I'm missing something ?

Thanks :)

**Comment by yyx990803** [comment]
This is because one of the dev dependencies has transitive dependency on jade, and with npm3 it can be directly required. However you should still explicitly `npm install jade --save-dev`.

**Comment by tiaod** [comment]
But I had already install `coffee-script` and `coffee-loader`,  It doesn't works.

**Comment by chrisvfritz** [comment]
@tiaod That looks like an eslint error. Try removing the following from `module.preloaders` in webpack.base.conf.js:

``` js
{
  test: /\.vue$/,
  loader: 'eslint',
  exclude: /node_modules/
},
```
