### ISSUE TITLE
add lang="scss" or sass report error

### ISSUE THREAD

**Issue by sharonlx** [vuejs-templates/webpack#556]
why? the error msg is 

!!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../node_modules/vue-loader/lib/style-rewriter?{"id":"data-v-5a66ccc8","scoped":false,"hasInlineConfig":false}!sass-loader?{"indentedSyntax":true,"sourceMap":false}!../node_modules/vue-loader/lib/selector?type=styles&index=0!./App.vue in ./src/App.vue

**Comment by limichange** [comment]
Do you have installed `sass-loader` and `node-sass` ?

**Comment by LinusBorg** [comment]
node-sass and sass-loader have to be installed by you.
