### ISSUE TITLE
can't use webpack ProvidePlugin ?

### ISSUE THREAD

**Issue by wenkanglin** [vuejs-templates/webpack#559]
### version
* vue-cli 2.8.1
* vue 2.2.1
* webpack 2.2.1

### issue
add webpack `ProvidePlugin` at `webpack.base.conf.js` file:
```
module.exports = {
    ...
    plugins: [
        new webpack.ProvidePlugin({
            Vue: 'vue',
            'window.Vue': 'vue'
        })
    ]
};
```
run the command: `npm run dev`, it will cause error:
![error](https://cloud.githubusercontent.com/assets/21100124/23403535/7c8a0702-fdeb-11e6-90f4-a39316063de2.png)

**Comment by LinusBorg** [comment]
*Sidenote: The DefinePlugin is already added in `webpack.dev.conf.js` and `webpack.prod.conf.js`*

What are you trying to achieve? currently, your code would replace `window.Vue` with a variable named `vue`

This would *not* replace this string with the `vue` module from `/node_modules`, in case you think it would. That would be done with the `ProvidePlugin`

**Comment by ArrowBaZ** [comment]
Same issue,
Vue is required by Webpack and expose a `default` property, not directly Vue
 
`console.log(Vue)`

```
Object
  __esModule: true
  default: Vue$2 (options)
```

**Comment by ArrowBaZ** [comment]
@wenkanglin add vue in your alias

```
module.exports = {
    entry: {
        ...
    },
    output: {
        ...
    },
    resolve: {
        ...
        alias: {
            'vue$': 'vue/dist/vue.common.js',
            'src': resolve('src')
        }
    },
```

**Comment by wenkanglin** [comment]
@ArrowBaZ it does work. But I don't konw what's the difference between `vue.common.js` and `vue.esm.js`

**Comment by LinusBorg** [comment]
https://github.com/vuejs/vue/tree/dev/dist#explanation-of-build-files
