### ISSUE TITLE
webpack CSS source map line numbers in the error messages

### ISSUE THREAD

**Issue by jpokrzyk** [vuejs-templates/webpack#56]
CSS line numbers are incorrect in linters (stylint) and preprocessor error messages (webpack, stylus..)

Check out the line numbers. 
![image](https://cloud.githubusercontent.com/assets/4333958/14030747/a53560e8-f1df-11e5-9cf4-efe2c5b79866.png)

Not sure where this issue should actually live: webpack html extract loader, vue-loader, vue-style-loader, css-loader.js? If someone gives me a hint I'll take a crack at fixing it. 

I have a few ideas but there's probably an easier way of fixing it than anything I can come up with. Seems like one of those webpack plugins needs to pad empty lines for the html and js that's no longer in there. Or maybe re-number the source maps or something like that.

Let me know if I should move the issue somewhere else.

**Comment by yyx990803** [comment]
This is a `vue-loader` issue - I think you have the right guess, probably need to do some SourceMap line number hacking in there.
