### ISSUE TITLE
Why does router need a separate folder?

### ISSUE THREAD

**Issue by pksunkara** [vuejs-templates/webpack#560]
If you look at https://github.com/vuejs-templates/webpack/blob/master/template/src/router/index.js, I am wondering why this `index.js` file needs a separate folder. All the vue-router ever needs is a single file. Why can't we just make it `src/router.js`?

**Comment by LinusBorg** [comment]
When apps grow, the number of routes grows, with beforeEnter hooks and so on, so you might want to put thta in a separate file, or files.
