### ISSUE TITLE
SyntaxError: Unexpected token: name when building for production

### ISSUE THREAD

**Issue by jesperlandberg** [vuejs-templates/webpack#561]
Hi,

I am getting the error "SyntaxError: Unexpected token: name" when building for production. Why is this and how can i fix it? Something about Uglify cannot parse es6?

I am using vue cli 2.5.1.

**Comment by LinusBorg** [comment]
> Something about Uglify cannot parse es6?

Probably. Can't say with this little information.

**Comment by ellipticaldoor** [comment]
Adding this to the package.json solved this problem for me

```
"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony",
```

**Comment by iamdubx** [comment]
@ellipticaldoor this doesn't solve anything.

Why this issue is closed? How to config to solve this errors? I got this errors with 2 packages already.

**Comment by LinusBorg** [comment]
> Why this issue is closed?

Because the OP didn't react to my request for more information, and an appearant solution was provided by someone else.
