### ISSUE TITLE
useless code for commonschunk

### ISSUE THREAD

**Issue by zzzgit** [vuejs-templates/webpack#564]
https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.prod.conf.js#L82-L85

It is totally useless.
Just a empty array it will get.You want to extract a new chunk with no modules in it?

![image](https://cloud.githubusercontent.com/assets/1060733/23472527/14b63fa8-fee8-11e6-832e-3f7f50796138.png)

**Comment by LinusBorg** [comment]
This is a vairation of this technique: 

https://webpack.js.org/guides/code-splitting-libraries/#manifest-file

Please read up on it.
