### ISSUE TITLE
Cannot resolve background-image when running npm run unit

### ISSUE THREAD

**Issue by dimirc** [vuejs-templates/webpack#569]
When I run `npm run dev` all is ok, but when trying to run unit test `npm run unit` I get this error:

```
ERROR in ./~/css-loader?{"minimize":false}!./~/sass-loader/lib/loader.js?{}!./src/assets/styles/main.scss
Module not found: Error: Can't resolve './assets/img/bg_network_purple.svg' in '/Users/wladimircoka/Documents/Develop/logahub/src/assets/styles'
 @ ./~/css-loader?{"minimize":false}!./~/sass-loader/lib/loader.js?{}!./src/assets/styles/main.scss 7:209572-209617
 @ ./src/assets/styles/main.scss
 @ ./src ^\.\/(?!main(\.js)?$)
 @ ./test/unit/index.js
03 03 2017 01:20:52.238:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
03 03 2017 01:20:52.240:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
03 03 2017 01:20:52.251:INFO [launcher]: Starting browser PhantomJS
03 03 2017 01:20:53.135:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket zQeZT4atqRJZ8DNgAAAA with id 75929886
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: Cannot find module "./assets/img/bg_network_purple.svg"
  at webpack:///src/assets/styles/main.scss:7:0 <- index.js:16980

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.187 secs / 0 secs)

```

The problem is with the background-image at my main.scss but only when testing not in dev:
```
.background-login {
  background-image: url(assets/img/bg_network_purple.svg);
}
``` 

I created [this repo](https://github.com/dimirc/vue-template-bgproblem) to be able to reproduce the problem.

Basically its the original template with unit test activated and I additionally only did this:

* At [App.vue](https://github.com/dimirc/vue-template-bgproblem/blob/master/src/App.vue#L14) I added this
```
<style lang="sass">
  @import 'assets/styles/main.scss'
</style>
```

* At [Hello.vue](https://github.com/dimirc/vue-template-bgproblem/blob/master/src/components/Hello.vue#L20) I added a `<div class="background-login"></div>`

* I created [main.scss](https://github.com/dimirc/vue-template-bgproblem/blob/master/src/assets/styles/main.scss#L1) with just this:

```
.background-login {
  background-image: url(assets/img/bg_network_purple.svg);
}
````

Related to https://github.com/vuejs-templates/webpack/issues/563#issuecomment-283876151

**Comment by dimirc** [comment]
@LinusBorg @yyx990803 any chance you could give me some quick hint of where I might need to check to fix this?

**Comment by jmanuelrosa** [comment]
I have the same problem, but with postcss :(

**Comment by dimirc** [comment]
I solve my problem making the pattern less permissive since it was checking not only test files but all files and this was causing me the problem

**Comment by jmanuelrosa** [comment]
I change this in `test/unit/index.js`
```
const srcContext = require.context('../../src', true, /^\.\/(?!main(\.js)?$)/)
```
instead of this
```
const srcContext = require.context('../../src', true, /^\.\/(?!main\.js$).+\.(js|vue)$/i)
```

and works good !!!! :smile:
