### ISSUE TITLE
is HashedModuleIdsPlugin needed for this project?

### ISSUE THREAD

**Issue by zzzgit** [vuejs-templates/webpack#570]
as `commonschunkplugin` is used in this projec,in order to guarantee the module identifiers will be stable,is [HashedModuleIdsPlugin](https://github.com/webpack/webpack/blob/master/lib/HashedModuleIdsPlugin.js) needed to add to this project too?

**Comment by lmk123** [comment]
I make a PR for it but seems no one interesting... #406

**Comment by LinusBorg** [comment]
it's added now.
