### ISSUE TITLE
`browserlist` should be `browserslist`

### ISSUE THREAD

**Issue by gera2ld** [vuejs-templates/webpack#572]
According to [document of browserslist](https://github.com/ai/browserslist), the key name for browserslist in [package.json](template/package.json) should be `browserslist` instead of `browserlist`.

BTW, I think using a `$PROJECT_ROOT/browserslist` file is a little bit more convenient since we don't have to write quotes and commas as in JSON.

**Comment by LinusBorg** [comment]
Thanks fpr the fix - but I think we want to keep this in package.json. We have more than enough cnofig files in the template root already.

@chrisvfritz @zigomir ?

**Comment by zigomir** [comment]
I agree @LinusBorg. One file to rule them all whenever possible.

**Comment by gera2ld** [comment]
OK, I have updated the PR.
