### ISSUE TITLE
what's role of the"template: '<App/>'" in new Vue({})

### ISSUE THREAD

**Issue by tangxu2424** [vuejs-templates/webpack#575]
`new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})`
I can use  `<app/>,<app>,<app>123<app/>`,instead and run successefully, but why it must"app",if I use "`<abb/>`" will be fault

**Comment by LinusBorg** [comment]
because the component is called 'app': `components: { App }`

**Comment by wangliangyu** [comment]
i‘m also confused, we have set components as { App },why need set template as '<App/>' again?

**Comment by LinusBorg** [comment]
`components:` is just making it aware of those components. The template defines which components to render.

**Comment by wangliangyu** [comment]
soga，thanks

发自我的 iPhone
