### ISSUE TITLE
使用脚手架，npm run unit的时候出错

### ISSUE THREAD

**Issue by jqjiang** [vuejs-templates/webpack#58]
![0m22gzkjc0l ujzi6t 6 ye](https://cloud.githubusercontent.com/assets/7692954/14129554/8e1a94fa-f65d-11e5-88c9-cb3758ac968d.jpg)

没有做任何修改

**Comment by yyx990803** [comment]
基本上是因为你的 npm install 有问题，重装 node_modules 看看。

**Comment by ppq1991** [comment]
遇到过同样的问题，应该是国内网络环境的锅，npm install 的时候某一步挂了，删 node_modules 开代理，重新 install 就好了。
