### ISSUE TITLE
"npm run test" fails: Error: Couldn't find preset "latest"

### ISSUE THREAD

**Issue by asselin** [vuejs-templates/webpack#583]
npm run test fails in the latest version of the template with the above error.

Root cause is that the dev/prod preset for babel was changed in .babelrc to "env" and "latest" was removed from package.json... but .babelrc still uses "latest" for test.

I can submit a PR for this... just need to know if the preset for test was intended to be changed to "env" also, or whether it needs to stay "latest" and that package put back into package.json.

**Comment by LinusBorg** [comment]
Just fixed with #582
