### ISSUE TITLE
Update Vue 1.0's template to webpack2

### ISSUE THREAD

**Issue by yuu2lee4** [vuejs-templates/webpack#584]
Our some vue1.0 projects running with webpack1, and i want use webpack2 to replace it to get better performance.

**Comment by LinusBorg** [comment]
To be perfectly honest, I suspect that we won't find time to do this anytime soon, there's a lot of other stuff to do that has a higher impact. At least I won't have the time, personally - can't speak for the rest of the guys with certainty.

We are open to PRs though, so the community might help out :)
