### ISSUE TITLE
Get error EOF when build production

### ISSUE THREAD

**Issue by haipc** [vuejs-templates/webpack#585]
In `config/index.js` and in `build` section set `productionSourceMap: false`. After that, start server and open file `http://static/js/vendor.js` in browsers. I get error message like this.

```
Error: Parse error on line 1:
[0,2],[function(t,e,n){t.
-----^
Expecting 'EOF'
```

**Comment by LinusBorg** [comment]
I don't understand your reproduction description, could you just upload a repository with the settings required for the error?
