### ISSUE TITLE
`npm run dev` ERROR

### ISSUE THREAD

**Issue by FarmanYu** [vuejs-templates/webpack#586]
ERROR in ./src/App.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.2.1
- vue-template-compiler@2.2.2

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by limichange** [comment]
Please upgrade vue.

```bash
$ npm i --save vue@2.2.2
```

**Comment by limichange** [comment]
Link https://github.com/vuejs-templates/webpack/pull/587
