### ISSUE TITLE
Is there any experimental features not supported in ESLint itself yet?

### ISSUE THREAD

**Issue by leohxj** [vuejs-templates/webpack#588]
Recently, I found [babel-eslint/README.md](https://github.com/babel/babel-eslint) says: 
    You only need to use babel-eslint if you are using types (Flow) or experimental features not supported in ESLint itself yet. 

So why we don't using the default parser?

**Comment by LinusBorg** [comment]
Eslint itself only supports the official standard. And The Object rest spread operator is not standard yet, but widely used, e.g. with vuex' map* helpers.
