### ISSUE TITLE
npm run dev 出错

### ISSUE THREAD

**Issue by ickeep** [vuejs-templates/webpack#59]
03-30 vue init webpack my-project 最新安装
执行 npm run dev 报错
![image](https://cloud.githubusercontent.com/assets/9164133/14134230/0be639dc-f688-11e5-805d-1ffc6c3201b9.png)

**Comment by ickeep** [comment]
webpack.base.conf.js  修改为 
![image](https://cloud.githubusercontent.com/assets/9164133/14134302/c77fccf8-f688-11e5-8229-f297145e8d82.png)

仍报错
![image](https://cloud.githubusercontent.com/assets/9164133/14134316/deed1940-f688-11e5-8fa8-c51e40a83ab9.png)

**Comment by chrisvfritz** [comment]
@ickeep Can you share the contents of your `.eslintrc` file?

你可以分享你 `.eslintrc` 文件？

**Comment by yyx990803** [comment]
重新安装 ok 了？关掉了啊
