### ISSUE TITLE
http://eslint.org/docs/rules/no-unused-vars  '<component>' is defined but never used  

### ISSUE THREAD

**Issue by Joshfindit** [vuejs-templates/webpack#592]
Trying to turn a single HTML file in to a webpacked one.
Ran across this issue when separating out components

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                         2:45:12 PM

 error  in ./src/App.vue


  ✘  http://eslint.org/docs/rules/no-unused-vars  'NodeList' is defined but never used  
  /root/vue-cli/src/App.vue:135:8
  import NodeList from './components/NodeList.vue'
```

NodeList.vue is simple (see below), and I'm using `<node-list></node-list>` in the `App.vue` template.

If it helps, there is a similar issue on the React side that was solved [here](https://github.com/eslint/eslint/issues/6303) with 

> Adding the following rule solved my issue:
> `"react/jsx-uses-vars": [2]`
> Thanks a lot @alberto

`NodeList.vue`

```
<template>
  <button class="ui basic button" v-on:click="getParentArtefactInfo( node.uuid )">
    {{ node.name }}
  </button>
</template>

<script>
export default {
  name: 'node-list',
  props: ['node'],
  methods: {
    getParentArtefactInfo: function (filename) {
      this.$root.getArtefactInfo(filename)
    }
  }
}
</script>

<style scoped>
</style>
```
*comments that improve structure are welcome*

**Comment by danishsoomro** [comment]
Exactly having the same issue - created a new single-file componenet and cannot import in the router.vue saying that the variable is defined but not used.  Any directions guys?? Thanks :)

**Comment by erdiegoant** [comment]
Did you add your NodeList Component in the App component export? Like so:
`export default {`
`  components: {`
`    NodeList`
`  },`
`  // Your code`
`}`

**Comment by eric-burel** [comment]
Same issue here, registering in the App export does not seem to work.
In any case, why does eslint errors prevent build by default ? Can this be disabled ? eslint tends to be buggy, especially when you start to work with stuffs like flow and webpack, so an unlinted code should not file.
