### ISSUE TITLE
[Feature Request] Vuex

### ISSUE THREAD

**Issue by ScratchOs** [vuejs-templates/webpack#602]
I was wondering if it would be possible to add an option to enable vuex, like is done for vue-router?

Thanks!

**Comment by nickmessing** [comment]
@ScratchOs, I've seen at least 2 PRs for Vuex, looks like maintainers of this template don't want to include it. Actually they didn't want to include vue-router for long time too so maybe you have a chance.

**Comment by CodinCat** [comment]
I have a fork of this template, which contains basic setups of vuex and vue-router: https://github.com/CodinCat/vue-webpack-plus You can use it before the official webpack template includes vuex
