### ISSUE TITLE
Feature request: copy to dist root

### ISSUE THREAD

**Issue by Christilut** [vuejs-templates/webpack#607]
My projects are usually hosted on Netlify, where I need to add a file called _redirects in order to always redirect to /index.html
This file must be located in the dist root folder. So `my-project/dist/_redirects`.

My current solution is to add the following to the build script:
```js
var copy = require('copy')

const staticRootPath = path.join(config.build.assetsSubDirectory, 'root')

copy(path.join(staticRootPath, '**'), config.build.assetsRoot, function () {
  // webpack called here
})
```

Which copies from `my-project/static/root` to `my-project/dist`.

This works fine. Can we integrate this (or similar) into the template? I'll add some checks and PR it if there are no objections.

**Comment by LinusBorg** [comment]
This would mean that we now have a folder `static/root` that now behaved differently. 

I don't really like this as a feature for the template. 

There would have to be a widespread use case to warrant this.

**Comment by gluons** [comment]
#657 may help you. 🙂

**Comment by andrebuchanan** [comment]
Would like to see an easy way of achieving this via config too. Angular 4 has an assets section for this purpose in .angular-cli.json.

`    "apps": [
        {
            "root": "src",
            "outDir": "dist",
            "assets": [
                "assets",
                "favicon.ico",
                "index.jsp"
            ],
         ....
`

**Comment by LinusBorg** [comment]
I'll close this for inactivity
