### ISSUE TITLE
Feature request: Watch unit tests

### ISSUE THREAD

**Issue by fvictorio** [vuejs-templates/webpack#608]
It would be nice to be able to do something like `npm run unit:watch` to improve the workflow of writing unit tests. Is something like this in the roadmap? Thanks!

**Comment by LinusBorg** [comment]
just do `npm run unit --no-single-run` (or was it `npm run unit -- --no-single-run` ?)

It's a Karma option: https://karma-runner.github.io/1.0/config/configuration-file.html

**Comment by fvictorio** [comment]
Awesome! (It's the second one, `npm run unit -- --no-single-run`, btw). Thanks a lot.
