### ISSUE TITLE
URLs prefixed with ~ are not working

### ISSUE THREAD

**Issue by ellipticaldoor** [vuejs-templates/webpack#609]
When I try to use URLs prefixed with ~ I get the following error:

```
 ERROR  Failed to compile with 1 errors              12:11:00 PM

This dependency was not found:

* assets/logo.png in ./~/vue-loader/lib/template-compiler.js?{"id":"data-v-7ca92acd"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/App.vue

To install it, you can run: npm install --save assets/logo.png
```

I'm using same line of code as the documentation:

``` html
<img src="~assets/logo.png">
```

http://vuejs-templates.github.io/webpack/static.html

**Comment by grantcarthew** [comment]
Docs must be out of date. Try the @ instead of tilda.

**Comment by ellipticaldoor** [comment]
With tilda doesn't give an error but I get a 404

```
<img src="@assets/logo.png">
```
![image](https://cloud.githubusercontent.com/assets/3449006/24105069/bcbba85e-0d7b-11e7-9a1b-a0de80e64c77.png)

**Comment by LinusBorg** [comment]
Adding a tilde is only necessary in css, not html.

**Comment by LinusBorg** [comment]
tildes are not necessary for urls in templates. They are a special syntax used by css-loader.

**Comment by oswaldomilet** [comment]
same here. When using @ or remove tild got 404

**Comment by LinusBorg** [comment]
The alias works like `@/assets` in CSS, it would be `~@/assets`

Please ask further questions on forum.vuejs.org

**Comment by oswaldomilet** [comment]
https://github.com/vuejs/vue-loader/issues/193#issuecomment-294504754

**Comment by LinusBorg** [comment]
Furthermore, tildes are only useful in CSS.
