### ISSUE TITLE
cannot use `less` for styles

### ISSUE THREAD

**Issue by indooorsman** [vuejs-templates/webpack#612]
i have installed `less` and `less-loader`, and added `lang="less"` to my style tag, but when i run `npm run dev` it reported an Error : `Can't resolve 'less-loader'`

i am using the latest version of vue-cli

**Comment by LinusBorg** [comment]
Can you share a repo? this usually works exactly like that.

**Comment by indooorsman** [comment]
it doesnot work with less-loader@4.0.0

less-loader@3.0.0  worked well

**Comment by indooorsman** [comment]
less-loader@4.0.2 has fixed this
