### ISSUE TITLE
Build deployed to Digital Ocean via Laravel Forge but not working...

### ISSUE THREAD

**Issue by PrimozRome** [vuejs-templates/webpack#613]
I am trying to deploy a build of Vue2 SPA app via Laravel Forge to Digital Ocean droplet server...

App was build with `npm run build`, with latest version of webpack template. It was built directly on the server with no error so I guess it should work right?

The error I get in console:

![error](https://cloud.githubusercontent.com/assets/1180467/24145225/80acead4-0e30-11e7-9f75-0444ae741b86.png)

Go ahead if you want to try: http://webshop.lastapp.xyz/

**Comment by heinzdmx** [comment]
Is this working when running `npm run dev`? I believe your error is on your router.beforeEach  function

I think your choice of naming of variables may have confused you. You define the variables as
`router.beforeEach((route, redirect, next) => {`
whereas the documentation define them as:
`router.beforeEach((to, from, next) => {`

You are trying to change the path using `redirect` but should instead do with with `next` as per the [documentation](https://router.vuejs.org/en/advanced/navigation-guards.html)

For example: 
`redirect({  path: '/auth/login' })` should be changed to `next({  path: '/auth/login' })`

I think that will take care of the first exception, as t is probably the renamed redirect variable.  

The last error I am not so sure about, but try commenting out all code in router.beforeEach, except `next()` and see if that helps.  I would also advice you to try running as development, as it can give some additional clues that build does not give

**Comment by PrimozRome** [comment]
Hmm a little bit confused... Works fine locally with `npm run dev`. 

I will look into it definitely but I'm pretty sure I should have problems locally to for what you are saying right...

**Comment by PrimozRome** [comment]
You were right... This was changed in v2.1.0... The way I used it was from v.2.0 pre-release from the example. I Guess this was changed later on.

**Comment by heinzdmx** [comment]
Then I guess it might have been caused by different dependencies on the Droplet compared to your local machine. As long as it works now I guess :)
