### ISSUE TITLE
After built the z-index changed

### ISSUE THREAD

**Issue by RoamIn** [vuejs-templates/webpack#614]
### Version
latest[mybe not just]
[zIndexBug.zip](https://github.com/vuejs-templates/webpack/files/858212/zIndexBug.zip)

### Steps to reproduce
- Just make a vue component，write z-index in style
- Run command: `npm  run dev`，everything fine
- Run command: 'npm run build`，what a mess...my z-index value changed

I think the z-index value shouldn't be changed，because we may use the third party plugin like jQuery plugin which could use z-index. In this condition, the z-index calculation is unnecessary, and make mistakes.

### What is expected?
keep my z-index value
![dev](https://cloud.githubusercontent.com/assets/11537595/24149110/5ed286c0-0e7c-11e7-9d25-875e4a507575.png)

### What is actually happening?
my z-index changed
![built](https://cloud.githubusercontent.com/assets/11537595/24149113/64f21d0e-0e7c-11e7-8e25-a0211b29dd3c.png)

**Comment by LinusBorg** [comment]
You likely set the same class somewhere else, with `z-index: 1`

During production, all CSS is extracted in one file and minified, which also removes duplicate definitions - and in this case, the duplciate with z-index: 1 was the "survivor".

**Comment by RoamIn** [comment]
No, absolutely not.
I just want to override z-index that setted in other plugin.

**Comment by LinusBorg** [comment]
> For example, I set `z-index:  2` in ``a.js``, then I import it at ``b.js``, and override ``z-index:  3`` , it wouldn't work.

This is exactly what I am talking about, though. If you override global styles in a component without using the `scoped`feature, the latest one will override all other versions. CSS is global by default.

If you still disagree, please provide a repository with a minimal reproduction for me to check out.

**Comment by RoamIn** [comment]
I write a simple demo.
- `npm run dev`: You will see the blue sky
- 'npm run build': You will see the tan land

> Maybe you would ask why set `z-index` in DOM, because we cannot guarantee what component will be used. It just like using a component doesn't write with Vue.

[zIndexBug.zip](https://github.com/vuejs-templates/webpack/files/882352/zIndexBug.zip)

**Comment by Vivi-wu** [comment]
Just run into the same problem. I think it is the same issue as : https://github.com/ben-eb/gulp-cssnano/issues/8

**Comment by LinusBorg** [comment]
Ah I see, so at the root, this is an issue with css-loader / cssnano default settings.

I think we should be able to fix this in the webpack config for css-loader.

Thanks for investigating! :)

**Comment by LinusBorg** [comment]
Hm, I'm currently trying to test my fix, but I can't reproduce the problematic behaviour, even if I set `minimize: { zindex: true }` in the css-loader's options...

**Comment by RoamIn** [comment]
I noticed that the `webpack/template/build/webpack.prod.conf.js` file has been changed by yyx990803.
[only use safe optimizations for css minification](https://github.com/vuejs-templates/webpack/commit/54d3bd247d421f8ce9938988283ce9c7badf554f)

**Comment by LinusBorg** [comment]
Oh, I missed that, thanks for the pointer!

**Comment by jahanzaibsuleman07** [comment]
@LinusBorg should this be added in the Readme.md file as well.

```
new OptimizeCssAssetsPlugin({
          cssProcessorOptions: {
            safe: true
          }
        }),
```
