### ISSUE TITLE
can't work with less-loader-4.0.0

### ISSUE THREAD

**Issue by transtone** [vuejs-templates/webpack#615]
some how less-loader updated, the whole project goes down.

https://github.com/vuejs/vue-cli/issues/410

**Comment by keepfool** [comment]
I have met this problem also, finally I downgrade my less-loader.

**Comment by indooorsman** [comment]
+1

**Comment by stbaer** [comment]
It's fixed in the latest version of less-loader (4.0.2).
see [issue#177](https://github.com/webpack-contrib/less-loader/issues/177)
