### ISSUE TITLE
Module build failed: SyntaxError: Unexpected token { on fresh install

### ISSUE THREAD

**Issue by jayming111** [vuejs-templates/webpack#617]
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-compiler?{"id":"data-v-44de71e8","scoped":false,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at loadLoader (/Users/zhopeng/UI/simple1/node_modules/loader-runner/lib/load

**Comment by akumatus** [comment]
Same here.
<img width="692" alt="2017-03-22 5 21 34" src="https://cloud.githubusercontent.com/assets/12724894/24190593/0f93f7c6-0f24-11e7-869f-1440f2daa392.png">

**Comment by ttian226** [comment]
same with me

**Comment by guixue** [comment]
try to  change package.json:

`"vue-loader": "^11.1.4"`

to 

`"vue-loader": "11.1.4"`

for temporary solution

**Comment by guixue** [comment]
I met the same issue, but report to the  https://github.com/vuejs/vue-cli/issues/414

**Comment by guixue** [comment]
Ref to https://github.com/vuejs-templates/webpack/issues/619

**Comment by zdy350** [comment]
It still does not work

**Comment by ryan-kite** [comment]
Thanks keeping "vue-loader": "11.1.4", worked for me on this fresh install :)

**Comment by damienix** [comment]
Using Node 6 instead of 4 helped me.

**Comment by Orocker** [comment]
Same here.
