### ISSUE TITLE
webpack template and typescript

### ISSUE THREAD

**Issue by gorshkov-leonid** [vuejs-templates/webpack#622]
Hello, 
I tested example with typescript from [vue-class-component](https://github.com/vuejs/vue-class-component), it is [working](https://github.com/gorshkov-leonid/vue-experiments/tree/master/vue-ts-loader). I tried to apply this solution to [webpack template](https://github.com/gorshkov-leonid/vue-experiments/tree/master/test-vue). So it is ts-loader+ typescript dependencies, tsconfig.json, lang="ts" of script tag, and webpack rule in webpack.base.conf.js. 
But I got error TS18003:
![vue_build exe](https://cloud.githubusercontent.com/assets/2270831/24243399/6e79033e-0fd4-11e7-8838-b9ed228b78b3.png)

It is not bug of this repository, but I hope you will help me

**Comment by Aladdin-ADD** [comment]
add a file named `tsconfig.json` in your root directory. just like this:
```js
{
	"compilerOptions": {
		"experimentalDecorators": true,
		"allowSyntheticDefaultImports": true,
		"module": "es2015",
		"moduleResolution": "node",
		"noImplicitAny": true,
		"target": "es5",
		"lib": ["dom", "es5", "es2015.promise"]
	},
	"files": [
		"./src/main.ts"
	]
}
```

**Comment by gorshkov-leonid** [comment]
Thank you. But I created https://github.com/gorshkov-leonid/vue-experiments/blob/master/test-vue/tsconfig.json but I do not know which settings can help me

**Comment by gorshkov-leonid** [comment]
I create thread in forum, but quiet yet...
https://forum.vuejs.org/t/vue-webpack-and-typescript/8568

**Comment by Aladdin-ADD** [comment]
maybe it's because of missing `files` in `tsconfig.json`, add `"files": ["./src/main.ts"]` and try again.
I just add simple support to ts. you can see here(#633), hope it can help you~😺

**Comment by LinusBorg** [comment]
Sounds like this is solved?

**Comment by gorshkov-leonid** [comment]
thank you!
