### ISSUE TITLE
Keeping up with the template

### ISSUE THREAD

**Issue by chmln** [vuejs-templates/webpack#629]
This template evolves rather fast, accounting for updates in webpack, babel, uglify, etc.
How should one keep up with changes?

It seems unreasonable to constantly respawn a project with vue-cli and port over components with proxy configs etc.

Could there be a vue [equivalent](https://github.com/infernojs/create-inferno-app/blob/master/README.md#creating-an-app) of [`inferno-scripts`](https://github.com/infernojs/create-inferno-app/tree/master/packages/inferno-scripts)?

Additionally, this would allow us devs not to check in webpack configs (looking at `build`, `config`) into repositories, which would then consist of just the source files.

**Comment by grantcarthew** [comment]
This is a common problem. I am currently manually updating the [vue-foundation](https://github.com/hal0gen/vue-foundation) template as PRs come in.

**Comment by awitherow** [comment]
@grantcarthew what are your most commonly manual done updates?

**Comment by grantcarthew** [comment]
@awitherow I've only been working with the template for a few months. So far I have changed the resolve character to @ and a few other minor changes. I am racking up a few issues to do all at once when I am next working on the template.

Current changes needing attention: https://github.com/hal0gen/vue-foundation/issues/10

**Comment by LinusBorg** [comment]
Hi guys! 

We are aware that keeping up is a problem with the current setup.. It that will always be the case for a "template". 

We are thinking about how to best solve this with something similar to react-scripts or inferno-script s, but so far haven't found the time to really work on this.

**Comment by LinusBorg** [comment]
Just as a small note: We ware actively planning a rewrite of this template that will extract the (webpack) config into a dependency, which will make updates more painless.

Since this is being worked on, I will close this for now.

**Comment by awitherow** [comment]
@LinusBorg would be great if you could link everything related to the changes you are making in this issue so that when people come here they have an idea of what is going on 👍

**Comment by LinusBorg** [comment]
I think when work is actually going ahad to something wotrh noting, we will open a new issue.

**Comment by grantcarthew** [comment]
Hey, this sounds great. Is the new dependency going to include #546 ?

**Comment by saintplay** [comment]
Also check #1212
