### ISSUE TITLE
“Unknown word” error when importing a JavaScript module

### ISSUE THREAD

**Issue by jsepia** [vuejs-templates/webpack#634]
I built a project using this template, and at first everything worked fine, but after some SASS refactoring I started seeing this error when running `npm run dev`:

    ERROR  Failed to compile with 1 errors                                                                                                                                            3:58:15 PM
    
    error  in ./src/components/views/debug/Debug.vue
    
    Module build failed: Unknown word (17:10)
    
      15 | import Icon from '@/components/icon/Icon'
      16 |
    > 17 | import { generateRandomCharacter } from '@/game/factories/character-factory'
         |          ^
      18 |
      19 | export default {
      20 |   name: 'debug',
    
     @ ./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"id":"data-v-5f003372","scoped":true,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=s
    tyles&index=0!./src/components/views/debug/Debug.vue 3:10-116
     @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"id":"data-v-5f003372","scoped":true,"hasInlineConfig":false}!./~/vue-loader/l
    ib/selector.js?type=styles&index=0!./src/components/views/debug/Debug.vue
     @ ./src/components/views/debug/Debug.vue
     @ ./src/router/index.js
     @ ./src/main.js
     @ multi ./build/dev-client ./src/main.js

This is the `Debug.vue` component where the error occurs:

```html
<template>
  <div class="debug">
    <icon name="heart"></icon>
    <battle :allies="allies" :enemies="enemies"></battle>
    <div>
      <btn>Button</btn>
      <btn icon="heart">Button with icon</btn>
      <btn icon="heart" primary>Primary button with icon</btn>
    </div>
  </div>
</template>
    
<script>
import Battle from '@/components/views/battle/Battle'
import Btn from '@/components/btn/Btn'
import Icon from '@/components/icon/Icon'
    
import { generateRandomCharacter } from '@/game/factories/character-factory'
    
export default {
  name: 'debug',
  data() {
    return {
      allies: [
        generateRandomCharacter(),
        generateRandomCharacter(),
      ],
      enemies: [
        generateRandomCharacter(),
        generateRandomCharacter(),
        generateRandomCharacter(),
      ],
      options: [
        {
          label: 'male',
          value: 0,
        },
        {
          label: 'female',
          value: 1,
        },
      ],
    }
  },
  components: {
    Battle,
    Btn,
    Icon,
  },
}
</script>
    
<style scoped>
  @import 'Debug';
</style>
```

The contents of the `character-factory` module are irrelevant, it happens regardless of what I try to import. Replacing `Debug.vue` with any other Vue component containing ES6-style imports with destructuring results in the same error.

Judging from the stack trace it would seem `css-loader` is being used to load the `<script>` tags, but I don't know a lot about Webpack (let alone Webpack 2) so I might be misinterpreting it.

**Comment by LinusBorg** [comment]
The point is that webpack is handling the import paths in the `@import 'Debug'` - and it uses node's module resolution, which probably picks up `Debug.vue`, when really you want it to pick up `Debug.scss`. 

Try adding the file extension.

**Comment by jsepia** [comment]
You were right in that the CSS `@import` was causing `Debug.vue` to be re-required as a CSS file. Adding the extension causes a linting error, but I was able to work around this by simply giving each SCSS file a unique filename (e.g. `debug-styles.scss`).

As an aside, this triggered a different error, but I'll open a different issue for that one.
