### ISSUE TITLE
why 'babel-runtime' can't support 'regenerator' or 'Object.assign' etc. in v2.8.1

### ISSUE THREAD

**Issue by lichinlichin** [vuejs-templates/webpack#635]
![image](https://cloud.githubusercontent.com/assets/13887816/24387883/4726399e-13aa-11e7-843a-4ad53006f628.png)

but the vue-cli with old version can support

**Comment by lichinlichin** [comment]
I found that diff in .babelrc about 'presets'
older version is 'es2015' and the lasted version is 'env',
but installed babel-preset-es2015 and changed the .babelrc as older version, still not work.

**Comment by Ewocker** [comment]
I tried Object.assign in my project with the newest template and it did not show any error.
Are you sure that it is the problem of Object.assign?
Did you try install the dependency above and restart the dev server?

**Comment by lichinlichin** [comment]
Hi.
I tried delete the 'node_modules' and installed all the package noce again, it works.
last but not least, thank you.
