### ISSUE TITLE
.eslintrc.js not recognized by editors?

### ISSUE THREAD

**Issue by codeofsumit** [vuejs-templates/webpack#636]
I got the problem that even though the build fails all the time due to linting errors (cool), my editor (Atom) doesn't show these errors.
And I just noticed that there is no `.eslintrc` but a `.eslintrc.js` file with a sligthly different syntax.

Is this causing the problem or what do I need to do to make eslint working with Atom again?

(works fine in other projects that have an `.eslintrc`.

Thanks in advance for any help

**Comment by LinusBorg** [comment]
Works well here:
![bildschirmfoto 2017-03-29 um 23 40 45](https://cloud.githubusercontent.com/assets/1444526/24477920/29db20e0-14d9-11e7-92ef-05e43f4b17cf.png)

So I Would assume this is a problem with your atom plugins/config. Which pluign are you using? I use linter-eslint.

Maybe you just ahven't enabled this setting, which is necessary to make linter-eslint work with .vue files:
![bildschirmfoto 2017-03-29 um 23 42 35](https://cloud.githubusercontent.com/assets/1444526/24477973/681802a6-14d9-11e7-95ee-7f50c886856d.png)

**Comment by codeofsumit** [comment]
argh yes the setting was disabled - thank you!
