### ISSUE TITLE
Cannot find module './full-chrome-versions'

### ISSUE THREAD

**Issue by flexwie** [vuejs-templates/webpack#637]
When I started a fresh project I got the following error message

> vue@1.0.0 dev C:\Users\felix\Documents\Code\Vue
> node build/dev-server.js
> 
> Starting dev server...
> 
> 
>  ERROR  Failed to compile with 1 errors                                                                         20:57:00
> 
>  error  in ./src/main.js
> 
> Module build failed: Error: Cannot find module './full-chrome-versions' (While processing preset: "C:\\Users\\felix\\Documents\\Code\\Vue\\node_modules\\babel-preset-env\\lib\\index.js")
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\felix\Documents\Code\Vue\node_modules\electron-to-chromium\index.js:4:26)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\felix\Documents\Code\Vue\node_modules\babel-preset-env\lib\normalize-options.js:11:27)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
> 
>  @ multi ./build/dev-client ./src/main.js
> 
> Listening at http://localhost:3000

How can I solve this?

**Comment by ashleahhill** [comment]
Possibly related: https://github.com/vuejs/vue-cli/issues/394

**Comment by ashleahhill** [comment]
I think the issue is in `/node_modules/electron-to-chromium/index.js`

They are mixing up `full-chromium-versions` with `full-chrome-versions`

If you have the luxury of a local build, you can hack it to make the build work.

**Comment by ashleahhill** [comment]
Looks like the dev is releasing hotfixes now: https://github.com/Kilian/electron-to-chromium/commit/ab29cb73d4e24b053a70690bd8fa0b31dc7895f6

**Comment by ashleahhill** [comment]
https://github.com/Kilian/electron-to-chromium/commit/f7b9b31cfdebfb48c69ede129b4376a3d9eb9f49

**Comment by Kilian** [comment]
Sorry about that. 1.3.2 should fix this.

**Comment by ashleahhill** [comment]
@Kilian Can confirm. Thanks
