### ISSUE TITLE
ie 11 and safari blank screen

### ISSUE THREAD

**Issue by miecio1212** [vuejs-templates/webpack#638]
Hey!
When I'm using es6 features project doesn't work with some browsers.
I use yours teamlate with .vue components.
Maybe vue-loader doesn't work good with babel? 
Can't find solution I'd like to use es6 syntax but I've got problem. Maybe you should do something about it or make some kind of guide how to improve compatibility.

**Comment by LinusBorg** [comment]
Please consider asking on our forum ar forum.vuejs.org

This template usually works very well with es6 and  IE, and by default all ES6 code is transpiled to ES5, so the problem is likely something specific to your setup or usage.

The issue tracker is not the right place for this.
