### ISSUE TITLE
.babelrc {module: false} and older browsers

### ISSUE THREAD

**Issue by Toilal** [vuejs-templates/webpack#649]
https://github.com/vuejs-templates/webpack/commit/56d0ad9e6356a48005afe8e0751dcfa4f6c15a2f introduce `{module: false}` in `.babelrc` env preset. 

I think it's to support Hot Module Replacement properly (see https://webpack.js.org/guides/hmr-react/), but won't this setting break the app when running in older browsers ?

In my project, I added a production env setting in `.babelrc` to make the production build transpile modules. What about adding this in the webpack template ?

```json
{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    },
    "production": {
      "presets": ["env", "stage-2"]
    }
  }
}
```

**Comment by LinusBorg** [comment]
This setting was added because webpack2 can handle ES modules itself - Babel doesn't have to transpile them. 

So this won't affect browsers in any way.

**Comment by Toilal** [comment]
Ho I see ! Thanks for the tip.

**Comment by leohxj** [comment]
@LinusBorg 
If we use webpack2 or 3, preset's module options could set  to false always?

**Comment by LinusBorg** [comment]
Inject-loader can't work with ES modules,, which we probably want to use in our tests to mock dependencies - so for tests, we have to let babel convert to commonjs.
