### ISSUE TITLE
jQuery / js-assets integration

### ISSUE THREAD

**Issue by cakebake** [vuejs-templates/webpack#65]
Sorry, stupid question ;) Which way do you recommend to integrate jquery to be reachable as global?

I have all the time error messages like `Uncaught Error: Cannot find module 'jquery'`

Tried it with the following code in main.html `<script>window.$ = window.jQuery = require('jquery')</script>`.

I will try to play with Semantic UI, Vue and this boilerplate https://github.com/bradstewart/electron-boilerplate-vue (which uses this webpack configuration).

**Comment by azamat-sharapov** [comment]
Check out [shimming modules docs](https://webpack.github.io/docs/shimming-modules.html). I personally use ProvidePlugin, if there is Semantic UI or something similar in project, because that's easiest way to inject jQuery (or other dependency) into tons of JS files.

**Comment by azamat-sharapov** [comment]
And question isn't stupid, just make sure to ask it on forums or chat, issues are for bugs or feature requests.

**Comment by chrisvfritz** [comment]
Thanks @azamat-sharapov!

**Comment by cakebake** [comment]
I understand Issues, but thanks anyway! ;)

> If someone has the same problem: bradstewart/electron-boilerplate-vue#14
