### ISSUE TITLE
Get assetsPublicPath from package.json in build task

### ISSUE THREAD

**Issue by goncy** [vuejs-templates/webpack#651]
I configured my project to do an easy deploy to Github pages, adding the homepage property on `package.json` like this:
```json
"homepage": "https://goncy.github.io/vue-vuex-todo/"
```
And editing the `config/index.js` to this:
```js
assetsPublicPath: pkg.homepage || '/'
```
So, to deploy to github pages you only need to, install `gh-pages` package and create a `deploy` task like this:
```json
"deploy": "yarn build && gh-pages -d dist"
```
I think it's pretty straightforward and i can do a pull request, what do you guys think?

**Comment by LinusBorg** [comment]
Hi @goncy, 

thanks for this suggestion.

However, I think this is a niche functionality for deploys like Github pages, and would only add another config options for all users of the template that they rarely need, but have to understand/learn to know what it does.

So I don't think that we should add this to the template.
