### ISSUE TITLE
npm run dev working but npm run build is not

### ISSUE THREAD

**Issue by Ewocker** [vuejs-templates/webpack#653]
I am working on a vue-cli project, and when I run npm run dev, everything serves normal, but no matter how I run npm run build, it will show:

⠴ building for production...
Starting to optimize CSS...
Processing static/css/app.e7c5d8517891f5f8941fcc5875e92c74.css...
Processed static/css/app.e7c5d8517891f5f8941fcc5875e92c74.css, before: 169389, after: 169260, ratio: 99.92%

/<My path to the folder>/VueJS/build/build.js:20
    if (err) throw err
             ^

Error: EISDIR: illegal operation on a directory, open '/Users/ylin/Dropbox/proofpoint/VueJS/dist'
    at Error (native)

and lots of ERR ... and so on.

**Comment by LinusBorg** [comment]
> illegal operation on a directory, open 

Please move the project out of dropbox and try again. 

Or it may ha e something to do with folder permissions.

**Comment by LinusBorg** [comment]
Closing for inacivity. This doesn't seem to be related to this template.
