### ISSUE TITLE
Want to have files in root

### ISSUE THREAD

**Issue by visualcookie** [vuejs-templates/webpack#657]
Hi,

I currently have a lot of files, which are normally meant to be in the ROOT directory of the project, inside the static directory. Now I literally have no idea, how to get these files to be in the ROOT directory, when the project is going to get builded.

Any1 got a solution for me?

**Comment by visualcookie** [comment]
Fixed it myself by adding a directory `root/`, copying the files over there and extending `webpack.prod.conf.js` copytask with this:

``` js
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.build.assetsSubDirectory,
        ignore: ['.*']
      },
      {
        from: path.resolve(__dirname, '../root'),
        to: config.build.assetsRoot,
        ignore: ['.*']
      }
    ])
```

**Comment by askmike** [comment]
For me the above solution from @visualcookie didn't work, getting this error:

> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> Error: [BABEL] /Users/pear/projects/gekko-develop/web/vue/src/main.js: .apply is not a valid Plugin property

instead I had to move the CopyWebpackPlugin config into a new file `vue.config.js` like so:

    const CopyWebpackPlugin = require('copy-webpack-plugin');

    module.exports = {
      configureWebpack: {
        plugins: [
          new CopyWebpackPlugin([
            {
              from: '../baseUIconfig.js',
              to: 'public/UIconfig.js'
            }
          ])
        ]
      }
    }

See these docs: https://cli.vuejs.org/guide/webpack.html#simple-configuration

**Comment by visualcookie** [comment]
@askmike Thanks for the response. It did work, but my post is from last year, so yeah... version has changed and such.

**Comment by askmike** [comment]
I know, I was just commenting my findings for future readers. Took me an
hour to figure out, so maybe I can save the next person that time (until it
changes again).

**Comment by Gerben-T** [comment]
@askmike Extending the existing `CopyWebpackPlugin` with

```JS
{
    from: path.resolve(__dirname, '../root'),
    to: config.build.assetsRoot
}
```

worked for me.

```JS
new CopyWebpackPlugin([
        {
            from: path.resolve(__dirname, '../static'),
            to: config.build.assetsSubDirectory,
            ignore: ['.*']
        },
        {
            from: path.resolve(__dirname, '../root'),
            to: config.build.assetsRoot
        }
]),
```

VueJS **^2.5.2**
