### ISSUE TITLE
How to use mapState in coffeescript + vuex

### ISSUE THREAD

**Issue by mshahbazi** [vuejs-templates/webpack#663]
I am trying to use `lang="coffee"` in my latest project. But I got stuck in importing and using mapState/mapActions/mapGetters. How could the following lines be converted to coffeescript?

` import {mapState, mapActions} from 'vuex'`

```
computed:{
  ...mapState(['users'])
}
```

Any advice would be appreciated

**Comment by mshahbazi** [comment]
I managed to make it work this way, however it sound like dirty:
`Vuex = require('vuex')`

```
computed:
  Vuex.mapState ['users']
```
the problem now is I cannot add more functions to computed:
``` computed:
   Vuex.mapState['users'],
   myfunc: () -> this raises error
```
obviously raises error

**Comment by LinusBorg** [comment]
As I already answered somewhere else, you will have to use Object.assign() to combine the results of `Vuex.mapState()` with the normal computed property functions.
