### ISSUE TITLE
Automatically set new local port numbers when running additional projects in development mode

### ISSUE THREAD

**Issue by jpoechill** [vuejs-templates/webpack#668]
Currently – when trying to run multiple (simultaneous) development projects in Vue-CLI, error will occur if the default port number has not been manually changed.

Command (with single project already running):
'npm run dev'

Error:
'Error: listen EADDRINUSE :::8080...'

**Comment by DanielPe05** [comment]
@jpoechill I ran into the same issue a while back, as I had other apps running simultaneously. I just submitted a PR which will help you with this issue (#669). It might not get merged as this is not something that everybody needs, but you can see what I did there. I hope it helps.

**Comment by jpoechill** [comment]
Oh, great. Much appreciated :)) @DanielPe05

**Comment by LinusBorg** [comment]
Will close the issue since further discussion can happen on the PR
