### ISSUE TITLE
No compatible version found: vue@^2.2.2

### ISSUE THREAD

**Issue by wangpin34** [vuejs-templates/webpack#670]
Full error segment:
```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP Sprout\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.7.4
npm ERR! npm  v4.3.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: vue@^2.2.2
npm ERR! notarget Valid install targets:
```
Hope any body could help me out of this. I already stuck here for several hours.

Thanks.

**Comment by LinusBorg** [comment]
No idea how to reproduce this, sorry. Is this still an issue for you?

**Comment by wangpin34** [comment]
@LinusBorg I changed vue to older version and also downgraded some of depends packages. And now it could work.  

By the way, I tried the template(changed nothing) on my Mac book and it worked fine.

**Comment by LinusBorg** [comment]
That's weird, but seems to be a windows&node/npm problem at its core.... Not sure what we can do about this :(

**Comment by wangpin34** [comment]
@LinusBorg  It's possible.  But I am not familar about this. 😞 .  Thanks for your kindly reply.
