### ISSUE TITLE
[Question] How can I import SASS/SCSS file in main.js

### ISSUE THREAD

**Issue by amranidev** [vuejs-templates/webpack#673]
Greetings,

 I'm trying to import/require an scss file in main.js 

```javascript
// main.js
require('./assets/sass/app.scss')
```

I got an error

```shell
This relative module was not found:

* ./assets/sass/app.scss in ./src/main.js
```

app.scss path : /src/assets/sass/app.scss

main.js path : /src/main.js

any suggestion please!!

**Comment by grantcarthew** [comment]
Checkout [vue-foundation](https://github.com/hal0gen/vue-foundation) as a reference. That template is importing scss files.

**Comment by amranidev** [comment]
This is the solution.
Go to `build/utils.js` and change
 `scss: generateLoaders('css')`  to  `scss: generateLoaders('sass')`

**Comment by LinusBorg** [comment]
This should simply work, provided that sass-loader is installed. The code line you changed certainly wasn't wrong.

**Comment by amranidev** [comment]
@LinusBorg Thanks 
I'm using vue-cli, the code line was `css`, so I've changed it to `sass` and it works now.
but while compiling, I got errors such like 'unexpected syntax' and stuffs like that, so I realize that I have to install `sass-loader`, and everything works out in the end.
