### ISSUE TITLE
[Question] Multi Page Application

### ISSUE THREAD

**Issue by dwikip** [vuejs-templates/webpack#675]
Hello, 
Has anyone ever create multi page app using this boilerplate?

Im still confused where to put the route.

I've tried to put
`app.get('/anotherpage', function (req, res) {
  res.send('hello world')
})`
in dev-server.js, but it still not working...

and also i need to know how to add another .html that will load another main.js (different name)

big thank you...

**Comment by grantcarthew** [comment]
Hi @dwikip. I would suggest you break the application up into different projects and use a reverse proxy like [nginx](https://www.nginx.com/resources/wiki/) to route between them.

**Comment by dwikip** [comment]
i see, this template is for single-page applications...
thank you @grantcarthew
