### ISSUE TITLE
[Question] How to exclude /components folder from karma coverage?

### ISSUE THREAD

**Issue by NikitaLiashenko** [vuejs-templates/webpack#681]
I am trying to exclude /components folder from karma coverage.
Unfortunately exclude section in karma.conf doesn't work
Example:
`exclude: ["**/components/**/*.js"]`

**Comment by LinusBorg** [comment]
In `/test/unit/index.js` you find this piece of code on the bottom:
```javascript
const srcContext = require.context('../../src', true, /^\.\/(?!main(\.js)?$)/)
srcContext.keys().forEach(srcContext)
```
It uses webpack's `require.context()` to require all modules in a folder (and subfolders). This function accepts a regex, we use it to exlcude `main.js`, but you could use it to exclude `/components` as well.

IF you need further assistance, plesse consider asking on out forum.vuejs.org so github issues can focus on bugs, thanks!

**Comment by TheDutchCoder** [comment]
Sorry to add to a closed issue, but how well is this tested?

This part of the configuration doesn't seem to do anything. I can change it, or comment it out, but the results stay the same.

Example:

``` js
const srcContext = require.context('../../src/framework/components/warning/src', true)
srcContext.keys().forEach(srcContext)
```

This doesn't do coverage for only the one component, it still does coverage for pretty much everything in my project.

Unless I'm missing something obvious, this is just not doing anything?

**Comment by whoisjorge** [comment]
Hi! I am pretty confused about how to exclude files and folders with certain flexibility, and my _humble tests_ should not pay for it. Even looking at the [documentation](http://webpack.github.io/docs/context.html#require-context) can't do what I look for...

```js
const srcContext = require.context('../../src', true, /^\.\/(?!index|app(\.js|)?$)/)
```
Is there any way to require all **src** files except `index.js`, `app.js` and, _for example_, the `assets`folder?
