### ISSUE TITLE
Pass props to component in Unit Test

### ISSUE THREAD

**Issue by jmanuelrosa** [vuejs-templates/webpack#686]
Hi!

I'm trying to create a unit test for my app based in Vue and vue-cli with webpack template.

I read Vue documentation, vue-loader, vue-cli and vue-template/webpack (an more!). When I try to make a unit test for my component, I use this.

```
const Constructor = Vue.extend(MyComponent)
vm = new Constructor().$mount()
```

like [Vue-template/webpack example](https://github.com/vuejs-templates/webpack/blob/master/template/test/unit/specs/Hello.spec.js) and like [Vue official](https://vuejs.org/v2/guide/unit-testing.html#Writing-Testable-Components)

This work fine. but the pronlem is when my component has some props. I try to pass with this

```
const Constructor = Vue.extend(MyComponent)
vm = new Constructor({
  myprop: 10
}).$mount()
```

And in my unit test, when I try to get this prop, I get undefined. How can I pass prop to my component in unit test?

**Comment by jmanuelrosa** [comment]
I solve it with this
```
const Constructor = Vue.extend(MovieList)
vm = new Constructor({
    data: {
        myProp: 10
    }
}).$mount()
```

**Comment by juliandavidmr** [comment]
You can use the next package **[vue-test-utils](https://github.com/vuejs/vue-test-utilshttps://github.com/vuejs/vue-test-utils)**
