### ISSUE TITLE
*.vue source maps in production

### ISSUE THREAD

**Issue by ronnievdc** [vuejs-templates/webpack#690]
The UglifyJsPlugin breaks the *.vue source files in chrome when outputting from console.log(). See the steps below to reproduce.

Start project test
```
vue init webpack test
cd test
npm install
```
Edit /src/components/Hello.vue
```
  mounted () {
    console.log('HELLO')
  },
```
Build production code and run production server
```
npm run build
cd dist/
python -m SimpleHTTPServer 9000
```
Open http://localhost:9000/ in chrome and view the console
> app.1842fbf….js:56 HELLO

# Disable the UglifyJsPlugin
Remove the following from /build/webpack.prod.conf.js
```
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: true
    }),
```
Build production code without UglifyJsPlugin and run production server
```
cd ..
npm run build
cd dist/
python -m SimpleHTTPServer 9000
```
Open http://localhost:9000/ in chrome and view the console
> Hello.vue:27 HELLO

**Comment by LinusBorg** [comment]
This issue is outdated.
