### ISSUE TITLE
Hot reloading from a VM

### ISSUE THREAD

**Issue by nicolas-t** [vuejs-templates/webpack#7]
Hi,

i'm trying to use hot-reloading (with vue-cli webpack) inside a virtual machine (with a custom domain name : `website.dev`).
(the virtual machine is laravel homestead: https://laravel.com/docs/5.2/homestead)

From the outside of the vm at localhost:8080 every thing is working fine.  
whereas from the vm, everything looks fine too, but hot reloading is not working at website.dev:8080

Following you recomandation i've tried to set up a `devServer.proxy` without success.  

Can you share some example of `devServer.proxy` ? 

thanks :3

**Comment by nicolas-t** [comment]
w00t!

Fixed it like this : 

```javascript
// webpack.dev.conf.js
config.devServer = {
  ...
  watchOptions: {
    aggregateTimeout: 300,
    poll: true
  }
}

```
source & info: http://stackoverflow.com/a/32164525/1609338

Thanks a lot, you can close :3

**Comment by thinsoldier** [comment]
> ```js
> // webpack.dev.conf.js
> config.devServer = {
>   ...
>   watchOptions: {
>     aggregateTimeout: 300,
>     poll: true
>   }
> }
> ```

Where exactly does this go? I don't have a file named `webpack.dev.conf.js` after running `$> vue create hello-world`

**Comment by nicolas-t** [comment]
You're probably using vue-cli 3
If so you should have a `vue.config.js` at the root of your project, containing a `devServer` Object.
Related documentation : 
https://cli.vuejs.org/config/#devserver

**Comment by thinsoldier** [comment]
Thanks. `vue.config.js` did not exist by default. Created it and it worked.
