### ISSUE TITLE
getting 404 error after changing assetsPublic path to '/manage/' instead of '/'

### ISSUE THREAD

**Issue by emostafa** [vuejs-templates/webpack#701]
i am building my first project using vue-cli and webpack template, i am using nginx reverse proxy to serve it on 8090/manage, and the cli is running on 4500. 

i supposed that editing  assetsPublicPath in config/index.js to be like this:
```js
dev: {
        env: require('./dev.env'),
        port: 4500,
        autoOpenBrowser: false,
        assetsSubDirectory: 'static',
        assetsPublicPath: '/manage/',
        proxyTable: {},
        // CSS Sourcemaps off by default because relative paths are "buggy"
        // with this option, according to the CSS-Loader README
       // (https://github.com/webpack/css-loader#sourcemaps)
       // In our experience, they generally work as expected,
       // just be aware of this issue when enabling this option.
       cssSourceMap: false
 }
```
but it gives an errors of 404 and "Cannot GET /manage"
i even tried change other values in build/dev-server.js but nothing seemed to work. any clues ?

**Comment by LinusBorg** [comment]
Since this is already being discussed on the forum, I will close this:

https://forum.vuejs.org/t/using-vue-cli-webpack-template-how-to-change-publicpath-correctly/10485
