### ISSUE TITLE
Run devserver in https

### ISSUE THREAD

**Issue by justtestbed** [vuejs-templates/webpack#715]
How can I set https property of the DevServer to true?

**Comment by LinusBorg** [comment]
This template doesn't use webpack-dev-server, it uses a custom express server with webpack-dev-middleware.

So you have to enable https in that express server.

The code of that server is found in `/build/dev-server.js`

A tutorial about how to use HTTPs with express can be found here:

http://blog.mgechev.com/2014/02/19/create-https-tls-ssl-application-with-express-nodejs/

Further questions should be asked on our forum @ forum.vuejs.org
