### ISSUE TITLE
Styles are ignored in .vue files from node_modules

### ISSUE THREAD

**Issue by prograhammer** [vuejs-templates/webpack#717]
When importing vue components from vendors (.vue files residing in node_modules) the styles from style blocks in those .vue files are not being processed by vue-loader. They don't appear anywhere after building. The styles don't appear in the browser when running the dev server `npm run dev`. And they don't show up anywhere in any build output in */dist* from `npm run build`. You can quickly try it yourself and see it doesn't work.

I simply ran the vue-cli on this template and imported the vendor component in the App.vue. I didn't touch any webpack config or anything. Am I misunderstanding something about how vue-loader works?

**Comment by LinusBorg** [comment]
> You can quickly try it yourself and see it doesn't work.

Please at least name the package that you loaded the `.vue` file in question from, as well as the file itself.

**Comment by prograhammer** [comment]
Oh stupid me, I was extracting the css in the package I imported, so of course it wasn't there. **However**, the css is stuck in the vender.[hash].js file and not being extracted in the parent project (while the other css is being correctly extracted into app.[hash].css) when I build.

**Comment by prograhammer** [comment]
^ this is probably more ideal though, when thinking about caching. Since likely vendor styles would change less and you don't want that included in your app.[hash].css file which will get rehashed more often.

**Comment by BartCorremans** [comment]
In my setup I changed the minChunks regex to the following (less optional):

`/\.(js|vue|css|less)$/`

This works pretty well for extracting CSS both from third-party .vue files and from standalone CSS files that you require().

**Comment by LinusBorg** [comment]
Seems like this is resolved and can be closed, great!
