### ISSUE TITLE
Can't manage to use .env variables. 

### ISSUE THREAD

**Issue by dagman** [vuejs-templates/webpack#722]
1. yarn add `dotenv-webpack`
2. created `.env` file in root directory
3. added `API_SECRET_KEY`(i have already deprecated it so can expose it for issue)
4. added initialization code in `/config/index.js`
```

const path = require('path')
const Dotenv = require('dotenv-webpack')

module.exports = {
...
...
...
  plugins: [
    new Dotenv({ path: path.join(process.cwd(), '.env') })
  ]
}
```
5. logged into console `process.env.API_SECRET_KEY` inside `App.vue` file

so i went through above steps like [dotenv-webpack](https://www.npmjs.com/package/dotenv-webpack) suggests
but got `undefined` logged into console.

How can i manage it to work correctly? How do you manage variable that you don't want to expose in this template?

i have created a [repo](https://github.com/dagman/vue-weather) to reproduce issue.

**Comment by LinusBorg** [comment]
`/config/index.js` is not the webpack config, it's just a small config file for paremters *used in the webpack config*.

The webpack config can be found in the /build directory, and this is where you have to add this plugin.

**Comment by coolguy1990** [comment]
I did the following modifications to ```config/prod.env.js``` to make dotenv work...

```
require('dotenv').config();
let _ = require('lodash');
let env = {};

env = _(process.env)
  .mapValues(value => `"${value}"`)
  .value();

module.exports = env;
```

Although this approach retrieves all the ENV data from the server.. so we simply prefixed all our ENV fields with some prefix like ```XY_``` and simply filtered them out like

```
env = _(process.env)
   .pickBy( (value, key) => key.match(/^XY_/))
  .mapKeys((value, key) => key.substring('XY_'.length))
  .mapValues(value => `"${value}"`)
  .value();
```

Doesn't look pretty but it works for us. :)
