### ISSUE TITLE
What about this packaging warning?

### ISSUE THREAD

**Issue by FrontEnd-GuoXi** [vuejs-templates/webpack#723]
![image](https://cloud.githubusercontent.com/assets/21993234/26337616/82ca10fa-3fac-11e7-862d-a88204658846.png)
How to solve?

**Comment by heinzdmx** [comment]
You are referencing two icon's with different casing `doubanIcon.png` and `doubanicon.png`
Most filesystems on Linux and Mac are case sensitive so this would two different files. On Windows the filesystem is not case sensitive so this could only be 1 file.
To fix it be consistent in the your casing when defining the paths to a filename.
