### ISSUE TITLE
Error with node 8.0.0 - Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by ellipticaldoor** [vuejs-templates/webpack#731]
I updated to node v8.0.0 with npm 5.0.1 and I'm getting the following error, it appears on the console after 10 seconds.
<img width="1052" alt="screen shot 2017-06-01 at 13 29 51" src="https://cloud.githubusercontent.com/assets/3449006/26679842/b059e08a-46ce-11e7-82d0-b44fdb2ff91e.png">

**Comment by oswaldomilet** [comment]
same here

**Comment by ellipticaldoor** [comment]
Sometimes the hot reload is not working or working very slow

**Comment by Christilut** [comment]
Same here
Node 8, npm 5.0.2

Starts fine, after about 10 seconds I get the HMR error:

`GET http://localhost:8080/__webpack_hmr net::ERR_INCOMPLETE_CHUNKED_ENCODING`

**Comment by nueko** [comment]
fixed with #739

**Comment by nguyendv** [comment]
How can I get the fixes into a existing project?

**Comment by oswaldofreitas** [comment]
@nguyendv just change build/dev-server.js:
```
var hotMiddleware = require('webpack-hot-middleware')(compiler, {
  log: () => { },
  heartbeat: 2000 // <== add this line
})
```

**Comment by nguyendv** [comment]
Great! Thanks!

**Comment by Matoo125** [comment]
I just fixed it with clearing cookies
