### ISSUE TITLE
Feature request - utilize CSS Purify in webpack template

### ISSUE THREAD

**Issue by focussing** [vuejs-templates/webpack#740]
This would be very helpful when using Bootstrap or Bulma. Significant reduction of final dist CSS file.
[https://github.com/purifycss/purifycss](https://github.com/purifycss/purifycss)

**Comment by MaxMilton** [comment]
See https://github.com/vuejs-templates/webpack/pull/743

**Comment by LinusBorg** [comment]
See comments in #743
