### ISSUE TITLE
Dev Build

### ISSUE THREAD

**Issue by mika76** [vuejs-templates/webpack#741]
Is there any way I could do a dev build? I am trying to run this within an existing aspnet mvc app and running this in dev in a node server does not help me, but running in the aspnet without vue debugging is challenging. So I would like to compile the build, but using the dev flag.

**Comment by LinusBorg** [comment]
I would change [this line](https://github.com/vuejs-templates/webpack/blob/master/template/build/build.js#L3) to:
```javascript
if (!process.env.NODE_ENV) {
  process.env.NODE_ENV = 'production'
}
```

Then you should simply be able to run
```
NODE_ENV=development node build/build.js

**Comment by mika76** [comment]
I'll give it a try, although I think I tried copying the build.js file and changing that like to be ```process.env.NODE_ENV = 'development'``` and that didn't seem to work properly...
