### ISSUE TITLE
is there a ci/test on the repo?

### ISSUE THREAD

**Issue by Aladdin-ADD** [vuejs-templates/webpack#748]

**Comment by LinusBorg** [comment]
this repository uses CircleCI, yes.

The projects created *from* this template don't have any CI solution preconfigured or anything, though.

**Comment by Aladdin-ADD** [comment]
thanks for your respond so quickly:(

I got an error running test on my Windows 10.
![image](https://user-images.githubusercontent.com/13050025/27264793-4d0c779c-54b9-11e7-8c3c-ea7b0fc8adce.png)

**Comment by Aladdin-ADD** [comment]
and seems contributors cannot see the test result for now. can we do something?

**Comment by sudo-suhas** [comment]
> I got an error running test on Windows 10.

This might have something to do with git `core.autocrlf` setting. Read more [here](https://help.github.com/articles/dealing-with-line-endings/)

**Comment by Aladdin-ADD** [comment]
fixed using `dos2unix test.sh`. thanks~
