### ISSUE TITLE
Add vue-router

### ISSUE THREAD

**Issue by rob-balfre** [vuejs-templates/webpack#75]
Can we add vue-router to this template please?  Seems like an unusual omission.

**Comment by chrisvfritz** [comment]
@rob-balfre We're currently working on a more modular build process, that will allow people to opt in or out of certain features, such as tests and eslint, when creating a new project. I think that would be a great time to add optional vue-router integration as well. 👍

**Comment by rob-balfre** [comment]
@chrisvfritz That sounds great.

**Comment by KevinNTH** [comment]
Hi,
As the vue-router is not integrated in the template yet, how can I manage to do this by myself ?
If you have some clues to give to me, it would be nice. Thanks !

**Comment by KevinNTH** [comment]
@chrisvfritz : Thanks a lot !!! Advanced exemple solves my problem !

**Comment by TheDutchCoder** [comment]
While on this topic (no need to open a new issue for this I think): it would be nice if the steps would also include modules like Vuex (Flux) or Revue (Redux) for state management, as well as Vue Resource.

Is there a list somewhere that contains what is planned for the modules? Maybe people could contribute there ;)

**Comment by KrishnaPG** [comment]
Not sure how to make the router work with this. Tried the example from the router documentation and it is throwing error `Unknown custom element: <router-link>` and `Unknown custom element: <router-view>`

![image](https://cloud.githubusercontent.com/assets/4610831/19376676/a378bc8c-91fd-11e6-86e5-e1ac7a1f2cc6.png)

Did like below:
````
var router = new VueRouter({
	history: false,
	root: '/',
	routes: [
		{ path: '/', component: Index },
		{ path: '/person', component: Person },
	]
});

var pageApp = new Vue({
	el: 'app',
	render: h => h(App),
	router: router,
});
````
**App.vue**
````
<template>
	<main class="container body">
		<div class="main_container">
			<tag-sidebar></tag-sidebar>
			<router-view></router-view>
			<tag-footer></tag-footer>
		</div>
	</main>
</template>
````
**Sidebar.vue**
````
<ul class="nav child_menu">
		<li><router-link to="/person">Person</router-link></li>
</ul>
````

How to make it work correctly?

**Comment by KrishnaPG** [comment]
The problem boils down to this. Would be great if someone could help.

I am getting the errors with the `vue-router` if I use `<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.1/vue.js"></script>` in the html page directly (and not use the `import Vue` inside main.js).

However, if I remove the CDN script tag and use rather use the `import Vue from 'vue'` inside the main.js then the same above code is working fine without problem.

To double check, I have compared the content from the CDN with the local node_module Vue content, and they are same. Loading order is also same.

Why is this behavior? How to take advantage of the CDN hosted vue in such cases?

**Comment by chrisvfritz** [comment]
@KrishnaPG Those are usage/support questions, while the issues are reserved solely for bug reports and feature requests. I recommend posting your question on either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue).

**Comment by kazupon** [comment]
Close (vie-router already included)
