### ISSUE TITLE
more maintainers?

### ISSUE THREAD

**Issue by Aladdin-ADD** [vuejs-templates/webpack#757]
do we need more maintainers?

**Comment by LinusBorg** [comment]
That Question needs a verb, at least.

**Comment by nickmessing** [comment]
@Aladdin-ADD, I wanted for long time to maintain a more advanced setup (jsx, prettier, vuex...) but I didn't have motivation, we can start it together if you want.

P.S. @LinusBorg, is there any chance to make it under `vuejs-templates` organisation?

**Comment by LinusBorg** [comment]
Hey, thanks for wanting to help out! 

First, let me start by saying sorry that we haven't added everything people wish to this template. It's always a task to balance approachability and complexity. 

That being said, if you want to start a more broad / sophisticated setup, that's fine. We can also accept it into this organization if it fits, i.e. It's different enough to this template so it's clear what use case the different templates address. 

So I can't promise anything yet, but if it fits, sure! 

We did the same for the pwa template recently.

**Comment by Aladdin-ADD** [comment]
there are so many developers use this template. so it is hard to meet all the needs.

+ can we give some more people a access to this repo? like @nickmessing 
+ for advanced features, it is a superset of the basic, I'm not sure  it is different enough.so there are two options:
a. we can create a new branch(naming like `advanced` or something);
b. if a. cannot be accepted, we can create a new fork, and add a linking on this repo. so if someone want advanced features, they can find the fork. this will also decrease the maintaining work on this repo.

**Comment by nickmessing** [comment]
@Aladdin-ADD, it's too irresponsible to give write access to some random people from internet. Maintaining community template for vue-cli is not a big deal, there was some idea that I had a while ago which Evan liked but I still didn't have enough time to work on it. Can you add me on gitter so maybe together we can do that?
