### ISSUE TITLE
HMR failing caused by html-webpack-plugin?

### ISSUE THREAD

**Issue by aimergenge** [vuejs-templates/webpack#764]
At first, I use `vue init webpack my-project` to init my project. HMR works well.
But after some days, I just see the HMR failing.
When I save the changes of some file, instead of hot replacing, the page just is reload.

I try to find out what causes this.

I see that page reloading caused the browser cancelled the request for ....hot-update.json, so the HMR failed.

There is a part of config in dev-server.js:
```js
compiler.plugin('compilation', function (compilation) {
  compilation.plugin('html-webpack-plugin-after-emit', function (data, cb) {
    hotMiddleware.publish({ action: 'reload' })
    cb()
  })
})
```
So this is  the reason. Each compilation will cause the `html-webpack-plugin-after-emit` event  triggered. So each time the page will be reload.
But why at the very start, the page will not be reload, that is to say, `html-webpack-plugin-after-emit` isn't triggered in every compilation.
I guess I do something causing the `html-webpack-plugin` executed once there are changes.

And, here is my project, you can clone it and `npm run dev` to see what problem is.
https://github.com/aimergenge/vue-cms

Sorry for my poor English, thank you very much.

**Comment by MaxMilton** [comment]
Try upgrading to: `"html-webpack-plugin": "^2.29.0"`

**Comment by aimergenge** [comment]
I updated as you say but it doesn't work still.
Thank you however

**Comment by LinusBorg** [comment]
You updated webpack to 3.0.0, but the html-webpack-plugin isn't fully compatible with that version yet, afaik.

That's why we didn't update the template yet.

**Comment by afontcu** [comment]
@aimergenge did downgrading work for you?

I upgraded to Webpack 3.0 and when I noticed issues related to HMR I ran into this issue and downgraded again to 2.6.1.

But HMR is still not working properly (reloads the whole page as happened to you) and just warning me in the console:

`[HMR] Update check failed: Error: Manifest request to /b1188c7fc17bb438d0f7.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange` in `handleError	@	process-update.js?e13e:122`.

I downgraded by removing `node_modules` directory, cleaning npm cache and installing again. 


Thanks!

**Comment by aimergenge** [comment]
The downgrading works for me.
Maybe there is something else blocking you.
You can open a new issue if you still can not solve the problem.

2017-07-04 23:46 GMT+08:00 Adrià Fontcuberta <notifications@github.com>:

**Comment by MaxMilton** [comment]
Make sure you keep `vue-loader` at version `^12.2.1` otherwise you'll continue to have HMR issues. I believe you can upgrade to v13 once vue 2.4 has been released.

**Comment by afontcu** [comment]
I downgrade `vue-loader` and now everything is working. Missed that change. Thanks :)
