### ISSUE TITLE
Getting files from local paths

### ISSUE THREAD

**Issue by wuaiwuai** [vuejs-templates/webpack#766]
Hey guys,

I have a directory `./src/posts/` with a few *.md files that i'd like to be able to perform a $http.get on. How can I move the posts directory to static when using `npm run dev` ?

I'm sure there are smarter ways to handle this, any feedback would be appreciated.

**Comment by nickmessing** [comment]
@wuaiwuai, why not keeping them in `static` folder in the first place?

**Comment by wuaiwuai** [comment]
I have tried putting some files in `static/posts/text.md` but the sources do not appear when running a local server.

![image](https://user-images.githubusercontent.com/2545142/27520647-ffc5b9c4-59dd-11e7-98b2-aeb8d37cbbdb.png)

Am I missing something?

**Comment by nickmessing** [comment]
If you put it in `static/posts/text.md` it should be accessible on `http://localhost:3000/posts/text.md`, you can see that [here](https://github.com/vuejs-templates/webpack/blob/d399afa403273862da2420881f01eba00aca47ae/template/build/dev-server.js#L64).

**Comment by wuaiwuai** [comment]
@nickmessing thank you for your quick responses,

I created a new project with `vue init webpack vue-webpack` and put in a test file at `static/posts/text.md`

![image](https://user-images.githubusercontent.com/2545142/27520749-194e38c4-59e0-11e7-915d-0fe8c2518203.png)

when running a local server, the .md file is not present at localhost:8080/posts/text.md. can anyone else confirm this?

**Comment by nickmessing** [comment]
Sorry, I was wrong, it should be `http://localhost:8080/static/posts/text.md` by default, you can find more information in [docs](https://github.com/vuejs-templates/webpack/blob/master/docs/static.md#real-static-assets).

**Comment by wuaiwuai** [comment]
@nickmessing this did the trick! Thank you for your help.
