### ISSUE TITLE
Integrate `google-fonts-webpack-plugin` into build process

### ISSUE THREAD

**Issue by ssc-hrep3** [vuejs-templates/webpack#769]
I'm currently trying to integrate static offline fonts into the Webpack build process. I found the nice library [`google-fonts-webpack-plugin`](https://github.com/gabiseabra/google-fonts-webpack-plugin) which provides all the font files and a single CSS file. I integrated it into the prod build like this:

```
  plugins: [
    // http://vuejs.github.io/vue-loader/en/workflow/production.html
    new webpack.DefinePlugin({
      'process.env': env
    }),
    new GoogleFontsPlugin({
      fonts: [
        { family: 'Roboto', variants: [ '300', '400', '400italic', '500' ] }
      ]
    }),
    new webpack.optimize.UglifyJsPlugin({
```

The resulting files are however not part of the built files. In the `dist/` folder, they appear as `fonts.css` and a directory `fonts/`, not even within the `static/` folder.

How can I hook this library into the regular CSS/font build process of `vue-webpack`, so that `fonts.css` ends up in the versioned CSS file and the style file in the regular directory?

**Comment by LinusBorg** [comment]
Please use forum.vuejs.org for support about how to use or extend the template for individual cases.
