### ISSUE TITLE
Unexpected token: punc

### ISSUE THREAD

**Issue by focussing** [vuejs-templates/webpack#770]
npm run build gives the following error:

ERROR in static/js/app.8fe2d0a4c905d085215f.js from UglifyJs
Unexpected token: punc ()) [static/js/app.8fe2d0a4c905d085215f.js:246,11]

However when I look into that app.8fe2d0a4c905d085215f.js over there: 
Line 246 is the one starting with data:()

```
/* harmony default export */ __webpack_exports__["default"] = ({
    data: () => ({
        items: [],
        errors: [],
        version: 0,
        recordChanged: -1,
        baseUrl: 'http://www.domain.com/db-sqlite.php/'
    }),

    methods: {
         .... 
```

The source code is like this:

```
export default {
    data: () => ({
        items: [],
        errors: [],
        version: 0,
        recordChanged: -1,
        baseUrl: 'http://www.domain.com/db-sqlite.php/'
    }),

    methods: {

```

Tested with node versions 4.6.2 and 8.1.0, npm version 5.0.3

**Comment by LinusBorg** [comment]
your project appearantly didn't transpile the arrow functions to  ES5, and uglify can't work with ES6.

Please check if you have a `.babelrc` file in your root directory, like this one:

https://github.com/vuejs-templates/webpack/blob/master/template/.babelrc

**Comment by focussing** [comment]
that did the job. my OwnCloud sync did not copy hidden files... so .babelrc file amongst others where not there... 

THANKS!
