### ISSUE TITLE
Webpack hmr being included in production

### ISSUE THREAD

**Issue by invmatt** [vuejs-templates/webpack#771]
When running `npm run build` calls to __webpack.hmr are still being made:

`[Tue Jun 27 2017 16:22:48 GMT+0100 (BST)] "GET /__webpack_hmr" Error (404): "Not found"`

Nothing has been modified from the source provided. To replicate simply run the build and launch a server (using http-server) and watch the terminal output.

**Comment by LinusBorg** [comment]
I can't reproduce this.

<img width="887" alt="bildschirmfoto 2017-06-28 um 00 16 39" src="https://user-images.githubusercontent.com/1444526/27612470-f3a9c440-5b96-11e7-90da-548c7bfb74f2.png">

**Comment by LinusBorg** [comment]
closed for inactivity
