### ISSUE TITLE
bundleAnalyzerReport: process.env.npm_config_report causing trouble

### ISSUE THREAD

**Issue by fyyyyy** [vuejs-templates/webpack#779]
I  created the vue-webpack project 3 weeks ago. Suddenly after a new npm package install, the build and dev server would fail with a syntax error.

The generated app.js code looked like this. Somehow the `'` are missing from the source code
```js
bundleAnalyzerReport: __webpack_require__.i({"NODE_ENV":"production","api":__webpack_require__.i({"common":__webpack_require__.i({"base":http://someurl.com:30016,"path":}),"fmm":__webpack_require__.i({"base":http://someurl.com:30018,"path":})})}).npm_config_report
```

I tried to wipe node_modules, do a fresh npm install but it didnt help. I generated a new project form this template and had no issues there.

If i remove this line from config/index.js then everything works fine
`bundleAnalyzerReport: process.env.npm_config_report`

**Comment by LinusBorg** [comment]
It's hard to say what the reason for that would be if all information you can provide is that it happened "after a enw npm package install"... :(
