### ISSUE TITLE
npm run build working but npm run dev is not 

### ISSUE THREAD

**Issue by billcolumbia** [vuejs-templates/webpack#78]
So I'm trying to use vue-cli to work with our PHP app (old CakePHP 2.6 sadly). I've got it so that it builds with `npm run build` and then injects the `<script>` tag into our main template file `default.ctp`, sourcing a `default-source.ctp` just fine. However, `npm run dev` seems to emit the updated JS, but _does not_ update the `default.ctp` file. It also does not reload the page.

I'm not sure where the missing link is with this. I can link to some files if you'd like to see the setup.

[I read the docs thoroughly](http://vuejs-templates.github.io/webpack/backend.html), but it seems that the `config` info set in these docs only addresses `build` though. Maybe that's the issue?

**Comment by billcolumbia** [comment]
The other thing is I'm not sure how the dev server works. It emits these new files but where do they go? They seem to be some runtime reference or something and not actually saved to the file system. Maybe the browser isn't connecting to webpack to get those modified sources?

**Comment by yyx990803** [comment]
In dev mode, no file is written to disk, everything is served directly from memory by the dev server. You should use the dev server and proxy requests to your PHP app during development.

**Comment by billcolumbia** [comment]
Ok cool that's what seemed like was happening. Here's the config.js - I am proxying all requests to it as far as I can tell and have tested:

App Structure:
```
- vue
  - build
  - src
  - test
  - config.js
- View
  - Layouts
    - default-source.ctp
    - default.ctp
- webroot
```

```js
// see http://vuejs-templates.github.io/webpack for documentation.
var path = require('path')

module.exports = {
  build: {
    index: path.resolve(__dirname, '../View/Layouts/default.ctp'),
    source: path.resolve(__dirname, '../View/Layouts/default-source.ctp'),
    assetsRoot: path.resolve(__dirname, '../webroot'),
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    productionSourceMap: true
  },
  dev: {
    port: 3000,
    proxyTable: {
      '/': {
        target: 'http://directory.dev',
        changeOrigin: true
      }
    }
  }
}
```

**Comment by yyx990803** [comment]
You should not be proxying everything - the proxys have highest priority and this would render your dev server useless. Only proxy API requests.

**Comment by billcolumbia** [comment]
Oh alright. I just get the index.html file in the vue directory when I hit localhost if I just proxy the API. So in this case do I not dev with localhost?

**Comment by yyx990803** [comment]
You do... dev server serves your frontend (index.html and static assets) at localhost, and it proxies API requests to your PHP app (which can be remote or local)

**Comment by billcolumbia** [comment]
Ok so the issue I'm having then is the `default.ctp` has PHP in it that needs to be rendered, so the dev server can't render that. But this is the same as how Laravel or Rails would do it. So that's why I get confused, as I have followed the directions in http://vuejs-templates.github.io/webpack/backend.html but still get output with PHP tags - how does webpack dev server account for the PHP needing to be rendered on the app? I've now set my config like this: 

```
js
// see http://vuejs-templates.github.io/webpack for documentation.
var path = require('path')

module.exports = {
  build: {
    index: path.resolve(__dirname, '../View/Layouts/default.ctp'),
    assetsRoot: path.resolve(__dirname, '../webroot'),
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    productionSourceMap: true
  },
  dev: {
    port: 3000,
    proxyTable: {
      '/api': {
        target: 'http://directory.dev',
        changeOrigin: true
      }
    }
  }
}
```

**Comment by yyx990803** [comment]
The config assumes your HTML file is pure. In your case you may need to instead proxy all static assets to the dev server on your PHP end!

**Comment by billcolumbia** [comment]
Ah ha crazy stuff marrying an old back end to a modern build system. Looking into this. Thanks so much :) I assumed it might be an overlook in docs - sorry for the bother.
