### ISSUE TITLE
Add sonar to template as opt-in?

### ISSUE THREAD

**Issue by sudo-suhas** [vuejs-templates/webpack#783]
sonar was added to the JS foundation - https://js.foundation/announcements/2017/06/22/sonar-js-foundation-welcomes-newest-project
sonar homepage - https://sonarwhal.com/

Do you think it will be a good idea to add sonar to the project as an opt-in similar to eslint? It includes [rules](https://sonarwhal.com/docs/user-guide/rules/index.html) for pwa which could be useful for vuejs-templates/pwa.
This however requires node 8.

**Comment by LinusBorg** [comment]
I don't think we will add it to this template - maybe it makes sense as a preset in vue-cli (https://github.com/vuejs/vue-cli/issues/589)
