### ISSUE TITLE
How can i update zhe webpack-template in my vue-cli?

### ISSUE THREAD

**Issue by zhuxiao2004** [vuejs-templates/webpack#786]
whenever  i run 'vue init webpack xxx', i can always get the newest template？ or should I do something to get the  newest version ?

**Comment by nickmessing** [comment]
@zhuxiao2004, it always gets latest template from github

**Comment by zhuxiao2004** [comment]
You means when I run 'vue init webpack xxx'  ,the npm download zhe latest template from github at the same time？

**Comment by nickmessing** [comment]
@zhuxiao2004, yes

**Comment by zhuxiao2004** [comment]
Thank youso much !
