### ISSUE TITLE
hmr not work when used in vuex

### ISSUE THREAD

**Issue by MorisHarA** [vuejs-templates/webpack#787]
https://github.com/MorisHarA/app

i just config by vuex official document

**Comment by LinusBorg** [comment]
https://github.com/MorisHarA/app/blob/master/src/store/index.js#L28

I think you have to provide all module paths, inthat array here...

**Comment by LinusBorg** [comment]
Hi there!

I close this issue because of inactivity. If you want to follow up on this issue, please open a new one, and provide the necessary information (a working reproduction etc.) in that issue.
