### ISSUE TITLE
"extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by changchengqin** [vuejs-templates/webpack#794]
when I debug file "build/build.js" in vscode

got this error:
![image](https://user-images.githubusercontent.com/3336443/28102184-49637290-6700-11e7-85bc-a0139db59f39.png)

the final build results is wrong:
![image](https://user-images.githubusercontent.com/3336443/28102297-e4fa8f36-6700-11e7-8aee-27b5996a7718.png)

the correct build results would be this:
![image](https://user-images.githubusercontent.com/3336443/28102360-45c5f7b0-6701-11e7-87ef-a2e6f25d0df7.png)

here is my project git repo
https://github.com/changchengqin/my-webpack-demo.git

**Comment by LinusBorg** [comment]
can'T run this right now, but have you tried setting the cwd properkly in launch.json?
```
"cwd": "${workspaceRoot}"
```

**Comment by changchengqin** [comment]
@LinusBorg 
I am sure,my project's launch.json have a correctly setting.
I guess It's vscode's bug,because when I type
> node --inspect build/build.js
in terminal under my workspace,everything is all right.
It's just a problem in the debug mode of vscode.

**Comment by LinusBorg** [comment]
Since we can't do much about this I will close.
