### ISSUE TITLE
Reference CSS from index.html outside of the static folder? 

### ISSUE THREAD

**Issue by dalanmiller** [vuejs-templates/webpack#800]
I'm totally lost on how to reference CSS files within the /src/assets folder. Why is the path not serving at `/assets/app.css`?

**Comment by heinzdmx** [comment]
As is documented in the [Vue docs ](https://vuejs-templates.github.io/webpack/static.html) you use the assets the following way (btw they are not under src) 

Asset Resolving Rules

- Relative
>  URLs, e.g. `./assets/logo.png` will be interpreted as a module dependency. They will be replaced with an auto-generated URL based on your Webpack output configuration.
- Non-prefixed
> URLs, e.g. `assets/logo.png` will be treated the same as the relative URLs and translated into `./assets/logo.png`.
- URLs
> prefixed with ~ are treated as a module request, similar to `require('some-module/image.png')`. You need to use this prefix if you want to leverage Webpack's module resolving configurations. For example if you have a resolve alias for assets, you need to use `<img src="~assets/logo.png">` to ensure that alias is respected.
- Root-relative URLs
> e.g. `/assets/logo.png` are not processed at all.
