### ISSUE TITLE
How do I generate extra.env.js file from extra.env.js.dist

### ISSUE THREAD

**Issue by bilougit** [vuejs-templates/webpack#808]
The point is to be able to store the same environment variables with their values that depend on the server the application is running from.

To access my application from my development server whose url looks like `http://hostname.com/myapplication/`, so I need to set `BASE_URL = '/myapplication/'`. My collegue needs to set it to `BASE_URL = '/dummyapp/`, and another collegue does not need it at all. I think you got the idea.

I created `config/extra.env.js.dist`:
```javascript
module.exports = {
    BASE_URL: ''
}
```

And I have created a script that looks for files that end with `.dist` to copy them.

Is there a plugin or something that already does this.

**Comment by LinusBorg** [comment]
Not that I know of. you might be better off asking on forum.vuejs.org or chat.vuejs.org - this question is only tangetially related to this template/repository.
