### ISSUE TITLE
subdomains?

### ISSUE THREAD

**Issue by abbrechen** [vuejs-templates/webpack#810]
Hi,

how can I manage subdomains (subdomain.awesomewebsite.com)? VueJs can't handle these and the webpack dev server [docs refer to the publicPath](http://webpack.github.io/docs/webpack-dev-server.html#the-historyapifallback-option). But the publicPath of this template looks way different.

------

Node: 6.9.5
npm: 3.10.10
OS: Debian 7.11

**Comment by LinusBorg** [comment]
> how can I manage subdomains (subdomain.awesomewebsite.com)? 

Can you explain what you mean by "manage" in this conext?

**Comment by abbrechen** [comment]
Oh, yeah. Just to write in my config the name and path of subdomains. No dashboard control.
