### ISSUE TITLE
[HMR] Update check failed

### ISSUE THREAD

**Issue by HauntedSmores** [vuejs-templates/webpack#813]
[HMR] Update check failed: Error: Manifest request to /0ca55ad0f6c9c867e01c.hot-update.json timed out. at XMLHttpRequest.request.onreadystatechange (http://localhost:8080/app.js:39:22)

From what I can tell, this happened after running `npm update`. From looking at other github issues such as this one: https://github.com/webpack/webpack-dev-middleware/issues/68

it seems like its an issue with the path config in webpack but this templates webpack config is almost too modularized so its hard to trace where its being set from.

EDIT: Found where the output path for the middleware is being set and traced the variable and it seems to be set properly. I also tried replacing my build and config folders with fresh ones from the repo. Still getting the issue.

**Comment by Piterden** [comment]
Have you tried rebuild?

**Comment by HauntedSmores** [comment]
@Piterden Closing this. I fixed it by replacing the files in my build and config folders with the ones in the template repo. Something must have gotten messed up along my development path.

**Comment by HauntedSmores** [comment]
@Piterden Okay that didnt actually work. Looks like the problem is intermittent. What did you mean by rebuild?

**Comment by piehei** [comment]
I'm having the same issue.

**Comment by HauntedSmores** [comment]
@Piterden `npm rebuild` didnt work unfortunately

**Comment by piehei** [comment]
This https://github.com/vuejs-templates/webpack/issues/751#issuecomment-309955295 fixed the issue for me too.

**Comment by HauntedSmores** [comment]
@piehei Hey so thanks for finding that comment, that works for me too. But Im really confused as too. I didnt realize webpack 3 was out, so when I ran npm-check-updates I upgraded.

Still curious about how that broke and we dont need those lines of code anymore

**Comment by wqjiao** [comment]
What you solved this question？

[HMR] Update failed: Error: Manifest request to 169319f72cbe014b6608.hot-update.json failed.
    at XMLHttpRequest.request.onreadystatechange (http://127.0.0.1:8081/app.js:50:22)

**Comment by wqjiao** [comment]
@HauntedSmores What you solved this question？

[HMR] Update failed: Error: Manifest request to 169319f72cbe014b6608.hot-update.json failed.
at XMLHttpRequest.request.onreadystatechange (http://127.0.0.1:8081/app.js:50:22)****
