### ISSUE TITLE
Place of auto injected files.

### ISSUE THREAD

**Issue by vad11** [vuejs-templates/webpack#818]
I define place of auto injected files before included  my.js file
but in index.html dist file I have different order of included files.
What wrong, can you help solve this.   (I run plugin in js file and I must run vue files before my plugin)

src file
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My APP</title>
  </head>
  <body>
    <div id="app"></div>
    <!-- built files will be auto injected -->
    <script src="/static/my.js" ></script>
  </body>
</html>
```

dist file 

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My APP</title>
  </head>
  <body>
    <div id="app"></div>
  
    <script src="/static/my.js" ></script>
    <!--auto injected files -->

  </body>
</html>
```

**Comment by LinusBorg** [comment]
> I define place of auto injected files before included my.js file

You think that this is a placeholder defining where your scripts are injected?:
```
<!-- built files will be auto injected -->
```
It isn't, that's not how it works. This HTML comment is just a hint, it has no meaning to `html-webpack-plugin`, which will simply place them at the very end of the body element.

**Comment by vad11** [comment]
Yes, I try inject to <head> 
```
//inject: true,
inject: 'head',
```
But vue example of webpack stop work for production.

Can I define in any way place to injected files ?

**Comment by LinusBorg** [comment]
No. Is there a specific reason that you want this script in a separate tag instead of adding it to your app' code? You could, forg example, add it right after you created your Vue instance:
```javascript
// main.js

// ... stuff

new Vue({
  // ...
})

import '../static/my.js'
```
