### ISSUE TITLE
Upgrade to webpack 3.4

### ISSUE THREAD

**Issue by joshikeerti** [vuejs-templates/webpack#823]
Now that webpack 3.4 is releases, is there a plan to upgrade to the new version?

**Comment by lucasleelz** [comment]
I am looking forward to `webpack 3`

**Comment by MaxMilton** [comment]
Dup #751 

This template doesn't support webpack 3 yet.

You can track Webpack 3 status on https://github.com/vuejs-templates/webpack/issues/751
