### ISSUE TITLE
In the vue file, the introduction of CSS by @import does not perform autoprefixer, how does it change

### ISSUE THREAD

**Issue by 450611** [vuejs-templates/webpack#825]
In the vue file, the introduction of CSS by @import does not perform autoprefixer, how does it change

#544 Like this 

I used the code by the first picture, but I still didn't solve my problem

**Comment by yoyo837** [comment]
Using # 544's modifications, it works fine.
Can you create a repo to show your question?

**Comment by LinusBorg** [comment]
Fixed in v 1.2.0 as of today
