### ISSUE TITLE
File loader inside of webpack template, how is it used?

### ISSUE THREAD

**Issue by khanharis87** [vuejs-templates/webpack#827]
what is the use of file loader in the webpack-template? I do not see it being used any where?
and is it responsibilty of url loader to compile fonts and images at a given folder? Just trying understand because my fonts are not being bundled and sass, style, css loaders are throwing errors of Module not found!

```
/** webpack baseconfig.js **/
module: {
      {
        test: /\.(png|jpe?g|gif)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
}
```

**Comment by LinusBorg** [comment]
You might want to read this guide on the webpack page:

https://webpack.js.org/guides/asset-management/
