### ISSUE TITLE
Unexpected token < when serving dist folder

### ISSUE THREAD

**Issue by nimonian** [vuejs-templates/webpack#828]
I saw [here](https://github.com/vuejs-templates/webpack/issues/768) a user who was having a similar issue, but his fix didn't work for me.

Here's what I did:

1. Download the latest template
2. Add the line `<script src="node_modules/abbrev/abbrev.js"></script>` to index.html
3. Run `npm run dev` and everything is fine on localhost:8080
4. Run `npm run build` and then `firebase serve` (I have initialised firebase) and, when accessing the dist version over localhost:5000 I get `Uncaught SyntaxError: Unexpected token <` in the console.

I've found a few others with similar problems but none of their fixes work for me. Hopefully, since all I have done is download a fresh template and include a simple javascript file, someone will be able to reproduce and maybe identify the problem.

**Comment by LinusBorg** [comment]
You are trying to load a commonjs module meant to be used in node or webpack directly into the browser. That will not work.
