### ISSUE TITLE
problem including third party css

### ISSUE THREAD

**Issue by collapsarzhang** [vuejs-templates/webpack#83]
I have tried doing `require('css-loader!./assets/css/bootstrap.css')` in `main.js`.
The bootstrap is there in the `app.js` (output of webpack), but styles do not get applied to any components.

any help? I must be missing something.

**Comment by collapsarzhang** [comment]
I thought it's due to ordering, so I did a separate entry for vendors and require bootstrap inside vendors.js.
But it's still not working, again, I can see bootstrap inside vendors.js

**Comment by Grafikart** [comment]
Basically this template is not configured to import CSS outside of .vue component. 

You can edit config to add your custom loader 

```
      {
        test: /\.css$/,
        loaders: ['style', 'css']
      },
```

Someone is working on this apparently :) https://github.com/vuejs-templates/webpack/pull/81

**Comment by collapsarzhang** [comment]
thanks @Grafikart, your pr works perfectly
