### ISSUE TITLE
Assets Public Path for build is set to '/', why not './' ?

### ISSUE THREAD

**Issue by verveysteven** [vuejs-templates/webpack#832]
Hi,

In the configuration, the AssetPublicPath for the build is set to '/'.

I got a directory on a IIS server where I publish all my app in subfolders.
Because of the '/' configuration, when I build and copy it in a subfolder all assets are not found.

For example, i put my built result in http://myserv/projects/myapp/static/js/manifest.add4406db34decf2ea44.js
And my website is at 
http://myserv/projects
All links like
/static/js/manifest.add4406db34decf2ea44.js
Will be search in 
http://myserv/projects/static/js/manifest.add4406db34decf2ea44.js
Instead of
http://myserv/projects/myapp/static/js/manifest.add4406db34decf2ea44.js

So i wonder why the AssetPublicPath is not set to './' for the build config, is there a reason ?

**Comment by myst729** [comment]
You're right, `'./'` works for the case.

The other day I had a short chat with Evan about this. But I can't remember why I didn't make a PR. Maybe you could do it.
