### ISSUE TITLE
How to resolve glob pattern?

### ISSUE THREAD

**Issue by adi518** [vuejs-templates/webpack#838]
My Scss: `@import 'components/*.*';`

I tried to configure [`import-glob`](https://www.npmjs.com/package/import-glob), but probably incorrectly:
```
rules: [
      {
        test: /\.scss$/,
        enforce: 'pre',
        loader: 'import-glob'
      },...
]
```

Edit: omit the above, I need to configure `vue-loader` to handle this. Suspecting it's in `config/utils.js`.

**Comment by chasegiunta** [comment]
@adi518 did you ever figure this out? I'm having a heck of a time. The vue-loader & webpack template docs are out of date, as far as webpack config goes, and I'm having no luck.

**Comment by adi518** [comment]
I'm afraid not. When you come to think of it though, if you make an SPA, you should rarely arrive at a point where you need to import CSS, not to mention going as far as glob-import the stuff. I only needed it to import some of my legacy code, which will be re-factored into something like `styled-components` eventually. Never meant to use it permanently. Despite that, I have more experience with the Vue-Webpack template now so I'll try to make it work, perhaps this weekend.

**Comment by chasegiunta** [comment]
@adi518 yeah this was mainly to be used for importing some global app-wide styles.

**Comment by adi518** [comment]
For the time being, just import it the boring way. I'll post here if I get it to work, or if you manage yourself, please share. 👍

**Comment by emdahlstrom** [comment]
Hi! @adi518 @chasegiunta did you guys figure this out? I'm also working with a big legacy sass setup that makes importing individual files cumbersome.

**Comment by S0yKaf** [comment]
I would also need to figure this out for importing plugins inside a folder like so:
```javascript
import * as plugins from 'plugins/**/*.vue';
```

The idea is, all you need to do is drop your plugin (which are vue components) inside the plugins folder and have vue load them all up as global components.

**Comment by tybruffy** [comment]
I think I have this working using [import-glob-loader](https://github.com/Aintaer/import-glob-loader).  I updated `build/vue-loader.conf.js` to include the following above the `loaders:` object.  
```
preLoaders: {
  css: 'import-glob-loader',
  scss: 'import-glob-loader',
},
```

The other caveat is that import-glob-loader doesn't like aliases.  I couldn't get it to work with any of my webpack aliases, but if i use the real path (starting after the `src` directory) it works like so:

```
  @import 'assets/styles/utilities/**/*.scss';
  @import 'assets/styles/animations/**/*.css';
```
