### ISSUE TITLE
dev-server not refreshing

### ISSUE THREAD

**Issue by idoooooo** [vuejs-templates/webpack#839]
If anyone encounter dev-server is not refresh the browser after make any changes in source code.
here the workaround:

(webpack: 3.4.1)

update:
file: build/dev-server.js

var devMiddleware = require('webpack-dev-middleware')(compiler, {
    publicPath: webpackConfig.output.publicPath,
    quiet: true,
    // add this options
    watchOptions: {
        aggregateTimeout: 300,
        poll: 1000
    }
})

**Comment by benjaminpwarren** [comment]
That had no effect for me.

**Comment by dduenker** [comment]
Nice, this works perfectly for me. I wondered, if i had somehow broken something, as it suddenly stopped working.
