### ISSUE TITLE
What is the best practice to build for QA environment instead of Production environment?

### ISSUE THREAD

**Issue by sutra** [vuejs-templates/webpack#840]
Before pushing the changes to production environment, we should have a QA environment for the test team to have necessary tests.

And in QA environment we should call the APIs for QA environment instead of Production environment,
for example: https://api.qa.example.com for QA environment, and https://api.example.com for Production environment.

So, I have to configure different API base URL for Prod and QA. As mentioned in the document [Environment Variables](http://vuejs-templates.github.io/webpack/env.html),
I can set the variables in `config/prod.env.js`, but where should I put the configurations for QA environment?

**Comment by sutra** [comment]
Seems I found the answer, just use the `config/test.env.js` and change one line in `build/build.js`, and use `cross-env NODE_ENV=testing npm run build` instead of `nom run build` to build for QA environment for testing:

diff --git a/build/build.js b/build/build.js
index 6b8add1..04087fc 100644
--- a/build/build.js
+++ b/build/build.js
@@ -1,6 +1,6 @@
 require('./check-versions')()
 
-process.env.NODE_ENV = 'production'
+process.env.NODE_ENV = process.env.NODE_ENV || 'production'
 
 var ora = require('ora')
 var rm = require('rimraf')
diff --git a/config/test.env.js b/config/test.env.js
index 89f90de..5638b9c 100644
--- a/config/test.env.js
+++ b/config/test.env.js
@@ -2,5 +2,7 @@ var merge = require('webpack-merge')
 var devEnv = require('./dev.env')
 
 module.exports = merge(devEnv, {
-  NODE_ENV: '"testing"'
+  NODE_ENV: '"testing"',
+  ROUTER_BASE: '"/"',
+  BASE_API: '"https://api.qa.example.com"'
 })

**Comment by kgrosvenor** [comment]
Does this work for webpack 3?
