### ISSUE TITLE
About font-size in this template.

### ISSUE THREAD

**Issue by hezhongfeng** [vuejs-templates/webpack#841]
I add this code in template `<div style="font-size: 16px;">年后萨达十大框架阿萨德</div>`,like this:
```
    <img src="./assets/logo.png">
    <div style="font-size: 16px;">年后萨达十大框架阿萨德</div>
    <router-view></router-view>
```
I use the same font-size(16px),but the result is [different](https://codepen.io/hezf/pen/RZKYEZ).
the code pen's font is large than in this template.
Do you know why?
![image](https://user-images.githubusercontent.com/12163050/29016097-872a7bcc-7b83-11e7-98c7-ac899e021c88.png)

Also with english.
 
![image](https://user-images.githubusercontent.com/12163050/29016221-2cecd42e-7b84-11e7-801b-c19221541d61.png)

**Comment by hezhongfeng** [comment]
Anybody know why?

**Comment by hezhongfeng** [comment]
@LinusBorg 
@myst729

**Comment by MaxMilton** [comment]
General support questions are better suited to the forum: https://forum.vuejs.org

To find out what CSS rules are applied to an element you can use Chrome Devtools. Right click the element and select `Inspect`. In the `Elements` tab on the right select the `Computed` panel. That area shows you all the rules applied. Check in both places and find out what's different.

**Comment by hezhongfeng** [comment]
@MaxMilton 
thank you, I Check in both places~
![](https://sfault-image.b0.upaiyun.com/112/968/1129689229-598d7987131b7_articlex)
