### ISSUE TITLE
Is it possible to run that pack without an HTTP server?

### ISSUE THREAD

**Issue by iharsuvorau** [vuejs-templates/webpack#847]
During the `npm run build` there is:

```
Tip: built files are meant to be served over an HTTP server.
Opening index.html over file:// won't work.
```

Is it possible just to bundle static files and serve them alone with `index.html` without an HTTP server?

**Comment by MaxMilton** [comment]
General support questions are probably better suited for the vue forum: https://forum.vuejs.org/c/help

When you post on the forum be sure to include more information about what you're trying to do, where are you trying to serve the files from? A local system? Electron? Anything else will require at least some type of HTTP server.

**Comment by LinusBorg** [comment]
it should work well if you turn the assetsRootPath in config/ into a relative path.
