### ISSUE TITLE
Support for Cordova?

### ISSUE THREAD

**Issue by nickm123** [vuejs-templates/webpack#848]
How would I go about getting this awesome template to work with Cordova? I'm trying to use the same code base to build both a web and a mobile application for iOs and Android.

At a first glance I might get away with writing separate index.html and main.js files.

[Cordova + Vue guide](https://coligo.io/building-a-mobile-app-with-cordova-vuejs/)

**Comment by asselin** [comment]
@nickm123 I have a Cordova template for Vue that I put together for a few internal projects for my company here: https://github.com/BlueOakJS/vue-cordova-template

Interested in collaborating?

**Comment by LinusBorg** [comment]
This template will not add cordova support.

So this question might be better asked on our forums or chat:

* forum.vuejs.org
* chat.vuejs.org
