### ISSUE TITLE
How to exclude vue.js lib from production build.

### ISSUE THREAD

**Issue by tmjaga** [vuejs-templates/webpack#849]
Hi,

In our project, we plan to include vue.js via <script> tag manually.
Is it possible to exclude vue.js lib (module) from production build?
In other words do not include vue.js source in vendor.js and/or app.js files.

Thanks in advance.

**Comment by myst729** [comment]
I use [webpack-cdn-plugin](https://www.npmjs.com/package/webpack-cdn-plugin) in my project to exclude libs from the bundle.

**Comment by LinusBorg** [comment]
https://webpack.js.org/configuration/externals/
