### ISSUE TITLE
Feature : Autoprefixer

### ISSUE THREAD

**Issue by Grafikart** [vuejs-templates/webpack#85]
Since this template is able to load CSS I was wondering if you would be interested into adding autoprefixer.

- PostCSS loader will be used
- browser support would be set using config.js file
- it will be added using `cssLoaders()`

I can do a PR if you are interested.

**Comment by yyx990803** [comment]
vue-loader actually already does autoprefixing for component CSS: http://vuejs.github.io/vue-loader/features/postcss.html

But yeah it doesn't get applied to non-component CSS. But I like your proposal, we can turn off vue-loader's own stuff and centralize it inside `cssLoaders()` and `config.js`.

**Comment by Grafikart** [comment]
Ok I'll work on it tomorrow. I'll close this issue when the PR is submitted

**Comment by shentao** [comment]
@Grafikart how is it going? Just stumbled on this problem myself.

**Comment by Grafikart** [comment]
I did this feature for a project but I didn't add this to the template. Is there a way to test a local template @yyx990803 ? I don't want to make a broken PR :)

**Comment by chrisvfritz** [comment]
@Grafikart I recommend forking the template, then you can run `vue init Grafikart/webpack name-of-test-project` to generate a new project using your fork.

**Comment by chrisvfritz** [comment]
@Grafikart Just pinging on this. Anything we can do to help?

**Comment by Grafikart** [comment]
No it's fine I just did the missing commits

**Comment by guidobouman** [comment]
You can actually import an external stylesheet in your top-most (App) component. That gets parsed as well, right? One implementation to rule them all.

**Comment by nerdyglasses** [comment]
I've added a new entry for other sass files that I don't want to go into a vue component directly. Unfortunately another sass entry doesn't get the autoprefixing. Is that something that can be added easily? I'm trying to figure this out for hours now.

Adding sass directly to the webpack modules hash breaks everything unfortunately.

**Comment by guidobouman** [comment]
That's what they're working on here.

For now you could import it in your topmost component. That way you don't need another entry.

**Comment by pksunkara** [comment]
@Grafikart Do you need any help on this?

**Comment by guidobouman** [comment]
Autoprefixer is in the latest template release. This can be closed.
