### ISSUE TITLE
Cannot find module './utils'

### ISSUE THREAD

**Issue by mlyknown** [vuejs-templates/webpack#86]
> node build/dev-server.js

module.js:327
    throw err;
    ^
Error: Cannot find module './utils'

var utils = require('./utils') 这里报错了，没在这个模板项目文件里面看到 utils这个文件啊 0.0

**Comment by airyland** [comment]
+1

**Comment by yyx990803** [comment]
错把 dist branch 的 commit merge 到 master 了...
顺便升级 vue-cli 吧
