### ISSUE TITLE
use alias in .vue files

### ISSUE THREAD

**Issue by yoyo837** [vuejs-templates/webpack#860]
I define an alias in webpack.base.conf.js like this
```
'@skin': resolve(`src/packages/${skinName}/components/pages`)
```

bug  it does not work，e.g. :

```
<style lang="scss">
@import '@skin/xxx/xxx.scss'
</style>
```

and 

```
<script>
import Something from '@skin/xxx/xxx/Xxx'
export default {

}
</script>
```

What should I do to make him work fine?

Thanks!

**Comment by myst729** [comment]
What is `skinName`?

**Comment by yoyo837** [comment]
It is here, I thought it was not so important
```
const env_pro = process.env.NODE_ENV === 'production';

const skinName = (env_pro ? config.build.skin : config.dev.skin) || 'default';
```

**Comment by myst729** [comment]
Oh I recalled that, you should use `@import '~@skin/xxx/xxx.scss'`.

**Comment by yoyo837** [comment]
That's great.
It's work fine .
script import with **@skin**,
style @import with **~@skin**.

Thanks!
