### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by carere** [vuejs-templates/webpack#865]
Hello everyone,

Im using the template webpack. And when i try to access localhost:8080 i get the message `Cannot GET /`

For info i only removed the content of src folder in order to put mine. Here is my main.js.

```import Vue from 'vue'
import MuseUI from 'muse-ui'
import 'vueify/lib/insert-css'
import 'muse-ui/dist/muse-ui.css'
import App from './components/App.vue'
import store from './store'

Vue.config.productionTip = false
Vue.use(MuseUI)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  store,
  template: '<App/>',
  components: {App}
})
```
I didn't touch any files from the original template except for src dir as i said above. So i wondering how can be possible since when i initiate the template, and i go to localhost:8080 i can see the hello welome page of the template.

Anyone has an idea ? i can't test my app since the server cannot found my files....

**Comment by KagamiChan** [comment]
This often indicates that an error is thrown during webpack compilation. You may read your terminal output for more detail.

**Comment by carere** [comment]
Thx for the help, i switched to webpack from brunch, and i didn't saw the command to build assets for dev env, since i use docker with compose and i launch my env with -d, i didn't saw the log.

node-sass was missing :)

I close this. Thx.
