### ISSUE TITLE
use  Babel-Minify (Babili) for better tree-shaking.

### ISSUE THREAD

**Issue by Aladdin-ADD** [vuejs-templates/webpack#867]

**Comment by LinusBorg** [comment]
Babili is still in its early stages, it's not "battle-tested" yet. Speed and size reductions are inferior to Uglify,

Those reasons make me think it's not a good fit for such a widely adopted template as this one.

But we could add code comments and/or documentation to make people aware that they can sue this when they choose to compile to a different target than ES5.

**Comment by saintplay** [comment]
Uglify gave me some problems, for example using  <https://github.com/vue-bulma/datepicker> UglifyJS won't work because of the ES5 restrictrions

**Comment by LinusBorg** [comment]
I'd say that its the responsibility of the package owner to provide a version compiled to ES5. 

Or at least make users aware that its using ES6.

Otherwise devs who have to serve ES5 to their end users have to transpile all of their node_modules which would be a huge overhead.
