### ISSUE TITLE
prod conf is loaded when `npm run dev`

### ISSUE THREAD

**Issue by lucidfrontier45** [vuejs-templates/webpack#877]
The recent change of https://github.com/vuejs-templates/webpack/pull/864 is problematic since webpack.prod.conf.js is loaded when running dev-server by `npm run dev`. The most critical problem for me is that the auto-reload feature doesn't work at all. 

I don't know the context of the fix #864 but the conditional operator seems wrong.

Changing

```js
var webpackConfig = process.env.NODE_ENV === 'testing' || 'production'
  ? require('./webpack.prod.conf')
  : require('./webpack.dev.conf')
```

to 

```js
var webpackConfig = (process.env.NODE_ENV === 'testing' || process.env.NODE_ENV === 'production')
  ? require('./webpack.prod.conf')
  : require('./webpack.dev.conf')
```

works for me.

**Comment by LinusBorg** [comment]
Oh damn, that was my mistake for merging it like this. Will correct in a second!
