### ISSUE TITLE
loading jquery.js, jquery plugins, etc

### ISSUE THREAD

**Issue by collapsarzhang** [vuejs-templates/webpack#88]
thanks to #84 , I am able to load third party css, but I am having problem loading jquery, and its plugins.
I had to load it through `script-loader`, `require('script!./vendors/js/jquery.js');`.
Just wondering if anyone had experience with it and have better way to do this.

**Comment by yyx990803** [comment]
Just put it in `static` and directly reference it in `index.html`. You don't want to pack it with your app code because jQuery never changes and would be better cached if loaded separately.

**Comment by collapsarzhang** [comment]
k, thanks Evan.
