### ISSUE TITLE
how to change assetsPublicPath: '/' to './' with no error?

### ISSUE THREAD

**Issue by hezhongfeng** [vuejs-templates/webpack#889]
I want to use my font-end static files on a tomcat server.
I find the js and css files are not found,because the path(`/`) are not relative path(`./`).
So I changed assetsPublicPath: from ` '/'` to `'./'`, but the vue-router will return a `404 (Not Found)`.
Do you know how to make the vue-router work well with relative path(`./`)?
Thank you.

**Comment by LinusBorg** [comment]
Relative assets paths don't work with history node of the router, that's technically impossible, pretty much.

**Comment by hezhongfeng** [comment]
Thank you.
I used the `base:`  option.
It's okay.
