### ISSUE TITLE
.eslintignore exclusions aren't used

### ISSUE THREAD

**Issue by robwierzbowski** [vuejs-templates/webpack#892]
The .eslintignore specifies `build/*.js` and `config/*.js` patterns. 

The lint task lints the `src test/unit/specs test/e2e/specs` directories, neither of which contain a build or config folder. If I understand the Webpack config, it lints similar folders with `include: [resolve('src'), resolve('test')]` in webpack.base.conf.js.

Do we need the .eslintignore rules at all? Conversely, could we include all ignored directories in the .eslintignore and remove the duplicate directory configurations?

**Comment by robwierzbowski** [comment]
If a project maintainer gives me their preferred direction I'll write a PR. Easiest is probably to remove the .eslintignore 😛

**Comment by LinusBorg** [comment]
> Do we need the .eslintignore rules at all?

Editors like atom or visual studio code can run eslint right in the editor. Excluding those files in `.eslintignore` makes sure that they don't show any errrors for those files after installing the template.
