### ISSUE TITLE
Webpack dev server doesn't detect changes of files inside local installed modules

### ISSUE THREAD

**Issue by ellipticaldoor** [vuejs-templates/webpack#899]
I installed like this a local module that I have:

```
 shell
npm install  ../db_tools
```

So in the package.json appears like this:

``` json
"dependencies": {
    "db_tools": "file:../db_tools",
},
```

The thing is that when I make a change inside the module webpack doesn't detects it and I have to manually restart the server each time a make a change into it.

**Comment by LinusBorg** [comment]
You should try to properly link the package with `npm link`
