### ISSUE TITLE
Remove unused file-loader dependency?

### ISSUE THREAD

**Issue by robwierzbowski** [vuejs-templates/webpack#902]
Hi again :). I notice that although you mention file-loader in the static readme, and also have it installed in package.json, it's not actually used in the project. 

`git grep` results for `file-loader`:
![image](https://user-images.githubusercontent.com/925735/30119465-d05890e0-92f3-11e7-9a6a-f8be460afced.png)

Would you like to remove it from the dependencies? I'd be happy to write a PR, and revise the readme to talk about file-loader as an option that a user has to install themselves.

**Comment by Gomah** [comment]
`file-loader` is definitely necessary!

`url-loader` has `file-loader` as a peer dependency & it uses `file-loader` as its fallback.

And as the documentation says, you need `file-loader` to process & return the resolved path & filename, without it, you won't be able to resolve & build your assets.

**Comment by robwierzbowski** [comment]
Ah, a peer dependency 🙃. That's always confusing. Thanks!
