### ISSUE TITLE
Docs for --report when working with yarn?

### ISSUE THREAD

**Issue by chrisnicola** [vuejs-templates/webpack#904]
I was noticing that `yarn build -- report` or `yarn build -- --report` doesn't work. I'm wondering if there is a way to make that work with yarn. I've searched around but have not found much documentation on this argument `process.env` feature of NPM either.

**Comment by saintplay** [comment]
Yeah, sadly it seems like yarn doesn't support environment from cli at [this moment](https://github.com/yarnpkg/yarn/issues/4581)

However you can do something like this
  
1.  Add this to you **package.json** scripts
```json
"scripts": {
    "build:report": "cross-env npm_config_report=true node build/build.js"
```
2.  Just run the script
```bash
yarn build:report
```

**Comment by fengerzh** [comment]
If you meet `cross-env command not found`, just run `yarn add -D cross-env`.
