### ISSUE TITLE
unittest：not  support export * from syntax  

### ISSUE THREAD

**Issue by Hanruis** [vuejs-templates/webpack#906]
while using the syntax `export * from './index.js`

in unittest env , it will throw error : `exports is not defined`

I find that it add `modules:false` to test env of babelrc  can fix 

but it cause another problem that relative inject-loader , see https://github.com/vuejs-templates/webpack/issues/528  but the issue tells us to remove `modules:false` .....

so how can i fix this problem ... thx

**Comment by LinusBorg** [comment]
No idea, sorry.

Heads up: We will soon add Jest as another option for unit tests, and the current karma setup will be available, but deprecated.

**Comment by LinusBorg** [comment]
No idea what to do with this, and no one else seems to care, so closing.
