### ISSUE TITLE
unittest：not  support export * from syntax  

### ISSUE THREAD

**Issue by Hanruis** [vuejs-templates/webpack#907]
while using the syntax `export * from './index.js` .   in unittest env , it will throw error : `exports is not defined`

I find that it add `modules:false` to test env of babelrc  can fix 

but it cause another problem that relative inject-loader , see https://github.com/vuejs-templates/webpack/issues/528  but the issue tells us to remove `modules:false` .....

so how can i fix this problem ... thx

**Comment by LinusBorg** [comment]
Duplicate #506
