### ISSUE TITLE
Autoprefix of extraneous components

### ISSUE THREAD

**Issue by adi518** [vuejs-templates/webpack#909]
It seems the CSS of extraneous components is not getting prefixed.

**Comment by KagamiChan** [comment]
Have you tried adding postcss-loader in your `build/utils.js`?

Something like this:
in `exports.cssLoaders`
```js

...

  var postcssLoader = {
    loader: 'postcss-loader',
    options: {
      plugins: [
        autoprefixer,
      ],
    },
  }

  // generate loader string to be used with extract text plugin
  function generateLoaders (loader, loaderOptions) {
    var loaders = [cssLoader]

    if (process.env.NODE_ENV === 'production') {
      loaders.push(postcssLoader)
    }

    if (loader) {
      loaders.push({
        loader: loader + '-loader',
        options: Object.assign({}, loaderOptions, {
          sourceMap: options.sourceMap
        })
      })
    }
...

```

**Comment by adi518** [comment]
I tried, but probably did it wrong. Still in the curve when it comes to Webpack.

**Comment by robwierzbowski** [comment]
I think postCss is already loaded in CSS loader function: https://github.com/vuejs-templates/webpack/blob/develop/template/build/utils.js#L50

Autoprefixer is added to postCss with the .postcssrc.js file here: https://github.com/vuejs-templates/webpack/blob/develop/template/.postcssrc.js

So it *should* be working. @adi518, what do you mean by extraneous components? Components that aren't required anywhere?

**Comment by adi518** [comment]
It means 3rd party components. By default, it isn't working for me atm. It's possible my `vue-loader` configuration is outdated.

**Comment by LinusBorg** [comment]
I'll close this since its been inactive and 5 months have passed. If this persists, please comment / open a news issue with further details.
