### ISSUE TITLE
cannot resolve module 'fs'

### ISSUE THREAD

**Issue by runarhk** [vuejs-templates/webpack#91]
Added lokijs to dependency for my project, and when attempting to build I get "Module not found: Error: Cannot resolve module 'fs'". This is related to the setup by this template as it worked in my old setup...

**Comment by runarhk** [comment]
Adding 


  node: {
    console: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }

to the webpack.base.conf.js fixes the problem

**Comment by chrisvfritz** [comment]
@runarhk Thanks for sharing this! Can you explain a little more about the implications of a change like this? I understand it's creating an empty mock of these node modules, but after [looking at the docs](http://webpack.github.io/docs/configuration.html#node), I'm still unsure why or when this is necessary. I'm also not sure what potential problems mocking these modules could cause (I imagine there's probably a reason it's not default behavior).

**Comment by runarhk** [comment]
Sorry, but I am still learning the loops in webpack. I had a problem, googled it and found a solution that worked for me. I am not able to explain more about the implications, but it would be nice if you guys had a look at it.

**Comment by chrisvfritz** [comment]
@runarhk Thanks for the follow-up! I'm a Webpack power user, but by no means a complete Webpack expert, so I'll leave this open with the `help wanted` tag until someone can enlighten us. 😃

**Comment by chrisvfritz** [comment]
Since this issue has been stale for a while and no one else has reported it, I'm closing for now. Happy to reopen pending new information or others indicating that it's a problem for them as well.

**Comment by tvld** [comment]
Still getting this problem as well. I can not use fs !!
Might be on to something:
Actually when ``npm install`` after a clean new ``vue init webpack my-fs-test``, I get warnings:
```
 npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
 npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

**Comment by eroncastro** [comment]
Im my case, I found the solution here:
https://github.com/webpack-contrib/css-loader/issues/447
