### ISSUE TITLE
Build on change

### ISSUE THREAD

**Issue by ivanjaros** [vuejs-templates/webpack#917]
Hi,
I am working on vue app that will be part of existing website. The website only serves basic html page structure and loads the vue assets. Due to CORS and me not being able to make axios work correctly I cannot develop the vue app on localhost that the vue cli serves any longer and having to manually run the build script(that takes QUITE some time to compile) is impractical so I’m looking for a solution that would build the scripts in dev mode fast. I do not need hotrealoading, just fast building in dev mode on change.

Is this possible with the webpack template or will the compilation take long no matter what?

**Comment by heinzdmx** [comment]
What about solving the original problem first? 

Try setting it up as a routing proxy: https://vuejs-templates.github.io/webpack/proxy.html
That way you don't have to worry about CORS and get get it setup rather easily, and get hot reload the like to work as well

**Comment by ivanjaros** [comment]
Thanks, that seems to be working just fine.
