### ISSUE TITLE
npm run build =>  error from UglifyJs Unexpected character '`' from UglifyJs Unexpected token: punc (() 

### ISSUE THREAD

**Issue by alexMugen** [vuejs-templates/webpack#918]
Hello , 

I 've got a problem that i can't fiind a solution .

i've got this conf : 
webpack.base.conf.js: 
```javascript
{
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: 'pre',
        include: [resolve('src'), resolve('test')],
        options: {
          formatter: require('eslint-friendly-formatter')
        }
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
```

in my package.json 
```javascript
"devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
```

I tried solutions like this https://stackoverflow.com/questions/41519344/webpack-build-xxx-vue-error-when-use-uglifyjs but it didn't work
Moreover, I use vue webpack template, i don't need to use .babelsrc file

Thanks for your help

**Comment by KagamiChan** [comment]
Are you using template literals in your code?

I don't get the point why you don't need `babelrc` file, vue-loader itself also uses this file.

**Comment by alexMugen** [comment]
in my code i have classical template in my .vue: 
 Inside my div template there is my html 
below i have my script 

I said that because in some solutions it suggests to add a file .babelrc with a typical conf  to overwrite the other

**Comment by LinusBorg** [comment]
The vue webpack template comes with a babelrc file and it is required for the template to work properly. 

If you removed it, you broke your setup.

**Comment by alexMugen** [comment]
I did'nt remove some file

**Comment by alexMugen** [comment]
In fact , the version of vue webpack when i get it is not the same than now

**Comment by zhouchangshun** [comment]
I come cross the same problem,how did you solve this problem?
