### ISSUE TITLE
Running build configuration from parent folder?

### ISSUE THREAD

**Issue by chuckdries** [vuejs-templates/webpack#919]
I'm working on a project where client and server live in the same git repo, (would like to) use the same package.json, etc. I read the [documentation on the subject](http://vuejs-templates.github.io/webpack/backend.html), which didn't mention calling the dev server from the parent of the folder it all lives in. 

For example:
`node client/build/dev-server.js`

I've spent a few hours mucking around with paths and whatnot and I've settled in just throwing a `cd` into the package.json scripts for now, but eventually I want to use concurrently to run the server and client together, and I can't do that in that case.

The pain points:
 - Can't manually specify location of `/source`,
 - Have to go through and change relative directory of dev-client.js in webpack.dev.conf.js
 - Have to manually change webpack entry and aliases
 - After all this, and hacing changed every path I could find, the production build succeeds but the dev server fails, with an empty error no less! It's just blank.

**Comment by LinusBorg** [comment]
I think this can be impropved upon, primarily by setting the [context](https://webpack.js.org/configuration/entry-context/#context) option and converting a couple of paths to absolute ones.

We should look at this after #975 has been merged - using the official webpack-dev-server might solve some of the issues you were having.

**Comment by LinusBorg** [comment]
Context is now set  properly. 

https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.base.conf.js#L23

I hope this resolves this issue..
