### ISSUE TITLE
error for build with --report

### ISSUE THREAD

**Issue by zhiga90** [vuejs-templates/webpack#920]
_npm run build_ - everything ok, but _npm run build  --report_ give me an error

vue init webpack foo //ok
press enter for all questions //ok
cd foo //ok
npm install //ok
npm run build //ok
npm run build --report //ok but no report

PS C:\foo> npm run build --report

> foo@1.0.0 build C:\foo
> node build/build.js

| building for production...
Starting to optimize CSS...
Processing static/css/app.92cd31919b254b14ab833079c875d4cf.css...
Processed static/css/app.92cd31919b254b14ab833079c875d4cf.css, before: 431, after: 363, ratio: 84.22%
Hash: 7ebde305c31cdf8f701a
Version: webpack 2.7.0
Time: 8707ms
                                                  Asset       Size  Chunks             Chunk Names
                  static/js/app.887b1bad52c6fdd64285.js    11.8 kB       0  [emitted]  app
               static/js/vendor.64d2873e0d2b30a3635a.js     110 kB       1  [emitted]  vendor
             static/js/manifest.4a86e0734583deee90f5.js    1.51 kB       2  [emitted]  manifest
    static/css/app.92cd31919b254b14ab833079c875d4cf.css  363 bytes       0  [emitted]  app
              static/js/app.887b1bad52c6fdd64285.js.map    41.1 kB       0  [emitted]  app
static/css/app.92cd31919b254b14ab833079c875d4cf.css.map  910 bytes       0  [emitted]  app
           static/js/vendor.64d2873e0d2b30a3635a.js.map     883 kB       1  [emitted]  vendor
         static/js/manifest.4a86e0734583deee90f5.js.map    14.6 kB       2  [emitted]  manifest
                                             index.html  440 bytes          [emitted]

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8888
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--report"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! foo@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foo@1.0.0 build script 'node build/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\foo\npm-debug.log

**Comment by MaxMilton** [comment]
`EADDRINUSE` means that node can't open the port because it'a already being used. Stop anything else that's using port 8888 and it should work.

**Comment by sidonaldson** [comment]
Or, it's being called multiple times. In the case of passing webpack an array rather than an object. 👍
