### ISSUE TITLE
Adding ProvidePlugin to webpack dev config breaks the app

### ISSUE THREAD

**Issue by Ganitzsh** [vuejs-templates/webpack#922]
Hi,

I was trying to use bootstrap 4 with vue-js and this boilerplate. I added the following to my webpack.dev.conf:
```js
new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery",
    }),
```
It kinda worked but asked for Tether. I went ahead and `npm install`'d tether and added it to the `ProvidePlugin` as follows:
```js
new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery",
      Tether: "tether",
      "window.Tether": "tether"
    })
```

And now I get a blank page and the following message in the console:

```
vue.esm.js?65d7:476 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Hello>
       <App> at src/App.vue
         <Root>
```
It also happened before randomly after stoping the dev server and then starting it again from a day to another. Anyway, I tried importing Tether inside the `main.js` file like this:
```js
import * as Tether from 'tether'; // once like this, didn't work
import Tether from 'tether'; // then like this
import 'tether'; // and as a desperate attempt like this
```
I couldn't find anything wrong in the webpack confguration and I'm running out of solutions.
What am I missing?

**Comment by donaldinos** [comment]
I think, that you have it correctly, only apostrophe is missing:
``` javascript
new webpack.ProvidePlugin({
      ...
      'Tether': "tether"
    })
```

**Comment by Ganitzsh** [comment]
Thanks for the help! It was actually me doing very stupid with the file names. I had `Hello.vue` and `Hello.js` at the same spot and the `import Hello from 'Hello'` just didn't know which one to take...

Sorry. It works now!

**Comment by anpegar** [comment]
@Ganitzsh Hey there !!
I am currently having the same problem with jquery and webpack, I am doing the following steps:

Step 1

```
$ vue init webpack my-project
$ cd my-project
$ npm install
$ npm install --save jquery
```

Step 2
Add jquery into webpack.dev.conf.js so that:

```
new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery",
    }),

```
Step 3
Add global vars into .eslintrc.js so that:

```
globals: {
    '$': true
  },

```
Step 4
Add the following code in the file HelloWorld.vue:

```
export default {
  name: 'HelloWorld',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  },
  mounted () {
    **console.log($('h1').html())**
  }
}
```
Step 5
Execute **npm run dev** and the following error appears:

```
[Vue warn]: Error in mounted hook: "ReferenceError: jquery is not defined" found in

---> <App> at src\App.vue
       <Root>

```

What's going wrong? 
Ganitzsh, do you have a template with vue-webpack + jquery + bootstrap 4?

Any help will be greatly appreciated.
Thanks in advance.
