### ISSUE TITLE
router 'require' component working sometimes

### ISSUE THREAD

**Issue by rolandszpond** [vuejs-templates/webpack#924]
This is just a question...

With an older project, I 'require' components inline with the 'component' parameter to the route and it works:

```javascript
const routes = [
    {
        path: '/',
        name: 'Home',
        component: require('@/pages/home')
    }
]
```

instead of:
```javascript
import Home from '@/pages/home'

const routes = [
    {
        path: '/',
        name: 'Home',
        component: Home
    }
]
```

but with a fresh install of a webpack project, it throws an error:

'Failed to mount component: template or render function not defined.

**Comment by rolandszpond** [comment]
I would like to add that this is how I've handled all my vue webpack projects and only started having projects recently these past few days

**Comment by rhyek** [comment]
Yeah, same here. Though, through this issue, I decided to try out [lazy-loading](https://router.vuejs.org/en/advanced/lazy-loading.html) and it works great!

Try:
```js
const routes = [
    {
        path: '/',
        name: 'Home',
        component: () => import('@/pages/home')
    }
]
```

**Comment by rolandszpond** [comment]
@rhyek Thanks! That works for me, at least temporarily until we find out if it's a bug or something

**Comment by LinusBorg** [comment]
You experience this because vue-loader exports ES modular since version 13.

So you have to do: `require('youcomponent.vue').default`

**Comment by rhyek** [comment]
@LinusBorg, thanks.
