### ISSUE TITLE
`require all src files` in unit/index.js useless?

### ISSUE THREAD

**Issue by njleonzhang** [vuejs-templates/webpack#928]
Hi team, 

Does the following code really useful? I remove the code from my project, but nothing change, it seems not impact the code coverage as the comments stated.

https://github.com/vuejs-templates/webpack/blob/fb39683846944f874244f88be4b05a1a2f1b7c96/template/test/unit/index.js#L9-L13

According to karma-webpack [doc](https://github.com/webpack-contrib/karma-webpack), I can not find the purpose of these code too. If they are useful would you please give some explanation?

**Comment by LinusBorg** [comment]
If you reference all source files from your tests, then this has indeed no effect.

If however you tests leave out some source files, then this code would make sure they are still required and therefore taken into account when calculating coverage.

If that doesn't work as expected for you, maybe there's a bug?

**Comment by njleonzhang** [comment]
@LinusBorg Tnx for explanation. I understand now. No bug exists. 
In my project, I split template code to a independent `pug` file (for some reason). when run release/dev, no error occurs. But if I run `npm run test`, the pug file is loaded by above code, which need a `pug-loader`, error occurs. So I start to look into this `test/index.js`, and thinking why we need these lines. Now you provide me  a explanation, I understand. tnx again.
