### ISSUE TITLE
Can't compile sass

### ISSUE THREAD

**Issue by mlyknown** [vuejs-templates/webpack#93]
error:
ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/sass-loader?ind
entedSyntax!./~/vue-loader/lib/selector.js?type=style&index=0!./src/views/index/
app.vue
Module build failed:
    <div class="r"></div>
    ^
      Invalid CSS after "div{}": expected 1 selector or at-rule, was "{}"
      in D:\MyProject\mall\mail-client\src\views\index\app.vue (line 5, column 6
)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/
sass-loader?indentedSyntax!./~/vue-loader/lib/selector.js?type=style&index=0!./s
rc/views/index/app.vue 4:14-267 13:2-17:4 14:20-273.

When I  comment  this code
  // vue: {
  //   loaders: utils.cssLoaders()
  // }
sass compile successfully.

code:
![qq 20160420182253](https://cloud.githubusercontent.com/assets/12880984/14671559/fea490e0-0724-11e6-8d72-1e9b961b6cbb.png)

**Comment by yyx990803** [comment]
Use `scss` if you are using the CSS superset syntax.
