### ISSUE TITLE
Vue.nextTick returns undefined instead of Promise in tests

### ISSUE THREAD

**Issue by fritx** [vuejs-templates/webpack#930]
Hi there,

As [documented](https://cn.vuejs.org/v2/api/index.html#Vue-nextTick), Vue.nextTick returns a Promise if supported.

Also, the spec of nextTick: https://github.com/vuejs/vue/blob/f242e119fab42e2f80dfea5fc9e0eaffd1587af7/test/unit/modules/util/next-tick.spec.js#L12-L15

```js
// next-tick.spec.js
if (typeof Promise !== 'undefined') {
    it('returns a Promise when provided no callback', done => {
      nextTick().then(done)
    })
// ...
```

However, when I added the code below to this repo (vuejs-templates/webpack), the test failed.

```js
// Hello.spec.js  chai-style
  it('Vue.nextTick', () => {
    expect(typeof Promise !== 'undefined').to.equal(true)
    const ret = Vue.nextTick()
    expect(ret).not.to.be(undefined)   // <--- ret === undefined
  })
```

```plain
  Hello.vue
    ✓ should render correct contents
    ✗ Vue.nextTick
        expected undefined to not equal undefined
```

What's more, I tried the same thing in the new [vue-test-utils-jest-example](https://github.com/eddyerburgh/vue-test-utils-jest-example), the test did not fail.

```js
// List.spec.js  jest-style
  it('Vue.nextTick', () => {
    expect(typeof Promise !== 'undefined').toBe(true)
    const ret = Vue.nextTick()
    expect(ret).not.toBe(undefined)
  })
```

Expected behavior: It should return Promise in test of this repo.

**Comment by fritx** [comment]
Now in order to simply `await Vue.nextTick` in test:

```js
  it('view => model', async () => {
    await Vue.nextTick()
    expect(vm.model.name).to.equal('')

    inputs[0].value = 'abc'
    triggerEvent(inputs[0], 'input')

    await Vue.nextTick()
    expect(vm.model.name).to.equal('abc')
  })
```

I have to do the trick like:

```js
// test/unit/index.js
// ...
// hack: monkey-patch Vue.nextTick bug as not returning Promise
// https://github.com/vuejs-templates/webpack/issues/930
Vue.nextTick = (original => {
  return cb => {
    if (cb == null) {
      return new Promise(resolve => {
        original(resolve)
      })
    } else {
      original(cb)
    }
  }
})(Vue.nextTick)
```

**Comment by LinusBorg** [comment]
Hm, good point. PhantomJS doesn't support promises (so I wonder why your first expect didn't fail).

We didn't include a polyfill originally because Vue.nextTick didn't support Promises  originally, (no part of Vue requires them).

So a better solution to your problem than monkeypatching Vue would be to polypill "Promise".

**Comment by LinusBorg** [comment]
FWIW, I made a PR to the main docs to mention the need for  polyfill:

https://github.com/vuejs/vuejs.org/pull/1180

**Comment by fritx** [comment]
@LinusBorg great work :+1:
