### ISSUE TITLE
How to disable minification and uglification?

### ISSUE THREAD

**Issue by d9k** [vuejs-templates/webpack#933]
Hello!
How can I disable minification and uglification in resulting bundle altogether?
(It's required for debugging purposes. The resulting code is intended to run in special secured environment, not regular browser, and source mapping doesn't work as expected there)

**Comment by LinusBorg** [comment]
remove the Uglify plugin from `/build/webpack.prod.conf.js`

**Comment by d9k** [comment]
@LinusBorg, excuse me, please, I created an issue in a wrong project...
https://github.com/vuejs-templates/webpack-simple/issues/137
