### ISSUE TITLE
relative path to static

### ISSUE THREAD

**Issue by alexey-baranov** [vuejs-templates/webpack#936]
Hello!

**what i do** 
start single page builded app from path https://my.domain.com/some/very/long/path/to/app/index.phtml

**what is want to get**
start index.html with relative path to `js/vendor.js` and `js/app.js`

**what i realy get**
start index.html with absolute path `/static/js/vendor.js` and `/static/js/app.js`

As i can understand this is new default behaviour. Later in my projects i did not get this problem. How i can move back to relative path?

my html generated by webpack template is 
```html
<script type="text/javascript" src="/static/js/manifest.06ddd12ed48332fe53ca.js"></script>
<script type="text/javascript" src="/static/js/vendor.e9dace6c7aed102ba830.js"></script>
<script type="text/javascript" src="/static/js/app.72274718ea92af4f5293.js"></script>
```

**Comment by LinusBorg** [comment]
IT's not new, but yes, it's default behaviour. you cna change the path in `/config/index.js`
