### ISSUE TITLE
Proxy isn't functioning.

### ISSUE THREAD

**Issue by eugenefedoto** [vuejs-templates/webpack#937]
```
// config/index.js
proxyTable: {
      '/api': {
        target: 'http://localhost:9090',
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      },
    },
```
```
$ npm start

> seagull-axz@1.0.0 start C:\Users\eugen\Projects\symphogear
> node build/dev-server.js

[HPM] Proxy created: /api  ->  http://localhost:9090
[HPM] Proxy rewrite rule created: "^/api" ~> ""
> Starting dev server...
 DONE  Compiled successfully in 5175ms01:19:15

> Listening at http://localhost:8080
```

![image](https://user-images.githubusercontent.com/14006633/30779754-4036ba6e-a0c7-11e7-84e7-0287c2ed5bf4.png)

I'm using Axios to send requests from localhost:8080. I want them to be proxied to localhost:9090. This was working with webpack-simple. It's not working with the webpack template.

Similar issue: #465

**Comment by eugenefedoto** [comment]
I got it working.
```
proxyTable: {
      '/api': {
        target: 'http://localhost:9090',
        changeOrigin: true
      }
    },
```

**Comment by Oscarz90** [comment]
I tried the same but It didnt work, whats the difference between the two options?

**Comment by luckymore** [comment]
@Oscarz90 check your config/index.js  dev.host. Is it localhost
