### ISSUE TITLE
try to save in dist after run npm run dev

### ISSUE THREAD

**Issue by fadiabualnaser** [vuejs-templates/webpack#938]
I try to save my builds files in dist folder as the script "npm run build" do but i can't, I try for many hours to used the same plugins in bulid.js file, but nothing works for me.

Anyone have an idea ? Please

**Comment by LinusBorg** [comment]
Hi,

I have no real idea since you don't really say what problems/errors you encounter.

Generally, it's better to ak question on forum.vuejs.org or chat.vuejs.org anyway. This is for bugs & features.
