### ISSUE TITLE
Make all directories configurable

### ISSUE THREAD

**Issue by gquintana** [vuejs-templates/webpack#943]
I'd like to configure all folders locations (except build/config scripts) in order to ease integration with other build tools (Maven):

* Build Input:
  - Main sources: `src`
  - Static sources: `static`
  - Unit test sources: `test/unit`
  - E2E sources: `test/e2e` 
* Build Output:
  - Main target: `dist` 
  - Unit test coverage target: `test/unit/coverage`
  - E2E test report target: `test/e2e/report`

**Comment by LinusBorg** [comment]
I don't think  that we will do this. This will make the generator much more complicated and will defeat the advantage that people can easily find their way in every project geenrated with this template.

I understand that the folder structure is not suitable for all use cases, but that's a downside I think we will accept.
