### ISSUE TITLE
Undefined SCSS variables when testing

### ISSUE THREAD

**Issue by matheusgrieger** [vuejs-templates/webpack#948]
I'm rewriting a web platform for an app we have in our company, so I have a lot of SCSS code added. Everything is working as expected so far, the SCSS is `import`ed and processed correctly (only imported inside a JS file, not within Vue files). It works nicely in the browser with `dev` and `build` commands.

But after writing a unit test in the given settings (after changing from PhantomJS to ChromeHeadless, otherwhise Vuex doesn't work), I keep getting "Undefined variables" in my SCSS, even though everything is working outside testing environment.

*karma.conf.js:*
```js
var webpackConfig = require('../../build/webpack.test.conf')

module.exports = function (config) {
  config.set({
    browsers: ['ChromeHeadless'],
    frameworks: ['mocha', 'sinon-chai'],
    reporters: ['spec', 'coverage'],
    files: ['./index.js'],
    preprocessors: {
      './index.js': ['webpack', 'sourcemap']
    },
    webpack: webpackConfig,
    webpackMiddleware: {
      noInfo: true
    },
    coverageReporter: {
      dir: './coverage',
      reporters: [
        { type: 'lcov', subdir: '.' },
        { type: 'text-summary' }
      ]
    }
  })
}
```

All SCSS variables are declared in the `main.scss` file, and all other files are imported from it, relatively. The error occurs in the imported files.

Am I missing anything?

**Comment by LinusBorg** [comment]
Hm, no idea from that information ...

**Comment by matheusgrieger** [comment]
I got it working by moving all variable declarations to a `variables.scss` file and importing it in *every* file that makes use of those variables. Not ideal, but works.

**Comment by LinusBorg** [comment]
this might be of interest to you: https://github.com/shakacode/sass-resources-loader

**Comment by matheusgrieger** [comment]
I'll check it out, thank you!

**Comment by basebandit** [comment]
To anyone who might still be facing @matheusgrieger's  issue and is using vuejs webpack template, check out this gist here https://gist.github.com/dc198689/9cf4ecfb4040d0a4564a561c27c81346. Works perfectly.
