### ISSUE TITLE
Warning when creating new Vue project

### ISSUE THREAD

**Issue by UrsMetz** [vuejs-templates/webpack#959]
Today I created a new Vue project using `vue-cli` and the `webpack` template.
Here's the configuration I chose:
```
? Vue build standalone
? Install vue-router? No
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Standard
? Setup unit tests with Karma + Mocha? Yes
? Setup e2e tests with Nightwatch? No
```
When `vue-cli` ran the initial `npm install` I got the warning
```
npm WARN karma-sinon-chai@1.3.2 requires a peer of sinon@^2.1.0 but none was installed.
```
The `sinon` version in the generated `package.json` is `^4.0.0`

The warning persists when running `npm install` manually.

I'm using Node version 6.6.0 on Debian 8.

**Comment by LinusBorg** [comment]
Thanks. Seems this was created by a recent dependency upgrade for other deps. 

This is likely not creating any issues (karma and Simon still work fine), but I'll clear up issue.

**Comment by LinusBorg** [comment]
It seems that `karma-sinon-chai` didn't update the peer dependency in a while:

https://github.com/kmees/karma-sinon-chai/issues/50

But it still works as intended, so there's not much we can do. You will just have to ignore it...
