### ISSUE TITLE
Should shelljs be a dev dependency?

### ISSUE THREAD

**Issue by thatandyrose** [vuejs-templates/webpack#96]
In the generated `build.js` for production there is a `require('shelljs/global')`. However in the generated `package.json` `shelljs` is listed a dev dependency only.

Is this correct? I ask because I'm getting errors when trying ti deploy to Heroku.

Thanks!

UPDATE:

Actually this applies to a bunch of dependencies in `build.js` like `ora` and `webpack` etc.

**Comment by chrisvfritz** [comment]
This is correct. build.js is a script that's used to build the production site, but its dependencies are not included in the static files generated in the dist folder. What errors exactly are you getting on Heroku? And what is your setup? Do you have a backend that you've integrated this into, or are you trying to deploy a static site?

**Comment by thatandyrose** [comment]
@chrisvfritz hey dude, thanks for the reply.

Basically I'm using this article to deploy the app on Heroku:

https://medium.com/@sagarjauhari/quick-n-dirty-way-to-deploying-vue-webpack-apps-on-heroku-4ab964ee536#.1qjrrs6jy

My set up is the same as the article EXCEPT in the build property in the webpack file I've left it as it is in the webpack template, which is to use `build.js`.

I think the issue is... `build.js` references dependencies that aren't loaded in production.

When the code is pushed to Heroku, Heroku run `build.js` with the `env` set to `Production` and it then throws an error saying it can't find any module that's only defined in the `devDependencies`.

Does that make sense?

**Comment by thatandyrose** [comment]
@chrisvfritz (FYI I'm totally new to Webpack, node, ES6, express and all that so excuse the ignorance)

**Comment by thatandyrose** [comment]
@chrisvfritz sorry, some extra info. This is from the Heroku build logs:

```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 5.10.1...
       Using default npm version: 3.8.3
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json)
       
       > the-100-mile-client@1.0.0 postinstall /tmp/build_17d3fe9944e0b6e4f078f45187434413/thatandyrose-the-100-mile-client-5dd0787c0434e15666cb0590f3e9c7301e673a41
       > npm run build
       
       
       > the-100-mile-client@1.0.0 build /tmp/build_17d3fe9944e0b6e4f078f45187434413/thatandyrose-the-100-mile-client-5dd0787c0434e15666cb0590f3e9c7301e673a41
       > node build/build.js
       
       module.js:341
       throw err;
       ^
       
       Error: Cannot find module 'shelljs/global'
       at Function.Module._resolveFilename (module.js:339:15)
       at Function.Module._load (module.js:290:25)
       at Module.require (module.js:367:17)
       at require (internal/module.js:16:19)
etc etc etc.
```

**Comment by yyx990803** [comment]
If you are executing the build step, then you need to install full dev dependencies.

**Comment by thatandyrose** [comment]
@yyx990803 thanks Evan! (Also thanks for Vue!!!). Could you point me to best practices for deploying vue apps.... it's not very clear for newcomers to this js-only world! Thanks so much.

**Comment by chrisvfritz** [comment]
@thatandyrose Heroku is great for dynamic sites that include a backend server, but for this template (which produces a purely static site), I'd actually recommend using static site hosting such as Surge or Netlify.

What's probably the simplest possible deployment process would look like this:

First, add the `surge` package to the dev dependencies in your `package.json` and install it with:

```
npm install --save-dev surge
```

Then you can add these two lines to the `scripts` section of `package.json`

``` json
"predeploy": "npm run build",
"deploy": "surge --project dist --domain whatever-subdomain-you-want.surge.sh"
```

And... now you're done. 😄  Whenever you run `npm run deploy`, your site with deploy to Surge, for free. The first time, it'll prompt you to create an account with an email and password and on subsequent runs, it'll just deploy.

Let me know if that works for you!

**Comment by thatandyrose** [comment]
@chrisvfritz wow awesome! Thanks so much Chris! I'll try that out. THANK YOU!

**Comment by CovertIII** [comment]
I ran into the same issue.  [Here's how I fixed it.](https://devcenter.heroku.com/articles/nodejs-support#devdependencies) 
(Copied below in case the link ever breaks)


> **devDependencies**
> We set NPM_CONFIG_PRODUCTION to true by default to install production dependencies only. If you would like to install devDependencies, you can disable production mode:
> `$ heroku config:set NPM_CONFIG_PRODUCTION=false`
> However, since you usually don’t want all development dependencies in your production builds, it’s preferable to move only the dependencies you actually need for production builds (bower, grunt, gulp, etc) into `dependencies`.
