### ISSUE TITLE
fork is not work

### ISSUE THREAD

**Issue by xu455255849** [vuejs-templates/webpack#961]
https://github.com/xu455255849/vue-xu  ,this is my repo,   i  revise the meta.js  

```
  plugins: {
            type: 'checkbox',
            message: 'Select which Vue plugins to install',
            choices: ['axios', 'vue-router', 'vuex'],
            default: ['axios', 'vue-router', 'vuex']
        },
```
but   `$vue init xu455255849/vue-xu test` is not work

**Comment by LinusBorg** [comment]
Please ask questions about your own projects on forum.vuejs.org or chat.vuejs.org

This issue list should be strictly about issues with the original template, not forks.
