### ISSUE TITLE
How can i  extract the css in vue components into a separate css file if i use the components as  async-component?

### ISSUE THREAD

**Issue by siyongXia** [vuejs-templates/webpack#962]
1.I use the vue-cli webpack template to init my project,and installed all the packages required;
2.Then,I use the command npm run build to build my project into dist directory;
3.I  found the css in helloworld.vue has been extracted to app.71661e4e06ab9d7ebc0e200f4ae039dc.css,it's ok;
4.I want to treat the helloworld.vue  as a async  component,so i change the file (/router/index.js) like this:

```
import Vue from 'vue'
import Router from 'vue-router'
// import HelloWorld from '@/components/HelloWorld'
//Here was changed
const HelloWorld = resolve => require(['@/components/HelloWorld'], resolve)

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Hello',
      component: HelloWorld
    }
  ]
})
```
5.repeat step 2;
6.I  found the css in helloworld.vue has been extracted to 0.c890b125815ec5adce3c.js,like the picture beblow;
![image](https://user-images.githubusercontent.com/24487873/31329260-d3a3217a-ad0b-11e7-8341-753fd031191e.png)
Question:How can i extracted  the css in 0.c890b125815ec5adce3c.js into a separate Css file?

**Comment by LinusBorg** [comment]
Currently, you can't. This is a restriction of webpack's treatment of CSS, not of vue-loader.

You can read about plans to improve that here:

https://medium.com/webpack/the-new-css-workflow-step-1-79583bd107d7

> This has a few benefits:
> * We can generate stylesheet files for on-demand-chunks (this was not possible with the extract-text-webpack-plugin)
