### ISSUE TITLE
Vue Source file is visible on production

### ISSUE THREAD

**Issue by alimirayman** [vuejs-templates/webpack#963]
After running `npm run build` in vue-cli webpack version, we can see vue source file in chrome source tab under `webpack://` dir 

![image](https://user-images.githubusercontent.com/3832930/31333824-65984b54-ad0d-11e7-805e-350092fbdb30.png)

**Comment by LinusBorg** [comment]
That's because the production build includes source Maps by default:

https://github.com/vuejs-templates/webpack/blob/develop/template/config/index.js#L14

Either deactivate that option or don't serve the sourcemap files that you find in the `/dist` folder.

**Comment by alimirayman** [comment]
Thank you
