### ISSUE TITLE
Example app generated by boilerplate is not running on ie10

### ISSUE THREAD

**Issue by iliran11** [vuejs-templates/webpack#967]
tested on:

- **Node.js:** 6.11.4
- **Browser:** Internet Explorer 10.0.9200.17609
- **Vue Cli:** 2.9.1
- **Vue:** 2.4.4

After creating a vue project using the webpack boilerplate (see appendix A to see the project setup),
running the project on chrome 60 is fine.

No changes at all were made to the code generated by the boilerplate.

however, while running the project on localhost, using IE 10 (see enviroment details for exact version), 
there is the following error:

```javascript
SCRIPT1002: Syntax error 
app.js, line 789 character 1
```

the error line itself is:
```javascript
eval("/* eslint-disable */\n\n__webpack_require__(10)\nconst hotClient = __webpack_require__(12)\n\nhotClient.subscribe(function (event) {\n  if (event.action === 'reload') {\n    window.location.reload()\n  }\n})\n\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiOS5qcyIsInNvdXJjZXMiOlsid2VicGFjazovLy8uL2J1aWxkL2Rldi1jbGllbnQuanM/N2Q2NyJdLCJzb3VyY2VzQ29udGVudCI6WyIvKiBlc2xpbnQtZGlzYWJsZSAqL1xuJ3VzZSBzdHJpY3QnXG5yZXF1aXJlKCdldmVudHNvdXJjZS1wb2x5ZmlsbCcpXG5jb25zdCBob3RDbGllbnQgPSByZXF1aXJlKCd3ZWJwYWNrLWhvdC1taWRkbGV3YXJlL2NsaWVudD9ub0luZm89dHJ1ZSZyZWxvYWQ9dHJ1ZScpXG5cbmhvdENsaWVudC5zdWJzY3JpYmUoZnVuY3Rpb24gKGV2ZW50KSB7XG4gIGlmIChldmVudC5hY3Rpb24gPT09ICdyZWxvYWQnKSB7XG4gICAgd2luZG93LmxvY2F0aW9uLnJlbG9hZCgpXG4gIH1cbn0pXG5cblxuXG4vLy8vLy8vLy8vLy8vLy8vLy9cbi8vIFdFQlBBQ0sgRk9PVEVSXG4vLyAuL2J1aWxkL2Rldi1jbGllbnQuanNcbi8vIG1vZHVsZSBpZCA9IDlcbi8vIG1vZHVsZSBjaHVua3MgPSAwIl0sIm1hcHBpbmdzIjoiQUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTsiLCJzb3VyY2VSb290IjoiIn0=\n//# sourceURL=webpack-internal:///9\n");
```

**_Appendix A - Project Setup_** 
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

 Project name liran
? Project description A Vue.js project
? Author
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Standard
? Setup unit tests with Karma + Mocha? Yes
? Setup e2e tests with Nightwatch? Yes

**Comment by LinusBorg** [comment]
Thanks, fixed now.

We recently transformed the build config files all to ES6 because the minimum node version supports it.

But dev-client.js is inserted into the client-side, and not transpiled, so it should stay in ES5.
