### ISSUE TITLE
why `plugins` is not needed in `karma.conf.js`?

### ISSUE THREAD

**Issue by zzzgit** [vuejs-templates/webpack#973]
In my own project, I configged plugins for karma

```javascript
		plugins: [
			"karma-phantomjs-launcher", 
			'karma-mocha', 
		],
```

but why in this project `plugins` is not needed in `karma.conf.js`?

**Comment by LinusBorg** [comment]
Just read the karma documentation:

`By default, Karma loads all sibling NPM modules which have a name starting with karma-*.`
