### ISSUE TITLE
module is not installed 

### ISSUE THREAD

**Issue by mfma** [vuejs-templates/webpack#977]
I create a project by vue-cli and open it by webstorm,then i import ‘Hello.vue' into 'index.js’，but there is a warning which says ‘moudle is not installed'.
![1](https://user-images.githubusercontent.com/5546094/31481135-6dedbfde-af54-11e7-883f-4ca644596084.png)

![2](https://user-images.githubusercontent.com/5546094/31481153-7ac45dee-af54-11e7-9873-236a60527a43.png)

**Comment by LinusBorg** [comment]
Where is that warnign coming from? Webstorm? I would assume that's because Webstorm doesn't understand the webpack alias.

If that is a problem for you, use relative paths instead.
