### ISSUE TITLE
Uglify error when build

### ISSUE THREAD

**Issue by iamdubx** [vuejs-templates/webpack#978]
Hello. I got an error with one of the packages `vue-particles` when building the project. It's because it's using ES6 syntax I guess. I can't find the answer how to solve it. I even doesn't see where Uglify comes from in `webpack` template, I see no related plugins. 

```
ERROR in static/js/vendor.65207c1cf20abf7ff70e.js from UglifyJs
Unexpected token: punc (() [./~/vue-particles/src/vue-particles/index.js:6,0][static/js/vendor.65207c1cf20abf7ff70e.js:33623,12]
```

Can somebody help?

**Comment by LinusBorg** [comment]
>  I even doesn't see where Uglify comes from in webpack template, I see no related plugins.
That would be [here](https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.prod.conf.js#L36)

>  I can't find the answer how to solve it.
You already commented two different closed issues where solutions were provided. You have to adjust the babel-loader's include paths [here](https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.base.conf.js#L52) so that the source will be transpiled to ES5

**Comment by iamdubx** [comment]
@LinusBorg if I add `resolve('node_modules/menu-aim')` then I got other kind of Error

```
ERROR in ./~/menu-aim/src/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/***/Documents/WORK/EXAMPLES/vue-examples/node_modules/menu-aim"
```

**Comment by LinusBorg** [comment]
then install that preset (`babel-preset-es2015`).

babel-loader finds the `.babelrc` file in that pakcages folder and tries to use its settings for transpilation, but  that package is not installed because the webapck template uses a different one.

**Comment by iamdubx** [comment]
@LinusBorg I had errors with both of this packages. It worked with `vue-particles`, but `menu-aim` throws this error.

**Comment by LinusBorg** [comment]
Well, then that seems to be a problem of that package - its code isa ppearantly not completely transpiled to ES5, even though it appears it should.

**Comment by iamdubx** [comment]
Thanks, @LinusBorg

**Comment by ddiegommachado** [comment]
How to solve it? Someone? I have same problem!
