### ISSUE TITLE
`./src/main.js` use `import Vue from 'vue'` why is not `import * as Vue from 'vue'`

### ISSUE THREAD

**Issue by biluochun** [vuejs-templates/webpack#985]
[MDN-import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)

## vue.js/dist/vue.js
```es
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.Vue = factory());
}(this, (function () {});
```
`./src/main.js`:
```es
import Vue from 'vue'
import App from './App'
import router from './router'
```
-----
I think
vue inside the export is `module.exports = Vue;`
The correct reference should be `import * as Vue from 'vue';`

Only export to `module.exports = Vue; Vue.default = Vue;` or `export default Vue;`
Reference is `import Vue from 'vue';`

--------
## update:
is it a vue issue?

**Comment by hstarorg** [comment]
I think you should use the `vue.esm.js`.

**Comment by yyx990803** [comment]
webpack imports the ES modules build, not the UDM build.
